INSERT INTO encu.formularios(
            for_ope, for_for, for_nombre, for_es_principal, for_orden, for_tlg)
    VALUES ('ebcp2014', 'TEM', 'TEM', NULL, 0, 1);
/*OTRA*/
INSERT INTO encu.matrices(
            mat_ope, mat_for, mat_mat, mat_texto, mat_ua, mat_ultimo_campo_pk, 
            mat_orden, mat_blanquear_clave_al_retroceder, mat_tlg)
    VALUES ('ebcp2014','TEM','','Principal','enc','enc',NULL,',tra_hog:0,tra_mie:0,tra_exm:0',1);
/*OTRA*/    
INSERT INTO bloques (blo_ope, blo_for, blo_blo, blo_mat, blo_texto, blo_incluir_mat, blo_orden, blo_aclaracion, blo_tlg) VALUES 
('ebcp2014', 'TEM', '', '', '', NULL, 999, NULL, 1),
('ebcp2014', 'TEM', '1', '', 'Encuestador', NULL, 999, NULL, 1),
('ebcp2014', 'TEM', '2', '', 'No realizada x el encuestador', NULL, 999, NULL, 1),
('ebcp2014', 'TEM', '3', '', 'Recuperación', NULL, 999, NULL, 1),
('ebcp2014', 'TEM', '4', '', 'Supervisión de Recuperador', NULL, 999, NULL, 1),
('ebcp2014', 'TEM', '5', '', 'Supervisión encuestador', NULL, 999, NULL, 1),
('ebcp2014', 'TEM', 'CARGA', '', 'Datos de la carga', NULL, 100, NULL, 1),
('ebcp2014', 'TEM', 'ftc', '', 'Fin de las tareas de campo', NULL, 999, NULL, 1),
('ebcp2014', 'TEM', 'RECEPCION', '', 'Recepción', NULL, 300, NULL, 1),
('ebcp2014', 'TEM', 'RESULTADO', '', 'Resultado del último trabajo de campo', NULL, 200, NULL, 1),
('ebcp2014', 'TEM', 't_ing', '', 'TAREAS DE INGRESO', NULL, 999, NULL, 1);
/*OTRA*/
INSERT INTO preguntas (pre_ope, pre_pre, pre_texto, pre_abreviado, pre_for, pre_mat, pre_blo, pre_aclaracion, pre_destino, pre_desp_opc, pre_desp_nombre, pre_orden, pre_tlg) VALUES 
('ebcp2014', 'verificado_ac', 'verificado del analista de campo', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 730, 1),
('ebcp2014', 'fin_de_campo', 'fin de campo', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 750, 1),
('ebcp2014', 'cod_anacon', 'Analista de consistencias asignado', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 760, 1),
('ebcp2014', 'fin_anacon', 'Fin de análisis de consistencias', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 763, 1),
('ebcp2014', 'dispositivo_supe', 'Fin de análisis de consistencias', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 763, 1),
('ebcp2014', 'casa', 'número de casa en villa', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 720, 1),
('ebcp2014', 'manzana', 'manzana de villa', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 730, 1),
('ebcp2014', 'inq_tot_hab', 'total de habitaciones del inquilinato', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 740, 1),
('ebcp2014', 'inq_ocu_flia', 'habitaciones del inquilinato ocupadas', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 750, 1),
('ebcp2014', 'fecha_primcarga_supe', 'fecha primera carga supervisor encuestador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 770, 1),
('ebcp2014', 'fecha_primcarga_supr', 'fecha primera carga supervisor recuperador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 780, 1),
('ebcp2014', 'bolsa', 'Carga de procesamiento', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 790, 1),
('ebcp2014', 'etapa_pro', 'Etapa de procesamiento', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 800, 1),
('ebcp2014', 'norea_sup', 'NO REA del supervisor', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 810, 1),
('ebcp2014', 'resol_campo', 'Resolución de campo', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 850, 1),
('ebcp2014', 'pob_tot', 'población total', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 300, 1),
('ebcp2014', 'estado', 'Estado en que se encuentra la encuesta', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 90, 1),
('ebcp2014', 'asignable', 'La encuesta está lista para ser asignada a un encuestador ', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 100, 1),
('ebcp2014', 'cod_enc', 'Encuestador asignado', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 110, 1),
('ebcp2014', 'dispositivo_enc', 'En qué tipo de dispositivo va a cargar', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 120, 1),
('ebcp2014', 'recepcionista', 'Código de recepcionista que asignó la encuesta ', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 130, 1),
('ebcp2014', 'fecha_carga_enc', 'Fecha en que se cargó el dispositivo', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 140, 1),
('ebcp2014', 'fecha_primcarga_enc', 'Fecha de la primera vez que se cargó el dispositivo', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 150, 1),
('ebcp2014', 'fecha_descarga_enc', 'Fecha en que se descargó', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 160, 1),
('ebcp2014', 'a_ingreso_enc', 'Si fue pasado a ingreso', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 170, 1),
('ebcp2014', 'volver_a_cargar_enc', 'Si la encuesta se volverá a cargar', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 190, 1),
('ebcp2014', 'fin_ingreso_enc', 'finalizó el ingreso de la encuesta', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 210, 1),
('ebcp2014', 'rea_enc', 'REA del encuestador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 220, 1),
('ebcp2014', 'comenzo_ingreso', 'Fecha de comienzo del ingreso de la encuesta', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 230, 1),
('ebcp2014', 'norea_enc', 'NO REA del encuestador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 240, 1),
('ebcp2014', 'rea', 'REA total', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 250, 1),
('ebcp2014', 'norea', 'NO REA total', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 260, 1),
('ebcp2014', 'hog_pre', 'hogares presentes', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 270, 1),
('ebcp2014', 'hog_tot', 'hogares totales', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 280, 1),
('ebcp2014', 'pob_pre', 'población presente', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 290, 1),
('ebcp2014', 'con_dato_enc', 'Encuesta ingresada con dato', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 310, 1),
('ebcp2014', 'carga', 'Número de carga', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 320, 1),
('ebcp2014', 'sup_aleat_enc', 'supervisión aleatoria', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 330, 1),
('ebcp2014', 'sup_dirigida_enc', 'supervisión dirigida', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 340, 1),
('ebcp2014', 'cantidad_inconsistencias', 'Cantidad de inconsistencias', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 350, 1),
('ebcp2014', 'verificado_enc', 'finalizó la recepción', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 360, 1),
('ebcp2014', 'comenzo_consistencias', 'Fecha de comienzo de consistencias', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 370, 1),
('ebcp2014', 'cod_recu', 'recuperador asignado', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 380, 1),
('ebcp2014', 'dispositivo_recu', 'En qué tipo de dispositivo va a cargar', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 390, 1),
('ebcp2014', 'fecha_carga_recu', 'Fecha en que se cargó el dispositivo', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 400, 1),
('ebcp2014', 'fecha_primcarga_recu', 'Fecha de la primera vez que se cargó el dispositivo', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 410, 1),
('ebcp2014', 'fecha_descarga_recu', 'Fecha en que se descargó', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 420, 1),
('ebcp2014', 'a_ingreso_recu', 'Si fue pasado a ingreso', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 430, 1),
('ebcp2014', 'volver_a_cargar_recu', 'Vuelve a cargar para el recuperador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 450, 1),
('ebcp2014', 'fin_ingreso_recu', 'finalizó el ingreso de la encuesta', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 470, 1),
('ebcp2014', 'rea_recu', 'REA del recuperador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 480, 1),
('ebcp2014', 'norea_recu', 'NO REA del recuperador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 490, 1),
('ebcp2014', 'con_dato_recu', 'Encuesta recuperada con datos', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 500, 1),
('ebcp2014', 'sup_aleat_recu', 'supervisión aleatoria', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 510, 1),
('ebcp2014', 'sup_dirigida_recu', 'supervisión dirigida', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 520, 1),
('ebcp2014', 'verificado_recu', 'finalizó la recuperación', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 530, 1),
('ebcp2014', 'cod_supe', 'Código de supervisor del encuestador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 540, 1),
('ebcp2014', 'fecha_carga_supe', 'Fecha de carga del supervisor de encuestador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 560, 1),
('ebcp2014', 'result_supe', 'Resultado de la supervisión de encuestador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 570, 1),
('ebcp2014', 'verificado_supe', 'finalizó la supervisión de encuestador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 590, 1),
('ebcp2014', 'cod_supr', 'Código de supervisor del encuestador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 610, 1),
('ebcp2014', 'fecha_carga_supr', 'Fecha de carga del supervisor de recuperador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 630, 1),
('ebcp2014', 'result_supr', 'Resultado de la supervisión de recuperador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 640, 1),
('ebcp2014', 'verificado_supr', 'finalizó la supervisión de recuperador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 660, 1),
('ebcp2014', 'per', 'Código de persona', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 680, 1),
('ebcp2014', 'rol', 'Rol', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 690, 1),
('ebcp2014', 'en_campo', 'Encuesta en campo', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 700, 1),
('ebcp2014', 'fecha_comenzo_descarga', 'fecha de comienzo de la descarga', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 710, 1);


/*OTRA*/
INSERT INTO variables (var_ope, var_for, var_mat, var_pre, var_var, var_texto, var_aclaracion, var_conopc, var_conopc_texto, var_tipovar, var_destino, var_subordinada_var, var_subordinada_opcion, var_desp_nombre, var_expresion_habilitar, var_optativa, var_editable_por, var_orden, var_nsnc_atipico, var_mejor_de_pregunta, var_maximo, var_minimo, var_advertencia_sup, var_advertencia_inf, var_destino_nsnc, var_tlg, var_calculada) VALUES 
('ebcp2014', 'TEM', '', 'cod_anacon', 'cod_anacon', NULL, NULL, NULL, NULL, 'texto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'verificado_ac', 'verificado_ac', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'fin_de_campo', 'fin_de_campo', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'casa', 'casa', NULL, NULL, NULL, NULL, 'texto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL),
('ebcp2014', 'TEM', '', 'bolsa', 'bolsa', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'manzana', 'manzana', NULL, NULL, NULL, NULL, 'texto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL),
('ebcp2014', 'TEM', '', 'inq_tot_hab', 'inq_tot_hab', NULL, NULL, NULL, NULL, 'texto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL),
('ebcp2014', 'TEM', '', 'inq_ocu_flia', 'inq_ocu_flia', NULL, NULL, NULL, NULL, 'texto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL),
('ebcp2014', 'TEM', '', 'etapa_pro', 'etapa_pro', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'norea_sup', 'norea_sup', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'fecha_primcarga_supe', 'fecha_primcarga_sup', NULL, NULL, NULL, NULL, 'timestamp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL),
('ebcp2014', 'TEM', '', 'dispositivo_supe', 'dispositivo_sup', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'resol_campo', 'resol_campo', NULL, NULL, NULL, NULL, 'texto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'fin_anacon', 'fin_anacon', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'estado', 'estado', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'asignable', 'asignable', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'cod_enc', 'cod_enc', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'dispositivo_enc', 'dispositivo_enc', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'recepcionista', 'recepcionista', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'fecha_carga_enc', 'fecha_carga_enc', NULL, NULL, NULL, NULL, 'timestamp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'fecha_primcarga_enc', 'fecha_primcarga_enc', NULL, NULL, NULL, NULL, 'timestamp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'fecha_descarga_enc', 'fecha_descarga_enc', NULL, NULL, NULL, NULL, 'timestamp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'a_ingreso_enc', 'a_ingreso_enc', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'volver_a_cargar_enc', 'volver_a_cargar_enc', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'fin_ingreso_enc', 'fin_ingreso_enc', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'rea_enc', 'rea_enc', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'comenzo_ingreso', 'comenzo_ingreso', NULL, NULL, NULL, NULL, 'timestamp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'norea_enc', 'norea_enc', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'rea', 'rea', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'norea', 'norea', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'hog_pre', 'hog_pre', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'hog_tot', 'hog_tot', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'pob_pre', 'pob_pre', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'pob_tot', 'pob_tot', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'con_dato_enc', 'con_dato_enc', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'carga', 'carga', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'cantidad_inconsistencias', 'cantidad_inconsistencias', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'verificado_enc', 'verificado_enc', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'comenzo_consistencias', 'comenzo_consistencias', NULL, NULL, NULL, NULL, 'timestamp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'cod_recu', 'cod_recu', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'dispositivo_recu', 'dispositivo_recu', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'fecha_carga_recu', 'fecha_carga_recu', NULL, NULL, NULL, NULL, 'timestamp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'fecha_primcarga_recu', 'fecha_primcarga_recu', NULL, NULL, NULL, NULL, 'timestamp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'fecha_descarga_recu', 'fecha_descarga_recu', NULL, NULL, NULL, NULL, 'timestamp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'a_ingreso_recu', 'a_ingreso_recu', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'volver_a_cargar_recu', 'volver_a_cargar_recu', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'fin_ingreso_recu', 'fin_ingreso_recu', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'rea_recu', 'rea_recu', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'norea_recu', 'norea_recu', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'con_dato_recu', 'con_dato_recu', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'verificado_recu', 'verificado_recu', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'per', 'per', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 'case when pla_estado<=29 then pla_cod_enc when pla_estado<=39 then pla_cod_recu when pla_estado<49 then pla_cod_supe when pla_estado<59 then pla_cod_supr else null end'),
('ebcp2014', 'TEM', '', 'rol', 'rol', NULL, NULL, NULL, NULL, 'texto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 'case when pla_estado<=29 then ''encuestador'' when pla_estado<=39 then ''recuperador'' when pla_estado<59 then ''supervisor'' else null end'),
('ebcp2014', 'TEM', '', 'en_campo', 'en_campo', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 'case when pla_estado in (23,24,33,34,44,54) then 1 else 0 end'),
('ebcp2014', 'TEM', '', 'fecha_comenzo_descarga', 'fecha_comenzo_descarga', NULL, NULL, NULL, NULL, 'timestamp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'sup_aleat_enc', 'sup_aleat', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'sup_dirigida_enc', 'sup_dirigida', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'cod_supe', 'cod_sup', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'fecha_carga_supe', 'fecha_carga_sup', NULL, NULL, NULL, NULL, 'timestamp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'result_supe', 'result_sup', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'verificado_supe', 'verificado_sup', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, '');
