set search_path=encu;
delete from anoenc;
delete from barrio_calle_a_comuna;
delete from bitacora;
delete from bloques;
delete from bolsas;
delete from claves;
delete from con_opc;
delete from con_var;
delete from consistencias;
delete from diccionario;
delete from dictra;
delete from dicvar;
delete from dispositivo;
delete from dominio;
delete from est_rol;
delete from est_var;
delete from estados;
delete from estados_ingreso;
delete from excepciones;
delete from filtros;
delete from formularios;
delete from importancia;
delete from inconsistencias;
delete from matrices;
delete from novedades;
delete from opciones;
delete from operativos;
delete from pla_est;
delete from pla_var;
delete from planillas;
delete from preguntas;
delete from replica;
delete from respuestas;
delete from result_sup;
delete from rol_pla;
delete from rol_rol;
delete from saltos;
delete from sesiones;
delete from tabulados;
delete from tem;
delete from tem_nueva;
delete from tem_temporaria;
delete from tiempo_logico;
delete from tipo_nov;
delete from ua;
delete from varcal;
delete from varcalopc;
delete from varcondic;
delete from variables;
delete from verificado;
delete from volver_a_cargar;



set search_path=encu;
drop table plana_a1_ cascade;
drop table plana_a1_x cascade;
drop table plana_i1_ cascade;
drop table plana_s1_ cascade;
drop table plana_s1_p cascade;
--select * from estados limit 100;