INSERT INTO preguntas (pre_ope, pre_pre, pre_texto, pre_abreviado, pre_for, pre_mat, pre_blo, pre_aclaracion, pre_destino, pre_desp_opc, pre_desp_nombre, pre_orden, pre_tlg) VALUES ('ebcp2014', 'telefono', '¿Podría Ud. proveer un teléfono de contacto de su hogar por si necesitamos confirmar o clarificar alguna de las preguntas?
', NULL, 'S1', '', 'S1.1', NULL, '', 'vertical', '', 145, 1),
('ebcp2014', 'verificado_ac', 'verificado del analista de campo', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 730, 1),
('ebcp2014', 'fin_de_campo', 'fin de campo', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 750, 1),
('ebcp2014', 'cod_anacon', 'Analista de consistencias asignado', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 760, 1),
('ebcp2014', 'fin_anacon', 'Fin de análisis de consistencias', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 763, 1),
('ebcp2014', 'dispositivo_supe', 'Fin de análisis de consistencias', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 763, 1),
('ebcp2014', 'casa', 'número de casa en villa', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 720, 1),
('ebcp2014', 'manzana', 'manzana de villa', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 730, 1),
('ebcp2014', 'inq_tot_hab', 'total de habitaciones del inquilinato', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 740, 1),
('ebcp2014', 'inq_ocu_flia', 'habitaciones del inquilinato ocupadas', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 750, 1),
('ebcp2014', 'fecha_primcarga_supe', 'fecha primera carga supervisor encuestador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 770, 1),
('ebcp2014', 'fecha_primcarga_supr', 'fecha primera carga supervisor recuperador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 780, 1),
('ebcp2014', 'bolsa', 'Carga de procesamiento', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 790, 1),
('ebcp2014', 'etapa_pro', 'Etapa de procesamiento', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 800, 1),
('ebcp2014', 'norea_sup', 'NO REA del supervisor', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 810, 1),
('ebcp2014', 'resol_campo', 'Resolución de campo', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 850, 1),
('ebcp2014', 'H1', '¿El baño es...', NULL, 'A1', '', 'Hog', 'G-S', '', 'vertical', NULL, 13, 1),
('ebcp2014', 'H3', '¿Cuántas habitaciones/ ambientes son de uso exclusivo de este hogar?', NULL, 'A1', '', 'Hog', NULL, '', 'vertical', NULL, 15, 1),
('ebcp2014', 'V2', 'Tipo de vivienda', NULL, 'A1', '', 'Viv', 'Observacional', '', 'vertical', NULL, 7, 1),
('ebcp2014', 'V4', '¿Cuántas habitaciones/ ambientes tiene, en total, esta vivienda? Sin contar baño/s, cocina/s, garajes o pasillo/s', NULL, 'A1', '', 'Viv', NULL, '', 'vertical', NULL, 8, 1),
('ebcp2014', 'V7', '¿El techo tiene cielorraso/ revestimiento interior?', NULL, 'A1', '', 'Viv', NULL, '', 'vertical', NULL, 11, 1),
('ebcp2014', 'X5_tot', 'Total de personas', NULL, 'A1', '', 'X', NULL, '', 'vertical', NULL, 30, 1),
('ebcp2014', 'niv_educ', 'Nivel educativo al momento de irse', NULL, 'A1', 'X', 'X_m', NULL, '', 'vertical', '', 24, 1),
('ebcp2014', 'pais_nac', 'País de nacimiento', NULL, 'A1', 'X', 'X_m', NULL, '', 'vertical', '', 22, 1),
('ebcp2014', 'sexo_ex', 'Sexo', NULL, 'A1', 'X', 'X_m', NULL, '', 'vertical', '', 21, 1),
('ebcp2014', 'E1', '¿Sabe leer y escribir?', NULL, 'I1', '', 'E', NULL, '', 'vertical', NULL, 1001, 1),
('ebcp2014', 'E2', '¿Asiste o asistió a algún establecimiento educativo?', NULL, 'I1', '', 'E', 'G-S', '', 'vertical', NULL, 1010, 1),
('ebcp2014', 'E3', '¿Este establecimiento educativo está en...', NULL, 'I1', '', 'EAE', 'G-S', '', 'vertical', NULL, 1240, 1),
('ebcp2014', 'E4', '¿El establecimiento al que asiste actualmente es....', NULL, 'I1', '', 'EAE', 'G-S', '', 'vertical', NULL, 1260, 1),
('ebcp2014', 'E8', '¿Cuál es el grado/ año que está cursando actualmente?', NULL, 'I1', '', 'EAE', 'E-S', '', 'vertical', NULL, 1290, 1),
('ebcp2014', 'E12', '¿Cuál es el nivel más alto que cursó?', NULL, 'I1', '', 'ENE', 'E-S con indagación', '', 'vertical', NULL, 1320, 1),
('ebcp2014', 'E13', '¿Completó ese nivel?', NULL, 'I1', '', 'ENE', NULL, '', 'vertical', NULL, 1330, 1),
('ebcp2014', 'E14', '¿Cuál es el último grado/ año que aprobó en ese nivel?', NULL, 'I1', '', 'ENE', 'E-S', '', 'vertical', NULL, 1340, 1),
('ebcp2014', 'T37sd', 'Si presta servicio doméstico en hogares particulares marque', NULL, 'I1', '', 'HUO', NULL, '', 'vertical', NULL, 385, 1),
('ebcp2014', 'T38', '¿Ese negocio/ empresa/ institución es...', NULL, 'I1', '', 'HUO', 'G-S', '', 'vertical', NULL, 390, 1),
('ebcp2014', 'T39', '¿Dónde está ubicado ese negocio/ empresa/ institución?', NULL, 'I1', '', 'HUO', 'E-S', '', 'vertical', NULL, 400, 1),
('ebcp2014', 'T40', '¿Cuántas personas trabajan allí?', NULL, 'I1', '', 'HUO', 'E-S', '', 'vertical', NULL, 440, 1),
('ebcp2014', 'T41', '¿Cuál es el nombre de su ocupación?', NULL, 'I1', '', 'HUO', NULL, '', 'vertical', NULL, 450, 1),
('ebcp2014', 'T42', '¿Qué tareas realiza en ella?', NULL, 'I1', '', 'HUO', NULL, '', 'vertical', NULL, 460, 1),
('ebcp2014', 'T43', '¿Qué herramientas, maquinarias o equipos usa?', NULL, 'I1', '', 'HUO', NULL, '', 'vertical', NULL, 470, 1),
('ebcp2014', 'T45', '¿Por ese trabajo...', NULL, 'I1', '', 'HUO', 'G-S', '', 'vertical', NULL, 490, 1),
('ebcp2014', 'T46', '¿En ese negocio/ empresa/ actividad, se emplean personas asalariadas?', NULL, 'I1', '', 'HUO', 'G-S', '', 'vertical', NULL, 500, 1),
('ebcp2014', 'T47', '¿Ese negocio/ empresa, trabaja...', NULL, 'I1', '', 'HUO', 'G-S', '', 'vertical', NULL, 510, 1),
('ebcp2014', 'T48', '¿Ese cliente es...', NULL, 'I1', '', 'HUO', 'G-S', '', 'vertical', NULL, 520, 1),
('ebcp2014', 'T48a', '¿Para poder realizar su actividad...', NULL, 'I1', '', 'HUO', 'G-S', '', 'vertical', NULL, 523, 1),
('ebcp2014', 'T49', '¿Ese trabajo tiene tiempo de finalización?', NULL, 'I1', '', 'HUO', 'E-S', '', 'vertical', NULL, 530, 1),
('ebcp2014', 'T50', '¿En esa ocupación...', NULL, 'I1', '', 'HUO', 'G-M', '', 'vertical', NULL, 540, 1),
('ebcp2014', 'T51', '¿En ese trabajo...', NULL, 'I1', '', 'HUO', 'G-S', '', 'vertical', NULL, 550, 1),
('ebcp2014', 'T52', '¿Recibe además como pago...', NULL, 'I1', '', 'HUO', 'G-M', '', 'vertical', NULL, 560, 1),
('ebcp2014', 'T53_bis2', '¿Cuántas horas promedio corresponde?', NULL, 'I1', '', 'HUO', 'en un día promedio', '', 'vertical', NULL, 576, 1),
('ebcp2014', 'V5', '¿Los pisos interiores son principalmente de...', NULL, 'A1', '', 'Viv', 'G-S', '', 'vertical', NULL, 9, 1),
('ebcp2014', 'V6', '¿La cubierta exterior del techo es de...', NULL, 'A1', '', 'Viv', 'G-S', '', 'vertical', NULL, 10, 1),
('ebcp2014', 'H21', 'Durante el ÚLTIMO MES, ¿algún miembro de este hogar cobró la Asignación Universal por Hijo?', NULL, 'A1', '', 'HEH', NULL, NULL, 'vertical', NULL, 20, 1),
('ebcp2014', 'H2', 'Este hogar, ¿es...', NULL, 'A1', '', 'Hog', 'G-S.                    Lea todas las opciones de respuesta hasta obtener una respuesta positiva', '', 'vertical', NULL, 14, 1),
('ebcp2014', 'T53_bis1', '¿Lo ganado corresponde a su trabajo de...', NULL, 'I1', '', 'HUO', 'G-S', '', 'vertical', NULL, 573, 1),
('ebcp2014', 'X5', '¿Alguna persona que formaba parte de este hogar y vivía en la Ciudad, se ha ido a vivir fuera de la Ciudad?', NULL, 'A1', '', 'X', NULL, '', 'vertical', NULL, 20, 1),
('ebcp2014', 'H21_bis', 'Durante el último mes, ¿cuántos menores de 18 años de este hogar percibieron la Asignación Universal por Hijo?', NULL, 'A1', '', 'HEH', NULL, NULL, 'vertical', NULL, 21, 1),
('ebcp2014', 'edad_ex', 'Edad al momento de irse', NULL, 'A1', 'X', 'X_m', '                     En años cumplidos', '', 'vertical', '', 23, 1),
('ebcp2014', 'T39_bis2', '¿Dónde realiza principalmente sus tareas?', NULL, 'I1', '', 'HUO', 'E-S', '', 'vertical', NULL, 435, 1),
('ebcp2014', 'lugar', '¿A qué lugar se fue?', NULL, 'A1', 'X', 'X_m', NULL, '', 'vertical', '', 26, 1),
('ebcp2014', 'anio', 'Año en que se fue', NULL, 'A1', 'X', 'X_m', NULL, '', 'vertical', '', 25, 1),
('ebcp2014', 'T44', '¿Ese trabajo_______ lo hace...', NULL, 'I1', '', 'HUO', 'G-S', '', 'vertical', NULL, 480, 1),
('ebcp2014', 'I3', 'Aparte de sus ingresos por trabajo, ¿recibió ingresos en el mes pasado por...', NULL, 'I1', '', 'HIT', '                                                                                                                        Encuestador: siga leyendo aún cuando obtenga alguna respuesta positiva.', '', 'vertical', NULL, 990, 1),
('ebcp2014', 'T48b', 'La jubilación, ¿la paga regularmente...', NULL, 'I1', '', 'HUO', 'G-S', '', 'vertical', NULL, 526, 1),
('ebcp2014', 'T53', '¿Cuánto gana en esa ocupación?.', NULL, 'I1', '', 'HUO', 'O si es nuevo, ¿cuánto arregló que le paguen?', '', 'vertical', NULL, 570, 1),
('ebcp2014', 'I1', 'Hablemos de los ingresos que percibió durante el mes pasado. En ese mes, ¿tuvo algún ingreso en efectivo por trabajo?', NULL, 'I1', '', 'HIT', NULL, '', 'vertical', NULL, 970, 1),
('ebcp2014', 'I2', 'En el mes pasado, ¿podría decirme de cuánto fueron sus ingresos por trabajo, en efectivo, en todas sus ocupaciones?.', NULL, 'I1', '', 'HIT', 'Incluye gratificaciones/ bonificaciones no habituales y/o sueldo asignado como ganancia de patrón.', '', 'vertical', NULL, 980, 1),
('ebcp2014', 'E6', '¿Qué nivel está cursando actualmente?', NULL, 'I1', '', 'EAE', 'E-S, con indagación', '', 'vertical', NULL, 1270, 1),
('ebcp2014', 'H20', 'Le voy a nombrar distintas formas para mantener un hogar y quisiera que me diga todas las que ud/s. utilizan. ¿En los últimos tres meses este hogar ha vivido...', NULL, 'A1', '', 'HEH', 'G-M', '', 'vertical', NULL, 19, 1),
('ebcp2014', 'T54b', '¿A qué edad empezó a trabajar?', NULL, 'I1', '', 'HUO', NULL, '', 'vertical', NULL, 600, 1),
('ebcp2014', 'M1', '¿Dónde nació?', NULL, 'I1', '', 'MIG', 'E-S', '', 'vertical', NULL, 1590, 1),
('ebcp2014', 'M4', '¿Dónde vivía antes de ese año?', NULL, 'I1', '', 'MIG', 'E-S', '', 'vertical', NULL, 1630, 1),
('ebcp2014', 'OBS', 'Observaciones', NULL, 'I1', '', 'OBS', NULL, '', 'vertical', '', 5, 1),
('ebcp2014', 'RespondI', 'Número del miembro respondente', NULL, 'I1', '', 'Respondi', NULL, '', 'vertical', '', 10, 1),
('ebcp2014', 'S28', '¿Tiene o tuvo hijos o hijas nacidos vivos?', NULL, 'I1', '', 'SMM', NULL, '', 'vertical', NULL, 2010, 1),
('ebcp2014', 'S29', '¿Cuántos hijos o hijas nacidos vivos tuvo en total?', NULL, 'I1', '', 'SMM', NULL, '', 'vertical', NULL, 2020, 1),
('ebcp2014', 'S30', '¿Cuántos hijos o hijas están actualmente vivos?', NULL, 'I1', '', 'SMM', NULL, '', 'vertical', NULL, 2030, 1),
('ebcp2014', 'S31', 'Año y mes de nacimiento del último hijo/a nacido vivo/a', NULL, 'I1', '', 'SMM', NULL, '', 'vertical', NULL, 2040, 1),
('ebcp2014', 'SN12', '¿Cuánto tiempo estuvo internado?', NULL, 'I1', '', 'STP', NULL, '', 'vertical', NULL, 1960, 1),
('ebcp2014', 'SN13', '¿Cuál fue el motivo de la última internación?', NULL, 'I1', '', 'STP', 'E-S', '', 'vertical', NULL, 1970, 1),
('ebcp2014', 'SN14', '¿Estuvo internado/a en...', NULL, 'I1', '', 'STP', 'G-S', '', 'vertical', NULL, 1980, 1),
('ebcp2014', 'SN2', '¿En los últimos 30 días realizó consultas con un médico clínico o un especialista como cirujano, traumatólogo, ginecólogo, oculista, etc?', NULL, 'I1', '', 'STP', NULL, '', 'vertical', NULL, 1860, 1),
('ebcp2014', 'SN3', '¿Cuánto tiempo hace que consultó con un médico clínico o un especialista como cirujano, traumatólogo, ginecólogo, oculista, etc?', NULL, 'I1', '', 'STP', NULL, '', 'vertical', NULL, 1870, 1),
('ebcp2014', 'T1', '¿La semana pasada trabajó _________ por lo menos una hora?', NULL, 'I1', '', 'T', NULL, '', 'vertical', NULL, 18, 1),
('ebcp2014', 'T4', '¿No concurrió a su trabajo por...', NULL, 'I1', '', 'T', 'G-S', '', 'vertical', NULL, 40, 1),
('ebcp2014', 'T5', '¿Le siguen pagando durante la suspensión?', NULL, 'I1', '', 'T', 'E-S', '', 'vertical', NULL, 50, 1),
('ebcp2014', 'T6', '¿Volverá a ese trabajo a lo sumo en un mes?', NULL, 'I1', '', 'T', 'E-S', '', 'vertical', NULL, 60, 1),
('ebcp2014', 'T8', '¿Trabajó...', NULL, 'I1', '', 'T', 'G-S', '', 'vertical', NULL, 80, 1),
('ebcp2014', 'T15', '¿Cuánto hace que está buscando trabajo?', NULL, 'I1', '', 'TD', 'E-S', '', 'vertical', NULL, 150, 1),
('ebcp2014', 'T16', '¿Durante ese tiempo hizo algún trabajo/ changa?', NULL, 'I1', '', 'TD', NULL, '', 'vertical', NULL, 160, 1),
('ebcp2014', 'T17', '¿Cuánto tiempo hace que terminó su último trabajo/ changa?', NULL, 'I1', '', 'TD', 'E-S', '', 'vertical', NULL, 170, 1),
('ebcp2014', 'T18', '¿Ha trabajado alguna vez?', NULL, 'I1', '', 'TD', NULL, '', 'vertical', NULL, 180, 1),
('ebcp2014', 'T19', '¿En qué año dejó de trabajar en su última ocupación, changa, empleo?', NULL, 'I1', '', 'TD', NULL, '', 'vertical', NULL, 190, 1),
('ebcp2014', 'T20', '¿Ese trabajo _________ lo hacía...', NULL, 'I1', '', 'TD', 'G-S', '', 'vertical', NULL, 200, 1),
('ebcp2014', 'T21', '¿Por ese trabajo...', NULL, 'I1', '', 'TD', 'G-S', '', 'vertical', NULL, 210, 1),
('ebcp2014', 'T22', '¿En ese negocio/ empresa/ actividad, se empleaban personas asalariadas?', NULL, 'I1', '', 'TD', 'G-S', '', 'vertical', NULL, 220, 1),
('ebcp2014', 'T24', '¿Cuál era el nombre de su ocupación?', NULL, 'I1', '', 'TD', NULL, '', 'vertical', NULL, 240, 1),
('ebcp2014', 'T25', '¿Qué tareas realizaba en ella?', NULL, 'I1', '', 'TD', NULL, '', 'vertical', NULL, 250, 1),
('ebcp2014', 'T27', '¿Cobra actualmente el seguro de desempleo?', NULL, 'I1', '', 'TDI', NULL, '', 'vertical', NULL, 270, 1),
('ebcp2014', 'T36b', '¿Estuvo buscando porque...', NULL, 'I1', '', 'TLO', 'G-S', NULL, 'vertical', NULL, 370, 1),
('ebcp2014', 'T9', 'Durante los últimos 30 días, ¿estuvo buscando trabajo de alguna manera?', NULL, 'I1', '', 'T', NULL, '', 'vertical', NULL, 90, 1),
('ebcp2014', 'T7', '¿Recibe u obtiene algún pago por su trabajo, en dinero o en especie?', NULL, 'I1', '', 'T', NULL, '', 'vertical', NULL, 70, 1),
('ebcp2014', 'T10', 'Durante esos 30 días, ¿hizo algo para instalarse por su cuenta/puso carteles/consultó con parientes, amigos?', NULL, 'I1', '', 'T', NULL, '', 'vertical', NULL, 100, 1),
('ebcp2014', 'SN1', '¿Esta afiliado a...', NULL, 'I1', '', 'STP', 'G-M.                                                                                            Encuestador: siga leyendo aún cuando obtenga una respuesta positiva.', '', 'vertical', NULL, 1850, 1),
('ebcp2014', 'T13', 'En los últimos 12 meses, ¿buscó trabajo?', NULL, 'I1', '', 'T', NULL, '', 'vertical', NULL, 130, 1),
('ebcp2014', 'T12', 'Si la semana pasada conseguía trabajo, ¿podía empezar a trabajar en ese momento, o a más tardar en dos semanas?', NULL, 'I1', '', 'T', NULL, '', 'vertical', NULL, 120, 1),
('ebcp2014', 'T14', 'En los últimos 12 meses, ¿tuvo alguna ocupación con pago?', NULL, 'I1', '', 'T', NULL, '', 'vertical', NULL, 140, 1),
('ebcp2014', 'T26', '¿Qué herramientas, máquinarias o equipos usaba?', NULL, 'I1', '', 'TD', NULL, '', 'vertical', NULL, 260, 1),
('ebcp2014', 'M3', '¿Desde qué año vive en forma continua en esta Ciudad?', NULL, 'I1', '', 'MIG', NULL, '', 'vertical', NULL, 1620, 1),
('ebcp2014', 'M5', '¿Cuál fue el motivo por el que vino a vivir a esta Ciudad?', NULL, 'I1', '', 'MIG', 'E-S', '', 'vertical', NULL, 1640, 1),
('ebcp2014', 'T35', 'En los últimos 30 días ¿buscó otra ocupación?', NULL, 'I1', '', 'TLO', '                                   Encuestador: debe buscar activamente otra ocupación', '', 'vertical', NULL, 360, 1),
('ebcp2014', 'SN5', '¿Dónde realizó la consulta?', NULL, 'I1', '', 'STP', 'de la última consulta si hizo más de una. G-S.', '', 'vertical', NULL, 1890, 1),
('ebcp2014', 'SN4', '¿Cuál fue el motivo de la consulta?', NULL, 'I1', '', 'STP', 'de la última consulta si hizo más de una. G-S.', '', 'vertical', NULL, 1880, 1),
('ebcp2014', 'SN11', 'En los últimos 12 meses, ¿estuvo internado/a?', NULL, 'I1', '', 'STP', NULL, NULL, 'vertical', NULL, 1950, 1),
('ebcp2014', 'SN15', '¿Alguna vez un médico le diagnosticó a usted una enfermedad que se extiende en el tiempo o que requiere tratamiento como las que se mencionan a continuación?', NULL, 'I1', '', 'STP', 'G-M', '', 'vertical', NULL, 1990, 1),
('ebcp2014', 'SN16', 'En líneas generales, ¿el estado de salud de _________ es...', NULL, 'I1', '', 'STP', 'G-S', '', 'vertical', NULL, 1995, 1),
('ebcp2014', 'T3', '¿La semana pasada...', NULL, 'I1', '', 'T', 'G-S. Primero lea todas las opciones y luego marque la respuesta', '', 'vertical', NULL, 30, 1),
('ebcp2014', 'T11', '¿No buscó trabajo, ni hizo algo para trabajar, porque...', NULL, 'I1', '', 'T', 'G-S. Primero lea todas las opciones y luego marque la respuesta.', '', 'vertical', NULL, 110, 1),
('ebcp2014', 'T54', '¿Participa en algún programa de empleo?', NULL, 'I1', '', 'HUO', NULL, '', 'vertical', NULL, 590, 1),
('ebcp2014', 'T29', '¿Cuántas horas semanales trabaja habitualmente en todos sus empleos/ ocupaciones?', NULL, 'I1', '', 'TNT', NULL, '', 'vertical', NULL, 290, 1),
('ebcp2014', 'T29a', '¿Quiere trabajar más horas?', NULL, 'I1', '', 'TNT', NULL, '', 'vertical', NULL, 300, 1),
('ebcp2014', 'T30', '¿Cuántos empleos/ ocupaciones tuvo la semana pasada?', NULL, 'I1', '', 'TST', NULL, '', 'vertical', NULL, 310, 1),
('ebcp2014', 'T34', 'Si hubiera conseguido más horas ¿podía trabajarlas esa semana?', NULL, 'I1', '', 'TST', 'o a más tardar en dos semanas', '', 'vertical', NULL, 350, 1),
('ebcp2014', 'P2', 'Sexo', 'sexo', 'S1', 'P', 'M.P_m', 'Anote el código', '', 'vertical', NULL, 3, 1),
('ebcp2014', 'razon', 'RAZÓN POR LA CUAL NO SE REALIZÓ LA ENTREVISTA', NULL, 'S1', '', 'RAZON', NULL, '', 'vertical', '', 900, 1),
('ebcp2014', 'razon_1', NULL, NULL, 'S1', '', 'RAZON', NULL, '', 'vertical', 'razón 1', 920, 1),
('ebcp2014', 'razon_2', NULL, NULL, 'S1', '', 'RAZON', NULL, '', 'vertical', 'razón 2', 930, 1),
('ebcp2014', 'pob_tot', 'población total', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 300, 1),
('ebcp2014', 'razon_3', NULL, NULL, 'S1', '', 'RAZON', 'Viven en otra vivienda la mayor parte...', '', 'vertical', 'razón 3', 940, 1),
('ebcp2014', 'razon_4', NULL, NULL, 'S1', '', 'RAZON', NULL, '', 'vertical', 'razón 4', 950, 1),
('ebcp2014', 'razon_5', NULL, NULL, 'S1', '', 'RAZON', NULL, '', 'vertical', 'razón 5', 960, 1),
('ebcp2014', 'razon_6', NULL, NULL, 'S1', '', 'RAZON', NULL, '', 'vertical', 'razón 6', 970, 1),
('ebcp2014', 'razon_7', NULL, NULL, 'S1', '', 'RAZON', NULL, '', 'vertical', 'razón 7', 980, 1),
('ebcp2014', 'razon_8', NULL, NULL, 'S1', '', 'RAZON', NULL, '', 'vertical', 'razón 8', 990, 1),
('ebcp2014', 'razon_9', NULL, NULL, 'S1', '', 'RAZON', NULL, '', 'vertical', 'razón 9', 1000, 1),
('ebcp2014', 's1a1_obs', 'Observaciones', NULL, 'S1', '', 'RAZON', NULL, '', 'vertical', '', 2000, 1),
('ebcp2014', 'entrea', 'Entrevista Realizada', NULL, 'S1', '', 'S1.1', NULL, '', 'vertical', '', 100, 1),
('ebcp2014', 'f_realiz_o', 'Fecha de realización', NULL, 'S1', '', 'S1.1', NULL, '', 'vertical', '', 140, 1),
('ebcp2014', 'nombrer', 'Nombre', NULL, 'S1', '', 'S1.1', NULL, '', 'vertical', '', 130, 1),
('ebcp2014', 'respond', 'Número de miembro respondente', NULL, 'S1', '', 'S1.1', NULL, '', 'vertical', '', 110, 1),
('ebcp2014', 'total_h', 'Total de hogares', NULL, 'S1', '', 'S1.1', NULL, '', 'vertical', '', 160, 1),
('ebcp2014', 'V1', '¿Todas las personas que residen en esta vivienda comparten los gastos de comida?', NULL, 'S1', '', 'S1.1', NULL, '', 'vertical', NULL, 150, 1),
('ebcp2014', 'P6', '¿Quién es el padre/madre de...?.', 'padre/madre', 'S1', 'P', 'M.P_m', 'Para 24 años o menos. ', '', 'vertical', NULL, 19, 1),
('ebcp2014', 'P7', 'Entradas y salidas del hogar', 'Ent/Sal', 'S1', 'P', 'M.P_m', NULL, '', 'vertical', NULL, 7, 1),
('ebcp2014', 'P8', 'Motivo de entradas y salidas del hogar', 'motivo', 'S1', 'P', 'M.P_m', NULL, '', 'vertical', NULL, 8, 1),
('ebcp2014', 'P5B', '¿Convive con alguien de este hogar? ¿Quién es?.', 'convive con', 'S1', 'P', 'M.P_m', 'Para 14 años y más unidos/casados. Si no convive anote código 95', '', 'vertical', NULL, 18, 1),
('ebcp2014', 'P3B', '¿Cuántos años cumplidos tiene en este momento?', 'años', 'S1', 'P', 'M.P_m', '                     Si tiene menos de un año anote 0', '', 'vertical', NULL, 15, 1),
('ebcp2014', 'P4', '¿Qué parentesco tiene con el jefe?', 'parentesco', 'S1', 'P', 'M.P_m', ' E-S', '', 'vertical', NULL, 16, 1),
('ebcp2014', 'T32', 'En su/s otra/s ocupación/es ¿cuántas horas trabajó…', NULL, 'I1', '', 'TST', NULL, '', 'vertical', NULL, 330, 1),
('ebcp2014', 'T33', 'La semana pasada ¿quería trabajar más horas?', NULL, 'I1', '', 'TST', NULL, '', 'vertical', NULL, 340, 1),
('ebcp2014', 'T31', 'En su OCUPACIÓN PRINCIPAL, si es más de una la que le lleva más horas, ¿cuántas horas trabajó...', NULL, 'I1', '', 'TST', '(CÓDIGOS para los que no trabajaron algún día de la semana: 30-Enfermedad /
31- Otra licencia con goce de sueldo /
32- Falta de trabajo o suspensión /
33- Feriados /
0- Otras no incluidas en las anteriores (francos, nunca trabaja esos días, etc.).', '', 'vertical', NULL, 320, 1),
('ebcp2014', 'T28', '¿Cuántos empleos/ ocupaciones tiene?', NULL, 'I1', '', 'TNT', '                              En el caso de tener más de un empleo, verifique que no haya trabajado en ninguno durante la semana pasada.', '', 'vertical', NULL, 280, 1),
('ebcp2014', 'total_m', 'Cantidad de miembros', NULL, 'S1', '', 'S1.1', NULL, '', 'vertical', '', 170, 1),
('ebcp2014', 'P1', 'Nombre o sobrenombre ', 'nombre', 'S1', 'P', 'M.P_m', ' ', '', 'vertical', NULL, 2, 1),
('ebcp2014', 'P3A', 'Fecha de nacimiento', 'f.nac', 'S1', 'P', 'M.P_m', NULL, '', 'vertical', NULL, 14, 1),
('ebcp2014', 'P5', '¿Actualmente es...?', 'estado cony', 'S1', 'P', 'M.P_m', ' G-S.       Para personas de 14 años y más.', '', 'vertical', NULL, 17, 1),
('ebcp2014', 'T37', '¿A qué se dedica o qué produce el negocio, empresa o institución en la que trabaja?', NULL, 'I1', '', 'HUO', 'Registre el producto principal que produce o los servicios que presta el establecimiento en el que trabaja, para los trabajadores por cuenta propia, el establecimiento es la misma actividad que realizan.', '', 'vertical', NULL, 380, 1),
('ebcp2014', 'T2', 'En esa semana, ¿hizo alguna changa, fabricó en su casa algo para vender, ayudó a un familiar o amigo en su negocio?', NULL, 'I1', '', 'T', NULL, '', 'vertical', NULL, 20, 1),
('ebcp2014', 'V12', 'Esta vivienda, ¿dispone de....', NULL, 'A1', '', 'Viv', 'G-S, lea todas las opciones de respuesta hasta obtener una respuesta positiva', '', 'vertical', NULL, 12, 1),
('ebcp2014', 'T23', '¿A qué se dedicaba o qué producía el negocio/ empresa/ institución en la que trabajaba?', NULL, 'I1', '', 'TD', 'Registre el producto principal que producía o los servicios que prestaba el establecimiento en el que trabajaba, para los trabajadores por cuenta propia, el establecimiento es la misma actividad que realizaban.', '', 'vertical', NULL, 230, 1),
('ebcp2014', 'T53c', '¿Cuánto tiempo hace que está trabajando en ese empleo/ ocupación en forma continua?', NULL, 'I1', '', 'HUO', '                                                                                                                   Para asalariados sin interrupciones de la relación laboral con la misma empresa/ negocio/ institución, para patrones y cuentapropias sin interrupciones laborales mayores de 15 días.', '', 'vertical', NULL, 580, 1),
('ebcp2014', 'estado', 'Estado en que se encuentra la encuesta', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 90, 1),
('ebcp2014', 'asignable', 'La encuesta está lista para ser asignada a un encuestador ', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 100, 1),
('ebcp2014', 'cod_enc', 'Encuestador asignado', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 110, 1),
('ebcp2014', 'dispositivo_enc', 'En qué tipo de dispositivo va a cargar', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 120, 1),
('ebcp2014', 'recepcionista', 'Código de recepcionista que asignó la encuesta ', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 130, 1),
('ebcp2014', 'fecha_carga_enc', 'Fecha en que se cargó el dispositivo', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 140, 1),
('ebcp2014', 'fecha_primcarga_enc', 'Fecha de la primera vez que se cargó el dispositivo', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 150, 1),
('ebcp2014', 'fecha_descarga_enc', 'Fecha en que se descargó', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 160, 1),
('ebcp2014', 'a_ingreso_enc', 'Si fue pasado a ingreso', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 170, 1),
('ebcp2014', 'volver_a_cargar_enc', 'Si la encuesta se volverá a cargar', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 190, 1),
('ebcp2014', 'fin_ingreso_enc', 'finalizó el ingreso de la encuesta', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 210, 1),
('ebcp2014', 'rea_enc', 'REA del encuestador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 220, 1),
('ebcp2014', 'comenzo_ingreso', 'Fecha de comienzo del ingreso de la encuesta', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 230, 1),
('ebcp2014', 'norea_enc', 'NO REA del encuestador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 240, 1),
('ebcp2014', 'rea', 'REA total', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 250, 1),
('ebcp2014', 'norea', 'NO REA total', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 260, 1),
('ebcp2014', 'hog_pre', 'hogares presentes', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 270, 1),
('ebcp2014', 'hog_tot', 'hogares totales', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 280, 1),
('ebcp2014', 'pob_pre', 'población presente', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 290, 1),
('ebcp2014', 'con_dato_enc', 'Encuesta ingresada con dato', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 310, 1),
('ebcp2014', 'carga', 'Número de carga', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 320, 1),
('ebcp2014', 'sup_aleat_enc', 'supervisión aleatoria', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 330, 1),
('ebcp2014', 'sup_dirigida_enc', 'supervisión dirigida', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 340, 1),
('ebcp2014', 'cantidad_inconsistencias', 'Cantidad de inconsistencias', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 350, 1),
('ebcp2014', 'verificado_enc', 'finalizó la recepción', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 360, 1),
('ebcp2014', 'comenzo_consistencias', 'Fecha de comienzo de consistencias', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 370, 1),
('ebcp2014', 'cod_recu', 'recuperador asignado', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 380, 1),
('ebcp2014', 'dispositivo_recu', 'En qué tipo de dispositivo va a cargar', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 390, 1),
('ebcp2014', 'fecha_carga_recu', 'Fecha en que se cargó el dispositivo', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 400, 1),
('ebcp2014', 'fecha_primcarga_recu', 'Fecha de la primera vez que se cargó el dispositivo', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 410, 1),
('ebcp2014', 'fecha_descarga_recu', 'Fecha en que se descargó', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 420, 1),
('ebcp2014', 'a_ingreso_recu', 'Si fue pasado a ingreso', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 430, 1),
('ebcp2014', 'volver_a_cargar_recu', 'Vuelve a cargar para el recuperador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 450, 1),
('ebcp2014', 'fin_ingreso_recu', 'finalizó el ingreso de la encuesta', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 470, 1),
('ebcp2014', 'rea_recu', 'REA del recuperador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 480, 1),
('ebcp2014', 'norea_recu', 'NO REA del recuperador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 490, 1),
('ebcp2014', 'con_dato_recu', 'Encuesta recuperada con datos', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 500, 1),
('ebcp2014', 'sup_aleat_recu', 'supervisión aleatoria', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 510, 1),
('ebcp2014', 'sup_dirigida_recu', 'supervisión dirigida', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 520, 1),
('ebcp2014', 'verificado_recu', 'finalizó la recuperación', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 530, 1),
('ebcp2014', 'cod_supe', 'Código de supervisor del encuestador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 540, 1),
('ebcp2014', 'fecha_carga_supe', 'Fecha de carga del supervisor de encuestador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 560, 1),
('ebcp2014', 'result_supe', 'Resultado de la supervisión de encuestador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 570, 1),
('ebcp2014', 'verificado_supe', 'finalizó la supervisión de encuestador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 590, 1),
('ebcp2014', 'cod_supr', 'Código de supervisor del encuestador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 610, 1),
('ebcp2014', 'fecha_carga_supr', 'Fecha de carga del supervisor de recuperador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 630, 1),
('ebcp2014', 'result_supr', 'Resultado de la supervisión de recuperador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 640, 1),
('ebcp2014', 'verificado_supr', 'finalizó la supervisión de recuperador', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 660, 1),
('ebcp2014', 'per', 'Código de persona', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 680, 1),
('ebcp2014', 'rol', 'Rol', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 690, 1),
('ebcp2014', 'en_campo', 'Encuesta en campo', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 700, 1),
('ebcp2014', 'fecha_comenzo_descarga', 'fecha de comienzo de la descarga', NULL, 'TEM', '', '', NULL, NULL, 'vertical', NULL, 710, 1);