INSERT INTO bloques (blo_ope, blo_for, blo_blo, blo_mat, blo_texto, blo_incluir_mat, blo_orden, blo_aclaracion, blo_tlg) VALUES 
('ebcp2014', 'A1', '', '', '', NULL, NULL, NULL, 1),
('ebcp2014', 'A1', 'HEH', '', 'Estrategias del hogar', NULL, 20, NULL, 1),
('ebcp2014', 'A1', 'Hog', '', 'Hogar', NULL, 15, NULL, 1),
('ebcp2014', 'A1', 'Viv', '', 'Vivienda', NULL, 5, 'Si existe más de un hogar, aplique el bloque vivienda sólo al primero. El segundo hogar pase a H1.', 1),
('ebcp2014', 'A1', 'X', '', 'Emigración', 'X', 25, NULL, 1),
('ebcp2014', 'A1', 'X_m', 'X', '', NULL, 40, NULL, 1),
('ebcp2014', 'I1', 'A170', '', 'Fin de Cuestionario Individual', NULL, 9000, NULL, 1),
('ebcp2014', 'I1', 'EAE', '', 'Para personas que asisten a un establecimiento educativo', NULL, 1235, NULL, 1),
('ebcp2014', 'I1', 'HUO', '', 'Hablemos ahora de su única ocupación o de la que le lleva más horas', NULL, 377, NULL, 1),
('ebcp2014', 'I1', 'OBS', '', '', NULL, 1, NULL, 1),
('ebcp2014', 'I1', 'Respondi', '', '', NULL, 2, NULL, 1),
('ebcp2014', 'I1', 'TD', '', 'Para desocupados', NULL, 145, NULL, 1),
('ebcp2014', 'I1', 'TDI', '', 'Para desocupados e inactivos', NULL, 265, NULL, 1),
('ebcp2014', 'I1', 'TLO', '', 'Para todos los ocupados', NULL, 355, NULL, 1),
('ebcp2014', 'S1', '', '', '', NULL, NULL, NULL, 1),
('ebcp2014', 'S1', 'RAZON', '', 'RAZONES DE NO ENTREVISTA', NULL, 900, NULL, 1),
('ebcp2014', 'S1', 'S1.1', '', 'DATOS DE LA ENTREVISTA ', NULL, 100, NULL, 1),
('ebcp2014', 'TEM', '', '', '', NULL, 999, NULL, 1),
('ebcp2014', 'TEM', '1', '', 'Encuestador', NULL, 999, NULL, 1),
('ebcp2014', 'TEM', '2', '', 'No realizada x el encuestador', NULL, 999, NULL, 1),
('ebcp2014', 'TEM', '3', '', 'Recuperación', NULL, 999, NULL, 1),
('ebcp2014', 'TEM', '4', '', 'Supervisión de Recuperador', NULL, 999, NULL, 1),
('ebcp2014', 'TEM', '5', '', 'Supervisión encuestador', NULL, 999, NULL, 1),
('ebcp2014', 'TEM', 'CARGA', '', 'Datos de la carga', NULL, 100, NULL, 1),
('ebcp2014', 'TEM', 'ftc', '', 'Fin de las tareas de campo', NULL, 999, NULL, 1),
('ebcp2014', 'TEM', 'RECEPCION', '', 'Recepción', NULL, 300, NULL, 1),
('ebcp2014', 'TEM', 'RESULTADO', '', 'Resultado del último trabajo de campo', NULL, 200, NULL, 1),
('ebcp2014', 'TEM', 't_ing', '', 'TAREAS DE INGRESO', NULL, 999, NULL, 1),
('ebcp2014', 'I1', 'TNT', '', 'Para ocupados que no trabajaron en la semana de referencia', NULL, 275, NULL, 1),
('ebcp2014', 'I1', 'TST', '', 'Para ocupados que trabajaron en la semana de referencia', NULL, 305, NULL, 1),
('ebcp2014', 'I1', 'ENE', '', 'Para personas que no asisten pero asistieron', NULL, 1295, NULL, 1),
('ebcp2014', 'I1', 'E', '', 'CONFRONTE EDAD ', NULL, 1000, NULL, 1),
('ebcp2014', 'I1', 'T', '', 'TRABAJO - Para todas las personas de 10 años o más', NULL, 9, NULL, 1),
('ebcp2014', 'I1', 'MIG', '', 'MIGRACIONES - Para todas las personas', NULL, 1500, NULL, 1),
('ebcp2014', 'I1', 'STP', '', 'SALUD - Para todas las personas', NULL, 1800, NULL, 1),
('ebcp2014', 'I1', 'SMM', '', 'FECUNDIDAD - Para mujeres de 14 años y más', NULL, 2005, NULL, 1),
('ebcp2014', 'S1', 'M.P_m', 'P', 'COMPONENTES DEL HOGAR  ', NULL, 800, NULL, 1),
('ebcp2014', 'I1', 'HIT', '', 'INGRESOS - Ahora vamos a hablar de los ingresos totales. ', NULL, 900, 'Recuerde que si tiene más de una ocupación debe registrar todos los ingresos.', 1),
('ebcp2014', 'S1', 'M.P', '', 'COMPONENTES DEL HOGAR - Por favor, nombre todas las personas que componen este hogar empezando por el jefe. No se olvide de Ud. ni de los bebés y niños.  ', 'P', 800, NULL, 1);
