INSERT INTO variables (var_ope, var_for, var_mat, var_pre, var_var, var_texto, var_aclaracion, var_conopc, var_conopc_texto, var_tipovar, var_destino, var_subordinada_var, var_subordinada_opcion, var_desp_nombre, var_expresion_habilitar, var_optativa, var_editable_por, var_orden, var_nsnc_atipico, var_mejor_de_pregunta, var_maximo, var_minimo, var_advertencia_sup, var_advertencia_inf, var_destino_nsnc, var_tlg, var_calculada) VALUES 
('ebcp2014', 'S1', 'P', 'P6', 'p6_a', 'Padre', 'Si no vive en el hogar anote 95', NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, 'edad<=24 and p7<3', false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'TEM', '', 'cod_anacon', 'cod_anacon', NULL, NULL, NULL, NULL, 'texto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'verificado_ac', 'verificado_ac', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'fin_de_campo', 'fin_de_campo', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'S1', 'P', 'P3A', 'f_nac_o', NULL, NULL, NULL, NULL, 'fecha', NULL, NULL, NULL, NULL, 'p7<3', false, NULL, 0, NULL, NULL, 2013, 1890, NULL, 1901, NULL, 1 , NULL),
('ebcp2014', 'TEM', '', 'casa', 'casa', NULL, NULL, NULL, NULL, 'texto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'TEM', '', 'bolsa', 'bolsa', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'manzana', 'manzana', NULL, NULL, NULL, NULL, 'texto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'TEM', '', 'inq_tot_hab', 'inq_tot_hab', NULL, NULL, NULL, NULL, 'texto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'TEM', '', 'inq_ocu_flia', 'inq_ocu_flia', NULL, NULL, NULL, NULL, 'texto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'TEM', '', 'etapa_pro', 'etapa_pro', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'S1', 'P', 'P4', 'p4', NULL, NULL, 'p4', NULL, 'opciones', NULL, NULL, NULL, NULL, 'p7<3', false, NULL, 0, 99, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T8', 't8', NULL, NULL, 't8', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 3, 1, NULL, NULL, 'T30', 1 , NULL),
('ebcp2014', 'I1', '', 'T38', 't38', NULL, NULL, 't38', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 3, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T46', 't46', NULL, NULL, 't46', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 3, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T48b', 't48b_esp', NULL, NULL, NULL, NULL, 'texto_especificar', 'T53', 't48b', '6', NULL, 't48b=6', false, NULL, 6, NULL, NULL, 3, 1, NULL, NULL, 'T53', 1 , NULL),
('ebcp2014', 'TEM', '', 'norea_sup', 'norea_sup', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'I1', '', 'T53c', 't53c_meses', 'Meses', NULL, NULL, NULL, 'meses', NULL, NULL, NULL, NULL, '!t53c_anios', true, NULL, 2, 99, NULL, 12, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN1', 'sn1_5', 'al Programa Cobertura Porteña de Salud / Plan  Médicos de Cabecera del GCBA?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 60, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN1', 'sn1_6', 'No tiene afiliación', 'No Leer', 'solamentesi_h', NULL, 'si_no', NULL, NULL, NULL, NULL, 'sn1_1=2 and sn1_2=2 and sn1_3=2 and sn1_4=2 and sn1_5=2 and sn1_7=2', false, NULL, 70, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN15', 'sn15i', 'Enfermedades del hígado o vesícula biliar', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 9, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I3', 'i3_tot', 'Total ingresos', NULL, NULL, NULL, 'monetaria', NULL, NULL, NULL, NULL, 'i3_1=1 or i3_2=1 or i3_3=1 or i3_4=1 or i3_5=1 or i3_6=1 or i3_7=1 or i3_8=1 or i3_10=1 or i3_11=1 or i3_12=1', true, NULL, 130, NULL, NULL, NULL, 0, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN16', 'sn16', NULL, NULL, 'sn16', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 6, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'TEM', '', 'fecha_primcarga_supe', 'fecha_primcarga_sup', NULL, NULL, NULL, NULL, 'timestamp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'V2', 'v2', NULL, NULL, 'v2', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 8, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'TEM', '', 'dispositivo_supe', 'dispositivo_sup', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'resol_campo', 'resol_campo', NULL, NULL, NULL, NULL, 'texto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'A1', '', 'V5', 'v5_esp', NULL, NULL, NULL, NULL, 'texto', NULL, 'v5', '4', NULL, 'v5=4', false, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'V12', 'v12', NULL, NULL, 'v12', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 4, 1, NULL, NULL, 'H2', 1 , NULL),
('ebcp2014', 'A1', '', 'H1', 'h1', NULL, NULL, 'h1', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'H2', 'h2', NULL, NULL, 'h2', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 7, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'H3', 'h3', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, 99, NULL, 49, 0, 7, 0, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'H21', 'h21', NULL, NULL, 'si_no', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'H21_bis', 'h21_bis', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, 99, NULL, 20, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'TEM', '', 'fin_anacon', 'fin_anacon', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'I1', '', 'I3', 'i3_6x', '$', NULL, NULL, NULL, 'monetaria', NULL, 'i3_6', '1', NULL, 'i3_6=1', false, NULL, 61, NULL, NULL, NULL, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', '', 'entrea', 'entrea', NULL, NULL, 'entrea', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'H20', 'h20_esp', NULL, NULL, NULL, NULL, 'texto_especificar', NULL, 'h20_14', '1', NULL, 'h20_14=1', false, NULL, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'H2', 'h2_esp', NULL, NULL, NULL, NULL, 'texto_especificar', NULL, 'h2', '7', NULL, 'h2=7', false, NULL, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'V2', 'v2_esp', NULL, NULL, NULL, NULL, 'texto_especificar', NULL, 'v2', '8', NULL, 'v2=8', false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', 'X', 'lugar', 'lugar_esp3', NULL, NULL, NULL, NULL, 'texto_especificar', NULL, 'lugar', '3', NULL, 'lugar=3', false, NULL, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T37', 't37', NULL, NULL, NULL, NULL, 'texto_libre', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T37sd', 't37sd', NULL, NULL, 't37sd', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, true, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T39_bis2', 't39_bis2_esp', NULL, NULL, NULL, NULL, 'texto_especificar', NULL, 't39_bis2', '8', NULL, 't39_bis2=8', true, NULL, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T41', 't41', NULL, NULL, NULL, NULL, 'texto_libre', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T42', 't42', NULL, NULL, NULL, NULL, 'texto_libre', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T43', 't43', NULL, NULL, NULL, NULL, 'texto_libre', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T45', 't45', NULL, NULL, 't45', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 3, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T39', 't39', NULL, NULL, 't39', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 5, 1, NULL, NULL, 't39_bis2', 1 , NULL),
('ebcp2014', 'I1', '', 'T39_bis2', 't39_bis2', '', NULL, 't39_bis2', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 13, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T40', 't40', NULL, NULL, 't40', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 9, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T44', 't44', NULL, NULL, 't44', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 3, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T47', 't47', NULL, NULL, 't47', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'V6', 'v6', NULL, NULL, 'v6', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 9, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T48', 't48', NULL, NULL, 't48', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T48a', 't48a', NULL, NULL, 't48a', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 9, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T48b', 't48b', NULL, NULL, 't48b', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 6, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I1', 'i1', NULL, NULL, 'si_no', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, 'I3', 1 , NULL),
('ebcp2014', 'I1', '', 'E1', 'e1', NULL, NULL, 'e1', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'E2', 'e2', NULL, NULL, 'e2', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 3, 1, NULL, NULL, 'MIG', 1 , NULL),
('ebcp2014', 'I1', '', 'E3', 'e3', NULL, NULL, 'e3', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 3, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'E4', 'e4', NULL, NULL, 'e4', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 3, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'E6', 'e6', NULL, NULL, 'e6', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 18, 2, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'E8', 'e8', NULL, NULL, 'e8', NULL, 'opciones', 'M1', NULL, NULL, NULL, NULL, false, NULL, 0, 99, NULL, 11, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'E12', 'e12', NULL, NULL, 'e12', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 18, 2, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'E13', 'e13', NULL, NULL, 'e13', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'E14', 'e14', NULL, NULL, 'e14', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, 99, NULL, 11, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'V4', 'v4', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, 99, NULL, 50, 1, 8, 1, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'V5', 'v5', NULL, NULL, 'v5', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 4, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'V7', 'v7', NULL, NULL, 'si_no', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I2', 'i2_ticx', 'Tickets', '    $', NULL, NULL, 'monetaria', NULL, NULL, NULL, NULL, 't52c=1', true, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'H20', 'h20_1', 'de lo que ganan los miembros del hogar en el trabajo?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 1, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'H20', 'h20_17', 'del seguro de desempleo?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 3, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'H20', 'h20_18', 'indemnización por despido?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 4, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'H20', 'h20_5', 'del cobro de alquileres, rentas, intereses o dividendos?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 5, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'H20', 'h20_6', 'de cuotas de alimento?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 6, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'H20', 'h20_7', 'de aportes en dinero de personas que no viven en el hogar?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 7, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'X5', 'x5', NULL, NULL, 'si_no', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'H20', 'h20_8', 'de otro subsidio o plan social, en dinero, del gobierno nacional o local?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 9, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'H20', 'h20_19', 'de una beca de estudio?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 10, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'H20', 'h20_12', 'comprando fiado o en cuotas', '(libreta, tarjeta de crédito)?', 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 11, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'H20', 'h20_11', 'gastando lo que tenía ahorrado?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 12, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'H20', 'h20_14', 'de alguna otra forma?', '(especificar)', 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 13, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'X5_tot', 'x5_tot', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 10, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', 'X', 'sexo_ex', 'sexo_ex', NULL, NULL, 'sexo_ex', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', 'X', 'pais_nac', 'pais_nac', NULL, NULL, 'pais_nac', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', 'X', 'edad_ex', 'edad_ex', NULL, '              En años cumplidos', NULL, NULL, 'edad', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 120, 0, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', 'X', 'niv_educ', 'niv_educ', NULL, NULL, 'niv_educ', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 4, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', 'X', 'anio', 'anio', NULL, NULL, NULL, NULL, 'anio', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2013, 1900, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', 'X', 'lugar', 'lugar', NULL, NULL, 'lugar', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 3, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I3', 'i3_1', 'jubilación o pensión?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 10, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I3', 'i3_2', 'alquileres, rentas o intereses?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 20, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I3', 'i3_3', 'utilidades, beneficios o dividendos?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 30, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I3', 'i3_4', 'seguro de desempleo?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 40, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I3', 'i3_5', 'indemnización por despido?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 50, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I3', 'i3_6', 'becas de estudio?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 60, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I3', 'i3_7', 'cuota por alimentos?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 70, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I3', 'i3_8', 'aportes de personas que no viven en el hogar?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 80, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I3', 'i3_11', 'el Programa Ciudadanía Porteña?', '(tarjeta cabal)', 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 90, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I3', 'i3_10', 'algún otro ingreso?', '(en dinero). Especificar', 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 110, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I3', 'i3_10x', '$', NULL, NULL, NULL, 'monetaria', NULL, 'i3_10', '1', NULL, 'i3_10=1', false, NULL, 111, NULL, NULL, NULL, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I3', 'i3_12x', '$', NULL, NULL, NULL, 'monetaria', NULL, 'i3_12', '1', NULL, 'i3_12=1', false, NULL, 101, NULL, NULL, NULL, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I3', 'i3_11x', '$', NULL, NULL, NULL, 'monetaria', NULL, 'i3_11', '1', NULL, 'i3_11=1', false, NULL, 91, NULL, NULL, NULL, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I3', 'i3_8x', '$', NULL, NULL, NULL, 'monetaria', NULL, 'i3_8', '1', NULL, 'i3_8=1', false, NULL, 81, NULL, NULL, NULL, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I3', 'i3_7x', '$', NULL, NULL, NULL, 'monetaria', NULL, 'i3_7', '1', NULL, 'i3_7=1', false, NULL, 71, NULL, NULL, NULL, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I3', 'i3_5x', '$', NULL, NULL, NULL, 'monetaria', NULL, 'i3_5', '1', NULL, 'i3_5=1', false, NULL, 51, NULL, NULL, NULL, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I3', 'i3_4x', '$', NULL, NULL, NULL, 'monetaria', NULL, 'i3_4', '1', NULL, 'i3_4=1', false, NULL, 41, NULL, NULL, NULL, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I3', 'i3_3x', '$', NULL, NULL, NULL, 'monetaria', NULL, 'i3_3', '1', NULL, 'i3_3=1', false, NULL, 31, NULL, NULL, NULL, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I3', 'i3_2x', '$', NULL, NULL, NULL, 'monetaria', NULL, 'i3_2', '1', NULL, 'i3_2=1', false, NULL, 21, NULL, NULL, NULL, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I3', 'i3_1x', '$', NULL, NULL, NULL, 'monetaria', NULL, 'i3_1', '1', NULL, 'i3_1=1', false, NULL, 11, NULL, NULL, NULL, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'S31', 's31_anio', 'Año', NULL, NULL, NULL, 'anio', NULL, NULL, NULL, NULL, NULL, false, NULL, 1, NULL, NULL, 2013, 1920, 2013, 1900, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'OBS', 'obs', NULL, NULL, NULL, NULL, 'observaciones', NULL, NULL, NULL, NULL, NULL, true, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'RespondI', 'respondi', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN1', 'sn1_2_esp', '¿A cuál?', NULL, NULL, NULL, 'texto_especificar', NULL, 'sn1_2', '1', NULL, 'sn1_2=1', false, NULL, 31, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN1', 'sn1_3_esp', '¿A cuál?', NULL, NULL, NULL, 'texto_especificar', NULL, 'sn1_3', '1', NULL, 'sn1_3=1', false, NULL, 41, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN1', 'sn1_4_esp', '¿A cuál?', NULL, NULL, NULL, 'texto_especificar', NULL, 'sn1_4', '1', NULL, 'sn1_4=1', false, NULL, 51, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN1', 'sn1_7_esp', '¿A cuál?', NULL, NULL, NULL, 'texto_especificar', NULL, 'sn1_7', '1', NULL, 'sn1_7=1', false, NULL, 21, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN12', 'sn12_esp', '¿cuántas?', NULL, NULL, NULL, 'numeros', NULL, 'sn12', '2', NULL, 'sn12=2', false, NULL, 2, 99, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN14', 'sn14_esp', 'especificar', NULL, NULL, NULL, 'texto_especificar', NULL, 'sn14', '4', NULL, 'sn14=4', false, NULL, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN15', 'sn15k_esp', '¿Cuál?', NULL, NULL, NULL, 'texto_especificar', NULL, 'sn15k', '1', NULL, 'sn15k=1', false, NULL, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'M1', 'm1_esp4', 'especificar', NULL, NULL, NULL, 'texto_especificar', NULL, 'm1', '4', NULL, 'm1=4', false, NULL, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T53_bis1', 't53_bis1_sem', '¿Cuántos días por semana?', NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, 't53_bis1=1 or t53_bis1=2', false, NULL, 1, 99, NULL, 7, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T53_bis1', 't53_bis1_mes', '¿Cuántos días por mes?', NULL, NULL, NULL, 'numeros', 'T53c', NULL, NULL, NULL, 't53_bis1=3', false, NULL, 2, 99, NULL, 31, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'M4', 'm4_esp1', 'especificar partido/ localidad', NULL, NULL, NULL, 'texto_especificar', NULL, 'm4', '1', NULL, 'm4=1', false, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'M4', 'm4_esp2', 'especificar', NULL, NULL, NULL, 'texto_especificar', NULL, 'm4', '2', NULL, 'm4=2', false, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'M4', 'm4_esp3', 'especificar', NULL, NULL, NULL, 'texto_especificar', NULL, 'm4', '3', NULL, 'm4=3', false, NULL, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN1', 'sn1_1_esp', '¿A cuál?', NULL, NULL, NULL, 'texto_especificar', NULL, 'sn1_1', '1', NULL, 'sn1_1=1', false, NULL, 11, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T53', 't53_ing', '                                                       $', NULL, NULL, NULL, 'monetaria', NULL, NULL, NULL, NULL, NULL, false, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', '', 's1a1_obs', 's1a1_obs', NULL, NULL, NULL, NULL, 'observaciones', NULL, NULL, NULL, NULL, NULL, true, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T12', 't12', NULL, NULL, 't12', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, 'HIT', 1 , NULL),
('ebcp2014', 'I1', '', 'T1', 't1', NULL, NULL, 'si_no', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T10', 't10', NULL, NULL, 't10', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, 'HIT', 1 , NULL),
('ebcp2014', 'I1', '', 'T11', 't11', NULL, NULL, 't11', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 4, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T49', 't49', NULL, NULL, 't49', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 3, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T50', 't50a', 'tiene vacaciones pagas?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 1, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T50', 't50b', 'le pagan aguinaldo?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 2, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T50', 't50d', 'tiene indemnización por despido?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 4, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T50', 't50e', 'le descuentan para una obra social?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 5, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T50', 't50f', 'le pagan salario familiar?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 6, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T51', 't51', NULL, NULL, 't51', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 3, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T52', 't52a', 'comida en el lugar de trabajo?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 1, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T52', 't52b', 'vivienda o alquiler para la vivienda?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 2, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T52', 't52c', 'tickets de comida o de compra?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 3, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T53_bis2', 't53_bis2', NULL, NULL, NULL, NULL, 'horas', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, 99, NULL, 24, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T53c', 't53c_anios', 'Años', NULL, NULL, NULL, 'anios', NULL, NULL, NULL, NULL, NULL, true, NULL, 1, NULL, NULL, 80, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN3', 'sn3', NULL, NULL, 'sn3', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 5, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T54', 't54', NULL, NULL, 'si_no', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T54b', 't54b', NULL, NULL, NULL, NULL, 'anios', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 100, 0, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'M1', 'm1', NULL, NULL, 'm1', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 4, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'M3', 'm3', NULL, NULL, 'm3', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'M3', 'm3_anio', NULL, NULL, NULL, NULL, 'anio', NULL, 'm3', '2', NULL, 'm3=2', false, NULL, 2, NULL, NULL, 2013, 1900, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'M4', 'm4', NULL, NULL, 'm4', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 3, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'M5', 'm5', NULL, NULL, 'm5', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 4, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN1', 'sn1_1', 'una obra social?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 10, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN1', 'sn1_7', 'una prepaga o mutual vía obra social?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 20, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN1', 'sn1_2', 'una mutual?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 30, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN1', 'sn1_3', 'un plan de medicina prepaga por contratación voluntaria ?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 40, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN1', 'sn1_4', 'un sistema de emergencias médicas?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 50, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN15', 'sn15a', 'Alergia', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 1, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN4', 'sn4', NULL, NULL, 'sn4', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 4, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN5', 'sn5', NULL, NULL, 'sn5', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, 99, NULL, 9, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN11', 'sn11', NULL, NULL, 'sn11', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN12', 'sn12', NULL, NULL, 'sn12', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN13', 'sn13', NULL, NULL, 'sn13', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 5, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN13', 'sn13_otro', NULL, NULL, NULL, NULL, 'texto_especificar', NULL, 'sn13', '5', NULL, 'sn13=5', false, NULL, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN14', 'sn14', NULL, NULL, 'sn14', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 4, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'S28', 's28', NULL, NULL, 's28', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN15', 'sn15b', 'Artritis/ reumatismo', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 2, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN15', 'sn15c', 'Presión alta', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 3, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN15', 'sn15d', 'Infarto de miocardio', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 4, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN15', 'sn15e', 'Otras enfermedades del corazón o arteriales', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 5, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN15', 'sn15f', 'Enfisema o bronquitis crónica', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 6, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN15', 'sn15g', 'Asma', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 7, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN15', 'sn15h', 'Diabetes', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 8, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN15', 'sn15j', 'Gastritis/ úlcera', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 10, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'S29', 's29', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, 99, NULL, 20, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T53c', 't53c_98', 'Si es menos de un mes consigne 98', NULL, NULL, NULL, 'marcar_nulidad', NULL, NULL, NULL, NULL, '!t53c_anios && !t53c_meses', false, NULL, 3, NULL, NULL, 98, 98, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'S30', 's30', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, 99, NULL, 20, 0, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'S31', 's31_mes', 'Mes', NULL, NULL, NULL, 'meses', NULL, NULL, NULL, NULL, NULL, true, NULL, 2, NULL, NULL, 12, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', 'X', 'lugar', 'lugar_esp1', NULL, NULL, NULL, NULL, 'texto_especificar', NULL, 'lugar', '1', NULL, 'lugar=1', false, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T24', 't24', NULL, NULL, NULL, NULL, 'texto_libre', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T25', 't25', NULL, NULL, NULL, NULL, 'texto_libre', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T26', 't26', NULL, NULL, NULL, NULL, 'texto_libre', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T31', 't31_d', 'el domingo?', NULL, NULL, NULL, 'horas', NULL, NULL, NULL, NULL, NULL, false, NULL, 1, 99, NULL, 33, 0, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T31', 't31_j', 'el jueves?', NULL, NULL, NULL, 'horas', NULL, NULL, NULL, NULL, NULL, false, NULL, 5, 99, NULL, 33, 0, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T31', 't31_l', 'el lunes?', NULL, NULL, NULL, 'horas', NULL, NULL, NULL, NULL, NULL, false, NULL, 2, 99, NULL, 33, 0, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T31', 't31_ma', 'el martes?', NULL, NULL, NULL, 'horas', NULL, NULL, NULL, NULL, NULL, false, NULL, 3, 99, NULL, 33, 0, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T31', 't31_mi', 'el miércoles?', NULL, NULL, NULL, 'horas', NULL, NULL, NULL, NULL, NULL, false, NULL, 4, 99, NULL, 33, 0, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T31', 't31_s', 'el sábado?', NULL, NULL, NULL, 'horas', NULL, NULL, NULL, NULL, NULL, false, NULL, 7, 99, NULL, 33, 0, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T31', 't31_v', 'el viernes?', NULL, NULL, NULL, 'horas', NULL, NULL, NULL, NULL, NULL, false, NULL, 6, 99, NULL, 33, 0, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T32', 't32_d', 'el domingo?', NULL, NULL, NULL, 'horas', NULL, NULL, NULL, NULL, 't30=2', false, NULL, 1, 99, NULL, 33, 0, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T32', 't32_j', 'el jueves?', NULL, NULL, NULL, 'horas', NULL, NULL, NULL, NULL, 't30=2', false, NULL, 5, 99, NULL, 33, 0, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T32', 't32_l', 'el lunes?', NULL, NULL, NULL, 'horas', NULL, NULL, NULL, NULL, 't30=2', false, NULL, 2, 99, NULL, 33, 0, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T32', 't32_ma', 'el martes?', NULL, NULL, NULL, 'horas', NULL, NULL, NULL, NULL, 't30=2', false, NULL, 3, 99, NULL, 33, 0, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T32', 't32_mi', 'el miércoles?', NULL, NULL, NULL, 'horas', NULL, NULL, NULL, NULL, 't30=2', false, NULL, 4, 99, NULL, 33, 0, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T32', 't32_s', 'el sábado?', NULL, NULL, NULL, 'horas', NULL, NULL, NULL, NULL, 't30=2', false, NULL, 7, 99, NULL, 33, 0, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T32', 't32_v', 'el viernes?', NULL, NULL, NULL, 'horas', NULL, NULL, NULL, NULL, 't30=2', false, NULL, 6, 99, NULL, 33, 0, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', 'P', 'P1', 'nombre', NULL, NULL, NULL, NULL, 'texto_libre', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', '', 'razon', 'razon1', NULL, NULL, 'razon1', NULL, 'opciones', NULL, NULL, NULL, NULL, 'entrea=2', false, NULL, 0, 99, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', '', 'razon_1', 'razon2_1', NULL, NULL, 'razon2_1', NULL, 'opciones', NULL, NULL, NULL, NULL, 'razon1=1', false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN4', 'sn4_esp', NULL, NULL, NULL, NULL, 'texto_especificar', NULL, 'sn4', '4', NULL, 'sn4=4', false, NULL, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN5', 'sn5_esp', NULL, NULL, NULL, NULL, 'texto_especificar', NULL, 'sn5', '9', NULL, 'sn5=9', false, NULL, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T8', 't8_otro', '(especificar)', NULL, NULL, NULL, 'texto_especificar', NULL, 't8', '3', NULL, 't8=3', false, NULL, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T11', 't11_otro', '(especificar)', NULL, NULL, NULL, 'texto_especificar', 'T13', 't11', '4', NULL, 't11=4', false, NULL, 4, NULL, NULL, NULL, NULL, NULL, NULL, 'T13', 1 , NULL),
('ebcp2014', 'S1', '', 'razon_2', 'razon2_2', NULL, NULL, 'razon2_2', NULL, 'opciones', NULL, NULL, NULL, NULL, 'razon1=2', false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', '', 'razon_3', 'razon2_3', NULL, NULL, 'razon2_3', NULL, 'opciones', NULL, NULL, NULL, NULL, 'razon1=3', true, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', '', 'razon_4', 'razon2_4', NULL, NULL, 'razon2_4', NULL, 'opciones', NULL, NULL, NULL, NULL, 'razon1=4', false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', '', 'razon_5', 'razon2_5', NULL, NULL, 'razon2_5', NULL, 'opciones', NULL, NULL, NULL, NULL, 'razon1=5', false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', '', 'razon_6', 'razon2_6', NULL, NULL, 'razon2_6', NULL, 'opciones', NULL, NULL, NULL, NULL, 'razon1=6', false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', '', 'razon_6', 'razon3', NULL, NULL, NULL, NULL, 'texto_especificar', NULL, 'razon2_6', '4', NULL, 'razon2_6=4', false, NULL, 65, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', '', 'razon_7', 'razon2_7', NULL, NULL, 'razon2_7', NULL, 'opciones', NULL, NULL, NULL, NULL, 'razon1=7', false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', '', 'razon_8', 'razon2_8', NULL, NULL, 'razon2_8', NULL, 'opciones', NULL, NULL, NULL, NULL, 'razon1=8', false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', '', 'razon_9', 'razon2_9', NULL, NULL, 'razon2_9', NULL, 'opciones', NULL, NULL, NULL, NULL, 'razon1=9', false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', 'P', 'P5', 'p5', NULL, NULL, 'p5', NULL, 'opciones', NULL, NULL, NULL, NULL, 'edad>=14 and p7<3', false, NULL, 0, 99, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', 'P', 'P5B', 'p5b', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, '(edad>=14) and (p5=1 or p5=2) and p7<3', false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', 'P', 'P6', 'p6_b', 'Madre', 'Si no vive en el hogar anote 95', NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, 'edad<=24 and p7<3', false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', '', 'f_realiz_o', 'f_realiz_o', NULL, NULL, NULL, NULL, 'fecha_corta', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', '', 'nombrer', 'nombrer', NULL, NULL, NULL, NULL, 'texto_libre', NULL, NULL, NULL, NULL, NULL, true, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', '', 'respond', 'respond', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, true, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', '', 'telefono', 'movil', 'Teléfono móvil', NULL, NULL, NULL, 'telefono', NULL, NULL, NULL, NULL, NULL, true, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', '', 'V1', 'v1', NULL, NULL, 'v1', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', '', 'telefono', 'telefono', 'Teléfono del hogar', NULL, NULL, NULL, 'telefono', NULL, NULL, NULL, NULL, NULL, true, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),

('ebcp2014', 'I1', '', 'M1', 'm1_anio', '¿En qué año llegó al país?', NULL, NULL, NULL, 'anio', '', 'm1', '4', NULL, 'm1=4', false, NULL, 5, NULL, NULL, NULL, NULL, NULL, NULL, 'M3', 1 , NULL),
('ebcp2014', 'S1', 'P', 'P3B', 'edad', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, 'p7<3', false, NULL, 0, NULL, NULL, 130, 0, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', 'P', 'P8', 'p8', NULL, NULL, 'p8', NULL, 'opciones', NULL, NULL, NULL, NULL, 'copia_participacion>1', false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T2', 't2', NULL, NULL, 'si_no', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', 'P', 'P2', 'sexo', NULL, NULL, 'sexo', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T3', 't3', NULL, NULL, 't3', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 5, 1, NULL, NULL, 'HIT', 1 , NULL),
('ebcp2014', 'I1', '', 'T7', 't7', NULL, NULL, 'si_no', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, 'T30', 1 , NULL),
('ebcp2014', 'I1', '', 'T4', 't4', NULL, NULL, 't4', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 5, 1, NULL, NULL, 'HIT', 1 , NULL),
('ebcp2014', 'I1', '', 'T5', 't5', NULL, NULL, 'si_no_nosabe3', NULL, 'si_no_nosabe3', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 3, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T6', 't6', NULL, NULL, 'si_no_nosabe3', NULL, 'si_no_nosabe3', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 3, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T16', 't16', NULL, NULL, 't16', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, 'T18', 1 , NULL),
('ebcp2014', 'I1', '', 'T9', 't9', NULL, NULL, 't9', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T14', 't14', NULL, NULL, 't14', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, 'HIT', 1 , NULL),
('ebcp2014', 'I1', '', 'T15', 't15', NULL, NULL, 't15', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 5, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T18', 't18', NULL, NULL, 't18', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, 'HIT', 1 , NULL),
('ebcp2014', 'I1', '', 'T17', 't17', NULL, NULL, 't17', NULL, 'opciones', 'T20', NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 5, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T28', 't28', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 10, 1, 5, 1, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T20', 't20', NULL, NULL, 't20', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 3, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T22', 't22', NULL, NULL, 't22', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 3, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T23', 't23', NULL, NULL, NULL, NULL, 'texto_libre', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T19', 't19_anio', NULL, NULL, NULL, NULL, 'anio', NULL, NULL, NULL, NULL, NULL, false, NULL, 1, NULL, NULL, 2013, 1920, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T27', 't27', NULL, NULL, 't27', NULL, 'opciones', 'I1', NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T34', 't34', NULL, NULL, 't34', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T29', 't29', NULL, NULL, 't29', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 3, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T29a', 't29a', NULL, NULL, 't29a', NULL, 'opciones', 'T35', NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T33', 't33', NULL, NULL, 't33', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T35', 't35', NULL, NULL, 't35', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, 'T37', 1 , NULL),
('ebcp2014', 'I1', '', 'T36b', 't36b', NULL, NULL, 't36b', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 1, NULL, NULL, 4, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN2', 'sn2', NULL, NULL, 'si_no', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, 'sn4', 1 , NULL),
('ebcp2014', 'I1', '', 'SN15', 'sn15k', 'Otra', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 11, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'I3', 'i3_10_otro', '', NULL, NULL, NULL, 'texto_especificar', NULL, 'i3_10', '1', NULL, 'i3_10=1', false, NULL, 112, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', '', 'total_h', 'total_h', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, NULL, 1, 4, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', '', 'total_m', 'total_m', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, NULL, 1, 20, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T39', 't39_otro', '(especificar)', NULL, NULL, NULL, 'texto_especificar', '', 't39', '4', NULL, 't39=4', false, NULL, 4, NULL, NULL, NULL, NULL, NULL, NULL, 't39_bis2', 1 , NULL),
('ebcp2014', 'I1', '', 'T39', 't39_barrio', 'Barrio/ calles', NULL, NULL, NULL, 'texto_especificar', '', 't39', '2', NULL, 't39=2', false, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, 't39_bis2', 1 , NULL),
('ebcp2014', 'I1', '', 'I2', 'i2_totx', 'Total Ingresos', '    $', NULL, NULL, 'monetaria', NULL, NULL, NULL, NULL, NULL, false, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'TEM', '', 'estado', 'estado', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'asignable', 'asignable', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'cod_enc', 'cod_enc', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'dispositivo_enc', 'dispositivo_enc', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'recepcionista', 'recepcionista', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'fecha_carga_enc', 'fecha_carga_enc', NULL, NULL, NULL, NULL, 'timestamp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'fecha_primcarga_enc', 'fecha_primcarga_enc', NULL, NULL, NULL, NULL, 'timestamp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'fecha_descarga_enc', 'fecha_descarga_enc', NULL, NULL, NULL, NULL, 'timestamp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'a_ingreso_enc', 'a_ingreso_enc', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'volver_a_cargar_enc', 'volver_a_cargar_enc', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'fin_ingreso_enc', 'fin_ingreso_enc', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'rea_enc', 'rea_enc', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'comenzo_ingreso', 'comenzo_ingreso', NULL, NULL, NULL, NULL, 'timestamp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'norea_enc', 'norea_enc', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'rea', 'rea', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'norea', 'norea', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'hog_pre', 'hog_pre', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'hog_tot', 'hog_tot', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'pob_pre', 'pob_pre', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'pob_tot', 'pob_tot', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'con_dato_enc', 'con_dato_enc', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'carga', 'carga', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'cantidad_inconsistencias', 'cantidad_inconsistencias', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'verificado_enc', 'verificado_enc', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'comenzo_consistencias', 'comenzo_consistencias', NULL, NULL, NULL, NULL, 'timestamp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'cod_recu', 'cod_recu', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'dispositivo_recu', 'dispositivo_recu', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'fecha_carga_recu', 'fecha_carga_recu', NULL, NULL, NULL, NULL, 'timestamp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'fecha_primcarga_recu', 'fecha_primcarga_recu', NULL, NULL, NULL, NULL, 'timestamp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'fecha_descarga_recu', 'fecha_descarga_recu', NULL, NULL, NULL, NULL, 'timestamp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'a_ingreso_recu', 'a_ingreso_recu', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'volver_a_cargar_recu', 'volver_a_cargar_recu', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'fin_ingreso_recu', 'fin_ingreso_recu', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'rea_recu', 'rea_recu', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'norea_recu', 'norea_recu', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'con_dato_recu', 'con_dato_recu', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'verificado_recu', 'verificado_recu', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'per', 'per', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 'case when pla_estado<=29 then pla_cod_enc when pla_estado<=39 then pla_cod_recu when pla_estado<49 then pla_cod_supe when pla_estado<59 then pla_cod_supr else null end'),
('ebcp2014', 'TEM', '', 'rol', 'rol', NULL, NULL, NULL, NULL, 'texto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 'case when pla_estado<=29 then ''encuestador'' when pla_estado<=39 then ''recuperador'' when pla_estado<59 then ''supervisor'' else null end'),
('ebcp2014', 'TEM', '', 'en_campo', 'en_campo', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 'case when pla_estado in (23,24,33,34,44,54) then 1 else 0 end'),
('ebcp2014', 'TEM', '', 'fecha_comenzo_descarga', 'fecha_comenzo_descarga', NULL, NULL, NULL, NULL, 'timestamp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'I1', '', 'T50', 't50c', 'tiene días pagos por enfermedad o accidente?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 3, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'S1', 'P', 'P7', 'p7', NULL, NULL, 'p7', NULL, 'opciones', NULL, NULL, NULL, NULL, 'copia_participacion>1', false, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T13', 't13', NULL, NULL, 't13', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'SN2', 'sn2_cant', '¿Cuántas consultas?', NULL, NULL, NULL, 'numeros', 'SN4', 'sn2', '1', NULL, 'sn2=1', false, NULL, 1, 99, NULL, 50, 1, 10, 1, 'sn4', 1 , NULL),
('ebcp2014', 'I1', '', 'M1', 'm1_esp3', 'especificar', NULL, NULL, NULL, 'texto_especificar', '', 'm1', '3', NULL, 'm1=3', false, NULL, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'M1', 'm1_esp2', 'especificar partido/ localidad ', NULL, NULL, NULL, 'texto_especificar', '', 'm1', '2', NULL, 'm1=2', false, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'H20', 'h20_2', 'de la jubilación o pensión de alguno/s de los miembros del hogar?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 2, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'TEM', '', 'sup_aleat_enc', 'sup_aleat', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'I1', '', 'I3', 'i3_12', 'otro subsidio o plan social, en dinero, del gobierno?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 100, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'TEM', '', 'sup_dirigida_enc', 'sup_dirigida', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'cod_supe', 'cod_sup', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'fecha_carga_supe', 'fecha_carga_sup', NULL, NULL, NULL, NULL, 'timestamp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'result_supe', 'result_sup', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'TEM', '', 'verificado_supe', 'verificado_sup', NULL, NULL, NULL, NULL, 'numeros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, ''),
('ebcp2014', 'I1', '', 'T21', 't21', NULL, NULL, 't21', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 3, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T53_bis1', 't53_bis1', '                                           ', NULL, 't53_bis1', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 3, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'A1', '', 'H20', 'h20_15', 'de lo que recibe del Programa Ciudadanía Porteña a través de la tarjeta de compra Cabal?', NULL, 'si_no_h', NULL, 'si_no', NULL, NULL, NULL, NULL, NULL, false, NULL, 8, NULL, NULL, 2, 1, NULL, NULL, NULL, 1 , NULL),
('ebcp2014', 'I1', '', 'T30', 't30', NULL, NULL, 't30', NULL, 'opciones', NULL, NULL, NULL, NULL, NULL, false, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, 1, NULL);