INSERT INTO encu.varcal(
            varcal_ope, varcal_varcal, varcal_destino, varcal_orden, varcal_nombre, 
            varcal_comentarios, varcal_tlg, varcal_activa, varcal_tipo, varcal_baseusuario, 
            varcal_nombrevar_baseusuario) VALUES 
('ebcp2014', 'h_perhab', 'hog', 830, 'h perhab', 'variable auxiliar para construir h_hacina', 1, true, 'normal', false, NULL),
('ebcp2014', 'f_edad', 'mie', 4000, 'Grupo de edad (años)', NULL, 1, true, 'normal', false, NULL),
('ebcp2014', 'cond_activ', 'mie', 580, 'Condición de actividad', NULL, 1, true, 'normal', false, NULL),
('ebcp2014', 'edad10a', 'mie', 100, 'Grupo de edad (años)', '', 1, true, 'normal', false, NULL),
('ebcp2014', 'h2_2', 'hog', 740, 'Régimen de tenencia de la vivienda', '', 1, true, 'normal', false, NULL),
('ebcp2014', 'h2_re', 'hog', 690, 'Régimen de tenencia de la vivienda', 'Ver si van a existir los sin dato y si es así con que valor van a aparecer en la base. La sintaxis supone que existen y que están representados por 0.', 1, true, 'normal', false, NULL),
('ebcp2014', 't_desoc', 'mie', 370, 't desoc', 'Variable auxiliar para construir cond_activ (condición de actividad)', 1, true, 'normal', false, NULL),
('ebcp2014', 't_ina', 'mie', 530, 't ina', 'Variable auxiliar para construir cond_activ (condición de actividad)', 1, true, 'normal', false, NULL),
('ebcp2014', 'tot_mi', 'hog', 620, 'Cantidad de personas en el hogar (abierta)', 'Acordar si la etiqueta de la variable sale con un nombre intermedio (que ayude a controlar el cuadro) o el nombre definitivo con el que sale el cuadro puntual', 1, true, 'normal', false, NULL),
('ebcp2014', 's28r', 'mie', 4001, 'Mujeres', NULL, 1, true, 'normal', false, NULL),
('ebcp2014', 'f_n_hij', 'mie', 4002, 'Cantidad de hijos', NULL, 1, true, 'normal', false, NULL),
('ebcp2014', 'e_nivel', 'mie', 1460, 'Máximo Nivel Educativo Alcanzado', 'excluye otras especiales no prim', 1, true, 'normal', false, NULL),
('ebcp2014', 'e_nivela', 'mie', 960, 'Nivel educativo al que asiste', 'Variable auxiliar para construir e_nivel. VER como llenar con ceros el resto de los casos: not(…) and not(…) - missing - null???', 1, true, 'normal', false, NULL),
('ebcp2014', 'e_nivelb', 'mie', 1090, 'Máximo nivel al que asistió', 'Variable auxiliar para construir e_nivel. VER como llenar con ceros el resto de los casos: not(…) and not(…) - missing - null???', 1, true, 'normal', false, NULL),
('ebcp2014', 'e_nivelc', 'mie', 1290, 'Máximo Nivel Educativo Alcanzado (desagregado)', 'Variable auxiliar para construir e_nivel. VER como llenar con ceros el resto de los casos: not(…) and not(…) - missing - null???', 1, true, 'normal', false, NULL),
('ebcp2014', 'm_rallp', 'mie', 2740, 'Año de llegada al país', 'La categoría 8 se actualiza todos los años. En algún momento Victoria Mazzeo debería desdoblarla', 1, true, 'normal', false, NULL),
('ebcp2014', 'categori', 'mie', 3350, 'Categoría ocupacional', NULL, 1, true, 'normal', false, NULL),
('ebcp2014', 't_categ', 'mie', 3290, 't categ', 'Variable auxiliar para construir CATEGORI (categoría ocupacional)', 1, true, 'normal', false, NULL),
('ebcp2014', 't51_re', 'mie', 3390, 'Cobertura jubilación', 'Requiere consistida la t51', 1, true, 'normal', false, NULL),
('ebcp2014', 'tipodes', 'mie', 3470, 'Tipo de desocupado', 'Requiere consistidas las variables t16 y t18', 1, true, 'normal', false, NULL),
('ebcp2014', 's_edad', 'mie', 2250, 'Grupo de edad (años)', NULL, 1, true, 'normal', false, NULL),
('ebcp2014', 'edad10b', 'mie', 230, 'Grupo de edad (años)', NULL, 1, true, 'normal', false, NULL),
('ebcp2014', 'tot_mr', 'hog', 630, 'Cantidad de personas en el hogar (grupo final cerrado)', 'Requiere la construcción de tot_mi', 1, true, 'normal', false, NULL),
('ebcp2014', 'm_ln1', 'mie', 2660, 'Lugar de nacimiento', '', 1, true, 'normal', false, NULL),
('ebcp2014', 'm1_2', 'mie', 1000, 'Lugar de nacimiento recategorizado', 'Nacidos en Perú junto a países limítrofes', 1, true, 'normal', false, NULL),
('ebcp2014', 'v2_re', 'hog', 910, 'Tipo de vivienda', 'V2 agregada en casa dpto y otros', 1, true, 'normal', false, NULL),
('ebcp2014', 'zona_3', 'hog', 190, 'Zona', NULL, 1, true, 'normal', false, NULL),
('ebcp2014', 'v2_2_mie', 'mie', 920, 'Tipo de vivienda', 'variable generada para tener v2 en base individuos', 1, true, 'normal', false, NULL),
('ebcp2014', 'categdes', 'mie', 4200, 'Categoría ocupacional para desocupados', 'requiere construcción de estado', 1, true, 'normal', false, NULL),
('ebcp2014', 'zona_3_1', 'mie', 200, 'Zona', 'zona para población (cuadro 26)', 1, true, 'normal', false, NULL),
('ebcp2014', 't_intens', 'mie', 2950, 'Horas semanales trabajadas por tramos ', 'Requiere la construcción de tsemref y sem_hs', 1, true, 'normal', false, NULL),
('ebcp2014', 's_tipco', 'mie', 2310, 'Tipo de cobertura desagregada', 'Variable auxiliar para construir s_tipco3', 1, true, 'normal', false, NULL),
('ebcp2014', 's_tipco2', 'mie', 2570, 'Tipo de cobertura', NULL, 1, true, 'normal', false, NULL),
('ebcp2014', 's_tipco3', 'mie', 2420, 'Tipo de cobertura', 'variable auxiliar para construir s_tipco3r', 1, true, 'normal', false, NULL),
('ebcp2014', 's_tipco3r', 'mie', 2500, 'Tipo de cobertura', NULL, 1, true, 'normal', false, NULL),
('ebcp2014', 'h_hacina', 'hog', 840, 'Personas por ambiente', NULL, 1, true, 'normal', false, NULL),
('ebcp2014', 't_ramde2', 'mie', 3520, 'Rama de actividad versión agregada tab. intranet (para desocupados)', 'Requiere la construcción de t_ramdes', 1, true, 'normal', false, NULL),
('ebcp2014', 'ingtot', 'mie', 4307, 'Monto de ingreso total individual (mes pasado)', '(i2+i3) sin tickets. Faltan más sintaxis de controles.', 1, true, 'normal', false, NULL),
('ebcp2014', 'codlab', 'mie', 4210, 'Declaración de ingresos laborales', '(sin tickets)', 1, true, 'normal', false, NULL),
('ebcp2014', 'codnolab', 'mie', 4211, 'Declaración de ingresos no laborales ', NULL, 1, true, 'normal', false, NULL),
('ebcp2014', 'tsemref', 'mie', 2800, 'Ocupados que trabajaron la semana de referencia', NULL, 1, true, 'normal', false, NULL),
('ebcp2014', 'coding', 'mie', 4220, 'Declaración ingresos totales individuales', 'Sin tickets', 1, true, 'normal', false, NULL),
('ebcp2014', 'ipcf', 'hog', 4230, 'Ingreso per capita familiar (mes pasado)', 'Excluye scio dom del denominador además del numerador SIN TICKETS', 1, true, 'normal', false, NULL),
('ebcp2014', 'e_raesc', 'mie', 2170, 'Años de escolarización', '', 1, true, 'normal', false, NULL),
('ebcp2014', 'itf', 'hog', 5500, 'Ingreso total familiar', 'Excluye personal doméstico', 1, true, 'normal', false, NULL),
('ebcp2014', 't_ocup', 'mie', 290, 'T ocup', 'Variable auxiliar para construir cond_activ (condición de actividad)', 1, true, 'normal', false, NULL),
('ebcp2014', 'e_aesc', 'mie', 1560, 'Años de escolarización (desagregada)', 'variable auxiliar para construir e_raesc. VER Opciones cargadas', 1, true, 'normal', false, NULL),
('ebcp2014', 'codi_tot', 'hog', 4302, 'Declaración de ingresos totales familiares', 'Sin tickets. Ver con Teresa construccion de esta variable', 1, true, 'normal', false, NULL),
('ebcp2014', 't39_comu', 'mie', 3460, 'Comuna generada', 'Variable auxiliar para construir t39_zona', 1, true, 'normal', false, NULL),
('ebcp2014', 't_ramoc2', 'mie', 3230, 'Rama de actividad versión agregada tab. intranet (para ocupados)', 'Requiere la construcción de t_ramocu', 1, true, 'normal', false, NULL),
('ebcp2014', 't_ramocu', 'mie', 3010, 'Rama de actividad para ocupados', 'Requiere la codificación de la actividad para ocupados', 1, false, 'normal', false, NULL),
('ebcp2014', 't_deman', 'mie', 3580, 'Condición de subocupación de los ocupados demandantes de otra ocupación', 'Requiere la costrucción de tsemref y consistida t35', 1, false, 'normal', false, NULL),
('ebcp2014', 'm_limit', 'mie', 2620, 'Marcador de lugar de nacimiento=país limítrofe', 'La construcción de esta variable varía según los textos año a año. Variable auxiliar para construir m_ln1', 1, true, 'normal', false, NULL),
('ebcp2014', 't_diastra1p', 'mie', 2820, 'días de la semana trabajados en la ocupación principal', 'para imputación de feriados y licencias en sem_hs1p', 1, true, 'normal', false, NULL),
('ebcp2014', 'sn1_1a7', 'mie', 2290, 'sn1 1a7', 'La sintaxis de SPSS está pensada con la lógica con la que se cargaba en 2012 las SN1_x (con 0 y 1). Variable auxiliar para construir s_tipco. ', 1, true, 'normal', false, NULL),
('ebcp2014', 'sn1_99', 'mie', 2300, 'sn1 99', NULL, 1, true, 'normal', false, NULL),
('ebcp2014', 'itf_calc', 'hog', 5480, 'Ingreso total familiar', 'Para calcular itf con categorías. Excluye personal doméstico', 1, true, 'normal', false, NULL),
('ebcp2014', 'pobnosd', 'hog', 626, 'Cantidad de personas en el hogar sin servicio doméstico', 'denominador de ipcf', 1, true, 'normal', false, NULL),
('ebcp2014', 'ipcf_calc', 'hog', 4229, 'Ingreso per capita familiar (mes pasado) sin categorías', 'da negativo para nsnc', 1, true, 'normal', false, NULL),
('ebcp2014', 'igtot', 'mie', 4308, 'Monto de ingreso total individual (mes pasado)', 'ingtot para tabulados (no tiene que tener in)', 1, true, 'normal', false, NULL),
('ebcp2014', 't_diasnotr2p', 'mie', 2850, 'días de la semana no trabajados en la/s otra/s ocupación/es ', 'para imputación de feriados y licencias en sem_hs2p', 1, true, 'normal', false, NULL),
('ebcp2014', 't_activ', 'mie', 590, 'Condición de actividad', NULL, 1, true, 'normal', false, NULL),
('ebcp2014', 't_diastra2p', 'mie', 2830, 'días de la semana trabajados en la/s otra/s ocupación/es ', 'para imputación de feriados y licencias en sem_hs2p', 1, true, 'normal', false, NULL),
('ebcp2014', 't_empleo', 'mie', 600, 'Condición de empleo', NULL, 1, true, 'normal', false, NULL),
('ebcp2014', 't_desocup', 'mie', 610, 'Condición de desempleo', NULL, 1, true, 'normal', false, NULL),
('ebcp2014', 't39_zona', 'mie', 3462, 'Zona generada', 'Variable auxiliar para construir t39_rec', 1, true, 'normal', false, NULL),
('ebcp2014', 't39_rec', 'mie', 3464, 'Ubicación del lugar de trabajo', 'Para cuadro 41', 1, true, 'normal', false, NULL),
('ebcp2014', 'sem_hs1p', 'mie', 2860, 'Cantidad de horas trabajadas en cada día de la semana de referencia en la ocupación principal', NULL, 1, true, 'normal', false, NULL),
('ebcp2014', 'sem_hs2p', 'mie', 2870, 'Cantidad de horas trabajadas en cada día de la semana de referencia en la otra ocupación ', NULL, 1, true, 'normal', false, NULL),
('ebcp2014', 't_subocup', 'mie', 620, 'Condición de subocupación', NULL, 1, false, 'normal', false, NULL),
('ebcp2014', 't_suboc3', 'mie', 296, NULL, 'Para construir t_deman', 1, false, 'normal', false, NULL),
('ebcp2014', 't_diasnotr1p', 'mie', 2840, 'días de la semana no trabajados en la ocupación principal', 'para imputación de feriados y licencias en sem_hs1p', 1, true, 'normal', false, NULL),
('ebcp2014', 't23_cod', 'mie', 1, 'Código rama de actividad para desoc cesantes', NULL, 1, true, 'externo', false, NULL),
('ebcp2014', 't24_cod', 'mie', 1, 'Código ocupación para desoc cesantes', NULL, 1, true, 'externo', false, NULL),
('ebcp2014', 't37_cod', 'mie', 1, 'Código rama de actividad para ocupados', NULL, 1, true, 'externo', false, NULL),
('ebcp2014', 't41_cod', 'mie', 1, 'Código ocupación para ocupados', NULL, 1, true, 'externo', false, NULL),
('ebcp2014', 'fexp', 'tem', 100, 'Factor de expansión', NULL, 1, true, 'externo', false, NULL),
('ebcp2014', 'v2_2', 'hog', 915, 'Tipo de vivienda', 'v2 para BU', 1, true, 'normal', true, 'v2_2'),
('ebcp2014', 'hacinam_2', 'hog', 841, 'Hacinamiento', NULL, 1, true, 'normal', true, 'hacinam_2'),
('ebcp2014', 'sem_hs', 'mie', 2890, 'cantidad de horas trabajadas en cada día de la semana de referencia', 'tiene imputados por media feriados y licencias', 1, true, 'normal', false, NULL),
('ebcp2014', 't_edad', 'mie', 322, 'Grupos de edad (años)', 'Grupos de edad para CUADRO 45', 1, true, 'normal', false, NULL),
('ebcp2014', 'fp5_r', 'mie', 502, 'Situación conyugal', 'Para cuadro 50', 1, true, 'normal', false, NULL),
('ebcp2014', 'fp5_agr', 'mie', 503, 'Situación conyugal agregada', 'Para cuadro 51', 1, true, 'normal', false, NULL),
('ebcp2014', 'sc_edad', 'mie', 324, 'Grupos de edad (años)', 'Grupos de edad para CUADRO 50', 1, true, 'normal', false, NULL);