CREATE TABLE encu.diccionario_agregar (
  diccionario text,
  origen text,
  destino text
  )
  WITH (
  OIDS=FALSE
);
ALTER TABLE encu.diccionario_agregar
  OWNER TO tedede_php;


insert into encu.diccionario_agregar values
('sn4_esp_txt', 'ADELGAZAR','8'),
('sn4_esp_txt', 'ADICCIONES','1'),
('sn4_esp_txt', 'APTO PSICOFISICO','3'),
('sn4_esp_txt', 'ART PROVINCIA','4'),
('sn4_esp_txt', 'ATAQUE DE PANICO','1'),
('sn4_esp_txt', 'ATENCION DEL PARTO','3'),
('sn4_esp_txt', 'ATENCION DEL PARTO NACIMIENTO DEL HIJO','3'),
('sn4_esp_txt', 'AUTORIZACION PARA GIMNASIA','3'),
('sn4_esp_txt', 'BACTERIA EN UN DEDO QUE LO INFECTO','1'),
('sn4_esp_txt', 'BIOPSIA PROSTATA','4'),
('sn4_esp_txt', 'CAMBIO DE ANTEOJOS','4'),
('sn4_esp_txt', 'CERVICALGIA','1'),
('sn4_esp_txt', 'CESAREA','3'),
('sn4_esp_txt', 'CIRUGIA ODONTOLOGICA','8'),
('sn4_esp_txt', 'CIRUJIA ESTETICA','4'),
('sn4_esp_txt', 'CIRUJIA PLASTICA','4'),
('sn4_esp_txt', 'CIRUJIA PROGRAMADA','4'),
('sn4_esp_txt', 'CONTOL DE OPERACION','3'),
('sn4_esp_txt', 'CONTROL DE MAMAS ONCOLOGICO','3'),
('sn4_esp_txt', 'CONTROL DE OPERACION','3'),
('sn4_esp_txt', 'CONTROL DE PARTO','3'),
('sn4_esp_txt', 'CONTROL DE POST PARTO','3'),
('sn4_esp_txt', 'CONTROL MATERNAL','3'),
('sn4_esp_txt', 'CONTROL ODONTOLOGICO PORQUE USA APARATOS','8'),
('sn4_esp_txt', 'CONTROL PARA CIRUGIA','3'),
('sn4_esp_txt', 'CONTROL POR PARTO CESAREA','3'),
('sn4_esp_txt', 'CONTROL PORQUE NACIO PREMATURA','3'),
('sn4_esp_txt', 'CONTROL PORQUE TIENE DIABETES TIPO 1','3'),
('sn4_esp_txt', 'CONTROL PORQUE TUVO UN ACV','3'),
('sn4_esp_txt', 'CONTROL POS EMBARAZO','3'),
('sn4_esp_txt', 'CONTROL POST PARTO','3'),
('sn4_esp_txt', 'CONTROLES DE SALUD LABORALES LIBRETA SANITARIA','3'),
('sn4_esp_txt', 'CUANDO TUVO A SU ULTIMO HIJO','3'),
('sn4_esp_txt', 'DAR A LUZ','3'),
('sn4_esp_txt', 'DENTISTA','8'),
('sn4_esp_txt', 'DESARROLLO PERSONAL (PSICOLOGO)','8'),
('sn4_esp_txt', 'DESGARRO DE MENISCO','1'),
('sn4_esp_txt', 'DETERIORO GENERAL','1'),
('sn4_esp_txt', 'DONACION DE SANGRE','4'),
('sn4_esp_txt', 'EFISCEMA CRONICA','1'),
('sn4_esp_txt', 'ELECTROCARDIOGRAMA','3'),
('sn4_esp_txt', 'ESGUINZE MANO DERECHA','1'),
('sn4_esp_txt', 'ESTA EMBARAZADA','3'),
('sn4_esp_txt', 'ESTETICA','4'),
('sn4_esp_txt', 'ESTUDIO DE INTESTINO','3'),
('sn4_esp_txt', 'ESTUDIO PARA LA EMPRESA DONDE TRABAJA','3'),
('sn4_esp_txt', 'ESTUDIOS POR TEST PREOCUPACIONAL','3'),
('sn4_esp_txt', 'ESTUDIOS PRENUPCIALES','3'),
('sn4_esp_txt', 'ESTUDIOS PREOCUPACIONALES','3'),
('sn4_esp_txt', 'ESTUDIOS QUE PIDIO SU EMPLEADOR','3'),
('sn4_esp_txt', 'EXAMEN PRELABORAL','3'),
('sn4_esp_txt', 'EXAMEN PREOCUPACIONAL','3'),
('sn4_esp_txt', 'EXTRACCION DE UN DIENTE','8'),
('sn4_esp_txt', 'FUE AL ODONTOLOGO PARA UNA EXTRACCION DE UNA PIEZA DENTAL','8'),
('sn4_esp_txt', 'HACERLE LENTES NUEVOS','4'),
('sn4_esp_txt', 'HERIDAS POR UN ENFRENTAMIENTO','4'),
('sn4_esp_txt', 'HERIDO DE BALA EN TIROTEO','4'),
('sn4_esp_txt', 'IRRITACION EN LA PIEL','1'),
('sn4_esp_txt', 'LESION DEPORTIVA','1'),
('sn4_esp_txt', 'MALESTAR ESTOMACAL','1'),
('sn4_esp_txt', 'MATERNIDAD','3'),
('sn4_esp_txt', 'MORDEDURA DE UN PERRO','2'),
('sn4_esp_txt', 'NACIMIENTO','3'),
('sn4_esp_txt', 'NACIMIENTO DE SU ULTIMO HIJO','3'),
('sn4_esp_txt', 'NACIO CON BAJO PESO ENTONCES TIENE QUE IR MUCHO AL MEDICO A CONTROLAR PESO PARA SABER SI PUEDE PONER LAS VACUNAS','1'),
('sn4_esp_txt', 'NECESITABA RECETAS','3'),
('sn4_esp_txt', 'NECESITABA UN APTO FISICO','3'),
('sn4_esp_txt', 'NO SE ACUERDA','-9'),
('sn4_esp_txt', 'ODONTOLOGIA','8'),
('sn4_esp_txt', 'ODONTOLOGICO','8'),
('sn4_esp_txt', 'OPERACION','1'),
('sn4_esp_txt', 'OPERACION APENDICITIS','1'),
('sn4_esp_txt', 'OPERACION DE CALCULOS','1'),
('sn4_esp_txt', 'OPERACION DE CATARATAS','1'),
('sn4_esp_txt', 'OPERACION DE CATARATAS (AMBULATORIA)','1'),
('sn4_esp_txt', 'OPERACION DE GUANETE','1'),
('sn4_esp_txt', 'OPERACION DE MUÑECA','1'),
('sn4_esp_txt', 'OPERACION DE PERITONITIS','1'),
('sn4_esp_txt', 'OPERACION TUMORES','1'),
('sn4_esp_txt', 'PARA INGRESAR AL TRABAJO POR LIBRETA SANITARIA','3'),
('sn4_esp_txt', 'PARTO','3'),
('sn4_esp_txt', 'PARTO PUERPERIO','3'),
('sn4_esp_txt', 'PARTOPUERPERIO','3'),
('sn4_esp_txt', 'PEDIR RECETAS','3'),
('sn4_esp_txt', 'PERDIDA DE EMBARAZO','1'),
('sn4_esp_txt', 'PERDIO EMBARAZO','1'),
('sn4_esp_txt', 'PEROCUPACIONAL','3'),
('sn4_esp_txt', 'POR GOLPES QUE RECIBIO EN UN ASALTO','4'),
('sn4_esp_txt', 'POR TIROIDES SE TIENE QUE CONTROLAR UNA VEZ AL AÑO','3'),
('sn4_esp_txt', 'PRENUPCIAL','3'),
('sn4_esp_txt', 'PREQUIRURGICO','3'),
('sn4_esp_txt', 'PRESION ALTA','1'),
('sn4_esp_txt', 'PROBLEMA CERVICAL','1'),
('sn4_esp_txt', 'PROBLEMA ODONTOLOGICO','8'),
('sn4_esp_txt', 'PROBLEMAS DE ADICCIONES','1'),
('sn4_esp_txt', 'PROBLEMAS EN LAS TIROIDES','1'),
('sn4_esp_txt', 'PROBLEMAS FAMILIARES POR VIOLENCIA DE GENERO PSICOLOGICO','8'),
('sn4_esp_txt', 'PROCESO DE EMBARAZO','3'),
('sn4_esp_txt', 'PSICOLOGO','8'),
('sn4_esp_txt', 'PSICOLOGO  PSIQUIATRA','1'),
('sn4_esp_txt', 'PSICOTERAPIA','8'),
('sn4_esp_txt', 'PSIQUIATRICO','1'),
('sn4_esp_txt', 'PSORIASIS','1'),
('sn4_esp_txt', 'PUERPERIO','3'),
('sn4_esp_txt', 'RADIOGRAFIAS BUCALES','8'),
('sn4_esp_txt', 'RAYOS','3'),
('sn4_esp_txt', 'REACCION ALERGICA','1'),
('sn4_esp_txt', 'RECETA DE MEDICAMENTOS','3'),
('sn4_esp_txt', 'RECETARIO DE MEDICAMENTOS','3'),
('sn4_esp_txt', 'RECETAS','3'),
('sn4_esp_txt', 'RECETAS DE REMEDIOS','3'),
('sn4_esp_txt', 'REHABILITACION','2'),
('sn4_esp_txt', 'REHABILITACION DEL PIE QUEBRADO','2'),
('sn4_esp_txt', 'REMEDIOS','3'),
('sn4_esp_txt', 'RESONANCIA MAGNETICA DE CABEZA','3'),
('sn4_esp_txt', 'RETIRAR LOS PUNTOS DE UNA CIRUGIA','3'),
('sn4_esp_txt', 'RETIRAR ORDEN PARA IR AL OFTALMOLOGO','3'),
('sn4_esp_txt', 'RINOPLASTIA','3'),
('sn4_esp_txt', 'SE CAYO CON EL SKATE','2'),
('sn4_esp_txt', 'SOBREPESO DIETA','8'),
('sn4_esp_txt', 'SOLICITAR TURNO PARA UN CHEQUEO','3'),
('sn4_esp_txt', 'STRESS','1'),
('sn4_esp_txt', 'TENDINITIS EN RODILLA','1'),
('sn4_esp_txt', 'TENIA QUE PRESETAR ESTUDIOS MEDICOS PARA EL TERCIARIO','3'),
('sn4_esp_txt', 'TEST PREOCUPACIONAL','3'),
('sn4_esp_txt', 'TIENE ALERGIA','1'),
('sn4_esp_txt', 'TRASTORNO GENERAL DEL DESARROLLO','1'),
('sn4_esp_txt', 'TRAT PARA CAMINAR','1'),
('sn4_esp_txt', 'TRATAMIENTO','1'),
('sn4_esp_txt', 'TRATAMIENTO ANTI TABACO','1'),
('sn4_esp_txt', 'TRATAMIENTO DE ADICCIONES','1'),
('sn4_esp_txt', 'TRATAMIENTO DE CANCER','1'),
('sn4_esp_txt', 'TRATAMIENTO DE ENFERMEDAD','1'),
('sn4_esp_txt', 'TRATAMIENTO DE LA VISTA','1'),
('sn4_esp_txt', 'TRATAMIENTO DE ORTODONCIA','8'),
('sn4_esp_txt', 'TRATAMIENTO DE SALUD','1'),
('sn4_esp_txt', 'TRATAMIENTO EN LAS UÑAS POR INFECCION','1'),
('sn4_esp_txt', 'TRATAMIENTO NEUROLOGICO','1'),
('sn4_esp_txt', 'TRATAMIENTO NEUROLOGICO Y DISCAPACIDAD MOTRIZ','1'),
('sn4_esp_txt', 'TRATAMIENTO ODONTOLOGICO','8'),
('sn4_esp_txt', 'TRATAMIENTO ONCOLOGICO','1'),
('sn4_esp_txt', 'TRATAMIENTO POR ALERGIA','1'),
('sn4_esp_txt', 'TRATAMIENTO POR ARTROSIS','1'),
('sn4_esp_txt', 'TRATAMIENTO POR OBESIDAD','1'),
('sn4_esp_txt', 'TRATAMIENTO PROETZ (OTORRINO)','1'),
('sn4_esp_txt', 'TRATAMIENTO PSICOLOGICO','8'),
('sn4_esp_txt', 'TRATAMIENTO PSIQUIATRICO','1'),
('sn4_esp_txt', 'TRAUMATOLOGIA','1'),
('sn4_esp_txt', 'TURNO CON EL PSIQUIATRA','1'),
('sn4_esp_txt', 'VACUNACION','3'),
('sn4_esp_txt', 'VACUNACION DE AÑO Y SEG DOSIS DE LA GRIPE','3'),
('sn4_esp_txt', 'VACUNAS','3');

insert into encu.dictra
select diccionario,origen,destino::integer, 1 from encu.diccionario_agregar
where trim(diccionario)||trim(origen) not in (
select trim(dictra_dic)||trim(dictra_ori) from encu.dictra);


drop table encu.diccionario_agregar;