CREATE TABLE encu.diccionario_agregar (
  diccionario text,
  origen text,
  destino text
  )
  WITH (
  OIDS=FALSE
);
ALTER TABLE encu.diccionario_agregar
  OWNER TO tedede_php;


insert into encu.diccionario_agregar values
('barrio', '-9','99'),
('barrio', '-1','99'),
('barrio', '11','11'),
('barrio', '24 DE NOVIEMBRE','99'),
('barrio', '25 DE MAYO ENTRE SARMIENTO Y PERON','1'),
('barrio', '25 DE MAYO Y BOLIVAR','1'),
('barrio', '25 DE MAYO Y LAVALLE','1'),
('barrio', '25 DE MAYO Y PERON','1'),
('barrio', '9 DE JULIO 1929','1'),
('barrio', '9 DE JULIO E INDEPENDENCIA','1'),
('barrio', '9 DE JULIO Y AV DE MAYO','1'),
('barrio', '9 DE JULIO Y BELGRANO','1'),
('barrio', '9 DE JULIO Y BELGRANOCABA','1'),
('barrio', '9 DE JULIO Y DIAGONAL NORTE','1'),
('barrio', '9 DE JULIO Y GARAY','1'),
('barrio', '9 DE JULIO Y SANTA FE','1'),
('barrio', '9 DE JULIO1925','1'),
('barrio', '9 JULIO Y SANTA FE','1'),
('barrio', 'A DOS CUADRAS DE TALCAHUANO Y LAVALLE TRIBUNALES','1'),
('barrio', 'ABASTO SHOPPING','3'),
('barrio', 'ABASTO SHOPPING CARLOS GARDEL Y AV CORRIENTES','3'),
('barrio', 'ACEVEDO 80','15'),
('barrio', 'AGRONOMIA  AV SAN MARTIN Y NOGOYA','15'),
('barrio', 'AGUERO 616','3'),
('barrio', 'AGÜERO Y LAVALLE','3'),
('barrio', 'ALBARELLOS 3153','12'),
('barrio', 'ALBARRELLOS 3153','12'),
('barrio', 'ALEM Y DELLA PAOLERA','1'),
('barrio', 'ALEM Y DELLA PAULERA','1'),
('barrio', 'ALEM Y VENEZUELA','1'),
('barrio', 'ALICIA M DE JUSTO AL 100','1'),
('barrio', 'ALICIA MOREAU DE JUSTO Y AVENIDA BELGRANO','1'),
('barrio', 'ALMAGRO  AV MEDRANO Y POTOSI','5'),
('barrio', 'ALMAGRO CORRIENTES 168','5'),
('barrio', 'ALMAGRO LORIA Y RIVADAVIA','5'),
('barrio', 'ALSINA AL 1800','1'),
('barrio', 'ALSINA Y 24 DE NOVIEMBRE','3'),
('barrio', 'ALSINA Y BOLIVAR','3'),
('barrio', 'ALSINA Y SAENZ PEÑA','3'),
('barrio', 'ALVAREZ TOMAS Y ELCANO','15'),
('barrio', 'ALVEAR Y AYACUCHO','2'),
('barrio', 'AMAGRO','5'),
('barrio', 'ANCHORENA Y CORDOBA','3'),
('barrio', 'ANDONAEGUI Y AV DE LOS INCAS','12'),
('barrio', 'ANGEL GALLARDO 470','6'),
('barrio', 'ARCOS Y MENDOZA','13'),
('barrio', 'ARENALES Y MAIPU','1'),
('barrio', 'ARISMENDI 2670','15'),
('barrio', 'ARRIBEÑOS Y BULLRICH','14'),
('barrio', 'ARRIZMENDI 2670','15'),
('barrio', 'ARTIGAS 5540','12'),
('barrio', 'AV','99'),
('barrio', 'AV 9 DE JULIO','1'),
('barrio', 'AV 9 DE JULIO Y MORENO','1'),
('barrio', 'AV ALEM 650','1'),
('barrio', 'AV BELGRANO 1300','1'),
('barrio', 'AV BELGRANO 1590','1'),
('barrio', 'AV BELGRANO AL 1300','1'),
('barrio', 'AV BELGRANO Y ALBERTI','3'),
('barrio', 'AV BELGRANO Y LIMA','1'),
('barrio', 'AV BELGRANO Y PASCO','1'),
('barrio', 'AV BELGRANO Y SAENZ PEÑA','1'),
('barrio', 'AV COBO','7'),
('barrio', 'AV CORDOBA PALERMO','14'),
('barrio', 'AV CORONEL DIAZ Y AV LAS HERAS','14'),
('barrio', 'AV CORRIENTES 1437','1'),
('barrio', 'AV CORRIENTES 846','1'),
('barrio', 'AV CORRIENTES Y AV CALLAO','1'),
('barrio', 'AV DE LOS CORRALES 6661','8'),
('barrio', 'AV DE LOS CORRALES 6661 MATADEROS','9'),
('barrio', 'AV DE MAYO 869 CABA','1'),
('barrio', 'AV DE MAYO SAN NICOLAS','1'),
('barrio', 'AV DE MAYO Y 9DE JULIO','1'),
('barrio', 'AV DE MAYO Y TALCHUANO','1'),
('barrio', 'AV DEL CAMPO 1449','15'),
('barrio', 'AV INCAS Y TRIUNVIRATO','15'),
('barrio', 'AV LA PLATA 1100','5'),
('barrio', 'AV LOS INCAS Y AVALOS','15'),
('barrio', 'AV MADERO Y ALEM','99'),
('barrio', 'AV MAYO CENTRO ESTACION PERU','1'),
('barrio', 'AV MEDRANO Y POTOSI','5'),
('barrio', 'AV NAZCA Y NAVARRO','11'),
('barrio', 'AV NAZCA Y PAREJA','12'),
('barrio', 'AV PATRICIAS ARGENTINAS','6'),
('barrio', 'AV RIVADAVIA','99'),
('barrio', 'AV RIVADAVIA Y NAZCA','7'),
('barrio', 'AV SAENZ 300','4'),
('barrio', 'AV SAN MARTIN Y NOGOYA','15'),
('barrio', 'AV SEGUROLA 1949 HOSPITAL MANUEL ROCCA','10'),
('barrio', 'AV WARNES Y MUÑECAS','15'),
('barrio', 'AVBELGRANO Y BOEDO','5'),
('barrio', 'AVBELGRANO Y BOEDO-ALMAGRO','5'),
('barrio', 'AVDA SAN JUAN AL 1700','1'),
('barrio', 'AVDA SAN MARTIN Y CHORROARIN','11'),
('barrio', 'AVELLANEDA','99'),
('barrio', 'AVELLANEDA 212','6'),
('barrio', 'AVELLANEDA Y NAZCA PLAZA FLORES','7'),
('barrio', 'AVENIDA CORDOBA','99'),
('barrio', 'AVENIDA CORDOBA Y BILLINGHURST','2'),
('barrio', 'AVENIDA DE MAYO','99'),
('barrio', 'AVENIDA JOSE LUIS CANTILO Y AV GENERAL PAZ','10'),
('barrio', 'AVENIDA RIVADAVIA Y DOBLAS','6'),
('barrio', 'AVLIBERTADOR','13'),
('barrio', 'AVRIVADAVIA 1330','1'),
('barrio', 'AZCUENAGA 351','3'),
('barrio', 'AZCUENAGA Y ARENALES','2'),
('barrio', 'AZCUENAGA Y CORRIENTES','3'),
('barrio', 'AZCUENAGA Y PARAGUAY','2'),
('barrio', 'AZOPARDO Y CHILE','1'),
('barrio', 'AZOPARDO Y GARAY','1'),
('barrio', 'BAEZ Y AREVALO','14'),
('barrio', 'BAEZ Y MATIENZO','14'),
('barrio', 'BAHIA BLANCO Y CAMARONES','10'),
('barrio', 'BALAVANERA','3'),
('barrio', 'BALCARCE 186','1'),
('barrio', 'BALCARCE 90','1'),
('barrio', 'BALCARCE AL 1000','1'),
('barrio', 'BALCARCE Y ALSINA','1'),
('barrio', 'BALCARCE Y MORENO','1'),
('barrio', 'BALCARCE Y VENEZUELA','1'),
('barrio', 'BALDOMERO FERNANDEZ MORENO 1200','7'),
('barrio', 'BALVANERA  AV BELGRANO Y ALBERTI','3'),
('barrio', 'BALVANERA CONGRESO','3'),
('barrio', 'BALVANERA MORENO 2366','3'),
('barrio', 'BALVANERA PICHINCHA Y RIVADAVIA','3'),
('barrio', 'BALVANERA SAENZ PEÑA Y AVENIDA DE MAYO','3'),
('barrio', 'BALVARERA','3'),
('barrio', 'BALVENERA','3'),
('barrio', 'BARRIO NORTE RECOLETA','2'),
('barrio', 'BARRIO PIEDRABUENA','8'),
('barrio', 'BARRIO SAMORE','8'),
('barrio', 'BARROS PAZOS AL 3600','8'),
('barrio', 'BARROS PAZOS AL 3600 SOLDATI','8'),
('barrio', 'BARTOLOME MITRE','99'),
('barrio', 'BARTOLOME MITRE 300','1'),
('barrio', 'BARTOLOME MITRE 600','1'),
('barrio', 'BARTOLOME MITRE AL 2200','1'),
('barrio', 'BARTOLOME MITRE Y DIAGONAL NORTE','1'),
('barrio', 'BARTOLOME MITRE Y JUNIN','1'),
('barrio', 'BARTOLOME MITRE Y PASO','1'),
('barrio', 'BARTOLOME MITRE Y RIVADAVIA','1'),
('barrio', 'BARTOLOME MITRE Y SAN MARTIN','1'),
('barrio', 'BARTOLOME MITRE Y SUIPACHA','1'),
('barrio', 'BARZANA 1192','15'),
('barrio', 'BDO DE IRIGOYEN Y ALSINA','1'),
('barrio', 'BEIRO Y CONCORDIA','11'),
('barrio', 'BEIRO Y EMILIO LAMARCA','11'),
('barrio', 'BELGRANO  CABILDO Y SUCRE','13'),
('barrio', 'BELGRANO  CIUDAD UNIVERSITARIA','13'),
('barrio', 'BELGRANO  EN LA CALLE MOLDES','13'),
('barrio', 'BELGRANO  MONTAÑESES Y MENDOZA','13'),
('barrio', 'BELGRANO  PASEO ALCORTA','13'),
('barrio', 'BELGRANO  SAPIOLA Y CESPEDES','13'),
('barrio', 'BELGRANO  VIDAL Y OLAZABAL','13'),
('barrio', 'BELGRANO 1381','1'),
('barrio', 'BELGRANO 1870','1'),
('barrio', 'BELGRANO LUIS MARIA CAMPOS Y DORREGO','13'),
('barrio', 'BELGRANO R','99'),
('barrio', 'BELGRANO TORTUGUITAS','13'),
('barrio', 'BELGRANO Y 9 DE JULIO','1'),
('barrio', 'BELGRANO Y AZOPARDO','1'),
('barrio', 'BELGRANO Y CEVALLOS','13'),
('barrio', 'BELGRANO Y ENTRE RIOS','1'),
('barrio', 'BELGRANO Y HUERGO','1'),
('barrio', 'BELGRANO Y MATEU','13'),
('barrio', 'BELGRANO Y MORENO','1'),
('barrio', 'BELGRANO Y PIEDRAS','1'),
('barrio', 'BELGRANO Y RIOJA','3'),
('barrio', 'BELGRANO Y SAN JOSE','1'),
('barrio', 'BELGRANO Y SOLIS','13'),
('barrio', 'BERNARDO DE IRIGOYEN Y BELGRANO','1'),
('barrio', 'BERNARDO DE IRIGOYEN Y VENEZUELA','1'),
('barrio', 'BERON DE ASTRADA 6351','8'),
('barrio', 'BERUTI Y AGUERO','2'),
('barrio', 'BILLIBGURST Y STA FE','2'),
('barrio', 'BILLINGURST Y AV SANTA FE','2'),
('barrio', 'BLANCO ENCALADA Y VUELTA DE OBLIGADO','13'),
('barrio', 'BME MITRE Y PARANA','1'),
('barrio', 'BME MITRE Y SAN MARTIN','1'),
('barrio', 'BOEDO E INDEPENDENCIA','5'),
('barrio', 'BOLIVAR 1','1'),
('barrio', 'BOLIVAR 1457','1'),
('barrio', 'BOLIVAR Y BELGRANO','1'),
('barrio', 'BOUCHARD 547','1'),
('barrio', 'BRANDSEN Y LUSURIAGA','4'),
('barrio', 'BRANSEN 2070','4'),
('barrio', 'BRASIL Y LIMA','1'),
('barrio', 'BRASIL Y TACUARI','1'),
('barrio', 'BUSTAMANTE ENTRE FRENCH Y PEÑA','2'),
('barrio', 'BUSTAMANTE ENTRENPEÑA Y FRENCH','2'),
('barrio', 'C PELLEGRINI Y BELGRANO','1'),
('barrio', 'CABA','99'),
('barrio', 'CABALLITO  AV IRIGOYEN Y MUÑIZ','6'),
('barrio', 'CABALLITO  LAMBARE Y BOGADO','6'),
('barrio', 'CABALLITO GAONA Y DONATO ALVAREZ','6'),
('barrio', 'CABALLITO LAMBARE Y BOGADO','6'),
('barrio', 'CABALLITO Y ALMAGRO','6'),
('barrio', 'CABEZON Y CAMPANA','11'),
('barrio', 'CABILDO 2677','13'),
('barrio', 'CABILDO 2932','13'),
('barrio', 'CABILDO 400','14'),
('barrio', 'CABILDO Y DORREGO','14'),
('barrio', 'CABILDO Y MANZANARES','13'),
('barrio', 'CABILLITO','6'),
('barrio', 'CALLAO Y MARCELO T DE ALVEAR','2'),
('barrio', 'CALLAO Y MITRE','1'),
('barrio', 'CALLAO Y PARAGUAY','2'),
('barrio', 'CALLAO Y RIVADAVIA','3'),
('barrio', 'CALLAO Y RODRIGUEZ PEÑA','99'),
('barrio', 'CALLE ALBARIÑO','99'),
('barrio', 'CALLE ALBARIÑO NO RECUERDA INTERSECCION','99'),
('barrio', 'CALLE ENTRE RIOS','99'),
('barrio', 'CALLE OLAZABAL EN BELGRANO','13'),
('barrio', 'CALLE PELLEGRINI','99'),
('barrio', 'CALLE PERON','99'),
('barrio', 'CALLE URUGUAY','99'),
('barrio', 'CALLE VIAMONTE','99'),
('barrio', 'CAMPILLO Y COMBATIENTE DE MALVINAS','15'),
('barrio', 'CAÑITAS  BAEZ Y MATIENZO','14'),
('barrio', 'CAPITAL Y PROVINCIA','99'),
('barrio', 'CARABOBO Y EVA PERON','7'),
('barrio', 'CARLOS CALVO','99'),
('barrio', 'CARLOS CALVO 1500','1'),
('barrio', 'CARLOS CALVO 1655','1'),
('barrio', 'CARLOS CALVO Y SALTA','1'),
('barrio', 'CARLOS GARDEL Y AV CORRIENTES','3'),
('barrio', 'CARLOS PELEGRINI 211','1'),
('barrio', 'CARLOS PELLEGRINI 200','1'),
('barrio', 'CARLOS PELLEGRINI Y BARTOLOME MITRE','1'),
('barrio', 'CARLOS PELLEGRINI Y DIAGONAL NORTE','1'),
('barrio', 'CARLOS PELLEGRINI Y LAVALLE','1'),
('barrio', 'CARRASCO Y JUAN B JUSTO','7'),
('barrio', 'CASEROS 3OOO','4'),
('barrio', 'CASEROS Y BOEDO','4'),
('barrio', 'CASTAÑARES Y RIVADAVIA','7'),
('barrio', 'CASTRO BARROS Y RIVADAVIA','5'),
('barrio', 'CATEDRAL','1'),
('barrio', 'CENTENERA Y PERITO MORENO','4'),
('barrio', 'CENTENERA Y SALAS','7'),
('barrio', 'CENTRO LAVALLE','1'),
('barrio', 'CERRITO 700','1'),
('barrio', 'CERRITO Y SARMIENTO','1'),
('barrio', 'CERRITO Y SARMIENTO SAN NICOLAS','1'),
('barrio', 'CERRITO Y TUCUMAN','1'),
('barrio', 'CHACABUCO Y MORENO','1'),
('barrio', 'CHACARITA  FOREST 800','15'),
('barrio', 'CHACARITA  GUEVARA 525','15'),
('barrio', 'CHACARITA  GUEVARA Y ELCANO','15'),
('barrio', 'CHACARITA  SANTOS DUMONT Y OTERO','15'),
('barrio', 'CHARCAS Y AGŪERO','2'),
('barrio', 'CHILE 1400','1'),
('barrio', 'CHILE Y COMBATE DE LOS POZOS','3'),
('barrio', 'CHILE Y DEFENSA','1'),
('barrio', 'CHIVILCOY Y SIMBRON','11'),
('barrio', 'CID CAMPEADOR','6'),
('barrio', 'CIUDAD','99'),
('barrio', 'CIUDAD UNIVERSITARIA NUÑEZ','13'),
('barrio', 'COBO','7'),
('barrio', 'COCHABAMBA 565','1'),
('barrio', 'COCHABAMBA 575','1'),
('barrio', 'COCHABAMBA AL 565','1'),
('barrio', 'COCHABAMBA Y LA RIOJA','1'),
('barrio', 'COELEGIALWS','13'),
('barrio', 'COGLAND','99'),
('barrio', 'COHOGLAN','99'),
('barrio', 'COLEGIALES  CONESA Y MAURE','13'),
('barrio', 'COLEGIALES  JORGE NEWBERY Y CORDOBA','13'),
('barrio', 'COMBATE DE LOS POSOS Y BELGRANO','3'),
('barrio', 'COMBATE DE LOS POZOS Y CACEROS','4'),
('barrio', 'COMBATE DE LOS POZOS Y ENTRE RIOS','99'),
('barrio', 'COMBATE DE LOS POZOSY ENTRE RIOS','99'),
('barrio', 'COMBATE Y BRASIL','4'),
('barrio', 'COMODORO PEDRO SAENZ 250','4'),
('barrio', 'COMUNA 14','14'),
('barrio', 'COMUNA 14 AEROPARQUE','14'),
('barrio', 'COMUNA 3','3'),
('barrio', 'COMUNA 6','6'),
('barrio', 'COMUNA 7','7'),
('barrio', 'COMUNA 8','8'),
('barrio', 'CONESA AL 2200 BELGRANO','13'),
('barrio', 'CONESA Y MAURE','13'),
('barrio', 'CONGRESO AVENIDA DE MAYO Y SANTIAGO DEL ESTERO','1'),
('barrio', 'CONGRESO BELGRADO Y SAENZ PEÑA','1'),
('barrio', 'CONGRESO RECOLETA Y PALERMO','99'),
('barrio', 'CONGRESO RIVADAVIA Y RIOBAMBA ANEXO DEL CONGRESO','1'),
('barrio', 'CONGRESO SOLIS Y BELGRANO','1'),
('barrio', 'CONGRESO VENEZUELA Y SOLIS','1'),
('barrio', 'CONGRESO Y TRONADOR','12'),
('barrio', 'CONSTITUCION  ENTRE RIOS Y GARAY','1'),
('barrio', 'CONSTITUCION EN LA CASA DE LOS DISTINTOS CLIENTES','1'),
('barrio', 'CONSTITUYENTES Y GENERAL PAZ','12'),
('barrio', 'CORDABA Y CERRITO','1'),
('barrio', 'CORDOBA 720','1'),
('barrio', 'CORDOBA 900','1'),
('barrio', 'CORDOBA AL 800','1'),
('barrio', 'CORDOBA Y 9 DE JULIO','1'),
('barrio', 'CORDOBA Y ALEM','1'),
('barrio', 'CORDOBA Y BOUCHARD','1'),
('barrio', 'CORDOBA Y CARLOS PELEGRINI','1'),
('barrio', 'CORDOBA Y CERRITO','1'),
('barrio', 'CORDOBA Y CONCEPCION ARENAL','15'),
('barrio', 'CORDOBA Y LIBERTAD','1'),
('barrio', 'CORDOBA Y MADERO','1'),
('barrio', 'CORDOBA Y MARIO BRAVO','2'),
('barrio', 'CORDOBA Y PELLEGRINI','1'),
('barrio', 'CORDOBA Y TALCAHUANO','1'),
('barrio', 'CORDOBA Y VIAMONTE','99'),
('barrio', 'CORDOBAY SUIPACHA','1'),
('barrio', 'CORRIENTES 2038','3'),
('barrio', 'CORRIENTES 400','1'),
('barrio', 'CORRIENTES 500','1'),
('barrio', 'CORRIENTES 640','1'),
('barrio', 'CORRIENTES Y 25 DE MAYO','1'),
('barrio', 'CORRIENTES Y 25DE MAYO','1'),
('barrio', 'CORRIENTES Y ANCHORENA','3'),
('barrio', 'CORRIENTES Y CERRITO','1'),
('barrio', 'CORRIENTES Y GASCON','5'),
('barrio', 'CORRIENTES Y JUAN B JUSTO','15'),
('barrio', 'CORRIENTES Y MONTEVIDEO','1'),
('barrio', 'CORRIENTES Y PASO','3'),
('barrio', 'CORRIENTES Y PASTEUR','3'),
('barrio', 'CORRIENTES Y SAN MARTIN','1'),
('barrio', 'CORRIENTES Y SCALABRINI ORTIZ','15'),
('barrio', 'CORRIENTES Y TALCAHUANO','1'),
('barrio', 'CORRIENTES1300','1'),
('barrio', 'COSTA SALGUERO','1'),
('barrio', 'COUMNA 2','2'),
('barrio', 'CPELLEGRINI Y CORDOBA','1'),
('barrio', 'CREVIÑO 3356 HOSPITAL FERNANDEZ','14'),
('barrio', 'CUBA AL 1500','99'),
('barrio', 'CUCHA CUCHA Y SAN MARTIN','15'),
('barrio', 'CUENCA 400','10'),
('barrio', 'CUENCA AL 400','10'),
('barrio', 'CULLEN Y BAUNES','12'),
('barrio', 'DARSENA F SIN NUMERO PUERTO MADERO','1'),
('barrio', 'DARWIN Y LOYOLA','15'),
('barrio', 'DEAN FUNES 2198','4'),
('barrio', 'DEFENSA E INDEPENDENCIA SAN TELMO','1'),
('barrio', 'DEFENSA Y BELGRANO','1'),
('barrio', 'DEFENSA Y PASAJE GIUFFRA','1'),
('barrio', 'DEL LIBERTADOR 238','1'),
('barrio', 'DELLEPIANE','99'),
('barrio', 'DELLEPIANE Y RAWSON','99'),
('barrio', 'DERQUI Y AVENIDA DEL TRABAJO','99'),
('barrio', 'DEVOTO CHIVILCOY Y AV BEIRO','11'),
('barrio', 'DIAGENTRE FLORIDA Y ESMERALDA','1'),
('barrio', 'DIAGONAL NORTE 200','1'),
('barrio', 'DIAGONAL NORTE 777','1'),
('barrio', 'DIAGONAL NORTE 788','1'),
('barrio', 'DIAGONAL NORTE 800','1'),
('barrio', 'DIAGONAL NORTE Y AVENIDA DE MAYO','1'),
('barrio', 'DIAGONAL NORTE Y ESMERALDA','1'),
('barrio', 'DIAGONAL NORTE Y MAIPU','1'),
('barrio', 'DIAGONAL SUR','1'),
('barrio', 'DIAGONAL SUR ENTRE ALSINA Y BOLIVAR','1'),
('barrio', 'DIAGONAL SUR Y 9 DE JULIO','1'),
('barrio', 'DIGONAL NORTE Y PERON','1'),
('barrio', 'DIRECTORIO Y LACARRA','9'),
('barrio', 'DIRECTORIO Y TANDIL','99'),
('barrio', 'DISTINTOS BARRIOS','99'),
('barrio', 'DISTINTOS CONSULTORIOS','99'),
('barrio', 'DIVERSOS BARRIOS','99'),
('barrio', 'DORREGO 690','15'),
('barrio', 'DORREGO Y FIGUEROA ALCORTA','14'),
('barrio', 'ECHEVERRIA Y MELO','99'),
('barrio', 'ECUADOR Y BAROLOME MITRE','3'),
('barrio', 'EMILIO CASTRO Y GENERAL PAZ','9'),
('barrio', 'EMILIO LAMARCA Y GUALEGUAYCHU','99'),
('barrio', 'EMILIO LAMARCA Y NOGOYA','11'),
('barrio', 'EN AV ENTRE RIOS Y MORENO','1'),
('barrio', 'EN LA CALLE LAVALLE A METROS DE TRIBUNALES','1'),
('barrio', 'EN LA CALLE MOLDES','13'),
('barrio', 'EN LA EXESMA','13'),
('barrio', 'EN LA EX-ESMA NUÑEZ','13'),
('barrio', 'ENTRE RIOS 144','1'),
('barrio', 'ENTRE RIOS Y BELGRANO','3'),
('barrio', 'ENTRE RIOS Y GARAY','1'),
('barrio', 'ENTRE RIOS Y MEXICO','3'),
('barrio', 'ESMERALDA 1319','1'),
('barrio', 'ESMERALDA Y CORRIENTES','1'),
('barrio', 'ESMERALDA Y CORRIRNETES','1'),
('barrio', 'ESMERALDA Y DIAGONAL NORTE','1'),
('barrio', 'ESMERALDA Y JUNCAL','1'),
('barrio', 'ESMERALDA Y PARAGUAY','1'),
('barrio', 'ESMERALDA Y VIAMONTE','1'),
('barrio', 'ESTADOS UNIDOS Y SANCHEZ DE LORIA','5'),
('barrio', 'ESTADOS UNIDOS Y TURQUIA','99'),
('barrio', 'ESTADPS UNIDOS 1228','1'),
('barrio', 'EVA PERON Y ZINNI','1'),
('barrio', 'FACULTAD DE MEDICINA','3'),
('barrio', 'FIGUROA ALCORTA Y PUYRREDON FACULTAD DE DERECHO','2'),
('barrio', 'FITZ ROY Y GUATEMALA','14'),
('barrio', 'FLORES  AV RIVADAVIA Y NAZCA','7'),
('barrio', 'FLORES  CARRASCO Y JUAN B JUSTO','7'),
('barrio', 'FLORES  JPVARELA 1301','7'),
('barrio', 'FLORES  PASAJE LA PORTEÑA Y AV RIVADAVIA','7'),
('barrio', 'FLORES AV NAZCA Y AVELLANEDA','7'),
('barrio', 'FLORES AV VARELA','7'),
('barrio', 'FLORES AVENIDA RIVADAVIA','7'),
('barrio', 'FLORES NAZCA Y AVELLANEDA','7'),
('barrio', 'FLORES RIVADAVIA Y CULPINA','7'),
('barrio', 'FLORESTA ARANGUREN Y SEGUROLA','7'),
('barrio', 'FLORESTA JUAN BAUTISTA ALBERDI Y LACARRA','7'),
('barrio', 'FLORIDA 681','1'),
('barrio', 'FLORIDA 701','1'),
('barrio', 'FLORIDA AL 1000','1'),
('barrio', 'FLORIDA Y CORDOBA','1'),
('barrio', 'FLORIDA Y PARAGUAY','1'),
('barrio', 'FLORIDA Y TUCUMAN','1'),
('barrio', 'FORES','7'),
('barrio', 'FOREST 800','15'),
('barrio', 'FRAGA 1500','15'),
('barrio', 'GALERIAS PACIFICO','1'),
('barrio', 'GALLARDO 100','9'),
('barrio', 'GAONA 3500','7'),
('barrio', 'GAONA Y H PUEYRREDON','6'),
('barrio', 'GAONA Y SEGUROLA','10'),
('barrio', 'GARAY Y CATAMARCA','3'),
('barrio', 'GARAY Y PASEO COLON','1'),
('barrio', 'GARCIA DEL RIO 3119','12'),
('barrio', 'GASCON Y CORRIENTES','5'),
('barrio', 'GASCON Y PERON','5'),
('barrio', 'GAVILAN Y LUIS VIALE','11'),
('barrio', 'GODOY CRUZ Y GUATEMALA','14'),
('barrio', 'GORRITI 5963','14'),
('barrio', 'GRAL PAZ Y AV EMILIO CASTRO','9'),
('barrio', 'GRAL PAZ Y AVENIDA ROCA','8'),
('barrio', 'GUAMI Y CHILAVERT','8'),
('barrio', 'GUEMES Y SANCHEZ DE BUSTAMENTE','2'),
('barrio', 'GUEVARA 525','15'),
('barrio', 'GUEVARA Y ELCANO','15'),
('barrio', 'HIDALGO 775','6'),
('barrio', 'HIDALGO 775 CABALLITO','6'),
('barrio', 'HIPOLITO YRIGOYEN','99'),
('barrio', 'HIPOLITO YRIGOYEN 2263','3'),
('barrio', 'HIPOLITO YRIGOYEN AL 2000','3'),
('barrio', 'HIPOLITO YRIGOYEN Y QUINTINO BOCAPYUBA','5'),
('barrio', 'HONDURAS Y BULNES','14'),
('barrio', 'HONDURAS Y GASCON','14'),
('barrio', 'HOSPITAL SANTA LUCIA','3'),
('barrio', 'HOSPITAL SANTA LUCIA SAN JUAN2021','3'),
('barrio', 'HUBAC Y LEGUIZAMON','8'),
('barrio', 'HUERGO Y GARAY','1'),
('barrio', 'HUMBOLDT Y PARAGUAY','14'),
('barrio', 'INDEPENCIA AL 3000','3'),
('barrio', 'INDEPENDENCIA 100','1'),
('barrio', 'INDEPENDENCIA 3000','1'),
('barrio', 'INDEPENDENCIA 3277','3'),
('barrio', 'INDEPENDENCIA Y CASTRO BARROS','5'),
('barrio', 'INDEPENDENCIA Y CHACABUCO','1'),
('barrio', 'IRIARTE Y LUNA','4'),
('barrio', 'IRIGOYEN Y SANTIAGO DEL ESTERO','99'),
('barrio', 'J A ROCA DIAGONAL SUR','1'),
('barrio', 'JEAN JAURES 545','3'),
('barrio', 'JEAN JOURE Y MANSILLA','2'),
('barrio', 'JEAN JOURE Y MANSILLA RECOLETA','2'),
('barrio', 'JORGE NEWBERY Y CORDOBA','13'),
('barrio', 'JOSE GERVASIO ARTIGAS 5540','12'),
('barrio', 'JOSE MARIA MORENO Y COBO','7'),
('barrio', 'JPVARELA 1301','7'),
('barrio', 'JUAN B JUSTO ENFRENTE DE JUMBO','99'),
('barrio', 'JUAN B JUSTO Y ARTIGAS','15'),
('barrio', 'JUAN B JUSTO Y CUCHA CUCHA','15'),
('barrio', 'JUJUY 150','3'),
('barrio', 'JUJUY Y 15 DE NOVIEMBRE','4'),
('barrio', 'JUJUY Y HPRIMO','3'),
('barrio', 'JUJUY Y HUMBERTO PRIMO','3'),
('barrio', 'JULIO ROCA','99'),
('barrio', 'JULIO ROCA 200','99'),
('barrio', 'JULIO ROCA AL 700','1'),
('barrio', 'JULIO ROCA Y BOLIVAR','1'),
('barrio', 'JUNCAL 3002','14'),
('barrio', 'JUNCAL Y BILLINGHURST','2'),
('barrio', 'JUNIN Y LAS HERAS','2'),
('barrio', 'JUNIN Y LAVALLE','3'),
('barrio', 'JUNIN Y TUCUMAN','3'),
('barrio', 'JURAMENTO 4367','12'),
('barrio', 'JURAMENTO Y CABILDO','13'),
('barrio', 'JURAMENTO Y MANSILLA','99'),
('barrio', 'JURAMENTO Y TRES DE FEBRERO','13'),
('barrio', 'L N ALEM 638','1'),
('barrio', 'LA BOCA ALMIRANTE BROWN Y MARTIN GARCIA','4'),
('barrio', 'LA PATERNAL','15'),
('barrio', 'LA PATERNAL  12 DE OCTUBRE ENTRE CUCHA CUCHA Y ESPINOZA','15'),
('barrio', 'LA PATERNAL  CUCHA CUCHA Y SAN MARTIN','15'),
('barrio', 'LA PATERNAL  JUAN B JUSTO Y ARTIGAS','15'),
('barrio', 'LA PATERNAL  SAN BLAS 1600','15'),
('barrio', 'LA PATERNAL  SAN MARTIN Y JUAN B JUSTO','15'),
('barrio', 'LA PATERNAL  WARNES Y CHORROARIN','15'),
('barrio', 'LAMBARE 948','5'),
('barrio', 'LARRALDE Y BALBIN','12'),
('barrio', 'LARREA Y VIAMONTE','3'),
('barrio', 'LAS CAÑITAS PALERMO','14'),
('barrio', 'LAS HERAS Y AUSTRIA','2'),
('barrio', 'LAS HERAS Y RODRIGUEZ PEÑA','2'),
('barrio', 'LAVALLE 1268','1'),
('barrio', 'LAVALLE 1686','1'),
('barrio', 'LAVALLE 730','1'),
('barrio', 'LAVALLE CERCA DE TRIBUNALES','1'),
('barrio', 'LAVALLE Y 25 DE MAYO','1'),
('barrio', 'LAVALLE Y 9 DE JULIO','1'),
('barrio', 'LAVALLE Y CALLAO','1'),
('barrio', 'LAVALLE Y FLORIDA','1'),
('barrio', 'LAVALLE Y MONTEVIDEO','1'),
('barrio', 'LAVALLE Y SAN MARTIN','1'),
('barrio', 'LAVALLE Y TALCAHUANO','1'),
('barrio', 'LAVALLE169','1'),
('barrio', 'LAVALLOL Y BAZURCO','11'),
('barrio', 'LEANDRO ALEM 1067','1'),
('barrio', 'LEANDRO ALEM 928','1'),
('barrio', 'LEGUIZAMON Y SANTANDER','8'),
('barrio', 'LERMA Y ESTADO DE ISRAEL','15'),
('barrio', 'LI IERS','9'),
('barrio', 'LIBERTAD 400','1'),
('barrio', 'LIBERTAD Y CORRIENTES','1'),
('barrio', 'LIBERTAD Y LAVALLE','1'),
('barrio', 'LIBERTADOR 1500','2'),
('barrio', 'LIBERTADOR 15000','2'),
('barrio', 'LIBERTADOR 6350','13'),
('barrio', 'LIBERTADOR Y PELLEGRINI','1'),
('barrio', 'LIMA 1261','1'),
('barrio', 'LIMA 163','1'),
('barrio', 'LINIERS  GALLARDO 149','9'),
('barrio', 'LINIERS PILAR 950','9'),
('barrio', 'LINUERS','9'),
('barrio', 'LISANDRO DE LA TORRE Y LA FERRERE','99'),
('barrio', 'LISANDRO DE LA TORRE Y LA FERRETEE MATADEROS','9'),
('barrio', 'LISANDRO DE LATORRE 2406','9'),
('barrio', 'LLAVALLE 400','1'),
('barrio', 'LLAVALLE AL 400','1'),
('barrio', 'LLAVALLOL 3000','11'),
('barrio', 'LOMA ALEGRE','4'),
('barrio', 'LOPE DE VEGA Y LISTA','10'),
('barrio', 'LOPE DE VEGA Y SASTRE','11'),
('barrio', 'LORIA Y RIVADAVIA','5'),
('barrio', 'LOYOLA Y GURRUCHAGA','15'),
('barrio', 'LUGANO I Y II','8'),
('barrio', 'LUGANO POLA Y ORDOÑES','8'),
('barrio', 'LUGANO ROCA Y PORTILLO','8'),
('barrio', 'LUGONES Y GARCIA DEL RIO','12'),
('barrio', 'LUIS MARIA CAMPOS 480','14'),
('barrio', 'LUIS MARIA CAMPOS 650','14'),
('barrio', 'LUIS MARIA CAMPOS Y AREVALO','14'),
('barrio', 'LUIS MARIA CAMPOS Y CHENAUT','14'),
('barrio', 'MADERO Y CORRIENTES','1'),
('barrio', 'MADERO Y PERON','1'),
('barrio', 'MAHATMA GANDHI Y OLAYA','15'),
('barrio', 'MAIPU 600','1'),
('barrio', 'MAIPU Y DIAGONAL NORTE','1'),
('barrio', 'MAIPU Y SARMIENTO','1'),
('barrio', 'MAIPU Y TUCUMAN','1'),
('barrio', 'MANCILLA Y GALLO','14'),
('barrio', 'MANUEL SOLA Y SANABRIA','11'),
('barrio', 'MANZANA14 CASA 135','99'),
('barrio', 'MARCELO T DE ALVEAR 1840','2'),
('barrio', 'MARCELO T DE ALVEAR Y CALLAO','2'),
('barrio', 'MARCELO T DE ALVEAR Y LARREA','2'),
('barrio', 'MARCELO T DE ALVEAR Y PELLEGRINI','1'),
('barrio', 'MARIO BRAVO Y CABRERA','14'),
('barrio', 'MARIO BRAVO Y HUMAHUACA','5'),
('barrio', 'MATADEROS AV CORRALES Y TANDIL','9'),
('barrio', 'MATIENZO Y BAEZ','14'),
('barrio', 'MEDRANO 951','5'),
('barrio', 'MEXICO Y AZOPARDO','1'),
('barrio', 'MEXICO Y QUINTINO BOCAYUVA','5'),
('barrio', 'MICORCENTRO','1'),
('barrio', 'MICROCENTRO  PARAGUAY Y LARREA','1'),
('barrio', 'MICROCENTRO LAVALLE','1'),
('barrio', 'MICROCENTRO SAN MARTIN','1'),
('barrio', 'MICROCENTRO TALCAHUANO','1'),
('barrio', 'MICROCENTRO TUCUMAN Y FLORIDA','1'),
('barrio', 'MICROCENTROSARMIENTO 517','1'),
('barrio', 'MISIONES Y RIVADAVIA','1'),
('barrio', 'MITRE 2766','3'),
('barrio', 'MITRE 648','1'),
('barrio', 'MITRE B Y 25 DE MAYO','1'),
('barrio', 'MITRE Y BILLINGHURST','5'),
('barrio', 'MITRE Y FLORIDA','1'),
('barrio', 'MITRE Y SUIPACHA','1'),
('barrio', 'MONROE 3248','13'),
('barrio', 'MONSERRAT  BDO DE IRIGOYEN Y ALSINA','1'),
('barrio', 'MONSERRAT  PASEO COLON 255','1'),
('barrio', 'MONSERRAT BELGRANO Y SAN JOSE','1'),
('barrio', 'MONSERRAT CARLOS PELLEGRINI Y DIAGONAL NORTE','1'),
('barrio', 'MONSERRAT PLAZA DE MAYO','1'),
('barrio', 'MONT 1372','99'),
('barrio', 'MONTAÑESES Y JURAMENTO','13'),
('barrio', 'MONTAÑESES Y MENDOZA','13'),
('barrio', 'MONTES DE OCA 40','4'),
('barrio', 'MONTES DE OCA 600','4'),
('barrio', 'MONTEVIDEO Y VIAMONTE','1'),
('barrio', 'MONTSERRAT','1'),
('barrio', 'MORENO 1300','4'),
('barrio', 'MORENO 1800','7'),
('barrio', 'MORENO 2366','3'),
('barrio', 'MORENO 300','4'),
('barrio', 'MORENO Y CARLOS PELLEGRINI','1'),
('barrio', 'MORENO Y DEFENSA','1'),
('barrio', 'MORENO Y LA RIOJA','3'),
('barrio', 'MORENO Y PERU  MONSERRAT','1'),
('barrio', 'MORENO Y ROQUE SAENZ PEÑA','1'),
('barrio', 'MORENO Y SALTA','1'),
('barrio', 'MORENO Y VERNET','99'),
('barrio', 'MT ALVEAR','99'),
('barrio', 'MT ALVEAR Y AGUERO','99'),
('barrio', 'MT ALVEAR Y AZCUENAGA','2'),
('barrio', 'MT DE ALVEAR Y RECONQUISTA','1'),
('barrio', 'NAON Y PAROICIENE','12'),
('barrio', 'NAON Y PAROISSIEN','12'),
('barrio', 'NO TIENE BARRIO FIJO','99'),
('barrio', 'NOGOYA Y HELGUERA','11'),
('barrio', 'NUEVA YORK Y BAHIA BLANCA','11'),
('barrio', 'NUEVA YORK Y CHIVILCOY','11'),
('barrio', 'NUEVA YORK Y DESAGUADERO','11'),
('barrio', 'NUEVA YORK Y DESAGUADERO DEVOTO','11'),
('barrio', 'NUNEZ','13'),
('barrio', 'NUÑEZ  CABILDO Y MANZANARES','13'),
('barrio', 'NUÑEZ  CONGRESO','13'),
('barrio', 'NUÑEZ CABILDO 2932','13'),
('barrio', 'NUÑEZ RAMSAY AL 2100','13'),
('barrio', 'OLLEROS 3570','15'),
('barrio', 'ONCE  LARREA Y VIAMONTE','3'),
('barrio', 'ONCE  MISIONES','3'),
('barrio', 'ONCE  PERON Y PASTEUR','3'),
('barrio', 'ONCE CERCA DEL ABASTO','3'),
('barrio', 'ONCE MITRE Y LARREA','3'),
('barrio', 'ORDOÑEZ  LUGANO','8'),
('barrio', 'ORTUZAR','15'),
('barrio', 'PACHECO','99'),
('barrio', 'PALERMO  ARRIBEÑOS Y BULLRICH','14'),
('barrio', 'PALERMO  AV CORONEL DIAZ Y AV LAS HERAS','14'),
('barrio', 'PALERMO  CABILDO Y DORREGO','14'),
('barrio', 'PALERMO  CAVIA Y FIGUEROA ALCORTA','14'),
('barrio', 'PALERMO  GODOY CRUZ Y GUATEMALA','14'),
('barrio', 'PALERMO  HONDURAS Y BULNES','14'),
('barrio', 'PALERMO  HONDURAS Y GASCON','14'),
('barrio', 'PALERMO  MANCILLA Y GALLO','14'),
('barrio', 'PALERMO  MARIO BRAVO Y CABRERA','14'),
('barrio', 'PALERMO  PAMPA Y ALCORTA','14'),
('barrio', 'PALERMO  PARAGUAY 2900','14'),
('barrio', 'PALERMO  VIDT Y CHARCAS','14'),
('barrio', 'PALERMO CHARCAS Y REPUBLICA ARMENIA','14'),
('barrio', 'PALERMO COMUNA 14','14'),
('barrio', 'PALERMO FITZ ROY','14'),
('barrio', 'PALERMO GODOY CRUZ 2320','14'),
('barrio', 'PALERMO HONDURAS','14'),
('barrio', 'PALERMO PACHECO DE MELO Y CORONEL DIAZ','14'),
('barrio', 'PALERMO SOHO','14'),
('barrio', 'PAMPA Y ALCORTA','14'),
('barrio', 'PARAGUAY 2900','14'),
('barrio', 'PARAGUAY 645','1'),
('barrio', 'PARAGUAY Y 9 DE JULIO','1'),
('barrio', 'PARAGUAY Y ESMERALDA','1'),
('barrio', 'PARAGUAY Y LARREA','1'),
('barrio', 'PARAGUAY Y MONTEVIDEO','2'),
('barrio', 'PARAGUAY Y NUEVE DE JULIO','1'),
('barrio', 'PARAGUAY Y RIOBAMBA','2'),
('barrio', 'PARANA 375','1'),
('barrio', 'PARANA Y MONSERRAT','1'),
('barrio', 'PARQUE AVELLANEDA DIRECTORIO Y LACARRA','9'),
('barrio', 'PARQUE AVELLANEDA EUGENIO GARZON Y LACARRA','9'),
('barrio', 'PARQUE NORTE','13'),
('barrio', 'PARQUE PATRICIOS ALBERTI ENTRE BRAZIL Y INCLAN','4'),
('barrio', 'PARQUE PATRICIOS JUJUY Y 15 DE NOVIEMBRE 1889','4'),
('barrio', 'PARQUE ROCA GRAL PAZ Y AVENIDA ROCA','8'),
('barrio', 'PARQUE SAAVEDRA','12'),
('barrio', 'PARRAL Y NEUQUEN','6'),
('barrio', 'PASAJE LA PORTEÑA Y AV RIVADAVIA','7'),
('barrio', 'PASEO ALCORTA','13'),
('barrio', 'PASEO COLON 1333','1'),
('barrio', 'PASEO COLON 250','1'),
('barrio', 'PASEO COLON 255','1'),
('barrio', 'PASEO COLON 321','1'),
('barrio', 'PASEO COLON 600','1'),
('barrio', 'PASEO COLON 900','1'),
('barrio', 'PASEO COLON Y AUTOPISTA 25 DE MAYO','1'),
('barrio', 'PASEO COLON Y BELGRANO','1'),
('barrio', 'PASEO COLON Y MORENO','1'),
('barrio', 'PASEO COLON Y VENEZUELA','1'),
('barrio', 'PASO AL 400','3'),
('barrio', 'PASO Y VIAMONTE','3'),
('barrio', 'PATERNAL  JUAN B JUSTO Y CUCHA CUCHA','15'),
('barrio', 'PATERNAL  TRELLES Y MATURIN','15'),
('barrio', 'PATERNAL AVENIDA SAN MARTIN CLUB PATERNAL','15'),
('barrio', 'PATERNAL GALICIA Y TRELLES','15'),
('barrio', 'PATRICIAS ARGENTINAS Y FRANKLIN','6'),
('barrio', 'PATRICIOS REGIMIENTO','4'),
('barrio', 'PAVON Y ENTRE RIOS','3'),
('barrio', 'PCHACABUCO','7'),
('barrio', 'PEDRAZA Y COLODRERO','12'),
('barrio', 'PEDRO VARELA Y LOPE DE VEGA','10'),
('barrio', 'PELLEGRINI','1'),
('barrio', 'PELLEGRINI Y CORDOBA','1'),
('barrio', 'PELLEGRINI Y MITRE','1'),
('barrio', 'PELLEGRINI Y PARAGUAY','1'),
('barrio', 'PEPIRI 400','4'),
('barrio', 'PERGAMINO Y AVDEL TRABAJO','3'),
('barrio', 'PERGARMINO Y ALBERDI','10'),
('barrio', 'PERON 1300','1'),
('barrio', 'PERON 1500','1'),
('barrio', 'PERON 1669','1'),
('barrio', 'PERON 2755','3'),
('barrio', 'PERON Y AZCUENAGA','3'),
('barrio', 'PERON Y CALLAO','1'),
('barrio', 'PERON Y CASTELLI','3'),
('barrio', 'PERON Y JUNIN','3'),
('barrio', 'PERON Y PELLEGRINI','1'),
('barrio', 'PERU 143','1'),
('barrio', 'PERU AL 200','1'),
('barrio', 'PERU E HIPOLITO IRIGOYEN','1'),
('barrio', 'PERU E IRIGOYEN','1'),
('barrio', 'PERU E YRIGOYEN','1'),
('barrio', 'PERU Y AV RIVADAVIA','1'),
('barrio', 'PERU Y B DE IRIGOYEN','99'),
('barrio', 'PERU Y HIPOLITO IRIGOYEN','99'),
('barrio', 'PICHINCHA Y MEJICO','3'),
('barrio', 'PIEDRABUENA','8'),
('barrio', 'PIEDRAS Y VENEZUELA','1'),
('barrio', 'PILAR 950','9'),
('barrio', 'POMPELLA','4'),
('barrio', 'POMPEYA BONORINO Y FRUCTUOSA RIVERA','4'),
('barrio', 'POSADAS AL 900','2'),
('barrio', 'PRESIDENTE LUIS SAENZ PEÑA 491','1'),
('barrio', 'PUAN Y PEDRO GOYENA','6'),
('barrio', 'PUERTO MADERO  ALEM Y CORDOBA','1'),
('barrio', 'PUERTO MADERO ALICIA M DE JUSTO AL 100','1'),
('barrio', 'PUERTO MADERO ALICIA MOREAU DE JUSTO Y AVENIDA BELGRANO','1'),
('barrio', 'PUERTO MADERO COSTANERA SUR','1'),
('barrio', 'PUEYRREDON 700','3'),
('barrio', 'PUEYRREDON AL 700','3'),
('barrio', 'PUEYRREDON Y CORRIENTES','3'),
('barrio', 'PUEYRREDON Y RIVADAVIA','3'),
('barrio', 'PUEYRREDON Y SARMIENTO','3'),
('barrio', 'PUNTA ARENAS 1600','15'),
('barrio', 'RAFAEL OBLIGADO COMPLEJO COSTA SALGUERO','14'),
('barrio', 'RAMSAY 2100','13'),
('barrio', 'RAMSAY Y ECHEVERRIA','13'),
('barrio', 'RAMSEY Y JURAMENTO','13'),
('barrio', 'RCOLETA','2'),
('barrio', 'RECOLETA  AZCUENAGA Y ARENALES','2'),
('barrio', 'RECOLETA  AZCUENAGA Y PARAGUAY','2'),
('barrio', 'RECOLETA  CORDOBA Y ESMERALDA','2'),
('barrio', 'RECOLETA  URIBURU ENTRE MARCELO T DE ALVEAR Y PARAGUAY','2'),
('barrio', 'RECOLETA CALLE PARAGUAY','2'),
('barrio', 'RECOLETA FACULTAD DE MEDICINA DE LA UBA','2'),
('barrio', 'RECOLETA POSADAS AL 900','2'),
('barrio', 'RECOLETA SANTA FE 2029','2'),
('barrio', 'RECOLTA','2'),
('barrio', 'RECONQUISTA 1100','1'),
('barrio', 'RECONQUISTA 656','1'),
('barrio', 'RECONQUISTA MICRO CENTRO','1'),
('barrio', 'RECONQUISTA Y PERON','1'),
('barrio', 'RECONQUISTA Y VIAMONTE','1'),
('barrio', 'REGIMIENTO PATRICIOS 230','4'),
('barrio', 'RETIRO  ALEM Y CORRIENTES','1'),
('barrio', 'RETIRO  ARENALES Y MAIPU','1'),
('barrio', 'RETIRO  AV ALEM Y AV CORDOBA','1'),
('barrio', 'RETIRO  CORRIENTES Y ESMERALDA','1'),
('barrio', 'RETIRO  PARAGUAY Y FLORIDA','1'),
('barrio', 'RETIRO MAIPU Y LIBERTADOR','1'),
('barrio', 'RETIRO SAN CRISTOBAL','1'),
('barrio', 'RETIRO: ALEM Y PARAGUAY','1'),
('barrio', 'RETIROMT DE ALVEAR Y RECONQUISTA','1'),
('barrio', 'RICARDO GUTIERREZ Y CUENCA','11'),
('barrio', 'RIO DE JANEIRO Y DIAZ VELEZ','6'),
('barrio', 'RIOBAMBA Y RIVADAVIA','3'),
('barrio', 'RIVADAVIA 1300','1'),
('barrio', 'RIVADAVIA 1367','1'),
('barrio', 'RIVADAVIA 4641','6'),
('barrio', 'RIVADAVIA QUINTINO BOCAYUVA','5'),
('barrio', 'RIVADAVIA Y BILLINGHURST','5'),
('barrio', 'RIVADAVIA Y BILLINGURST','5'),
('barrio', 'RIVADAVIA Y GASCON','5'),
('barrio', 'RIVADAVIA Y RIOBAMBA','3'),
('barrio', 'RIVADAVIA Y RIOBAMBACONGRESO','3'),
('barrio', 'RIVADAVIA Y TALCAHUANO','1'),
('barrio', 'ROCA Y PERU','1'),
('barrio', 'RODRIGUEZ PEÑA Y GUIDO','2'),
('barrio', 'RODRIGUEZ PEÑA Y LAVALLE','1'),
('barrio', 'ROJAS Y RECONQUISTA','1'),
('barrio', 'ROJAS Y YERBAL','6'),
('barrio', 'ROQUE SAENZ PEÑA 570','1'),
('barrio', 'ROQUE SAEZ PEÑA 760','1'),
('barrio', 'ROSALES Y SENILLOSA','99'),
('barrio', 'SAENZ PEÑA 1500','1'),
('barrio', 'SALGUERO Y ALCORTA','14'),
('barrio', 'SALGUERO Y RIVADAVIA','5'),
('barrio', 'SALTA E HIPOLITO IRIGOYEN','1'),
('barrio', 'SAN BLAS 1600','15'),
('barrio', 'SAN CRISTIBAL','3'),
('barrio', 'SAN CRISTOBAL  INDEPENDENCIA AL 3000','3'),
('barrio', 'SAN JOSE Y CONSTITUCION','1'),
('barrio', 'SAN JUAN 2100','3'),
('barrio', 'SAN JUAN 350','1'),
('barrio', 'SAN JUAN 727','1'),
('barrio', 'SAN JUAN AL 2100','3'),
('barrio', 'SAN JUAN Y ALBERTI','3'),
('barrio', 'SAN JUAN Y JUJUY','3'),
('barrio', 'SAN JUAN Y LIMA 1261 CONSTITUCION','1'),
('barrio', 'SAN JUAN Y PASCO','3'),
('barrio', 'SAN JUAN Y PICHINCHA','3'),
('barrio', 'SAN JUAN2021','3'),
('barrio', 'SAN MARTIN Y CORDOBA','1'),
('barrio', 'SAN MARTIN Y CORRIENTES','1'),
('barrio', 'SAN MARTIN Y JUAN B JUSTO','15'),
('barrio', 'SAN MARTIN Y PARAGUAY','1'),
('barrio', 'SAN MARTIN Y SAN ALBERTO','11'),
('barrio', 'SAN MARTIN Y SARMIENTO','15'),
('barrio', 'SAN MARTIN Y TUCUMAN','1'),
('barrio', 'SAN NCIOLAS','1'),
('barrio', 'SAN NICOAS  LAVALLE 730','1'),
('barrio', 'SAN NICOLAS  9 DE JULIO Y MORENO','1'),
('barrio', 'SAN NICOLAS  ALEM Y TUCUMAN','1'),
('barrio', 'SAN NICOLAS  AV PASEO COLON Y AV BELGRANO','1'),
('barrio', 'SAN NICOLAS  CORDOBA Y FLORIDA','1'),
('barrio', 'SAN NICOLAS  CORRIENTES Y CALLAO','1'),
('barrio', 'SAN NICOLAS  CORRIENTES Y URUGUAY','1'),
('barrio', 'SAN NICOLAS  LAVALLE Y SAN MARTIN','1'),
('barrio', 'SAN NICOLAS  MAIPU Y SARMIENTO','1'),
('barrio', 'SAN NICOLAS  MISIONES Y RIVADAVIA','1'),
('barrio', 'SAN NICOLAS  PLAZA DE MAYO','1'),
('barrio', 'SAN NICOLAS CENTRO','1'),
('barrio', 'SAN NICOLAS FLORIDA','1'),
('barrio', 'SAN NICOLAS TRIBUNALES','1'),
('barrio', 'SAN NIICOLAS','1'),
('barrio', 'SAN TELMO  SAN JUAN 350','1'),
('barrio', 'SAN TELMO AV GARAY Y PASEO COLON','1'),
('barrio', 'SAN TELMO CCALVO 357','1'),
('barrio', 'SANABRIA 326','99'),
('barrio', 'SANCHEZ DE BUSTAMANTE Y GUEMES','2'),
('barrio', 'SANCHEZ DE LORIA Y MORENO','5'),
('barrio', 'SANTA CATALINA','8'),
('barrio', 'SANTA FE 2029','2'),
('barrio', 'SANTA FE 2245','2'),
('barrio', 'SANTA FE Y ANCHORENA','2'),
('barrio', 'SANTA FE Y CARLOS PELLEGRINI','1'),
('barrio', 'SANTA FE Y CERRITO','1'),
('barrio', 'SANTA FE Y MONTEVIDEO','2'),
('barrio', 'SANTA FE Y ORO','14'),
('barrio', 'SANTA FE Y RAVIGNANI','14'),
('barrio', 'SANTANDER Y LEGUIZAMON','8'),
('barrio', 'SANTIAGO DEL ESTERO 1300','1'),
('barrio', 'SANTIAGO DEL ESTERO 941','1'),
('barrio', 'SANTIAGO DEL ESTERO 977','1'),
('barrio', 'SANTIAGO DEL ESTERO Y HUMBERTO1','1'),
('barrio', 'SANTO TOME Y TERRERO','99'),
('barrio', 'SANTOS DUMONT Y OTERO','15'),
('barrio', 'SAPIOLA Y CESPEDES','13'),
('barrio', 'SARAZA Y SENILLOSA','7'),
('barrio', 'SARMIENTO 1169','1'),
('barrio', 'SARMIENTO AL 300','1'),
('barrio', 'SARMIENTO Y CERRITO','1'),
('barrio', 'SARMIENTO Y MONTEVIDEO','1'),
('barrio', 'SARMIENTO Y PUEYRREDON','3'),
('barrio', 'SASTRE Y HELGUERA','11'),
('barrio', 'SAVEDRA','12'),
('barrio', 'SCALABRINI ORTIZ Y CORRIENTES','15'),
('barrio', 'SEGUROLA Y ARREGUI','10'),
('barrio', 'SEGUROLA Y MIRANDA','10'),
('barrio', 'SFE BILLIBGURST Y STA FE','2'),
('barrio', 'SN CRISTOBAL','3'),
('barrio', 'SOBRE CALLE LAVALLE A METROS DE TRIBUNALES','1'),
('barrio', 'SOLDADO DE LA FRONTERA 5386','8'),
('barrio', 'SOLDATI CASTAÑON Y CULPINA','99'),
('barrio', 'SOLDATI PORTEÑA Y AVENIDA CRUZ','8'),
('barrio', 'SOLDATI RABANAL Y BERG','8'),
('barrio', 'SOLIS Y COCHABAMBA','1'),
('barrio', 'STA FE Y ANCHORENA','2'),
('barrio', 'STA FE Y MONTEVIDEO','2'),
('barrio', 'STA FE Y ORO','14'),
('barrio', 'SUIPACHA 10','1'),
('barrio', 'SUIPACHA 200','1'),
('barrio', 'SUIPACHA Y BARTOLOME MITRE','1'),
('barrio', 'SUIPACHA Y LAVALLE','1'),
('barrio', 'SUIPACHA Y RIVADAVIA','1'),
('barrio', 'SUIPACHA Y SANTA FE','1'),
('barrio', 'SUIPACHA Y VIAMONTE','1'),
('barrio', 'TACUARI Y BELGRANO','1'),
('barrio', 'TACUARIY BELGRANO','1'),
('barrio', 'TAGLE Y LIBERTADOR','14'),
('barrio', 'TALCAHUANO','1'),
('barrio', 'TALCAHUANO 490','1'),
('barrio', 'TALCAHUANO Y ALVEAR','1'),
('barrio', 'TALCAHUANO Y SANTA FE','1'),
('barrio', 'TALCAHUANO Y VIAMONTE','1'),
('barrio', 'TAMBORINI 4800','12'),
('barrio', 'TAMBORINI Y ACHEGA','12'),
('barrio', 'THAMES Y CORDOBA','14'),
('barrio', 'TIMOTEO GORDILLO Y DIRECTORIO','9'),
('barrio', 'TINOGASTA Y AV SAN MARTIN','11'),
('barrio', 'TINOGASTA Y AV SAN MARTIN AGRONOMIA','15'),
('barrio', 'TRES DE FEBRERO Y CONGRESO','13'),
('barrio', 'TRIBUNALES 1300 DE CALLE ALSINA','1'),
('barrio', 'TRIBUNALES POR LA ZONA DE URUGUAY Y CORRIENTES','1'),
('barrio', 'TRIBUNALES TALCAHUANO Y VIAMONTE','1'),
('barrio', 'TRIUMBIRATO Y ACHA','15'),
('barrio', 'TRIUNBIRATO Y ACHA','15'),
('barrio', 'TRIUNVIRATO 3441','15'),
('barrio', 'TRIUNVIRATO Y ACHA','15'),
('barrio', 'TUCUMAN 2035','3'),
('barrio', 'TUCUMAN 240','1'),
('barrio', 'TUCUMAN 300','1'),
('barrio', 'TUCUMAN 800','1'),
('barrio', 'TUCUMAN AL 300','1'),
('barrio', 'TUCUMAN Y AZCUENAGA','3'),
('barrio', 'TUCUMAN Y BULNES','5'),
('barrio', 'TUCUMAN Y FLORIDA','1'),
('barrio', 'TUCUMAN Y LAVALLE','99'),
('barrio', 'TUCUMAN Y PARANA','1'),
('barrio', 'TUCUMAN Y PUEYRREDON','3'),
('barrio', 'TUCUMAN Y RECONQUISTA','1'),
('barrio', 'TUCUMAN Y URUGUAY','1'),
('barrio', 'ULRICO SCHMIDL Y MOLINA','9'),
('barrio', 'URIBURU Y MARCELO T DE ALVEAR','2'),
('barrio', 'URIBURU Y PERON','3'),
('barrio', 'URIBURU Y SANTA FE','2'),
('barrio', 'URQUIZA 600','3'),
('barrio', 'VALENTIN GOMEZ Y AGUERO','3'),
('barrio', 'VELAZCO 145','15'),
('barrio', 'VELEZ SARLFIELD','4'),
('barrio', 'VENEZUELA 1300','1'),
('barrio', 'VENEZUELA 160','1'),
('barrio', 'VENEZUELA Y ALBERTI','3'),
('barrio', 'VENTURA DE LA VEGA 3940','4'),
('barrio', 'VERON DE ASTRADA 6351','8'),
('barrio', 'VIAMONTE 1570','1'),
('barrio', 'VIAMONTE 1570 1','1'),
('barrio', 'VIAMONTE 200','1'),
('barrio', 'VIAMONTE 500','1'),
('barrio', 'VIAMONTE AL 200300','1'),
('barrio', 'VIAMONTE Y AZCUENAGA','3'),
('barrio', 'VIAMONTE Y BOUCHARD','1'),
('barrio', 'VIAMONTE Y BUCHARD','1'),
('barrio', 'VIAMONTE Y NUEVE DE JULIO','1'),
('barrio', 'VIAMONTE Y PASO','3'),
('barrio', 'VIILLA URQUIZA','12'),
('barrio', 'VILLA','99'),
('barrio', 'VILLA 11 14','7'),
('barrio', 'VILLA 15','8'),
('barrio', 'VILLA 21- 24','4'),
('barrio', 'VILLA 2124','4'),
('barrio', 'VILLA 3','8'),
('barrio', 'VILLA 3 FATIMA','8'),
('barrio', 'VILLA 31 MANZANA 12','1'),
('barrio', 'VILLA 31 MZ 32 CASA 35','1'),
('barrio', 'VILLA 31 RETIRO','1'),
('barrio', 'VILLA 31BARRIO PLAYON','1'),
('barrio', 'VILLA CFRESPO','15'),
('barrio', 'VILLA CRESPO  AV WARNES Y MUÑECAS','15'),
('barrio', 'VILLA CRESPO  LERMA Y ESTADO DE ISRAEL','15'),
('barrio', 'VILLA CRESPO  LOYOLA Y GURRUCHAGA','15'),
('barrio', 'VILLA DEL PARQUE  CUENCA Y SIMBRON','11'),
('barrio', 'VILLA DEL PARQUE  RICARDO GUTIERREZ Y CUENCA','11'),
('barrio', 'VILLA DEL PARQUE AV NAZCA Y NAVARRO','11'),
('barrio', 'VILLA DEL PARQUE CUENCA Y TINOGASTA','11'),
('barrio', 'VILLA DEVOTO BEIRO Y CONCORDIA','11'),
('barrio', 'VILLA GRAL MITRE','12'),
('barrio', 'VILLA LUGANO BARRIO SAMORE','8'),
('barrio', 'VILLA ORTUZAR  BARZANA 1192','15'),
('barrio', 'VILLA ORTUZAR  CAMPILLO Y COMBATIENTE DE MALVINAS','15'),
('barrio', 'VILLA ORTUZAR  TRIUMBIRATO Y ACHA','15'),
('barrio', 'VILLA ORTUZAR  TRIUNBIRATO Y ACHA','15'),
('barrio', 'VILLA PARQUE','11'),
('barrio', 'VILLA PUEYRREDON  AV NAZCA Y PAREJA','12'),
('barrio', 'VILLA PUYRREDON','12'),
('barrio', 'VILLA REAL  AVENIDA JOSE LUIS CANTILO Y AV GENERAL PAZ','10'),
('barrio', 'VILLA URQUIZA  ANDONAEGUI Y AV DE LOS INCAS','12'),
('barrio', 'VILLA URQUIZA  JURAMENTO 4367','12'),
('barrio', 'VILLA31','1'),
('barrio', 'VILLANUEVA ENTRE MAURE Y GOROSTIAGA','14'),
('barrio', 'VILLANUEVA Y GOROSTIAGA','14'),
('barrio', 'VILLANUEVA Y MAURE','14'),
('barrio', 'VILLLA 11114','7'),
('barrio', 'VILLLA 1-11-14','7'),
('barrio', 'WARNES Y MUÑECAS','15'),
('barrio', 'YATAY 130','5'),
('barrio', 'YATAY 200','5'),
('barrio', 'ZAAVEDRA','12'),
('barrio', 'ZAAVEDRA  NAON Y PAROICIENE','12'),
('barrio', 'ZAAVEDRA  PEDRAZA Y COLODRERO','12'),
('barrio', 'ZAVALETA Y CRUZ','4');

insert into encu.dictra
select diccionario,origen,destino::integer, 1 from encu.diccionario_agregar
where trim(diccionario)||trim(origen) not in (
select trim(dictra_dic)||trim(dictra_ori) from encu.dictra);


drop table encu.diccionario_agregar;