CREATE TABLE encu.diccionario_agregar (
  diccionario text,
  origen text,
  destino text
  )
  WITH (
  OIDS=FALSE
);
ALTER TABLE encu.diccionario_agregar
  OWNER TO tedede_php;


insert into encu.diccionario_agregar values
('barrio', 'AGRONOMIA  AV SAN MARTIN Y NOGOYA','15'),
('barrio', 'ALMAGRO  AV MEDRANO Y POTOSI','5'),
('barrio', 'BALVANERA  AV BELGRANO Y ALBERTI','3'),
('barrio', 'BALVANERA SAENZ PEŃA Y AVENIDA DE MAYO','3'),
('barrio', 'BELGRANO  CABILDO Y SUCRE','13'),
('barrio', 'BELGRANO  CIUDAD UNIVERSITARIA','13'),
('barrio', 'BELGRANO  EN LA CALLE MOLDES','13'),
('barrio', 'BELGRANO  MONTAÑESES Y MENDOZA','13'),
('barrio', 'BELGRANO  PASEO ALCORTA','13'),
('barrio', 'BELGRANO  SAPIOLA Y CESPEDES','13'),
('barrio', 'BELGRANO  VIDAL Y OLAZABAL','13'),
('barrio', 'BELGRANO Y PERU','1'),
('barrio', 'CABALLITO  AV IRIGOYEN Y MUÑIZ','6'),
('barrio', 'CAÑITAS  BAEZ Y MATIENZO','14'),
('barrio', 'CHACARITA  FOREST 800','15'),
('barrio', 'CHACARITA  GUEVARA 525','15'),
('barrio', 'CHACARITA  GUEVARA Y ELCANO','15'),
('barrio', 'CHACARITA  SANTOS DUMONT Y OTERO','15'),
('barrio', 'COBO FLORES','7'),
('barrio', 'COLEGIALES  CONESA Y MAURE','13'),
('barrio', 'COLEGIALES  JORGE NEWBERY Y CORDOBA','13'),
('barrio', 'CONSTITUCION  ENTRE RIOS Y GARAY','1'),
('barrio', 'DIRECTORIO Y ACOSTA','9'),
('barrio', 'EMILIO LAMARCA Y ARANGUREN','10'),
('barrio', 'FLORES  AV RIVADAVIA Y NAZCA','7'),
('barrio', 'FLORES  CARRASCO Y JUAN B JUSTO','7'),
('barrio', 'FLORES  JPVARELA 1301','7'),
('barrio', 'FLORES  PASAJE LA PORTEÑA Y AV RIVADAVIA','7'),
('barrio', 'LA PATERNAL  12 DE OCTUBRE ENTRE CUCHA CUCHA Y ESPINOZA','15'),
('barrio', 'LA PATERNAL  CUCHA CUCHA Y SAN MARTIN','15'),
('barrio', 'LA PATERNAL  JUAN B JUSTO Y ARTIGAS','15'),
('barrio', 'LA PATERNAL  SAN BLAS 1600','15'),
('barrio', 'LA PATERNAL  SAN MARTIN Y JUAN B JUSTO','15'),
('barrio', 'LA PATERNAL  WARNES Y CHORROARIN','15'),
('barrio', 'LINIERS  GALLARDO 149','9'),
('barrio', 'MICROCENTRO  PARAGUAY Y LARREA','1'),
('barrio', 'MONSERRAT  BDO DE IRIGOYEN Y ALSINA','1'),
('barrio', 'MONSERRAT  PASEO COLON 255','1'),
('barrio', 'MORENO Y PERU  MONSERRAT','1'),
('barrio', 'NUÑEZ  CABILDO Y MANZANARES','13'),
('barrio', 'ONCE  LARREA Y VIAMONTE','3'),
('barrio', 'ONCE  MISIONES','3'),
('barrio', 'ONCE  PERON Y PASTEUR','3'),
('barrio', 'ORDOÑEZ  LUGANO','8'),
('barrio', 'PALERMO  ARRIBEÑOS Y BULLRICH','14'),
('barrio', 'PALERMO  AV CORONEL DIAZ Y AV LAS HERAS','14'),
('barrio', 'PALERMO  CABILDO Y DORREGO','14'),
('barrio', 'PALERMO  CAVIA Y FIGUEROA ALCORTA','14'),
('barrio', 'PALERMO  GODOY CRUZ Y GUATEMALA','14'),
('barrio', 'PALERMO  HONDURAS Y BULNES','14'),
('barrio', 'PALERMO  HONDURAS Y GASCON','14'),
('barrio', 'PALERMO  MANCILLA Y GALLO','14'),
('barrio', 'PALERMO  MARIO BRAVO Y CABRERA','14'),
('barrio', 'PALERMO  PAMPA Y ALCORTA','14'),
('barrio', 'PALERMO  PARAGUAY 2900','14'),
('barrio', 'PALERMO  VIDT Y CHARCAS','14'),
('barrio', 'PATERNAL  JUAN B JUSTO Y CUCHA CUCHA','15'),
('barrio', 'PATERNAL  TRELLES Y MATURIN','15'),
('barrio', 'PUERTO MADERO  ALEM Y CORDOBA','1'),
('barrio', 'RECOLETA  AZCUENAGA Y ARENALES','2'),
('barrio', 'RECOLETA  AZCUENAGA Y PARAGUAY','2'),
('barrio', 'RECOLETA  CORDOBA Y ESMERALDA','2'),
('barrio', 'RECOLETA  URIBURU ENTRE MARCELO T DE ALVEAR Y PARAGUAY','2'),
('barrio', 'RETIRO  ALEM Y CORRIENTES','1'),
('barrio', 'RETIRO  ARENALES Y MAIPU','1'),
('barrio', 'RETIRO  AV ALEM Y AV CORDOBA','1'),
('barrio', 'RETIRO  CORRIENTES Y ESMERALDA','1'),
('barrio', 'RETIRO  PARAGUAY Y FLORIDA','1'),
('barrio', 'RETIROMT DE ALVEAR Y RECONQUISTA','1'),
('barrio', 'RIVADAVIA Y RIOBAMBACONGRESO','1'),
('barrio', 'SAN CRISTOBAL  INDEPENDENCIA AL 3000','3'),
('barrio', 'SAN NICOAS  LAVALLE 730','1'),
('barrio', 'SAN NICOLAS  9 DE JULIO Y MORENO','1'),
('barrio', 'SAN NICOLAS  ALEM Y TUCUMAN','1'),
('barrio', 'SAN NICOLAS  AV PASEO COLON Y AV BELGRANO','1'),
('barrio', 'SAN NICOLAS  CORDOBA Y FLORIDA','1'),
('barrio', 'SAN NICOLAS  CORRIENTES Y CALLAO','1'),
('barrio', 'SAN NICOLAS  CORRIENTES Y URUGUAY','1'),
('barrio', 'SAN NICOLAS  LAVALLE Y SAN MARTIN','1'),
('barrio', 'SAN NICOLAS  MAIPU Y SARMIENTO','1'),
('barrio', 'SAN NICOLAS  MISIONES Y RIVADAVIA','1'),
('barrio', 'SAN NICOLAS  PLAZA DE MAYO','1'),
('barrio', 'SAN TELMO  SAN JUAN 350','1'),
('barrio', 'VILLA 31BARRIO PLAYON','1'),
('barrio', 'VILLA CRESPO  AV WARNES Y MUÑECAS','15'),
('barrio', 'VILLA CRESPO  LERMA Y ESTADO DE ISRAEL','15'),
('barrio', 'VILLA CRESPO  LOYOLA Y GURRUCHAGA','15'),
('barrio', 'VILLA DEL PARQUE  CUENCA Y SIMBRON','11'),
('barrio', 'VILLA DEL PARQUE  RICARDO GUTIERREZ Y CUENCA','11'),
('barrio', 'VILLA ORTUZAR  BARZANA 1192','15'),
('barrio', 'VILLA ORTUZAR  CAMPILLO Y COMBATIENTE DE MALVINAS','15'),
('barrio', 'VILLA ORTUZAR  TRIUMBIRATO Y ACHA','15'),
('barrio', 'VILLA ORTUZAR  TRIUNBIRATO Y ACHA','15'),
('barrio', 'VILLA PUEYRREDON  AV NAZCA Y PAREJA','12'),
('barrio', 'VILLA REAL  AVENIDA JOSE LUIS CANTILO Y AV GENERAL PAZ','10'),
('barrio', 'VILLA URQUIZA  ANDONAEGUI Y AV DE LOS INCAS','12'),
('barrio', 'VILLA URQUIZA  JURAMENTO 4367','12'),
('barrio', 'ZAAVEDRA  NAON Y PAROICIENE','12'),
('barrio', 'ZAAVEDRA  PEDRAZA Y COLODRERO','12');

insert into encu.dictra
select diccionario,origen,destino::integer, 1 from encu.diccionario_agregar
where trim(diccionario)||trim(origen) not in (
select trim(dictra_dic)||trim(dictra_ori) from encu.dictra);


drop table encu.diccionario_agregar;