CREATE TABLE encu.diccionario_agregar (
  diccionario text,
  origen text,
  destino text
  )
  WITH (
  OIDS=FALSE
);
ALTER TABLE encu.diccionario_agregar
  OWNER TO tedede_php;


insert into encu.diccionario_agregar values
('pais','ALBANIA','3'),
('pais','ALEMANIA','3'),
('pais','ARMENIA','3'),
('pais','AUSTRALIA','3'),
('pais','AUSTRIA','3'),
('pais','BELGICA','3'),
('pais','BOLIVIA','1'),
('pais','BRASIL','1'),
('pais','CANADA','3'),
('pais','CHECOSLOVAQUIA','3'),
('pais','CHILE','1'),
('pais','CHINA','3'),
('pais','COLOMBIA','3'),
('pais','COREA','3'),
('pais','COREA DEL NORTE','3'),
('pais','COREA DEL SUR','3'),
('pais','COSTA RICA','3'),
('pais','CUBA','3'),
('pais','ECUADOR','3'),
('pais','EE UU','3'),
('pais','EEUU','3'),
('pais','ESPAÑA','3'),
('pais','ESTADOS UNIDOS','3'),
('pais','FRANCIA','3'),
('pais','GRECIA','3'),
('pais','HAITI','3'),
('pais','HONG KONG','3'),
('pais','HUNGRIA','3'),
('pais','INGLATERRA','3'),
('pais','IRLANDA','3'),
('pais','ISRAEL','3'),
('pais','ITALIA','3'),
('pais','JAPON','3'),
('pais','LIBANO','3'),
('pais','MEXICO','3'),
('pais','NIGERIA','3'),
('pais','NUEVA ZELANDA','3'),
('pais','PARAGUAY','1'),
('pais','PERU','2'),
('pais','POLONIA','3'),
('pais','PORTUGAL','3'),
('pais','PUERTO RICO','3'),
('pais','REPUBLICA CHECA','3'),
('pais','REPUBLICA DOMINICANA','3'),
('pais','RUMANIA','3'),
('pais','RUSIA','3'),
('pais','SENEGAL','3'),
('pais','SIRIA','3'),
('pais','SUDAFRICA','3'),
('pais','SUECIA','3'),
('pais','SUIZA','3'),
('pais','TAIWAN','3'),
('pais','TURQUIA','3'),
('pais','UCRANIA','3'),
('pais','URUGUAY','1'),
('pais','VENEZUELA','3'),
('provincia','CATAMARCA','1'),
('provincia','CHACO','1'),
('provincia','CHUBUT','1'),
('provincia','CORDOBA','1'),
('provincia','CORRIENTES','1'),
('provincia','ENTRE RIOS','1'),
('provincia','FORMOSA','1'),
('provincia','JUJUY','1'),
('provincia','LA PAMPA','1'),
('provincia','LA RIOJA','1'),
('provincia','MENDOZA','1'),
('provincia','MISIONES','1'),
('provincia','NEUQUEN','1'),
('provincia','RIO NEGRO','1'),
('provincia','SALTA','1'),
('provincia','SAN JUAN','1'),
('provincia','SAN LUIS','1'),
('provincia','SAN MARTIN','1'),
('provincia','SANTA CRUZ','1'),
('provincia','SANTA FE','1'),
('provincia','SANTIAGO DEL ESTERO','1'),
('provincia','TIERRA DEL FUEGO','1'),
('provincia','TUCUMAN','1'),
('partido','25 DE MAYO','2'),
('partido','3 ARROYOS','2'),
('partido','3 DE FEBRERO','1'),
('partido','9 DE JULIO','2'),
('partido','ACASUSO','1'),
('partido','ACASSUSO','1'),
('partido','ADROGUE','1'),
('partido','ALBERTI','2'),
('partido','ALDO BONZI','1'),
('partido','ALEJANDRO KORN','2'),
('partido','ALMIRANTE BROWN','1'),
('partido','AMEGHINO','2'),
('partido','AMEGUINO','2'),
('partido','ARENALES','2'),
('partido','ARRECIFE','2'),
('partido','ARRECIFES','2'),
('partido','ARROYO CORTO','2'),
('partido','AVELLANEDA','1'),
('partido','AYACUCHO','2'),
('partido','AZUL','2'),
('partido','BAHIA BLANCA','2'),
('partido','BALCARCE','2'),
('partido','BANFIELD','1'),
('partido','BARADERO','2'),
('partido','BECCAR','1'),
('partido','BELLA VISTA','1'),
('partido','BENITO JUAREZ','2'),
('partido','BERAZATEGUI','1'),
('partido','BERISO','2'),
('partido','BERISSO','2'),
('partido','BERNAL','1'),
('partido','BOLIVAR','2'),
('partido','BOULOGNE','1'),
('partido','BRAGADO','2'),
('partido','BURZACO','1'),
('partido','CABILDO','2'),
('partido','CACHARI','2'),
('partido','CAMPANA','2'),
('partido','CAÑUELAS','1'),
('partido','CAPILLA DEL SEÑOR','2'),
('partido','CAPITAN SARMIENTO','2'),
('partido','CARLOS CASARES','2'),
('partido','CARLOS TEJEDOR','2'),
('partido','CARMEN DE PATAGONES','2'),
('partido','CASBAS','2'),
('partido','CASEROS','1'),
('partido','CASTELAR','1'),
('partido','CHACABUCO','2'),
('partido','CHIVILCOY','2'),
('partido','CIUDAD EVITA','1'),
('partido','CIUDADELA','1'),
('partido','CLAYPOLE','1'),
('partido','COLON','2'),
('partido','CORONEL DORREGO','2'),
('partido','CORONEL PRINGLES','2'),
('partido','CORONEL SEGUI','2'),
('partido','CORONEL SUAREZ','2'),
('partido','CUIDADELA','1'),
('partido','DAIREAUX','2'),
('partido','DARREGUEIRA','2'),
('partido','DERQUI','2'),
('partido','DOLORES','2'),
('partido','DON TORCUATO','1'),
('partido','ESTEBAN ECHEVERRIA','1'),
('partido','EL PALOMAR','1'),
('partido','EL TALAR','1'),
('partido','EMILIO BUNGE','2'),
('partido','ESCOBAR','2'),
('partido','EZEIZA','1'),
('partido','EZPELETA','2'),
('partido','FLORENCIO VARELA','1'),
('partido','FLORENTINO AMEGUINO','2'),
('partido','FLORENTINO AMEGHINO','2'),
('partido','FLORIDA','1'),
('partido','FRANCISCO ALVAREZ','1'),
('partido','FRANCISCO SOLANO','1'),
('partido','GARIN','2'),
('partido','GENERAL ALVARADO','2'),
('partido','GENERAL BELGRANO','2'),
('partido','GENERAL LAS HERAS','2'),
('partido','GENERAL PINTOS','2'),
('partido','GENERAL RODRIGUEZ','2'),
('partido','GENERAL SARMIENTO','2'),
('partido','GENERAL VEDIA','2'),
('partido','GENERAL VIAMONTE','2'),
('partido','GERLI','1'),
('partido','GLEW','1'),
('partido','GONZALEZ CATAN','1'),
('partido','GONZALES CATAN','1'),
('partido','GENERAL PINTO','2'),
('partido','GRAN BUENOS AIRES','1'),
('partido','GRAND BOURG','1'),
('partido','GUAMINI','2'),
('partido','GUERNICA','2'),
('partido','HAEDO','1'),
('partido','HURLINGHAM','1'),
('partido','INGENIERO BUDGE','1'),
('partido','INGENIERO MASCHWITZ','2'),
('partido','ISIDRO CASANOVA','1'),
('partido','ITUZAINGO','1'),
('partido','ALBERDI','2'),
('partido','J B ALBERDI','2'),
('partido','JOSE C PAZ','1'),
('partido','JOSE INGENIEROS','1'),
('partido','JOSE LEON SUAREZ','1'),
('partido','JUNIN','2'),
('partido','LA FERRERE','1'),
('partido','LA LUCILA','2'),
('partido','LA MATANZA','1'),
('partido','LA PLATA','2'),
('partido','LA TABLADA','1'),
('partido','LAFERRERE','1'),
('partido','LANUS','1'),
('partido','LANUS ESTE','1'),
('partido','LANUS OESTE','1'),
('partido','LAS FLORES','2'),
('partido','LAS HERAS','2'),
('partido','LAVALLOL','1'),
('partido','LEZAMA','2'),
('partido','LIBERTAD','1'),
('partido','LINCOLN','2'),
('partido','LOBERIA','2'),
('partido','LOBOS','2'),
('partido','LOMA HERMOSA','1'),
('partido','LOMAS','1'),
('partido','LOMAS DE ZAMORA','1'),
('partido','LOMAS DEL MIRADOR','1'),
('partido','LONGCHAMPS','1'),
('partido','LOS POLVORINES','1'),
('partido','LOS TOLDOS','2'),
('partido','LUIS GUILLON','1'),
('partido','LUJAN','2'),
('partido','MAIPU','2'),
('partido','MALVINAS ARGENTINAS','1'),
('partido','MAR DE AJO','2'),
('partido','MAR DEL PLATA','2'),
('partido','MAR DEL TUYU','2'),
('partido','MARCOS PAZ','2'),
('partido','MARTIN CORONADO','1'),
('partido','MARTINEZ','1'),
('partido','MATANZA','1'),
('partido','MATHEU','2'),
('partido','MERCEDES','2'),
('partido','MERLO','1'),
('partido','MIRAMAR','2'),
('partido','MOCTEZUMA','2'),
('partido','MONTE GRANDE','1'),
('partido','MORENO','1'),
('partido','MORON','1'),
('partido','MUNRO','1'),
('partido','MUÑIZ','2'),
('partido','NAVARRO','2'),
('partido','NECOCHEA','2'),
('partido','NORBERTO DE LA RIESTRA','2'),
('partido','NUEVE DE JULIO','2'),
('partido','OLAVARRIA','2'),
('partido','OLIVOS','1'),
('partido','PACHECO','1'),
('partido','PADUA','1'),
('partido','PALOMAR','1'),
('partido','PARADA ROBLES','2'),
('partido','PARQUE LELOIR','1'),
('partido','PARTIDO DE ESTEBAN ETCHEVERRIA','1'),
('partido','PARTIDO DE LA COSTA','2'),
('partido','PARTIDO DE LA MATANZA','1'),
('partido','PARTIDO DE LOBOS','2'),
('partido','PARTIDO DE SAN MARTIN','1'),
('partido','PARTIDO GENERAL VILLEGAS','2'),
('partido','PARTIDO MALVINAS ARGENTINAS','1'),
('partido','PASO DEL REY','1'),
('partido','PEDRO LURO','2'),
('partido','PEHUAJO','2'),
('partido','PELLEGRINI','2'),
('partido','PERGAMINO','2'),
('partido','PIGÜE','2'),
('partido','PILAR','2'),
('partido','PINAMAR','2'),
('partido','POLVORINES','1'),
('partido','PONTEVEDRA','1'),
('partido','PRINGLES','2'),
('partido','PUAN','2'),
('partido','PUERTO BELGRANO','2'),
('partido','PUNTA ALTA','2'),
('partido','QUILMES','1'),
('partido','RAFAEL CALZADA','1'),
('partido','RAFAEL CASTILLO','1'),
('partido','RAMALLO','2'),
('partido','RAMOS','1'),
('partido','RAMOS MEJIA','1'),
('partido','RANCHOS','2'),
('partido','RAUCH','2'),
('partido','REMEDIOS DE ESCALADA','1'),
('partido','RIVADAVIA','2'),
('partido','ROJAS','2'),
('partido','ROQUE PEREZ','2'),
('partido','SAENZ PEÑA','1'),
('partido','SALADILLO','2'),
('partido','SALTO','2'),
('partido','SALTO ARGENTINO','2'),
('partido','SAN ANDRES','1'),
('partido','SAN ANDRES DE GILES','2'),
('partido','SAN ANTONIO DE ARECO','2'),
('partido','SAN ANTONIO DE PADUA','1'),
('partido','SAN CLEMENTE','2'),
('partido','SAN FERNANDO','1'),
('partido','SAN FRANCISCO SOLANO','1'),
('partido','SAN ISIDRO','1'),
('partido','SAN JUSTO','1'),
('partido','SAN MIGUEL','1'),
('partido','SAN MIGUEL DEL MONTE','2'),
('partido','SAN NICOLAS','2'),
('partido','SAN PEDRO','2'),
('partido','SAN VICENTE','2'),
('partido','SANTA TERESITA','2'),
('partido','SANTOS LUGARES','1'),
('partido','SARANDI','1'),
('partido','SOLANO','1'),
('partido','TANDIL','2'),
('partido','TAPALQUE','2'),
('partido','TAPIALES','1'),
('partido','TEMPERLEY','1'),
('partido','TIGRE','1'),
('partido','TORNQUIST','2'),
('partido','TORTUGUITAS','1'),
('partido','TRENQUE LAUQUEN','2'),
('partido','TRENQUELAUQUEN','2'),
('partido','TRES ARROYOS','2'),
('partido','TRES DE FEBRERO','1'),
('partido','TRES LOMAS','2'),
('partido','TURDERA','1'),
('partido','VALENTIN ALSINA','1'),
('partido','VARELA','1'),
('partido','VEDIA','2'),
('partido','VICENTE LOPEZ','1'),
('partido','VICTORIA ','1'),
('partido','VILLA ADELINA','1'),
('partido','VILLA BALLESTER','1'),
('partido','VILLA BOSCH','1'),
('partido','VILLA CELINA','1'),
('partido','VILLA DOMINICO','1'),
('partido','VILLA FIORITO ','1'),
('partido','VILLA GESELL','2'),
('partido','VILLA INSUPERABLE','1'),
('partido','VILLA LINCH','1'),
('partido','VILLA LUZURIAGA','1'),
('partido','VILLA LYNCH','1'),
('partido','VILLA MADERO','1'),
('partido','VILLA MAIPU','1'),
('partido','VILLA MARTELLI','1'),
('partido','VILLA RECONDO','1'),
('partido','VILLARINO','2'),
('partido','VILLEGAS','2'),
('partido','VIRREYES','1'),
('partido','WILDE','1'),
('partido','ZARATE','2'),
('comuna','-9','99'),
('comuna','24 DE NOVIEMBRE','99'),
('comuna','25 DE MAYO ENTRE SARMIENTO Y PERON','1'),
('comuna','25 DE MAYO Y BOLIVAR','1'),
('comuna','25 DE MAYO Y LAVALLE','1'),
('comuna','25 DE MAYO Y PERON','1'),
('comuna','9 DE JULIO 1925','1'),
('comuna','9 DE JULIO E INDEPENDENCIA','1'),
('comuna','9 DE JULIO Y AV DE MAYO','1'),
('comuna','9 DE JULIO Y BELGRANO','1'),
('comuna','9 DE JULIO Y BELGRANOCABA','1'),
('comuna','9 DE JULIO Y DIAGONAL NORTE','1'),
('comuna','9 DE JULIO Y GARAY','1'),
('comuna','9 DE JULIO Y MORENO','1'),
('comuna','9 DE JULIO Y SANTA FE','1'),
('comuna','9 JULIO Y SANTA FE','1'),
('comuna','ABASTO','3'),
('comuna','ABASTO SHOPPING','3'),
('comuna','ACEVEDO 80','15'),
('comuna','AEROPARQUE','14'),
('comuna','AGRONOMIA','15'),
('comuna','AGUERO 616','3'),
('comuna','AGÜERO Y LAVALLE','3'),
('comuna','ALBARELLOS 3153','12'),
('comuna','ALBARRELLOS 3153','12'),
('comuna','ALEM Y CORDOBA','1'),
('comuna','ALEM Y CORRIENTES','1'),
('comuna','ALEM Y DELLA PAOLERA','1'),
('comuna','ALEM Y DELLA PAULERA','1'),
('comuna','ALEM Y PARAGUAY','1'),
('comuna','ALEM Y TUCUMAN','1'),
('comuna','ALEM Y VENEZUELA','1'),
('comuna','ALICIA M DE JUSTO AL 100','1'),
('comuna','ALICIA MOREAU DE JUSTO Y AVENIDA BELGRANO','1'),
('comuna','ALMAGRO','5'),
('comuna','ALSINA Y 24 DE NOVIEMBRE','3'),
('comuna','ALSINA Y BOLIVAR','3'),
('comuna','ALSINA Y SAENZ PEÑA','3'),
('comuna','ALVAREZ TOMAS Y ELCANO','15'),
('comuna','ALVEAR Y AYACUCHO','2'),
('comuna','AMAGRO','5'),
('comuna','ANCHORENA Y CORDOBA','3'),
('comuna','ANDONAEGUI Y AV DE LOS INCAS','12'),
('comuna','ANGEL GALLARDO 470','6'),
('comuna','ARCOS Y MENDOZA','13'),
('comuna','ARENALES Y MAIPU','1'),
('comuna','ARISMENDI 2670','15'),
('comuna','ARRIBEÑOS Y BULLRICH','14'),
('comuna','ARRIZMENDI 2670','15'),
('comuna','ARTIGAS 5540','12'),
('comuna','AV','99'),
('comuna','AV 9 DE JULIO','1'),
('comuna','AV 9 DE JULIO Y MORENO','1'),
('comuna','AV ALEM 650','1'),
('comuna','AV BELGRANO 1590','1'),
('comuna','AV BELGRANO AL 1300','1'),
('comuna','AV BELGRANO Y ALBERTI','3'),
('comuna','AV BELGRANO Y LIMA','1'),
('comuna','AV BELGRANO Y PASCO','1'),
('comuna','AV BELGRANO Y SAENZ PEÑA','1'),
('comuna','AV COBO','7'),
('comuna','AV CORDOBA','99'),
('comuna','AV CORONEL DIAZ Y AV LAS HERAS','14'),
('comuna','AV CORRIENTES 1437','1'),
('comuna','AV CORRIENTES 846','1'),
('comuna','AV CORRIENTES Y AV CALLAO','1'),
('comuna','AV DE LOS CORRALES 6661','8'),
('comuna','AV DE MAYO','1'),
('comuna','AV DE MAYO 869 CABA','1'),
('comuna','AV DE MAYO Y 9DE JULIO','1'),
('comuna','AV DE MAYO Y TALCHUANO','1'),
('comuna','AV INCAS Y TRIUNVIRATO','15'),
('comuna','AV LA PLATA 1100','5'),
('comuna','AV LOS INCAS Y AVALOS','15'),
('comuna','AV MADERO Y ALEM','99'),
('comuna','AV MAYO CENTRO ESTACION PERU','1'),
('comuna','AV MEDRANO Y POTOSI','5'),
('comuna','AV NAZCA Y NAVARRO','11'),
('comuna','AV NAZCA Y PAREJA','12'),
('comuna','AV PATRICIAS ARGENTINAS','6'),
('comuna','AV RIVADAVIA','99'),
('comuna','AV RIVADAVIA Y NAZCA','7'),
('comuna','AV SAENZ 300','4'),
('comuna','AV SAN MARTIN Y NOGOYA','15'),
('comuna','AV SEGUROLA 1949 HOSPITAL MANUEL ROCCA','10'),
('comuna','AV WARNES Y MUÑECAS','15'),
('comuna','AVBELGRANO Y BOEDO','5'),
('comuna','AVDA SAN JUAN AL 1700','1'),
('comuna','AVDA SAN MARTIN Y CHORROARIN','11'),
('comuna','AVELLANEDA','99'),
('comuna','AVELLANEDA 212','6'),
('comuna','AVELLANEDA Y NAZCA','7'),
('comuna','AVENIDA CORDOBA','99'),
('comuna','AVENIDA CORDOBA Y BILLINGHURST','2'),
('comuna','AVENIDA DE MAYO','99'),
('comuna','AVENIDA JOSE LUIS CANTILO Y AV GENERAL PAZ','10'),
('comuna','AVENIDA RIVADAVIA Y DOBLAS','6'),
('comuna','AVLIBERTADOR','13'),
('comuna','AZCUENAGA 351','3'),
('comuna','AZCUENAGA Y ARENALES','2'),
('comuna','AZCUENAGA Y CORRIENTES','3'),
('comuna','AZCUENAGA Y PARAGUAY','2'),
('comuna','AZOPARDO Y CHILE','1'),
('comuna','AZOPARDO Y GARAY','1'),
('comuna','BAEZ Y AREVALO','14'),
('comuna','BAEZ Y MATIENZO','14'),
('comuna','BAHIA BLANCO Y CAMARONES','10'),
('comuna','BALAVANERA','3'),
('comuna','BALCARCE 186','1'),
('comuna','BALCARCE 90','1'),
('comuna','BALCARCE AL 1000','1'),
('comuna','BALCARCE Y ALSINA','1'),
('comuna','BALCARCE Y MORENO','1'),
('comuna','BALCARCE Y VENEZUELA','1'),
('comuna','BALDOMERO FERNANDEZ MORENO 1200','7'),
('comuna','BALVANERA','3'),
('comuna','BALVARERA','3'),
('comuna','BALVENERA','3'),
('comuna','BARRIO NORTE','2'),
('comuna','BARRIO PIEDRABUENA','8'),
('comuna','BARRIO SAMORE','8'),
('comuna','BARROS PAZOS AL 3600','8'),
('comuna','BARTOLOME MITRE','99'),
('comuna','BARTOLOME MITRE 300','1'),
('comuna','BARTOLOME MITRE 600','1'),
('comuna','BARTOLOME MITRE AL 2200','1'),
('comuna','BARTOLOME MITRE Y DIAGONAL NORTE','1'),
('comuna','BARTOLOME MITRE Y JUNIN','1'),
('comuna','BARTOLOME MITRE Y PASO','1'),
('comuna','BARTOLOME MITRE Y RIVADAVIA','1'),
('comuna','BARTOLOME MITRE Y SUIPACHA','1'),
('comuna','BARZANA 1192','15'),
('comuna','BDO DE IRIGOYEN Y ALSINA','1'),
('comuna','BEIRO Y CONCORDIA','11'),
('comuna','BEIRO Y EMILIO LAMARCA','11'),
('comuna','BELGRANO','13'),
('comuna','BELGRANO 1381','1'),
('comuna','BELGRANO 1870','1'),
('comuna','BELGRANO LUIS MARIA CAMPOS Y DORREGO','13'),
('comuna','BELGRANO R','99'),
('comuna','BELGRANO Y 9 DE JULIO','1'),
('comuna','BELGRANO Y AZOPARDO','1'),
('comuna','BELGRANO Y ENTRE RIOS','1'),
('comuna','BELGRANO Y HUERGO','1'),
('comuna','BELGRANO Y MORENO','1'),
('comuna','BELGRANO Y PIEDRAS','1'),
('comuna','BELGRANO Y RIOJA','3'),
('comuna','BELGRANO Y SAN JOSE','1'),
('comuna','BERNARDO DE IRIGOYEN Y BELGRANO','1'),
('comuna','BERNARDO DE IRIGOYEN Y VENEZUELA','1'),
('comuna','BERON DE ASTRADA 6351','8'),
('comuna','BERUTI Y AGUERO','2'),
('comuna','BILLIBGURST Y STA FE','2'),
('comuna','BILLINGURST Y AV SANTA FE','2'),
('comuna','BLANCO ENCALADA Y VUELTA DE OBLIGADO','13'),
('comuna','BME MITRE Y PARANA','1'),
('comuna','BME MITRE Y SAN MARTIN','1'),
('comuna','BOEDO','5'),
('comuna','BOEDO E INDEPENDENCIA','5'),
('comuna','BOLIVAR 1','1'),
('comuna','BOLIVAR 1457','1'),
('comuna','BOLIVAR Y BELGRANO','1'),
('comuna','BOUCHARD 547','1'),
('comuna','BRANDSEN Y LUSURIAGA','4'),
('comuna','BRANSEN 2070','4'),
('comuna','BRASIL Y LIMA','1'),
('comuna','BRASIL Y TACUARI','1'),
('comuna','BUSTAMANTE ENTRE FRENCH Y PEÑA','2'),
('comuna','BUSTAMANTE ENTRENPEÑA Y FRENCH','2'),
('comuna','C PELLEGRINI Y BELGRANO','1'),
('comuna','CABALLITO','6'),
('comuna','CABALLITO ','6'),
('comuna','CABALLITO  LAMBARE Y BOGADO','6'),
('comuna','CABALLITO Y ALMAGRO','6'),
('comuna','CABEZON Y CAMPANA','11'),
('comuna','CABILDO 2677','13'),
('comuna','CABILDO 2932','13'),
('comuna','CABILDO 400','14'),
('comuna','CABILDO Y DORREGO','14'),
('comuna','CABILDO Y MANZANARES','13'),
('comuna','CABILDO Y SUCRE','13'),
('comuna','CABILLITO','6'),
('comuna','CALLAO Y MARCELO T DE ALVEAR','2'),
('comuna','CALLAO Y MITRE','1'),
('comuna','CALLAO Y PARAGUAY','2'),
('comuna','CALLAO Y RIVADAVIA','3'),
('comuna','CALLAO Y RODRIGUEZ PEÑA','99'),
('comuna','CALLE ALBARIÑO','99'),
('comuna','CALLE ENTRE RIOS','99'),
('comuna','CALLE OLAZABAL EN BELGRANO','13'),
('comuna','CALLE PELLEGRINI','99'),
('comuna','CALLE PERON','99'),
('comuna','CALLE URUGUAY','99'),
('comuna','CALLE VIAMONTE','99'),
('comuna','CAMPILLO Y COMBATIENTE DE MALVINAS','15'),
('comuna','CAÑITAS','14'),
('comuna','CARABOBO Y EVA PERON','7'),
('comuna','CARLOS CALVO','99'),
('comuna','CARLOS CALVO 1500','1'),
('comuna','CARLOS CALVO 1655','1'),
('comuna','CARLOS GARDEL Y AV CORRIENTES','3'),
('comuna','CARLOS PELLEGRINI Y BARTOLOME MITRE','1'),
('comuna','CARLOS PELLEGRINI Y DIAGONAL NORTE','1'),
('comuna','CARLOS PELLEGRINI Y LAVALLE','1'),
('comuna','CARRASCO Y JUAN B JUSTO','7'),
('comuna','CASEROS 3OOO','4'),
('comuna','CASEROS Y BOEDO','4'),
('comuna','CASTAÑARES Y RIVADAVIA','7'),
('comuna','CASTRO BARROS Y RIVADAVIA','5'),
('comuna','CATEDRAL','1'),
('comuna','CENTENERA Y PERITO MORENO','4'),
('comuna','CENTENERA Y SALAS','7'),
('comuna','CENTRO','1'),
('comuna','CENTRO LAVALLE','1'),
('comuna','CERRITO 700','1'),
('comuna','CERRITO Y SARMIENTO','1'),
('comuna','CERRITO Y TUCUMAN','1'),
('comuna','CHACABUCO Y MORENO','1'),
('comuna','CHACARITA','15'),
('comuna','CHARCAS Y AGŪERO','2'),
('comuna','CHILE 1400','1'),
('comuna','CHILE Y COMBATE DE LOS POZOS','3'),
('comuna','CHILE Y DEFENSA','1'),
('comuna','CHIVILCOY Y SIMBRON','11'),
('comuna','CIUDAD','99'),
('comuna','CIUDAD UNIVERSITARIA','13'),
('comuna','COBO','7'),
('comuna','COCHABAMBA AL 565','1'),
('comuna','COCHABAMBA Y LA RIOJA','1'),
('comuna','COGLAND','99'),
('comuna','COHOGLAN','99'),
('comuna','COLEGIALES','13'),
('comuna','COMBATE DE LOS POSOS Y BELGRANO','3'),
('comuna','COMBATE DE LOS POZOS Y CACEROS','4'),
('comuna','COMBATE DE LOS POZOSY ENTRE RIOS','99'),
('comuna','COMBATE Y BRASIL','4'),
('comuna','COMODORO PEDRO SAENZ 250','4'),
('comuna','COMUNA 14','14'),
('comuna','COMUNA 3','3'),
('comuna','COMUNA 6','6'),
('comuna','COMUNA 8','8'),
('comuna','CONESA AL 2200 BELGRANO','13'),
('comuna','CONESA Y MAURE','13'),
('comuna','CONGRESO','3'),
('comuna','CONGRESO Y TRONADOR','12'),
('comuna','CONSTITUCION','1'),
('comuna','CONSTITUYENTES Y GENERAL PAZ','12'),
('comuna','CONSTITUYENTES Y GRAL PAZ','12'),
('comuna','CORDABA Y CERRITO','1'),
('comuna','CORDOBA 720','1'),
('comuna','CORDOBA 900','1'),
('comuna','CORDOBA AL 800','1'),
('comuna','CORDOBA Y 9 DE JULIO','1'),
('comuna','CORDOBA Y BOUCHARD','1'),
('comuna','CORDOBA Y CARLOS PELEGRINI','1'),
('comuna','CORDOBA Y CERRITO','1'),
('comuna','CORDOBA Y CONCEPCION ARENAL','15'),
('comuna','CORDOBA Y ESMERALDA','1'),
('comuna','CORDOBA Y LIBERTAD','1'),
('comuna','CORDOBA Y MADERO','1'),
('comuna','CORDOBA Y MARIO BRAVO','2'),
('comuna','CORDOBA Y PELLEGRINI','1'),
('comuna','CORDOBA Y TALCAHUANO','1'),
('comuna','CORDOBA Y VIAMONTE','99'),
('comuna','CORDOBAY SUIPACHA','1'),
('comuna','CORRIENTES 2038','3'),
('comuna','CORRIENTES 400','1'),
('comuna','CORRIENTES 500','1'),
('comuna','CORRIENTES 640','1'),
('comuna','CORRIENTES Y 25 DE MAYO','1'),
('comuna','CORRIENTES Y 25DE MAYO','1'),
('comuna','CORRIENTES Y ANCHORENA','3'),
('comuna','CORRIENTES Y CALLAO','1'),
('comuna','CORRIENTES Y CERRITO','1'),
('comuna','CORRIENTES Y ESMERALDA','1'),
('comuna','CORRIENTES Y GASCON','5'),
('comuna','CORRIENTES Y JUAN B JUSTO','15'),
('comuna','CORRIENTES Y MONTEVIDEO','1'),
('comuna','CORRIENTES Y PASO','3'),
('comuna','CORRIENTES Y PASTEUR','3'),
('comuna','CORRIENTES Y SAN MARTIN','1'),
('comuna','CORRIENTES Y TALCAHUANO','1'),
('comuna','CORRIENTES1300','1'),
('comuna','COSTA SALGUERO','1'),
('comuna','COSTANERA SUR','1'),
('comuna','COUMNA 2','2'),
('comuna','CPELLEGRINI Y CORDOBA','1'),
('comuna','CREVIÑO 3356 HOSPITAL FERNANDEZ','14'),
('comuna','CUBA AL 1500','99'),
('comuna','CUCHA CUCHA Y SAN MARTIN','15'),
('comuna','CUENCA AL 400','10'),
('comuna','CULLEN Y BAUNES','12'),
('comuna','DARSENA F','1'),
('comuna','DARWIN Y LOYOLA','15'),
('comuna','DEAN FUNES 2198','4'),
('comuna','DEFENSA E INDEPENDENCIA','1'),
('comuna','DEFENSA Y BELGRANO','1'),
('comuna','DEFENSA Y PASAJE GIUFFRA','1'),
('comuna','DEL LIBERTADOR 238','1'),
('comuna','DELLEPIANE','99'),
('comuna','DELLEPIANE Y RAWSON','99'),
('comuna','DERQUI Y AVENIDA DEL TRABAJO','99'),
('comuna','DEVOTO','11'),
('comuna','DIAGENTRE FLORIDA Y ESMERALDA','1'),
('comuna','DIAGONAL NORTE 200','1'),
('comuna','DIAGONAL NORTE 777','1'),
('comuna','DIAGONAL NORTE 800','1'),
('comuna','DIAGONAL NORTE Y AVENIDA DE MAYO','1'),
('comuna','DIAGONAL NORTE Y ESMERALDA','1'),
('comuna','DIAGONAL NORTE Y MAIPU','1'),
('comuna','DIAGONAL SUR','1'),
('comuna','DIAGONAL SUR ENTRE ALSINA Y BOLIVAR','1'),
('comuna','DIAGONAL SUR Y 9 DE JULIO','1'),
('comuna','DIGONAL NORTE Y PERON','1'),
('comuna','DIRECTORIO Y LACARRA','9'),
('comuna','DIRECTORIO Y TANDIL','99'),
('comuna','DISTINTOS BARRIOS','99'),
('comuna','DISTINTOS CONSULTORIOS','99'),
('comuna','DIVERSOS BARRIOS','99'),
('comuna','DORREGO Y FIGUEROA ALCORTA','14'),
('comuna','ECHEVERRIA Y MELO','99'),
('comuna','ECUADOR Y BAROLOME MITRE','3'),
('comuna','EMILIO CASTRO Y GENERAL PAZ','9'),
('comuna','EMILIO LAMARCA Y GUALEGUAYCHU','99'),
('comuna','EMILIO LAMARCA Y NOGOYA','11'),
('comuna','EN AV ENTRE RIOS Y MORENO','1'),
('comuna','EN LA CALLE LAVALLE A METROS DE TRIBUNALES','1'),
('comuna','EN LA CALLE MOLDES','13'),
('comuna','EN LA EXESMA','13'),
('comuna','ENTRE RIOS 144','1'),
('comuna','ENTRE RIOS Y BELGRANO','3'),
('comuna','ENTRE RIOS Y GARAY','1'),
('comuna','ENTRE RIOS Y MEXICO','3'),
('comuna','ESMERALDA 1319','1'),
('comuna','ESMERALDA Y CORRIENTES','1'),
('comuna','ESMERALDA Y CORRIRNETES','1'),
('comuna','ESMERALDA Y DIAGONAL NORTE','1'),
('comuna','ESMERALDA Y JUNCAL','1'),
('comuna','ESMERALDA Y PARAGUAY','1'),
('comuna','ESMERALDA Y VIAMONTE','1'),
('comuna','ESTADOS UNIDOS Y TURQUIA','99'),
('comuna','ESTADPS UNIDOS 1228','1'),
('comuna','EVA PERON Y ZINNI','1'),
('comuna','FACULTAD DE MEDICINA','3'),
('comuna','FIGUROA ALCORTA Y PUYRREDON FACULTAD DE DERECHO','2'),
('comuna','FITZ ROY Y GUATEMALA','14'),
('comuna','FLORES','7'),
('comuna','FLORES AV VARELA','7'),
('comuna','FLORESTA','10'),
('comuna','FLORIDA','1'),
('comuna','FORES','7'),
('comuna','FOREST 800','15'),
('comuna','FRAGA 1500','15'),
('comuna','GALERIAS PACIFICO','1'),
('comuna','GALLARDO 100','9'),
('comuna','GAONA 3500','7'),
('comuna','GAONA Y SEGUROLA','10'),
('comuna','GARAY Y CATAMARCA','3'),
('comuna','GARAY Y PASEO COLON','1'),
('comuna','GARCIA DEL RIO 3119','12'),
('comuna','GASCON Y CORRIENTES','5'),
('comuna','GASCON Y PERON','5'),
('comuna','GAVILAN Y LUIS VIALE','11'),
('comuna','GODOY CRUZ Y GUATEMALA','14'),
('comuna','GORRITI 5963','14'),
('comuna','GRAL PAZ Y AV EMILIO CASTRO','9'),
('comuna','GRAL PAZ Y AVENIDA ROCA','8'),
('comuna','GUAMI Y CHILAVERT','8'),
('comuna','GUEMES Y SANCHEZ DE BUSTAMENTE','2'),
('comuna','GUEVARA 525','15'),
('comuna','GUEVARA Y ELCANO','15'),
('comuna','HIDALGO 775','6'),
('comuna','HIPOLITO YRIGOYEN','99'),
('comuna','HIPOLITO YRIGOYEN 2263','3'),
('comuna','HIPOLITO YRIGOYEN AL 2000','3'),
('comuna','HIPOLITO YRIGOYEN Y QUINTINO BOCAPYUBA','5'),
('comuna','HONDURAS Y BULNES','14'),
('comuna','HONDURAS Y GASCON','14'),
('comuna','HOSPITAL SANTA LUCIA','3'),
('comuna','HUBAC Y LEGUIZAMON','8'),
('comuna','HUERGO Y GARAY','1'),
('comuna','HUMBOLDT Y PARAGUAY','14'),
('comuna','INDEPENCIA AL 3000','3'),
('comuna','INDEPENDENCIA 100','1'),
('comuna','INDEPENDENCIA 3000','1'),
('comuna','INDEPENDENCIA 3277','3'),
('comuna','INDEPENDENCIA Y CASTRO BARROS','5'),
('comuna','INDEPENDENCIA Y CHACABUCO','1'),
('comuna','IRIARTE Y LUNA','4'),
('comuna','IRIGOYEN Y SANTIAGO DEL ESTERO','99'),
('comuna','J A ROCA DIAGONAL SUR','1'),
('comuna','JEAN JOURE Y MANSILLA','2'),
('comuna','JORGE NEWBERY Y CORDOBA','13'),
('comuna','JOSE MARIA MORENO Y COBO','7'),
('comuna','JPVARELA 1301','7'),
('comuna','JUAN B JUSTO ENFRENTE DE JUMBO','99'),
('comuna','JUAN B JUSTO Y ARTIGAS','15'),
('comuna','JUAN B JUSTO Y CUCHA CUCHA','15'),
('comuna','JUJUY Y 15 DE NOVIEMBRE','4'),
('comuna','JUJUY Y HPRIMO','3'),
('comuna','JULIO ROCA','99'),
('comuna','JULIO ROCA AL 700','1'),
('comuna','JULIO ROCA Y BOLIVAR','1'),
('comuna','JUNCAL 3002','14'),
('comuna','JUNCAL Y BILLINGHURST','2'),
('comuna','JUNIN Y LAS HERAS','2'),
('comuna','JUNIN Y LAVALLE','3'),
('comuna','JUNIN Y TUCUMAN','3'),
('comuna','JURAMENTO 4367','12'),
('comuna','JURAMENTO Y CABILDO','13'),
('comuna','JURAMENTO Y MANSILLA','99'),
('comuna','JURAMENTO Y TRES DE FEBRERO','13'),
('comuna','LA BOCA','4'),
('comuna','LA PATERNAL','15'),
('comuna','LAMBARE 948','5'),
('comuna','LARRALDE Y BALBIN','12'),
('comuna','LARREA Y VIAMONTE','3'),
('comuna','LAS CAÑITAS','14'),
('comuna','LAS HERAS Y AUSTRIA','2'),
('comuna','LAS HERAS Y RODRIGUEZ PEÑA','2'),
('comuna','LAVALLE','99'),
('comuna','LAVALLE 1268','1'),
('comuna','LAVALLE 1686','1'),
('comuna','LAVALLE 730','1'),
('comuna','LAVALLE Y 25 DE MAYO','1'),
('comuna','LAVALLE Y 9 DE JULIO','1'),
('comuna','LAVALLE Y CALLAO','1'),
('comuna','LAVALLE Y FLORIDA','1'),
('comuna','LAVALLE Y MONTEVIDEO','1'),
('comuna','LAVALLE Y SAN MARTIN','1'),
('comuna','LAVALLE Y TALCAHUANO','1'),
('comuna','LAVALLE169','1'),
('comuna','LAVALLOL Y BAZURCO','11'),
('comuna','LEANDRO ALEM 1067','1'),
('comuna','LEANDRO ALEM 928','1'),
('comuna','LEGUIZAMON Y SANTANDER','8'),
('comuna','LERMA Y ESTADO DE ISRAEL','15'),
('comuna','LI IERS','9'),
('comuna','LIBERTAD 400','1'),
('comuna','LIBERTAD Y CORRIENTES','1'),
('comuna','LIBERTAD Y LAVALLE','1'),
('comuna','LIBERTADOR 1500','2'),
('comuna','LIBERTADOR 6350','13'),
('comuna','LIBERTADOR Y PELLEGRINI','1'),
('comuna','LIMA 1261','1'),
('comuna','LINIERS','9'),
('comuna','LISANDRO DE LA TORRE Y LA FERRERE','99'),
('comuna','LISANDRO DE LATORRE 2406','9'),
('comuna','LLAVALLE 400','1'),
('comuna','LLAVALLOL 3000','11'),
('comuna','LOMA ALEGRE','4'),
('comuna','LOPE DE VEGA Y LISTA','10'),
('comuna','LOPE DE VEGA Y SASTRE','11'),
('comuna','LORIA Y RIVADAVIA','5'),
('comuna','LOYOLA Y GURRUCHAGA','15'),
('comuna','LUGANO','8'),
('comuna','LUGONES Y GARCIA DEL RIO','12'),
('comuna','LUIS MARIA CAMPOS 480','14'),
('comuna','LUIS MARIA CAMPOS 650','14'),
('comuna','LUIS MARIA CAMPOS Y AREVALO','14'),
('comuna','LUIS MARIA CAMPOS Y CHENAUT','14'),
('comuna','MADERO Y CORRIENTES','1'),
('comuna','MADERO Y PERON','1'),
('comuna','MAHATMA GANDHI Y OLAYA','15'),
('comuna','MAIPU 600','1'),
('comuna','MAIPU Y DIAGONAL NORTE','1'),
('comuna','MAIPU Y SARMIENTO','1'),
('comuna','MAIPU Y TUCUMAN','1'),
('comuna','MANCILLA Y GALLO','14'),
('comuna','MANUEL SOLA Y SANABRIA','11'),
('comuna','MANZANA14 CASA 135','99'),
('comuna','MARCELO T DE ALVEAR 1840','2'),
('comuna','MARCELO T DE ALVEAR Y CALLAO','2'),
('comuna','MARCELO T DE ALVEAR Y LARREA','2'),
('comuna','MARCELO T DE ALVEAR Y PELLEGRINI','1'),
('comuna','MARIO BRAVO Y CABRERA','14'),
('comuna','MARIO BRAVO Y HUMAHUACA','5'),
('comuna','MATADEROS','9'),
('comuna','MATIENZO Y BAEZ','14'),
('comuna','MEDRANO 951','5'),
('comuna','MEXICO Y AZOPARDO','1'),
('comuna','MEXICO Y QUINTINO BOCAYUVA','5'),
('comuna','MICORCENTRO','1'),
('comuna','MICRO CENTRO','1'),
('comuna','MISIONES Y RIVADAVIA','1'),
('comuna','MITRE 2766','3'),
('comuna','MITRE 648','1'),
('comuna','MITRE B Y 25 DE MAYO','1'),
('comuna','MITRE Y BILLINGHURST','5'),
('comuna','MITRE Y FLORIDA','1'),
('comuna','MITRE Y SUIPACHA','1'),
('comuna','MONROE 3248','13'),
('comuna','MONSERRAT ','1'),
('comuna','MONTAÑESES Y JURAMENTO','13'),
('comuna','MONTAÑESES Y MENDOZA','13'),
('comuna','MONTES DE OCA 40','4'),
('comuna','MONTES DE OCA 600','4'),
('comuna','MONTEVIDEO Y VIAMONTE','1'),
('comuna','MONTSERRAT','1'),
('comuna','MORENO 1300','4'),
('comuna','MORENO 1800','7'),
('comuna','MORENO 2366','3'),
('comuna','MORENO 300','4'),
('comuna','MORENO Y CARLOS PELLEGRINI','1'),
('comuna','MORENO Y DEFENSA','1'),
('comuna','MORENO Y LA RIOJA','3'),
('comuna','MORENO Y PERU ','1'),
('comuna','MORENO Y ROQUE SAENZ PEÑA','1'),
('comuna','MORENO Y SALTA','1'),
('comuna','MT ALVEAR','99'),
('comuna','MT ALVEAR Y AGUERO','99'),
('comuna','MT ALVEAR Y AZCUENAGA','2'),
('comuna','MT DE ALVEAR Y RECONQUISTA','1'),
('comuna','NAON Y PAROICIENE','12'),
('comuna','NAON Y PAROISSIEN','12'),
('comuna','NOGOYA Y HELGUERA','11'),
('comuna','NUEVA YORK Y BAHIA BLANCA','11'),
('comuna','NUEVA YORK Y CHIVILCOY','11'),
('comuna','NUEVA YORK Y DESAGUADERO','11'),
('comuna','NUÑEZ','13'),
('comuna','OLLEROS 3570','15'),
('comuna','ONCE','3'),
('comuna','PALERMO','14'),
('comuna','PALERMO ','14'),
('comuna','PALERMO SOHO','14'),
('comuna','PAMPA Y ALCORTA','14'),
('comuna','PARAGUAY 2900','14'),
('comuna','PARAGUAY 645','1'),
('comuna','PARAGUAY Y 9 DE JULIO','1'),
('comuna','PARAGUAY Y ESMERALDA','1'),
('comuna','PARAGUAY Y LARREA','1'),
('comuna','PARAGUAY Y MONTEVIDEO','2'),
('comuna','PARAGUAY Y NUEVE DE JULIO','1'),
('comuna','PARAGUAY Y RIOBAMBA','2'),
('comuna','PARANA 375','1'),
('comuna','PARQUE AVELLANEDA','9'),
('comuna','PARQUE NORTE','13'),
('comuna','PARQUE PATRICIOS','4'),
('comuna','PARQUE SAAVEDRA','12'),
('comuna','PARRAL Y NEUQUEN','6'),
('comuna','PASAJE LA PORTEÑA Y AV RIVADAVIA','7'),
('comuna','PASEO ALCORTA','13'),
('comuna','PASEO COLON 1333','1'),
('comuna','PASEO COLON 250','1'),
('comuna','PASEO COLON 255','1'),
('comuna','PASEO COLON 321','1'),
('comuna','PASEO COLON 600','1'),
('comuna','PASEO COLON 900','1'),
('comuna','PASEO COLON Y AUTOPISTA 25 DE MAYO','1'),
('comuna','PASEO COLON Y BELGRANO','1'),
('comuna','PASEO COLON Y MORENO','1'),
('comuna','PASEO COLON Y VENEZUELA','1'),
('comuna','PASO AL 400','3'),
('comuna','PASO Y VIAMONTE','3'),
('comuna','PATERNAL','15'),
('comuna','PATERNAL ','15'),
('comuna','PATRICIAS ARGENTINAS Y FRANKLIN','6'),
('comuna','PATRICIOS REGIMIENTO','4'),
('comuna','PAVON Y ENTRE RIOS','3'),
('comuna','PEDRAZA Y COLODRERO','12'),
('comuna','PEDRO VARELA Y LOPE DE VEGA','10'),
('comuna','PELLEGRINI','1'),
('comuna','PELLEGRINI Y CORDOBA','1'),
('comuna','PELLEGRINI Y MITRE','1'),
('comuna','PELLEGRINI Y PARAGUAY','1'),
('comuna','PEPIRI 400','4'),
('comuna','PERGAMINO Y AVDEL TRABAJO','3'),
('comuna','PERGARMINO Y ALBERDI','10'),
('comuna','PERON 1300','1'),
('comuna','PERON 1500','1'),
('comuna','PERON 2755','3'),
('comuna','PERON Y AZCUENAGA','3'),
('comuna','PERON Y CALLAO','1'),
('comuna','PERON Y CASTELLI','3'),
('comuna','PERON Y JUNIN','3'),
('comuna','PERON Y PASTEUR','3'),
('comuna','PERON Y PELLEGRINI','1'),
('comuna','PERU 143','1'),
('comuna','PERU AL 200','1'),
('comuna','PERU E HIPOLITO IRIGOYEN','1'),
('comuna','PERU E IRIGOYEN','1'),
('comuna','PERU E YRIGOYEN','1'),
('comuna','PERU Y AV RIVADAVIA','1'),
('comuna','PIEDRAS Y VENEZUELA','1'),
('comuna','PILAR 950','9'),
('comuna','PLAZA DE MAYO','1'),
('comuna','POMPEYA','4'),
('comuna','POSADAS AL 900','2'),
('comuna','PRESIDENTE LUIS SAENZ PEÑA 491','1'),
('comuna','PUAN Y PEDRO GOYENA','6'),
('comuna','PUERTO MADERO','1'),
('comuna','PUEYRREDON 700','3'),
('comuna','PUEYRREDON Y CORRIENTES','3'),
('comuna','PUEYRREDON Y RIVADAVIA','3'),
('comuna','PUEYRREDON Y SARMIENTO','3'),
('comuna','PUNTA ARENAS 1600','15'),
('comuna','RAFAEL OBLIGADO COMPLEJO COSTA SALGUERO','14'),
('comuna','RAMSAY  2100','13'),
('comuna','RAMSAY Y ECHEVERRIA','13'),
('comuna','RAMSEY Y JURAMENTO','13'),
('comuna','RECOLETA','2'),
('comuna','RECONQUISTA 1100','1'),
('comuna','RECONQUISTA 656','1'),
('comuna','RECONQUISTA Y PERON','1'),
('comuna','RECONQUISTA Y VIAMONTE','1'),
('comuna','REGIMIENTO PATRICIOS 230','4'),
('comuna','RETIRO ','1'),
('comuna','RICARDO GUTIERREZ Y CUENCA','11'),
('comuna','RIO DE JANEIRO Y DIAZ VELEZ','6'),
('comuna','RIOBAMBA Y RIVADAVIA','3'),
('comuna','RIVADAVIA 1300','1'),
('comuna','RIVADAVIA 1367','1'),
('comuna','RIVADAVIA 4641','6'),
('comuna','RIVADAVIA QUINTINO BOCAYUVA','5'),
('comuna','RIVADAVIA Y BILLINGURST','5'),
('comuna','RIVADAVIA Y GASCON','5'),
('comuna','RIVADAVIA Y RIOBAMBA','3'),
('comuna','ROCA Y PERU','1'),
('comuna','RODRIGUEZ PEÑA Y GUIDO','2'),
('comuna','RODRIGUEZ PEÑA Y LAVALLE','1'),
('comuna','ROJAS Y RECONQUISTA','1'),
('comuna','ROJAS Y YERBAL','6'),
('comuna','ROQUE SAENZ PEÑA 570','1'),
('comuna','ROQUE SAEZ PEÑA 760','1'),
('comuna','ROSALES Y SENILLOSA','99'),
('comuna','SAAVEDRA','12'),
('comuna','SAENZ PEÑA 1500','1'),
('comuna','SALGUERO Y ALCORTA','14'),
('comuna','SALGUERO Y RIVADAVIA','5'),
('comuna','SALTA E HIPOLITO IRIGOYEN','1'),
('comuna','SAN BLAS 1600','15'),
('comuna','SAN CRISTIBAL','3'),
('comuna','SAN CRISTOBAL','3'),
('comuna','SAN JOSE Y CONSTITUCION','1'),
('comuna','SAN JUAN 2100','3'),
('comuna','SAN JUAN 350','1'),
('comuna','SAN JUAN 727','1'),
('comuna','SAN JUAN Y ALBERTI','3'),
('comuna','SAN JUAN Y JUJUY','3'),
('comuna','SAN JUAN Y PASCO','3'),
('comuna','SAN JUAN Y PICHINCHA','3'),
('comuna','SAN JUAN2021','3'),
('comuna','SAN MARTIN Y CORDOBA','1'),
('comuna','SAN MARTIN Y CORRIENTES','1'),
('comuna','SAN MARTIN Y JUAN B JUSTO','15'),
('comuna','SAN MARTIN Y PARAGUAY','1'),
('comuna','SAN MARTIN Y SAN ALBERTO','11'),
('comuna','SAN MARTIN Y SARMIENTO','15'),
('comuna','SAN MARTIN Y TUCUMAN','1'),
('comuna','SAN NICOLAS','1'),
('comuna','SAN NICOLAS ','1'),
('comuna','SANCHEZ DE BUSTAMANTE Y GUEMES','2'),
('comuna','SANCHEZ DE LORIA Y MORENO','5'),
('comuna','SANTA CATALINA','8'),
('comuna','SANTA FE 2029','2'),
('comuna','SANTA FE 2245','2'),
('comuna','SANTA FE Y ANCHORENA','2'),
('comuna','SANTA FE Y CARLOS PELLEGRINI','1'),
('comuna','SANTA FE Y CERRITO','1'),
('comuna','SANTA FE Y MONTEVIDEO','2'),
('comuna','SANTA FE Y ORO','14'),
('comuna','SANTA FE Y RAVIGNANI','14'),
('comuna','SANTANDER Y LEGUIZAMON','8'),
('comuna','SANTIAGO DEL ESTERO 1300','1'),
('comuna','SANTIAGO DEL ESTERO 941','1'),
('comuna','SANTIAGO DEL ESTERO 977','1'),
('comuna','SANTIAGO DEL ESTERO Y HUMBERTO1','1'),
('comuna','SANTO TOME Y TERRERO','99'),
('comuna','SANTOS DUMONT Y OTERO','15'),
('comuna','SAPIOLA Y CESPEDES','13'),
('comuna','SARAZA Y SENILLOSA','7'),
('comuna','SARMIENTO 1169','1'),
('comuna','SARMIENTO 300','1'),
('comuna','SARMIENTO Y CERRITO','1'),
('comuna','SARMIENTO Y MONTEVIDEO','1'),
('comuna','SASTRE Y HELGUERA','11'),
('comuna','SCALABRINI ORTIZ Y CORRIENTES','15'),
('comuna','SEGUROLA Y ARREGUI','10'),
('comuna','SEGUROLA Y MIRANDA','10'),
('comuna','SOLDADO DE LA FRONTERA 5386','8'),
('comuna','SOLDATI','8'),
('comuna','SOLIS Y COCHABAMBA','1'),
('comuna','SUIPACHA 10','1'),
('comuna','SUIPACHA 200','1'),
('comuna','SUIPACHA Y BARTOLOME MITRE','1'),
('comuna','SUIPACHA Y LAVALLE','1'),
('comuna','SUIPACHA Y RIVADAVIA','1'),
('comuna','SUIPACHA Y SANTA FE','1'),
('comuna','SUIPACHA Y VIAMONTE','1'),
('comuna','TACUARI Y BELGRANO','1'),
('comuna','TAGLE Y LIBERTADOR','14'),
('comuna','TALCAHUANO','1'),
('comuna','TALCAHUANO 490','1'),
('comuna','TALCAHUANO Y ALVEAR','1'),
('comuna','TALCAHUANO Y LAVALLE','1'),
('comuna','TALCAHUANO Y SANTA FE','1'),
('comuna','TALCAHUANO Y VIAMONTE','1'),
('comuna','TAMBORINI 4800','12'),
('comuna','TAMBORINI Y ACHEGA','12'),
('comuna','THAMES Y CORDOBA','14'),
('comuna','TIMOTEO GORDILLO Y DIRECTORIO','9'),
('comuna','TINOGASTA Y AV SAN MARTIN','11'),
('comuna','TRES DE FEBRERO Y CONGRESO','13'),
('comuna','TRIBUNALES','1'),
('comuna','TRIUMBIRATO Y ACHA','15'),
('comuna','TRIUNBIRATO Y ACHA','15'),
('comuna','TRIUNVIRATO 3441','15'),
('comuna','TRIUNVIRATO Y ACHA','15'),
('comuna','TUCUMAN 2035','3'),
('comuna','TUCUMAN 240','1'),
('comuna','TUCUMAN 300','1'),
('comuna','TUCUMAN 800','1'),
('comuna','TUCUMAN Y AZCUENAGA','3'),
('comuna','TUCUMAN Y BULNES','5'),
('comuna','TUCUMAN Y FLORIDA','1'),
('comuna','TUCUMAN Y LAVALLE','99'),
('comuna','TUCUMAN Y PARANA','1'),
('comuna','TUCUMAN Y PUEYRREDON','3'),
('comuna','TUCUMAN Y RECONQUISTA','1'),
('comuna','TUCUMAN Y URUGUAY','1'),
('comuna','ULRICO SCHMIDL Y MOLINA','9'),
('comuna','URIBURU Y MARCELO T DE ALVEAR','2'),
('comuna','URIBURU Y PERON','3'),
('comuna','URIBURU Y SANTA FE','2'),
('comuna','URQUIZA 600','3'),
('comuna','VALENTIN GOMEZ Y AGUERO','3'),
('comuna','VELAZCO 145','15'),
('comuna','VELEZ SARLFIELD','4'),
('comuna','VENEZUELA 1300','1'),
('comuna','VENEZUELA 160','1'),
('comuna','VENEZUELA Y ALBERTI','3'),
('comuna','VENTURA DE LA VEGA 3940','4'),
('comuna','VERON DE ASTRADA 6351','8'),
('comuna','VIAMONTE 1570','1'),
('comuna','VIAMONTE 200','1'),
('comuna','VIAMONTE 500','1'),
('comuna','VIAMONTE Y AZCUENAGA','3'),
('comuna','VIAMONTE Y BOUCHARD','1'),
('comuna','VIAMONTE Y NUEVE DE JULIO','1'),
('comuna','VIAMONTE Y PASO','3'),
('comuna','VIILLA URQUIZA','12'),
('comuna','VILLA','99'),
('comuna','VILLA 11 14','7'),
('comuna','VILLA 15','8'),
('comuna','VILLA 2124','4'),
('comuna','VILLA 3','8'),
('comuna','VILLA 31 ','1'),
('comuna','VILLA CFRESPO','15'),
('comuna','VILLA CRESPO','15'),
('comuna','VILLA DEL PARQUE','11'),
('comuna','VILLA DEVOTO','11'),
('comuna','VILLA GRAL MITRE','12'),
('comuna','VILLA LUGANO BARRIO SAMORE','8'),
('comuna','VILLA ORTUZAR','15'),
('comuna','VILLA PARQUE','11'),
('comuna','VILLA PUYRREDON','12'),
('comuna','VILLA REAL','10'),
('comuna','VILLA URQUIZA','12'),
('comuna','VILLA31','1'),
('comuna','VILLANUEVA ENTRE MAURE Y GOROSTIAGA','14'),
('comuna','VILLANUEVA Y GOROSTIAGA','14'),
('comuna','VILLANUEVA Y MAURE ','14'),
('comuna','VILLLA 11114','7'),
('comuna','WARNES Y MUÑECAS','15'),
('comuna','YATAY 130','5'),
('comuna','YATAY 200','5'),
('comuna','ZAAVEDRA','12'),
('comuna','ZAVALETA Y CRUZ','4'),
('sn15k_esp_txt','ALERGIA','1'),
('sn15k_esp_txt','ALERGIAS','1'),
('sn15k_esp_txt','RINITIS ALERGICA','1'),
('sn15k_esp_txt','FIEBRE DEL HENO','1'),
('sn15k_esp_txt','ARTRITIS','2'),
('sn15k_esp_txt','ARTRITIS DE RODILLA','2'),
('sn15k_esp_txt','ARTRITIS REUMATOIDEA','2'),
('sn15k_esp_txt','ARTROSIS','2'),
('sn15k_esp_txt','ARTROSIS , TIROIDES','2'),
('sn15k_esp_txt','ARTROSIS CERVICAL','2'),
('sn15k_esp_txt','ARTROSIS DE CADERA','2'),
('sn15k_esp_txt','ARTROSIS DE HOMBRO DERECHO','2'),
('sn15k_esp_txt','ARTROSIS DE RODILLA','2'),
('sn15k_esp_txt','ARTROSIS DE RODILLA IZQUIERDA.','2'),
('sn15k_esp_txt','ARTROSIS EN HOMBRO.','2'),
('sn15k_esp_txt','ARTROSIS RODILLA','2'),
('sn15k_esp_txt','ARTROSIS Y ARTRITIS.','2'),
('sn15k_esp_txt','ARTROSIS Y COLESTEROL ALTO','2'),
('sn15k_esp_txt','ARTROSIS Y TIROIDES.','2'),
('sn15k_esp_txt','REUMA','2'),
('sn15k_esp_txt','REUMATISMO','2'),
('sn15k_esp_txt','PRESION ALTA','3'),
('sn15k_esp_txt','HIPERTENSION','3'),
('sn15k_esp_txt','INFARTO DE MIOCARDIO','4'),
('sn15k_esp_txt','INFARTO','4'),
('sn15k_esp_txt','ARITMIA CARDIACA','5'),
('sn15k_esp_txt','ARRITMIA','5'),
('sn15k_esp_txt','ARTERIAS DE PIERNAS TAPADAS','5'),
('sn15k_esp_txt','COLESTEROL','5'),
('sn15k_esp_txt','COLESTEROL ALTO','5'),
('sn15k_esp_txt','ENFERMEDAD DEL CORAZON','5'),
('sn15k_esp_txt','HIPERCOLESTEROLEMIA','5'),
('sn15k_esp_txt','HIPERTENCION ARTERIAL','3'),
('sn15k_esp_txt','HIPERTENSO','3'),
('sn15k_esp_txt','INFLAMACION DE ARTERIAS PERIFERICAS','5'),
('sn15k_esp_txt','ISQUEMIA DE CORAZÓN','5'),
('sn15k_esp_txt','MARCAPASO','5'),
('sn15k_esp_txt','MARCAPASOS','5'),
('sn15k_esp_txt','OBSTRUCCION DE VIAS CORONARIAS','5'),
('sn15k_esp_txt','SOPLO','5'),
('sn15k_esp_txt','SOPLO CORAZON','5'),
('sn15k_esp_txt','SOPLO EN EL CORAZON','5'),
('sn15k_esp_txt','SOPLO INOCENTE','5'),
('sn15k_esp_txt','SOPLO PULMONAR','5'),
('sn15k_esp_txt','TIENE UNA VÁLVULA EN EL CORAZON QUE SE HACE CONTROLAR TODOS LOS MESES','5'),
('sn15k_esp_txt','BRONQUITIS','6'),
('sn15k_esp_txt','BRONQUITIS CRONICA','6'),
('sn15k_esp_txt','ENFISEMA','6'),
('sn15k_esp_txt','ENFISEMA PULMONAR','6'),
('sn15k_esp_txt','ASMA','7'),
('sn15k_esp_txt','PRINCIPIO DE ASMA','7'),
('sn15k_esp_txt','ALTERACION DE GLUCEMIA','8'),
('sn15k_esp_txt','DIABETES','8'),
('sn15k_esp_txt','DIABETES GESTACIONAL','8'),
('sn15k_esp_txt','DIABETES INSÍPIDA','8'),
('sn15k_esp_txt','DIABETES TIPO DOS','8'),
('sn15k_esp_txt','DIABETIS','8'),
('sn15k_esp_txt','INSULINA DEPENDIENTE','8'),
('sn15k_esp_txt','DIABETES INSULINA DEPENDIENTE','8'),
('sn15k_esp_txt','DIABETES INSULINODEPENDIENTE','8'),
('sn15k_esp_txt','INSULINA RESISTENTE','8'),
('sn15k_esp_txt','INSULINO RESISTENTE','8'),
('sn15k_esp_txt','INSULINODEPENDIENTE','8'),
('sn15k_esp_txt','PREDIABETICA','8'),
('sn15k_esp_txt','PREDIABETES','8'),
('sn15k_esp_txt','PROBLEMA MOVILIDAD POR LA DIABETES.','8'),
('sn15k_esp_txt','PROBLEMAS CON LA GLUCEMIA','8'),
('sn15k_esp_txt','RESISTENCIA A LA INSULINA','8'),
('sn15k_esp_txt','HEPATITIS','9'),
('sn15k_esp_txt','HEPATITIS B','9'),
('sn15k_esp_txt','HEPATITIS C','9'),
('sn15k_esp_txt','HÍGADO GRASO','9'),
('sn15k_esp_txt','PROBLEMAS DE VESICULA','9'),
('sn15k_esp_txt','PROBLEMAS HEPATICOS','9'),
('sn15k_esp_txt','DISPEPCIA','10'),
('sn15k_esp_txt','GASTRICOS','10'),
('sn15k_esp_txt','GASTRITIS','10'),
('sn15k_esp_txt','GASTROENTERITIS','10'),
('sn15k_esp_txt','PROBLEMAS GASTRICOS','10');


insert into encu.diccionario
select diccionario, true as completo, 1 as tlg from encu.diccionario_agregar group by diccionario, completo, tlg;

insert into encu.dictra
select diccionario,origen,destino::integer, 1 from encu.diccionario_agregar

INSERT INTO encu.dicvar values
('sn15k_esp_txt','sn15k_esp',1),
('partido','lugar_esp1',1),
('partido','m1_esp2',1),	    
('partido','m4_esp1',1),	    
('provincia','m1_esp3',1),	    
('provincia','m4_esp2',1),	    
('pais','lugar_esp3',1),	
('pais','m1_esp4',1),	    
('pais','m4_esp3',1);

drop table encu.diccionario_agregar;