CREATE TABLE encu.diccionario_agregar (
  diccionario text,
  origen text,
  destino text
  )
  WITH (
  OIDS=FALSE
);
ALTER TABLE encu.diccionario_agregar
  OWNER TO tedede_php;

insert into encu.diccionario_agregar values
('nombre', 'ABELINA','2'),
('nombre', 'ABELINO','1'),
('nombre', 'ABRHAM','1'),
('nombre', 'ADALBERTO RAUL','1'),
('nombre', 'ADOLFO LUIS','1'),
('nombre', 'AEGENTINA','2'),
('nombre', 'AIDA ADRIANA','2'),
('nombre', 'AIDE','2'),
('nombre', 'AIMARA','2'),
('nombre', 'ALBERT','1'),
('nombre', 'ALDANA FLORENCIA','2'),
('nombre', 'ALDO ANGEL','1'),
('nombre', 'ALDO ANTONIO','1'),
('nombre', 'ALEJANDA','2'),
('nombre', 'ALEJANDO','1'),
('nombre', 'ALELI','2'),
('nombre', 'ALEXA','2'),
('nombre', 'ALINA','2'),
('nombre', 'ALISON','2'),
('nombre', 'ALMA','2'),
('nombre', 'ALTA GRACIA','2'),
('nombre', 'AMELI','2'),
('nombre', 'ANA BELEN','2'),
('nombre', 'ANA INES','2'),
('nombre', 'ANA LAURA','2'),
('nombre', 'ANA MARIA','2'),
('nombre', 'ANA MARIA ELISA','2'),
('nombre', 'ANA ROSA','2'),
('nombre', 'ANABELLA','2'),
('nombre', 'ANALIA VERONICA','2'),
('nombre', 'ANAMARIA','2'),
('nombre', 'ANASTACIA','2'),
('nombre', 'ANDRES','1'),
('nombre', 'ANDRES ENRIQUE','1'),
('nombre', 'ANGEL AGUSTIN','1'),
('nombre', 'ANGELIE','2'),
('nombre', 'ANTOINE','1'),
('nombre', 'ANTONELA','2'),
('nombre', 'ANTONI','1'),
('nombre', 'ANTONY','1'),
('nombre', 'ARACELI','2'),
('nombre', 'AREVALO','1'),
('nombre', 'ARGENTINA','2'),
('nombre', 'ARIADNA','2'),
('nombre', 'ARIANA','2'),
('nombre', 'ARMADO','1'),
('nombre', 'ARNOLD','1'),
('nombre', 'ASTRID','2'),
('nombre', 'ASUNCION','2'),
('nombre', 'AYDEE','2'),
('nombre', 'AYLIN','2'),
('nombre', 'AZUZENA','2'),
('nombre', 'BEATRIZ CORDEÑOZA','2'),
('nombre', 'BELLA ROSA','2'),
('nombre', 'BENARDO','1'),
('nombre', 'BENISIO','1'),
('nombre', 'BENJAIN','1'),
('nombre', 'BENJAMINA','2'),
('nombre', 'BETI','2'),
('nombre', 'BETTY','2'),
('nombre', 'BETY','2'),
('nombre', 'BIANCA FLORENCIA','2'),
('nombre', 'BIBIANA','2'),
('nombre', 'BLADIMIR','1'),
('nombre', 'BONIFACIA','2'),
('nombre', 'BRAIN','1'),
('nombre', 'BRANDOM','1'),
('nombre', 'BRIGIT','2'),
('nombre', 'BRISAS','2'),
('nombre', 'BRIZA','2'),
('nombre', 'BRUCE','1'),
('nombre', 'BRUS','1'),
('nombre', 'BRYAN','1'),
('nombre', 'BRYITH','2'),
('nombre', 'CARLOS ALBERTO','1'),
('nombre', 'CARLOS ANDRES','1'),
('nombre', 'CARLOS JORGE','1'),
('nombre', 'CARLOS JOSUE','1'),
('nombre', 'CARLOS MANUEL','1'),
('nombre', 'CARLOS NAHUEL','1'),
('nombre', 'CAROLINE','2'),
('nombre', 'CASILDA','2'),
('nombre', 'CATALINO','1'),
('nombre', 'CATERIN','2'),
('nombre', 'CATERINE','2'),
('nombre', 'CATINA','2'),
('nombre', 'CATY','2'),
('nombre', 'CEFERINA','2'),
('nombre', 'CERAPIO','1'),
('nombre', 'CERIMEDO','1'),
('nombre', 'CESAR ANTONIO','1'),
('nombre', 'CHILA','2'),
('nombre', 'CHINITA','2'),
('nombre', 'CHINO','1'),
('nombre', 'CHRISTOFER','1'),
('nombre', 'CINTIA','2'),
('nombre', 'CIRIACA','2'),
('nombre', 'CIRILA','2'),
('nombre', 'CLAUDIA ESTHER','2'),
('nombre', 'CLAUDIA MERCEDES','2'),
('nombre', 'CLEIDY','2'),
('nombre', 'CLEMENCIA','2'),
('nombre', 'CLEMENTINO','1'),
('nombre', 'CLOE AMELIA','2'),
('nombre', 'CONDORI','2'),
('nombre', 'COSUELO','2'),
('nombre', 'CRISPINIANO','1'),
('nombre', 'CRISTOFER','1'),
('nombre', 'CYNTHIA','2'),
('nombre', 'CYNTIA','2'),
('nombre', 'DAFNE VALENTINA','2'),
('nombre', 'DAISY','2'),
('nombre', 'DALY','2'),
('nombre', 'DARIA','2'),
('nombre', 'DARIL','1'),
('nombre', 'DAYSI','2'),
('nombre', 'DEBORAH','2'),
('nombre', 'DEISI','2'),
('nombre', 'DEISY','2'),
('nombre', 'DELCIA','2'),
('nombre', 'DELMESIO','1'),
('nombre', 'DEMIR','1'),
('nombre', 'DENISSE','2'),
('nombre', 'DERLIS','1'),
('nombre', 'DESIDERIA','2'),
('nombre', 'DIEGO ALEJANDRO','1'),
('nombre', 'DIGNA','2'),
('nombre', 'DILAN','1'),
('nombre', 'DOLERES','2'),
('nombre', 'DORA ALICIA','2'),
('nombre', 'DOROTHEA','2'),
('nombre', 'DULCELINA','2'),
('nombre', 'DUQUE','1'),
('nombre', 'EDISON','1'),
('nombre', 'EDSON','1'),
('nombre', 'EDUARDO J','1'),
('nombre', 'EDWIN','1'),
('nombre', 'ELEN','2'),
('nombre', 'ELENE','2'),
('nombre', 'ELIANE','2'),
('nombre', 'ELICEO','1'),
('nombre', 'ELIGIO','1'),
('nombre', 'ELISABET','2'),
('nombre', 'ELIZABET','2'),
('nombre', 'ELIZARDO','1'),
('nombre', 'ELLEN','2'),
('nombre', 'ELMIRA','2'),
('nombre', 'ELODIA','2'),
('nombre', 'ELONDINA','2'),
('nombre', 'ELONDINA CONCEPCION','2'),
('nombre', 'ELSA SUSANA','2'),
('nombre', 'ELVA','2'),
('nombre', 'ELVER','1'),
('nombre', 'ELVIN','1'),
('nombre', 'EMILCE','2'),
('nombre', 'EMILIAN','1'),
('nombre', 'EMYLI','2'),
('nombre', 'ENMUNDO JOSE','1'),
('nombre', 'ENRRIQUE','1'),
('nombre', 'ERCILLA','2'),
('nombre', 'ERIBERTO','1'),
('nombre', 'ERICA','2'),
('nombre', 'ERICO','1'),
('nombre', 'ERLIA','2'),
('nombre', 'ERMIL','1'),
('nombre', 'ERNESTINA JUDITH','2'),
('nombre', 'EROTIDA','2'),
('nombre', 'ESEQUIEL','1'),
('nombre', 'ESMILDA','2'),
('nombre', 'ESPHANIE','2'),
('nombre', 'ESTANISLAO PEDRO','1'),
('nombre', 'ESTEBAN MESSINA','1'),
('nombre', 'ESTEBAN YANG SONG','1'),
('nombre', 'ESTEFANI','2'),
('nombre', 'ESTELA MARIS','2'),
('nombre', 'ESTELLA','2'),
('nombre', 'ESTELLA MARIS','2'),
('nombre', 'ESTER','2'),
('nombre', 'ESTERH','2'),
('nombre', 'ESTRER','2'),
('nombre', 'ETELVINA (ETHEL)','2'),
('nombre', 'ETTHEL','2'),
('nombre', 'EUDES GAMARRA','1'),
('nombre', 'EUDOXIA','2'),
('nombre', 'EUFRACIO','1'),
('nombre', 'EUFRASIO','1'),
('nombre', 'EVARISTA','2'),
('nombre', 'EVELIN','2'),
('nombre', 'EVELIYN','2'),
('nombre', 'EVER','1'),
('nombre', 'EZEQUILEL','1'),
('nombre', 'FACU','1'),
('nombre', 'FACUNDO JOSE','1'),
('nombre', 'FANCISCO','1'),
('nombre', 'FANI','2'),
('nombre', 'FANNI','2'),
('nombre', 'FANNY ESTELA','2'),
('nombre', 'FEDRICO','1'),
('nombre', 'FELICIANA','2'),
('nombre', 'FERMINA','2'),
('nombre', 'FERNAANDO','1'),
('nombre', 'FERNANDO J','1'),
('nombre', 'FERNANDO RICARDO','1'),
('nombre', 'FIAMA','2'),
('nombre', 'FIDELINA','2'),
('nombre', 'FILEMON','1'),
('nombre', 'FIORELA','2'),
('nombre', 'FLOPY','2'),
('nombre', 'FLRENCIA','2'),
('nombre', 'FRANCHESCA','2'),
('nombre', 'FRANCHESCO','1'),
('nombre', 'FRANCYS','2'),
('nombre', 'FRANKLIN','1'),
('nombre', 'FRANSISCO','1'),
('nombre', 'FREDDY','1'),
('nombre', 'FUJIKO','2'),
('nombre', 'FUMIKO','2'),
('nombre', 'GABRIWLA','2'),
('nombre', 'GAGO','1'),
('nombre', 'GAGRIEL','1'),
('nombre', 'GAVINO','1'),
('nombre', 'GEINER','1'),
('nombre', 'GERARDO JHAIR','1'),
('nombre', 'GEREMIAS','1'),
('nombre', 'GESER','1'),
('nombre', 'GIAN FRANCO','1'),
('nombre', 'GIANELA','2'),
('nombre', 'GILLERMO','1'),
('nombre', 'GIMNEA','2'),
('nombre', 'GINETT','2'),
('nombre', 'GIOVANI','1'),
('nombre', 'GISEL','2'),
('nombre', 'GISELE','2'),
('nombre', 'GISELL','2'),
('nombre', 'GISELLA','2'),
('nombre', 'GIULLIANA','2'),
('nombre', 'GIUSEPE','1'),
('nombre', 'GLADIZ','2'),
('nombre', 'GLDYS','2'),
('nombre', 'GREGORIA','2'),
('nombre', 'GROBERT','1'),
('nombre', 'GUATAVO','1'),
('nombre', 'GUILERRMO','1'),
('nombre', 'GUILIANA','2'),
('nombre', 'GUILIANA VICTORIA','2'),
('nombre', 'GUILLE','1'),
('nombre', 'GUMERCINDA','2'),
('nombre', 'GUSTAVO JUNIOR','1'),
('nombre', 'GUSTINA','2'),
('nombre', 'HAIDE','2'),
('nombre', 'HAIDEE','2'),
('nombre', 'HANA','2'),
('nombre', 'HAYDE','2'),
('nombre', 'HEBE MARIA','2'),
('nombre', 'HECTOR A','1'),
('nombre', 'HECTOR JOSE','1'),
('nombre', 'HEDY','2'),
('nombre', 'HEIDY','2'),
('nombre', 'HELEN','2'),
('nombre', 'HENRI','1'),
('nombre', 'HERBERT','1'),
('nombre', 'HERLAN','1'),
('nombre', 'HERNAN RAUL','1'),
('nombre', 'HIGINIA','2'),
('nombre', 'HILARY','2'),
('nombre', 'HILDA LELIA','2'),
('nombre', 'HIPOLITA','2'),
('nombre', 'HORQUIDIA','2'),
('nombre', 'HORTENSIA','2'),
('nombre', 'HOUSTON','1'),
('nombre', 'HUBER','1'),
('nombre', 'HUGO LEANDRO','1'),
('nombre', 'IANA','2'),
('nombre', 'IDANEA','2'),
('nombre', 'IDLE','2'),
('nombre', 'IGINIO','1'),
('nombre', 'IGNAVIO','1'),
('nombre', 'IILIANA','2'),
('nombre', 'ILMA','2'),
('nombre', 'ILSA','2'),
('nombre', 'ILUMINADA','2'),
('nombre', 'INDIA','2'),
('nombre', 'INGVILD','2'),
('nombre', 'INNA','2'),
('nombre', 'INOCENCIA','2'),
('nombre', 'IONI','1'),
('nombre', 'IONIT','2'),
('nombre', 'IRACEMA','2'),
('nombre', 'ISABELA','2'),
('nombre', 'ISABELINA','2'),
('nombre', 'ISIDORA','2'),
('nombre', 'IVANNA','2'),
('nombre', 'IVETE','2'),
('nombre', 'J CORNELIO','1'),
('nombre', 'J CARLOS','1'),
('nombre', 'J CESAR','1'),
('nombre', 'JDAVID','1'),
('nombre', 'JACKELIN','2'),
('nombre', 'JACKELINE','2'),
('nombre', 'JACSON','1'),
('nombre', 'JADIR','1'),
('nombre', 'JAKELINE','2'),
('nombre', 'JAN CARLA','2'),
('nombre', 'JANET','2'),
('nombre', 'JANINA','2'),
('nombre', 'JANINE','2'),
('nombre', 'JANIRA','2'),
('nombre', 'JAOQUIN','1'),
('nombre', 'JAQUELIN','2'),
('nombre', 'JAQUELINE','2'),
('nombre', 'JARNO','1'),
('nombre', 'JARTUNINO','1'),
('nombre', 'JASAON','1'),
('nombre', 'JAVIER MAXIMILIANO','1'),
('nombre', 'JEAN PIERRE','1'),
('nombre', 'JEFA DE HOGAR','2'),
('nombre', 'JEFE','1'),
('nombre', 'JENI','2'),
('nombre', 'JENIFER','2'),
('nombre', 'JENNER','1'),
('nombre', 'JENNY','2'),
('nombre', 'JENOVEVA','2'),
('nombre', 'JERARDO','1'),
('nombre', 'JERONIMA','2'),
('nombre', 'JERRY','1'),
('nombre', 'JESSICA','2'),
('nombre', 'JESUS BARRERA','1'),
('nombre', 'JESUS MARIA','1'),
('nombre', 'JESUSA','2'),
('nombre', 'JHANET','2'),
('nombre', 'JHON','1'),
('nombre', 'JHOSSELLIN','2'),
('nombre', 'JILMAR','1'),
('nombre', 'JIMMY','1'),
('nombre', 'JOACO','1'),
('nombre', 'JOAKIN','2'),
('nombre', 'JOAN MANUEL','1'),
('nombre', 'JOANNA','2'),
('nombre', 'JOAQUIN','1'),
('nombre', 'JOE','1'),
('nombre', 'JOEGE','1'),
('nombre', 'JOHANA','2'),
('nombre', 'JOHN','1'),
('nombre', 'JOHNATAN','1'),
('nombre', 'JOHNNY','1'),
('nombre', 'JOKIN','1'),
('nombre', 'JONHATAN','1'),
('nombre', 'JONI','1'),
('nombre', 'JONNY','1'),
('nombre', 'JONY','1'),
('nombre', 'JORGE ALBERTO','1'),
('nombre', 'JORGE DAVID','1'),
('nombre', 'JORGE IGNACIO','1'),
('nombre', 'JORGE LUIS','1'),
('nombre', 'JORGITO','1'),
('nombre', 'JOSE','1'),
('nombre', 'JOSE ALBERTO','1'),
('nombre', 'JOSE ALEJANDRO','1'),
('nombre', 'JOSE ANTONIO','1'),
('nombre', 'JOSE CARLOS','1'),
('nombre', 'JOSE CRUZ','1'),
('nombre', 'JOSE IGNACIO','1'),
('nombre', 'JOSE LUIS','1'),
('nombre', 'JOSE LUIS 2','1'),
('nombre', 'JOSE MANUEL','1'),
('nombre', 'JOSE MARIA','1'),
('nombre', 'JOSE MARIO','1'),
('nombre', 'JOSE NAHUEL','1'),
('nombre', 'JOSE NICOLAS','1'),
('nombre', 'JOSE OSVASDO','1'),
('nombre', 'JOSELIN','2'),
('nombre', 'JOSELINA','2'),
('nombre', 'JOSELINE','2'),
('nombre', 'JOSEMAR','1'),
('nombre', 'JOSIMAR','2'),
('nombre', 'JOSUA','1'),
('nombre', 'JUAN ALBERTO','1'),
('nombre', 'JUAN ANTONIO','1'),
('nombre', 'JUAN BAUTISTA','1'),
('nombre', 'JUAN CARLOS','1'),
('nombre', 'JUAN CESAR','1'),
('nombre', 'JUAN CRUZ','1'),
('nombre', 'JUAN DOMINGO','1'),
('nombre', 'JUAN EMANUEL','1'),
('nombre', 'JUAN ESTEBAN','1'),
('nombre', 'JUAN FELIPE','1'),
('nombre', 'JUAN FRANCISCI','1'),
('nombre', 'JUAN IGNACIO','1'),
('nombre', 'JUAN JOSE','1'),
('nombre', 'JUAN LEONARDO','1'),
('nombre', 'JUAN LUIS','1'),
('nombre', 'JUAN MANUEL','1'),
('nombre', 'JUAN MARCELO','1'),
('nombre', 'JUAN MARTIN','1'),
('nombre', 'JUAN MAXIMILIANO','1'),
('nombre', 'JUAN MIGUEL','1'),
('nombre', 'JUAN PABLO','1'),
('nombre', 'JUAN RAUL','1'),
('nombre', 'JUAN RODRIGO','1'),
('nombre', 'JUANA MARIA GARCIA','2'),
('nombre', 'JUANY','2'),
('nombre', 'JULEN','1'),
('nombre', 'JULI','2'),
('nombre', 'JULIAN','1'),
('nombre', 'JULIO ALBERTO','1'),
('nombre', 'JULIO CESAR','1'),
('nombre', 'JULIO ENRIQUE','1'),
('nombre', 'JULIO FRANCISCO','1'),
('nombre', 'JULIO JOAQUIN','1'),
('nombre', 'JUSTIN','1'),
('nombre', 'JUSTNIANA','2'),
('nombre', 'KAREM','2'),
('nombre', 'KARMEN','2'),
('nombre', 'KATERIN','2'),
('nombre', 'KATRINA','2'),
('nombre', 'KELLY','2'),
('nombre', 'KELVIN','1'),
('nombre', 'KETY','2'),
('nombre', 'KHEYCO','2'),
('nombre', 'KIEFFER','1'),
('nombre', 'KIM','1'),
('nombre', 'KIMEY','2'),
('nombre', 'KIMI','2'),
('nombre', 'KRISTEN','2'),
('nombre', 'KUN','1'),
('nombre', 'LADISLAO LORENZO','1'),
('nombre', 'LADYS','2'),
('nombre', 'LALY','2'),
('nombre', 'LANE','2'),
('nombre', 'LARISSA','2'),
('nombre', 'LAURA BETIANA','2'),
('nombre', 'LAUREN','2'),
('nombre', 'LEIDY','2'),
('nombre', 'LEILEN','2'),
('nombre', 'LENY','1'),
('nombre', 'LEO','1'),
('nombre', 'LEONCIA','2'),
('nombre', 'LEONGINA','2'),
('nombre', 'LETIZIA','2'),
('nombre', 'LEYDI','2'),
('nombre', 'LEYDY','2'),
('nombre', 'LIBOLIO','1'),
('nombre', 'LIBRANA','2'),
('nombre', 'LICHUTAN','2'),
('nombre', 'LIDEA','2'),
('nombre', 'LIDIO','1'),
('nombre', 'LIDUVINA','2'),
('nombre', 'LILANA','2'),
('nombre', 'LILI','2'),
('nombre', 'LILIA A','2'),
('nombre', 'LILIN','1'),
('nombre', 'LIMBER','1'),
('nombre', 'LIS DAIANA','2'),
('nombre', 'LITA','2'),
('nombre', 'LIZET','2'),
('nombre', 'LIZETH','2'),
('nombre', 'LIZZY','2'),
('nombre', 'LORENZ','1'),
('nombre', 'LUCCA','1'),
('nombre', 'LUCIA F','2'),
('nombre', 'LUDIVINA','2'),
('nombre', 'LUIS ALBERTO','1'),
('nombre', 'LUIS ENRIQUE','1'),
('nombre', 'LUIS FRANCISCO','1'),
('nombre', 'LUIS MARIA','1'),
('nombre', 'LUIS MIGUEL','1'),
('nombre', 'LUISA BEATRIZ','2'),
('nombre', 'LUKY','2'),
('nombre', 'LUNA (WANG RUINAN)','2'),
('nombre', 'LURDES','2'),
('nombre', 'LUYBON','2'),
('nombre', 'LUZ MARIA','2'),
('nombre', 'LUZCELI','2'),
('nombre', 'LYDIA','2'),
('nombre', 'M ANGELES','2'),
('nombre', 'M DEL CARMEN','2'),
('nombre', 'M INES','2'),
('nombre', 'M LUJAN','2'),
('nombre', 'M PILAR','2'),
('nombre', 'M VICTORIA','2'),
('nombre', 'MLUISA','2'),
('nombre', 'MA ANGELES','2'),
('nombre', 'MA CRISTINA','2'),
('nombre', 'MA DE LOS ANGELES','2'),
('nombre', 'MA DE LOS MILAGROS','2'),
('nombre', 'MACELESTE','2'),
('nombre', 'MAFERNANDA','2'),
('nombre', 'MAGDALENA LUISA','2'),
('nombre', 'MAICOL','1'),
('nombre', 'MAIDA','2'),
('nombre', 'MAMORU','1'),
('nombre', 'MANDELA','1'),
('nombre', 'MANUEL JESUS','1'),
('nombre', 'MAR','1'),
('nombre', 'MARANI','2'),
('nombre', 'MARBIN','1'),
('nombre', 'MARCELO JUNIOR','1'),
('nombre', 'MARCO ANTONIO','1'),
('nombre', 'MARGARITA EMMA','2'),
('nombre', 'MARI','2'),
('nombre', 'MARIA ADELA','2'),
('nombre', 'MARIA AGUSTINA','2'),
('nombre', 'MARIA ALEJANDRA','2'),
('nombre', 'MARIA AMELIA','2'),
('nombre', 'MARIA ANA','2'),
('nombre', 'MARIA ANDREA','2'),
('nombre', 'MARIA ANGELA','2'),
('nombre', 'MARIA ANGELES','2'),
('nombre', 'MARIA ANGELICA','2'),
('nombre', 'MARIA ANTONIA','2'),
('nombre', 'MARIA ASUNCION','2'),
('nombre', 'MARIA BELEN','2'),
('nombre', 'MARIA BERTA','2'),
('nombre', 'MARIA CAROLINA','2'),
('nombre', 'MARIA CECILIA','2'),
('nombre', 'MARIA CELESTE','2'),
('nombre', 'MARIA CLARA','2'),
('nombre', 'MARIA CRISTINA','2'),
('nombre', 'MARIA DAISEY','2'),
('nombre', 'MARIA DE LOS ANGELES','2'),
('nombre', 'MARIA DE LOS REMEDIOS','2'),
('nombre', 'MARIA DEL CARMEN','2'),
('nombre', 'MARIA DEL PILAR','2'),
('nombre', 'MARIA DEL ROSARIO','2'),
('nombre', 'MARIA DEL VALLE','2'),
('nombre', 'MARIA DELFINA','2'),
('nombre', 'MARIA ELBA','2'),
('nombre', 'MARIA ELENA','2'),
('nombre', 'MARIA ELISA','2'),
('nombre', 'MARIA ELSA','2'),
('nombre', 'MARIA EMILIA','2'),
('nombre', 'MARIA EMMA','2'),
('nombre', 'MARIA ERICA','2'),
('nombre', 'MARIA ESTER','2'),
('nombre', 'MARIA ESTHER','2'),
('nombre', 'MARIA EUGENIA','2'),
('nombre', 'MARIA EVA','2'),
('nombre', 'MARIA FERNANDA','2'),
('nombre', 'MARIA FLORENCIA','2'),
('nombre', 'MARIA FLORENCIA DI FIORE','2'),
('nombre', 'MARIA GABRIELA','2'),
('nombre', 'MARIA GRACIELA','2'),
('nombre', 'MARIA HAYDEE','2'),
('nombre', 'MARIA HERMINIA','2'),
('nombre', 'MARIA INES','2'),
('nombre', 'MARIA IRMA','2'),
('nombre', 'MARIA ISABEL','2'),
('nombre', 'MARIA JIMENA','2'),
('nombre', 'MARIA JOSE','2'),
('nombre', 'MARIA JOSEFA','2'),
('nombre', 'MARIA JOSEFINA','2'),
('nombre', 'MARIA JULIA','2'),
('nombre', 'MARIA LAURA','2'),
('nombre', 'MARIA LAURO','2'),
('nombre', 'MARIA LEANDRA','2'),
('nombre', 'MARIA LEONOR','2'),
('nombre', 'MARIA LIDIA','2'),
('nombre', 'MARIA LUCI','2'),
('nombre', 'MARIA LUCIA','2'),
('nombre', 'MARIA LUISA','2'),
('nombre', 'MARIA LUZ','2'),
('nombre', 'MARIA MAGDALENA','2'),
('nombre', 'MARIA MARTA','2'),
('nombre', 'MARIA MERCEDES','2'),
('nombre', 'MARIA MORA','2'),
('nombre', 'MARIA NOEMI','2'),
('nombre', 'MARIA PAULA','2'),
('nombre', 'MARIA PAZ','2'),
('nombre', 'MARIA PIA','2'),
('nombre', 'MARIA ROMELIA','2'),
('nombre', 'MARIA ROSA','2'),
('nombre', 'MARIA SILVANA','2'),
('nombre', 'MARIA SILVIA','2'),
('nombre', 'MARIA SOFIA','2'),
('nombre', 'MARIA SOL','2'),
('nombre', 'MARIA SOLEDAD','2'),
('nombre', 'MARIA TERESA','2'),
('nombre', 'MARIA TERESITA','2'),
('nombre', 'MARIA TRINIDAD','2'),
('nombre', 'MARIA VALERIA','2'),
('nombre', 'MARIA VERONICA','2'),
('nombre', 'MARIA VICTORIA','2'),
('nombre', 'MARIAMDEL CARMEN','2'),
('nombre', 'MARIANA CAROLINA','2'),
('nombre', 'MARIE FRANCE','2'),
('nombre', 'MARIELY','2'),
('nombre', 'MARILUZ','2'),
('nombre', 'MARIM','2'),
('nombre', 'MARIN','1'),
('nombre', 'MARISEL','2'),
('nombre', 'MARITA','2'),
('nombre', 'MARLY','2'),
('nombre', 'MARTA INES','2'),
('nombre', 'MARU','2'),
('nombre', 'MARY','2'),
('nombre', 'MATEO JUAN','1'),
('nombre', 'MATIA FLORENCIA','2'),
('nombre', 'MATIAN','1'),
('nombre', 'MATIAS','1'),
('nombre', 'MATRTA','2'),
('nombre', 'MAXI','1'),
('nombre', 'MAXIMO RUBEN','1'),
('nombre', 'MAYLEN','2'),
('nombre', 'MAYUMI','2'),
('nombre', 'MEDIO','1'),
('nombre', 'MELANI','2'),
('nombre', 'MELFIS','2'),
('nombre', 'MELIZA','2'),
('nombre', 'MELODI','2'),
('nombre', 'MELVIN','1'),
('nombre', 'MERINA','2'),
('nombre', 'MERLIN','1'),
('nombre', 'MERUZH','1'),
('nombre', 'MERY','2'),
('nombre', 'MICA','2'),
('nombre', 'MICHEL CECILIA','2'),
('nombre', 'MIGDONIO','1'),
('nombre', 'MIGUEL ANGEL','1'),
('nombre', 'MIGUEL ANGEL (H)','1'),
('nombre', 'MIGUEL IGNACIO','1'),
('nombre', 'MIGUELA','2'),
('nombre', 'MIKELE','2'),
('nombre', 'MILAGROS MARIANA','2'),
('nombre', 'MILAN','1'),
('nombre', 'MILCIADES','1'),
('nombre', 'MILDREE','2'),
('nombre', 'MILU','2'),
('nombre', 'MINA','2'),
('nombre', 'MINDA','2'),
('nombre', 'MIRI','2'),
('nombre', 'MIRIAM ALEJANDRA','2'),
('nombre', 'MISEL','1'),
('nombre', 'MOULAGE','1'),
('nombre', 'MRIAM','2'),
('nombre', 'MRIANO','1'),
('nombre', 'MUIGUEL','1'),
('nombre', 'MURICIO','1'),
('nombre', 'NAIRA','2'),
('nombre', 'NANCI','2'),
('nombre', 'NARSIZA','2'),
('nombre', 'NATI','2'),
('nombre', 'NATY','2'),
('nombre', 'NAYELI','2'),
('nombre', 'NEHMIAS','1'),
('nombre', 'NEHUEL','1'),
('nombre', 'NEIDA','2'),
('nombre', 'NEIDE','2'),
('nombre', 'NELCI','2'),
('nombre', 'NELI','2'),
('nombre', 'NELIDA','2'),
('nombre', 'NELY','2'),
('nombre', 'NERY','2'),
('nombre', 'NESTOR DARIO','1'),
('nombre', 'NESTOR OSCAR','1'),
('nombre', 'NICO','1'),
('nombre', 'NICOL','2'),
('nombre', 'NICOLAS','1'),
('nombre', 'NICOLAS MARCELO','1'),
('nombre', 'NICOMEDES','1'),
('nombre', 'NILSA','2'),
('nombre', 'NILSEN','2'),
('nombre', 'NOEMI NELIDA','2'),
('nombre', 'NOLAZCO','1'),
('nombre', 'NORHA','2'),
('nombre', 'NORMA ADRIANA','2'),
('nombre', 'NORMALIA','2'),
('nombre', 'OLANDA','2'),
('nombre', 'OLGA ANGELICA','2'),
('nombre', 'OLGA MARIA','2'),
('nombre', 'OLGA NOEMI','2'),
('nombre', 'OLLANTE','2'),
('nombre', 'ORACIO','1'),
('nombre', 'ORALIE','2'),
('nombre', 'ORESTE','1'),
('nombre', 'ORNELA','2'),
('nombre', 'ORVILLE','1'),
('nombre', 'OSBALDO','1'),
('nombre', 'OSVADO','1'),
('nombre', 'OSVALDO MIGUEL','1'),
('nombre', 'PABLO ANTONIO','1'),
('nombre', 'PABLO DANIEL','1'),
('nombre', 'PABLO JAVIER','1'),
('nombre', 'PABLO JULIO','1'),
('nombre', 'PARICIO','1'),
('nombre', 'PATROCINIA','2'),
('nombre', 'PATSY','2'),
('nombre', 'PAULA DANIELA','2'),
('nombre', 'PEDRO ENRIQUE','1'),
('nombre', 'PENI','2'),
('nombre', 'PEPE','1'),
('nombre', 'PERCI','1'),
('nombre', 'PETER','1'),
('nombre', 'PETRONELA','2'),
('nombre', 'PIERRE ALEJANDRO','1'),
('nombre', 'PLASIDA','2'),
('nombre', 'PRICILA','2'),
('nombre', 'QUIARA','2'),
('nombre', 'RAFAEL NICOLAS','1'),
('nombre', 'RAMIRA','2'),
('nombre', 'RANDY','1'),
('nombre', 'REMEDIOS','2'),
('nombre', 'REQUEL','2'),
('nombre', 'REYNA','2'),
('nombre', 'RIANA','2'),
('nombre', 'RICARDO ALBERTO','1'),
('nombre', 'RICARDO AUGUSTO','1'),
('nombre', 'RICARDO HIJO','1'),
('nombre', 'RICHAR','1'),
('nombre', 'RICHARD','1'),
('nombre', 'RICHY','1'),
('nombre', 'RIOVAL','1'),
('nombre', 'RIVERO','1'),
('nombre', 'ROBERT','1'),
('nombre', 'ROMALDO','1'),
('nombre', 'ROMMEL','1'),
('nombre', 'ROMY','2'),
('nombre', 'RONALD','1'),
('nombre', 'ROSA ALICIA','2'),
('nombre', 'ROSALBA','2'),
('nombre', 'ROSALINA','2'),
('nombre', 'ROSANNA','2'),
('nombre', 'ROSE','2'),
('nombre', 'ROSITA','2'),
('nombre', 'ROSMARY','2'),
('nombre', 'ROSMERI','2'),
('nombre', 'ROSSANA','2'),
('nombre', 'RUBEN JR','1'),
('nombre', 'RUMILDA','2'),
('nombre', 'RUSBEL','1'),
('nombre', 'SADY','2'),
('nombre', 'SAFINO','1'),
('nombre', 'SANDRA GABRIELA','2'),
('nombre', 'SANNTIAGO','1'),
('nombre', 'SANTA LEDESMA','2'),
('nombre', 'SANTI','1'),
('nombre', 'SARELLA','2'),
('nombre', 'SAYDA','2'),
('nombre', 'SEBASTIAN LUIS ACOSTA','1'),
('nombre', 'SEBATIAN','1'),
('nombre', 'SEGUNDINO','1'),
('nombre', 'SELSO','1'),
('nombre', 'SENOVIA','2'),
('nombre', 'SERGIO GUSTAVO','1'),
('nombre', 'SERVINO','1'),
('nombre', 'SHEENA','2'),
('nombre', 'SILDA','2'),
('nombre', 'SILVANA GIORGINA','2'),
('nombre', 'SILVANA GRACIELA','2'),
('nombre', 'SILVVANA','2'),
('nombre', 'SINDY','2'),
('nombre', 'SIOMARA','2'),
('nombre', 'SIRLEY','2'),
('nombre', 'SIVANA','2'),
('nombre', 'SIXTA','2'),
('nombre', 'SLEDAD','2'),
('nombre', 'SOBRINA','2'),
('nombre', 'SOFIA','2'),
('nombre', 'SOLE','2'),
('nombre', 'SONIA ELIZABETH','2'),
('nombre', 'SOO JA','2'),
('nombre', 'SSANA','2'),
('nombre', 'STEFANI','2'),
('nombre', 'STEFANY','2'),
('nombre', 'STEFI','2'),
('nombre', 'STELA MARIS','2'),
('nombre', 'STELLA','2'),
('nombre', 'STEPHAN','1'),
('nombre', 'SUE','2'),
('nombre', 'SULEMA','2'),
('nombre', 'SUSAN','2'),
('nombre', 'SUSHAOFANG','2'),
('nombre', 'SUSI','2'),
('nombre', 'SYOMARA','2'),
('nombre', 'SYRLEY','2'),
('nombre', 'TAHIREL','1'),
('nombre', 'TAIS TAMARA','2'),
('nombre', 'TALI','2'),
('nombre', 'TANO','1'),
('nombre', 'TAYARA','2'),
('nombre', 'TELMO HIJO','1'),
('nombre', 'TEO GAEL','1'),
('nombre', 'TEODOMIRO','1'),
('nombre', 'THAIEL','1'),
('nombre', 'TIHAHO','1'),
('nombre', 'TILITA','2'),
('nombre', 'TINO','1'),
('nombre', 'TISIANO','1'),
('nombre', 'TOMAS AGUSTIN','1'),
('nombre', 'TOMASSO','1'),
('nombre', 'TOMY','1'),
('nombre', 'TONY','1'),
('nombre', 'TORIBIA','2'),
('nombre', 'TRIESTINA','2'),
('nombre', 'TRIFINA','2'),
('nombre', 'TUFIC','1'),
('nombre', 'TULA','2'),
('nombre', 'TUOMAS','1'),
('nombre', 'TZIPORA','2'),
('nombre', 'UDSON','1'),
('nombre', 'UMAR','1'),
('nombre', 'UMMA','2'),
('nombre', 'URSUKA','2'),
('nombre', 'UVENCIA','2'),
('nombre', 'VALDOMINO','1'),
('nombre', 'VALEN','2'),
('nombre', 'VALENTIN','1'),
('nombre', 'VALERIA INES','2'),
('nombre', 'VANESSA','2'),
('nombre', 'VENANCIA','2'),
('nombre', 'VENEDICTO','1'),
('nombre', 'VENESA','2'),
('nombre', 'VENORICA','2'),
('nombre', 'VERA INES','2'),
('nombre', 'VERONICS','2'),
('nombre', 'VICENTA','2'),
('nombre', 'VICENTE CARLOS','1'),
('nombre', 'VICKY','2'),
('nombre', 'VICTOR HUGO','1'),
('nombre', 'VIKI','2'),
('nombre', 'VIRGILIO','1'),
('nombre', 'VISPE','1'),
('nombre', 'VIVANA','2'),
('nombre', 'VIVIANA LAURA','2'),
('nombre', 'WILE','1'),
('nombre', 'WILIAMS','1'),
('nombre', 'WILLAM','1'),
('nombre', 'WILLIAMS','1'),
('nombre', 'WILLIANS','1'),
('nombre', 'WILMER','1'),
('nombre', 'WINNIE','2'),
('nombre', 'YADICEL','2'),
('nombre', 'YAKELINE','2'),
('nombre', 'YAMILLA','2'),
('nombre', 'YANE','2'),
('nombre', 'YANILSE','2'),
('nombre', 'YAQUELIN','2'),
('nombre', 'YAQUELINE','2'),
('nombre', 'YAROSLV','1'),
('nombre', 'YEKA','1'),
('nombre', 'YENIFER','2'),
('nombre', 'YENIFER SANDOBAL','2'),
('nombre', 'YENNE','2'),
('nombre', 'YENNY','2'),
('nombre', 'YERUSKA','2'),
('nombre', 'YESENIA','2'),
('nombre', 'YHOANA','2'),
('nombre', 'YOHANA','2'),
('nombre', 'YOHANNA','2'),
('nombre', 'YOJANA','2'),
('nombre', 'YONI','1'),
('nombre', 'YOSELIN','2'),
('nombre', 'YOUNG HOI','1'),
('nombre', 'YOVANA','2'),
('nombre', 'YUDDER','1'),
('nombre', 'ZACH','1'),
('nombre', 'ZAIR','1'),
('nombre', 'ZEINEP','2'),
('nombre', 'ZENGCONG','1'),
('nombre', 'ZIMO','1'),
('nombre', 'ZOE ABRIL','2'),
('nombre', 'ZUK','2'),
('nombre', 'ZULEIMA','2'),
('nombre', 'ZULLY','2');

insert into encu.dictra
select diccionario,origen,destino::integer, 1 from encu.diccionario_agregar
where trim(diccionario)||trim(origen) not in (
select trim(dictra_dic)||trim(dictra_ori) from encu.dictra);

drop table encu.diccionario_agregar;