CREATE TABLE encu.diccionario_agregar (
  diccionario text,
  origen text,
  destino text
  )
  WITH (
  OIDS=FALSE
);
ALTER TABLE encu.diccionario_agregar
  OWNER TO tedede_php;


insert into encu.diccionario_agregar values
('sn4_esp_txt', 'ABORTO ESPONTANEO','1'),
('sn4_esp_txt', 'ACCIDENTE ESCUELA','2'),
('sn4_esp_txt', 'ACCIDENTE LABORAL','2'),
('sn4_esp_txt', 'ACTUALIZÓ LIBRETA SANITARIA','3'),
('sn4_esp_txt', 'ALERGIA','4'),
('sn4_esp_txt', 'ANALISIS PARA UN INGRESO A CURSO','3'),
('sn4_esp_txt', 'ANALISIS PRE LABORALES','3'),
('sn4_esp_txt', 'ANGINA','1'),
('sn4_esp_txt', 'ANGINAS','1'),
('sn4_esp_txt', 'ANGINAS CON SINUSITIS','1'),
('sn4_esp_txt', 'APENDICITIS','1'),
('sn4_esp_txt', 'APTITUD MEDICA CERTIFICADO','3'),
('sn4_esp_txt', 'APTO FISICO','3'),
('sn4_esp_txt', 'APTO MEDICO','3'),
('sn4_esp_txt', 'BIOPSIA','4'),
('sn4_esp_txt', 'BRONCOESPASMO','1'),
('sn4_esp_txt', 'BUCAL','4'),
('sn4_esp_txt', 'BUSQUEDA DE GESTACION','4'),
('sn4_esp_txt', 'CAIDA','2'),
('sn4_esp_txt', 'CAÍDA DE CABELLO','1'),
('sn4_esp_txt', 'CÁNCER DE PRÓSTATA','1'),
('sn4_esp_txt', 'CASAMIENTO','3'),
('sn4_esp_txt', 'CASAMIENTO, ANALISIS PRENUPCIALES','3'),
('sn4_esp_txt', 'CERTIFICADO DE APTITUD FISICA PARA GIMNASIO','3'),
('sn4_esp_txt', 'CERTIFICADO ESCOLAR','3'),
('sn4_esp_txt', 'CHEQUEO ANUAL DEL TRABAJO','3'),
('sn4_esp_txt', 'CHEQUEO LABORAL','3'),
('sn4_esp_txt', 'CIRUGIA','1'),
('sn4_esp_txt', 'CIRUGIA DE RODILLA','1'),
('sn4_esp_txt', 'CONSULTA DOLOR DEL HOMBRO','1'),
('sn4_esp_txt', 'CONSULTA PARTICULAR SOBRE FERTILIDAD','4'),
('sn4_esp_txt', 'CONSULTA PREOCUPACIONAL','3'),
('sn4_esp_txt', 'CONTROL DE EMBARAZO','3'),
('sn4_esp_txt', 'CONTROL DE LA EMPRESA','3'),
('sn4_esp_txt', 'CONTROL DE MARCAPASOS','3'),
('sn4_esp_txt', 'CONTROL DE MEDICACION','3'),
('sn4_esp_txt', 'CONTROL DE POST OPERATORIO','3'),
('sn4_esp_txt', 'CONTROL EMBARAZO','3'),
('sn4_esp_txt', 'CONTROL PARA EL TRABAJO','3'),
('sn4_esp_txt', 'CONTROL PARA LA ESCUELA, CERTIFICADO DE APTITUD FISICA','3'),
('sn4_esp_txt', 'CONTROL PERMANENTE : ESTIMULACIÓN TEMPRANA, Q90','3'),
('sn4_esp_txt', 'CONTROL POR MATERNIDAD','3'),
('sn4_esp_txt', 'CONTROL POST OPERACION','3'),
('sn4_esp_txt', 'CONTROL POST OPERATORIO','3'),
('sn4_esp_txt', 'CRISIS ASMÁTICA','1'),
('sn4_esp_txt', 'DEPRESION','1'),
('sn4_esp_txt', 'DEPRESION PORQUE PERDIÓ A SU MUJER EN LA TRAGEDIA DE ONCE','1'),
('sn4_esp_txt', 'DESGANO','1'),
('sn4_esp_txt', 'DIALISIS','1'),
('sn4_esp_txt', 'DOLOR DE CERVICAL','1'),
('sn4_esp_txt', 'DOLOR DE ESTOMAGO','1'),
('sn4_esp_txt', 'DOLOR DE MUELA','1'),
('sn4_esp_txt', 'DOLOR DE TALON','1'),
('sn4_esp_txt', 'EMBARAZO','3'),
('sn4_esp_txt', 'EMBARAZO DE ALTO RIESGO','3'),
('sn4_esp_txt', 'EMBARAZO Y PARTO','3'),
('sn4_esp_txt', 'EMBARAZO, CONTROLES','3'),
('sn4_esp_txt', 'ESGUINCE DE TOBILLO','1'),
('sn4_esp_txt', 'ESGUINCE RODILLA','1'),
('sn4_esp_txt', 'ESTA YENDO A UNA NUTRICIONISTA','8'),
('sn4_esp_txt', 'ESTRES','1'),
('sn4_esp_txt', 'ESTUDIO DE APTITID FISICA','3'),
('sn4_esp_txt', 'ESTUDIO PRE OCUPACIONAL','3'),
('sn4_esp_txt', 'ESTUDIOS PARA INGRESAR EN LA POLICIA','3'),
('sn4_esp_txt', 'ESTUDIOS PRE LABORALES','3'),
('sn4_esp_txt', 'EXAMEN PRE OCUPACIONAL','3'),
('sn4_esp_txt', 'FICHA MEDICA','3'),
('sn4_esp_txt', 'FISURA EN EL PIE','1'),
('sn4_esp_txt', 'FONOAUDIOLOGA','8'),
('sn4_esp_txt', 'FRACTURA DE PIERNA','1'),
('sn4_esp_txt', 'GUARDIA','4'),
('sn4_esp_txt', 'HABITUALMENTE X TRATAMIENTOO  KINESIOLOGICO','8'),
('sn4_esp_txt', 'HEMORRAGIA INTESTINAL','1'),
('sn4_esp_txt', 'HIPERTENSION','1'),
('sn4_esp_txt', 'HIPOCONDRIACA','1'),
('sn4_esp_txt', 'INICIAR ESTUDIOS PARA PENSIÓN POR DISCAPACIDAD','3'),
('sn4_esp_txt', 'INSCRIPCIÓN PARA INGRESAR AL ESCUELA','3'),
('sn4_esp_txt', 'INTERVENCION QUIRURJICA','1'),
('sn4_esp_txt', 'LE ASUSTABA LA RONQUERA QUE ESTABA TENIENDO','3'),
('sn4_esp_txt', 'LE TENIAN QUE DAR EL ALTA','1'),
('sn4_esp_txt', 'LENTES','4'),
('sn4_esp_txt', 'LENTES NUEVOS','4'),
('sn4_esp_txt', 'LIBRETA DE SALUD DEL COLEGIO','3'),
('sn4_esp_txt', 'LIBRETA SANITARIA','3'),
('sn4_esp_txt', 'LIBRETA SANITARIA PARA SECUNDARIA','3'),
('sn4_esp_txt', 'MORDEDURA DE PERRO','2'),
('sn4_esp_txt', 'NEUMONIA','1'),
('sn4_esp_txt', 'NUTRICIONISTA','8'),
('sn4_esp_txt', 'OBTENER CERTIFICADO APTITUD FISICA','3'),
('sn4_esp_txt', 'OPERACION DE AMIGDALAS','1'),
('sn4_esp_txt', 'OPERACIÓN DE LIGAMIENTO DE TROMPAS','1'),
('sn4_esp_txt', 'OPERACION DE OIDO','1'),
('sn4_esp_txt', 'OPERACION DE RODILLA','1'),
('sn4_esp_txt', 'OPERACION DEL OIDO','1'),
('sn4_esp_txt', 'PARA INGRESAR A NATACIÓN','3'),
('sn4_esp_txt', 'PARA SACAR LA LIBRETA SANITARIA PARA EL TRABAJO','3'),
('sn4_esp_txt', 'PARIO POR CESAREA, SE TIENE QUE HACER CONTROLES','3'),
('sn4_esp_txt', 'PEE OCUPACIONAL','3'),
('sn4_esp_txt', 'PERO OCUPACIONAL','3'),
('sn4_esp_txt', 'POR EMBARAZO','3'),
('sn4_esp_txt', 'POR ENTREVISTA LABORAL','3'),
('sn4_esp_txt', 'POR PROBLEMAS DE VISION','1'),
('sn4_esp_txt', 'POR RAZONES LABORALES','3'),
('sn4_esp_txt', 'POR UNA ENTREVISTA LABORAL','3'),
('sn4_esp_txt', 'POSOPERATORIO','3'),
('sn4_esp_txt', 'POST PARTO','3'),
('sn4_esp_txt', 'POSTEMBARAZO','3'),
('sn4_esp_txt', 'PRE LABORAL','3'),
('sn4_esp_txt', 'PRE OCUPACIONAL','3'),
('sn4_esp_txt', 'PRE QUIRURGICOS','3'),
('sn4_esp_txt', 'PRELABORAL','3'),
('sn4_esp_txt', 'PREOCUPACIONAL','3'),
('sn4_esp_txt', 'PRE-OCUPACIONAL','3'),
('sn4_esp_txt', 'PREOCUPACIONAL PARA TRABAJO','3'),
('sn4_esp_txt', 'PREOOCUPACIONAL','3'),
('sn4_esp_txt', 'PREOPERATORIO','3'),
('sn4_esp_txt', 'PROBLEMAS DE NUTRICION','1'),
('sn4_esp_txt', 'PROBLEMAS DE OIDO','1'),
('sn4_esp_txt', 'PROBLEMAS DE PARTO','1'),
('sn4_esp_txt', 'PROBLEMAS DEL COMPORTAMIENTO','1'),
('sn4_esp_txt', 'PROBLEMAS NEUROLÓGICOS','1'),
('sn4_esp_txt', 'PROBLEMAS SERVICAL','1'),
('sn4_esp_txt', 'PROBLEMAS SICOLOGICOS','1'),
('sn4_esp_txt', 'PROTESIS EN LA PIERNA','1'),
('sn4_esp_txt', 'PSICOFISICO LABORAL','3'),
('sn4_esp_txt', 'PSICOFÍSICO, LABORAL','3'),
('sn4_esp_txt', 'PSIQUIATRA','1'),
('sn4_esp_txt', 'PULIDO DE LENTES DE CONTACTO','4'),
('sn4_esp_txt', 'QUISTE','1'),
('sn4_esp_txt', 'REALIZACIÓN DE LIBRETA SANITARIA','3'),
('sn4_esp_txt', 'REFLUJO','1'),
('sn4_esp_txt', 'RENOVACION DE REGISTRO DE CONDUCIR','3'),
('sn4_esp_txt', 'RENOVAR LIBRETA SANITARIA','3'),
('sn4_esp_txt', 'REVISACION PARA INGRESO ESCOLAR','3'),
('sn4_esp_txt', 'RODILLAS Y MANO','1'),
('sn4_esp_txt', 'SACAR DIENTE','3'),
('sn4_esp_txt', 'SE CONTRACTURO EL CUELLO','1'),
('sn4_esp_txt', 'SN4_ESP=LICENCIA DE CONDUCIR PROFESIONAL','3'),
('sn4_esp_txt', 'SOBRE HUESO EN EL PIE','1'),
('sn4_esp_txt', 'SOLICITAR CERTIFICADO DE APTITUD MEDICA.','3'),
('sn4_esp_txt', 'TGD','1'),
('sn4_esp_txt', 'TOS','1'),
('sn4_esp_txt', 'TOS MUY FUERTE','1'),
('sn4_esp_txt', 'TRATAMIENTO DE FERTILIDAD','1'),
('sn4_esp_txt', 'TRATAMIENTO DIABETES','1'),
('sn4_esp_txt', 'TRATAMIENTO EN CURSO','1'),
('sn4_esp_txt', 'TRATAMIENTO FERTILIDAD','1'),
('sn4_esp_txt', 'TRATAMIENTO MEDICO','1'),
('sn4_esp_txt', 'TRATAMIENTO POR UNA ROTURA DE LIGAMENTO','1'),
('sn4_esp_txt', 'TRATAMIENTO, ES DIABETICA','1'),
('sn4_esp_txt', 'UNA OPERACION DE OIDO','1'),
('sn4_esp_txt', 'VACUNA','3'),
('sn4_esp_txt', 'VACUNA.','3'),
('sn4_esp_txt', 'X ESTRES','1');

insert into encu.diccionario
select diccionario, true as completo, 1 as tlg from encu.diccionario_agregar group by diccionario, completo, tlg;

insert into encu.dictra
select diccionario,origen,destino::integer, 1 from encu.diccionario_agregar;

INSERT INTO encu.dicvar values
('sn4_esp_txt','sn4_esp',1);

drop table encu.diccionario_agregar;