delete from encu.consistencias;
alter table encu.consistencias add column con_estado character varying(100) DEFAULT 'pendiente'::character varying;
alter table encu.consistencias add column con_falsos_positivos  character varying(100);
alter table encu.consistencias add column con_importancia  character varying(100);

INSERT INTO encu.consistencias(
            con_ope, 
            con_con, 
            con_precondicion, 
            con_rel, 
            con_postcondicion, 
            con_activa, 
            con_descripcion, 
            con_grupo, 
            con_modulo, 
            con_tipo, 
            con_gravedad, 
            con_momento, 
            con_version, 
            con_explicacion, 
            con_orden, 
            con_expl_ok, 
            con_rev, 
            con_junta, 
            con_clausula_from, 
            con_expresion_sql, 
            con_valida, 
            con_error_compilacion, 
            con_ultima_modificacion, 
            con_ultima_variable, 
            con_ignorar_nulls,
            con_estado,
            con_falsos_positivos,
            con_importancia, 
            con_tlg)
SELECT  'pp2012' as con_ope,
	con_con, 
        con_precondicion, 
        con_rel, 
        con_postcondicion, 
        con_activa, 
        con_descripcion, 
        con_grupo, 
        con_modulo, 
        con_tipo, 
        'Error' as con_gravedad,
        con_momento, 
        con_version, 
        con_explicacion, 
        con_orden, 
        con_expl_ok, 
        con_rev, 
        con_junta, 
        con_clausula_from, 
        con_expresion_sql, 
        con_valida, 
        con_error_compilacion, 
        con_ultima_modificacion, 
        con_ultima_variable, 
        con_ignorar_nulls, 
        con_estado, 
        con_falsos_positivos, 
        con_importancia,
        '1' as con_tlg
FROM yeah.consistencias;