INSERT INTO encu.rol_rol (rolrol_principal, rolrol_delegado,rolrol_tlg) VALUES ('subcoor_campo', 'aux_info_campo'/*CAMPOS_AUDITORIA*/),
('subcoor_campo', 'recepcionista'/*CAMPOS_AUDITORIA*/),
('aux_info_campo', 'subcoor_campo'/*CAMPOS_AUDITORIA*/),
('aux_info_campo', 'recepcionista'/*CAMPOS_AUDITORIA*/),
('mues_campo', 'ana_campo'/*CAMPOS_AUDITORIA*/),
('coor_campo', 'subcoor_campo'/*CAMPOS_AUDITORIA*/),
('coor_campo', 'recepcionista'/*CAMPOS_AUDITORIA*/),
('coor_campo', 'aux_info_campo'/*CAMPOS_AUDITORIA*/),
('aux_info_campo', 'coor_campo'/*CAMPOS_AUDITORIA*/),
('mues_campo', 'subcoor_campo'/*CAMPOS_AUDITORIA*/),
('mues_campo', 'recepcionista'/*CAMPOS_AUDITORIA*/),
('mues_campo', 'aux_info_campo'/*CAMPOS_AUDITORIA*/),
('mues_campo', 'coor_campo'/*CAMPOS_AUDITORIA*/),
('sup_ing', 'ana_ing'/*CAMPOS_AUDITORIA*/),
('sup_ing', 'ingresador'/*CAMPOS_AUDITORIA*/),
('sup_ing', 'coor_campo'/*CAMPOS_AUDITORIA*/),
('ana_ing', 'ingresador'/*CAMPOS_AUDITORIA*/),
('procesamiento', 'sup_ing'/*CAMPOS_AUDITORIA*/),
('procesamiento', 'ana_ing'/*CAMPOS_AUDITORIA*/),
('procesamiento', 'ingresador'/*CAMPOS_AUDITORIA*/),
('subcoor_campo', 'ingresador'/*CAMPOS_AUDITORIA*/),
('mues_campo', 'ingresador'/*CAMPOS_AUDITORIA*/),
('coor_campo', 'ingresador'/*CAMPOS_AUDITORIA*/)

