-- Table: encu.rama

-- DROP TABLE encu.rama;

CREATE TABLE encu.rama
(
  ram_ram integer NOT NULL,
  ram_descripcion character varying(200),
  ram_tlg bigint,
  CONSTRAINT rama_pk PRIMARY KEY (ram_ram),
  CONSTRAINT "texto de descripción de rama inválido" CHECK (comun.cadena_valida(ram_descripcion::text, 'castellano'::text))
);
ALTER TABLE encu.rama
  OWNER TO tedede_php;

-- Table: encu.ocupacion

-- DROP TABLE encu.ocupacion;

CREATE TABLE encu.ocupacion
(
  ocu_ocu integer NOT NULL,
  ocu_descripcion character varying(200),
  ocu_tlg bigint,
  CONSTRAINT ocupacion_pk PRIMARY KEY (ocu_ocu),
  CONSTRAINT "texto de descripción de ocupacion inválido" CHECK (comun.cadena_valida(ocu_descripcion::text, 'castellano'::text))
);
ALTER TABLE encu.ocupacion
  OWNER TO tedede_php;
  
/*-- ya figuran en rpm2016
ALTER TABLE encu.varcal DROP CONSTRAINT "texto invalido en varcal_tipodedato de tabla varcal" ;   
ALTER TABLE encu.varcal ADD CONSTRAINT "texto invalido en varcal_tipodedato de tabla varcal" CHECK (varcal_tipodedato = ANY (ARRAY['entero', 'decimal', 'texto']));
  
  
--agregamos los campos a la tabla encu.plana_i1.
ALTER TABLE encu.plana_i1_  ADD COLUMN pla_t37_cod INTEGER;
ALTER TABLE encu.plana_i1_  ADD COLUMN pla_t41_cod INTEGER;
ALTER TABLE encu.plana_i1_  ADD COLUMN pla_t37_cod2 INTEGER;
ALTER TABLE encu.plana_i1_  ADD COLUMN pla_t41_cod2 INTEGER;
ALTER TABLE encu.plana_i1_  ADD COLUMN pla_rama1 CHARACTER VARYING(2);
ALTER TABLE encu.plana_i1_  ADD COLUMN pla_rama2 CHARACTER VARYING(2);
ALTER TABLE encu.plana_i1_  ADD COLUMN pla_ocu1 CHARACTER VARYING(1);
ALTER TABLE encu.plana_i1_  ADD COLUMN pla_ocu2 CHARACTER VARYING(1);
ALTER TABLE encu.plana_i1_  ADD COLUMN pla_ocu3 CHARACTER VARYING(1);
ALTER TABLE encu.plana_i1_  ADD COLUMN pla_ocu4 CHARACTER VARYING(1);
ALTER TABLE encu.plana_i1_  ADD COLUMN pla_ocu5 CHARACTER VARYING(1);
ALTER TABLE encu.plana_i1_  ADD COLUMN pla_obsrama TEXT;
ALTER TABLE encu.plana_i1_  ADD COLUMN pla_obsocu TEXT;

ALTER TABLE his.plana_i1_  ADD COLUMN pla_t37_cod INTEGER;
ALTER TABLE his.plana_i1_  ADD COLUMN pla_t41_cod INTEGER;
ALTER TABLE his.plana_i1_  ADD COLUMN pla_t37_cod2 INTEGER;
ALTER TABLE his.plana_i1_  ADD COLUMN pla_t41_cod2 INTEGER;
ALTER TABLE his.plana_i1_  ADD COLUMN pla_rama1 CHARACTER VARYING(2);
ALTER TABLE his.plana_i1_  ADD COLUMN pla_rama2 CHARACTER VARYING(2);
ALTER TABLE his.plana_i1_  ADD COLUMN pla_ocu1 CHARACTER VARYING(1);
ALTER TABLE his.plana_i1_  ADD COLUMN pla_ocu2 CHARACTER VARYING(1);
ALTER TABLE his.plana_i1_  ADD COLUMN pla_ocu3 CHARACTER VARYING(1);
ALTER TABLE his.plana_i1_  ADD COLUMN pla_ocu4 CHARACTER VARYING(1);
ALTER TABLE his.plana_i1_  ADD COLUMN pla_ocu5 CHARACTER VARYING(1);
ALTER TABLE his.plana_i1_  ADD COLUMN pla_obsrama TEXT;
ALTER TABLE his.plana_i1_  ADD COLUMN pla_obsocu TEXT;

 INSERT INTO encu.varcal(varcal_ope, varcal_varcal, varcal_destino, varcal_orden, varcal_nombre, varcal_activa, varcal_tipo, varcal_baseusuario, varcal_nombrevar_baseusuario, varcal_tipodedato, varcal_tlg, varcal_valida, varcal_opciones_excluyentes) VALUES 
 ('rpm2016', 't37_cod2', 'mie', 1, 'Código rama de actividad para ocupados', true, 'especial', true, 't37_cod2', 'entero', 1, true, false),
 ('rpm2016', 't41_cod2', 'mie', 1, 'Código ocupación para ocupados', true, 'especial', true, 't41_cod2', 'entero', 1, true, false),
 ('rpm2016', 'rama1', 'mie', 1, 'Código rama primeros dígitos(2)', true, 'especial', false, null, 'texto', 1, true, false),
 ('rpm2016', 'rama2', 'mie', 1, 'Código rama últimos dígitos(2)', true, 'especial', false, null, 'texto', 1, true, false),
 ('rpm2016', 'ocu1', 'mie', 1, 'Código ocupación primer dígito', true, 'especial', false, null, 'texto', 1, true, false),
 ('rpm2016', 'ocu2', 'mie', 1, 'Código ocupación segundo dígito', true, 'especial', false, null, 'texto', 1, true, false),
 ('rpm2016', 'ocu3', 'mie', 1, 'Código ocupación tercer dígito', true, 'especial', false, null, 'texto', 1, true, false),
 ('rpm2016', 'ocu4', 'mie', 1, 'Código ocupación cuarto dígito', true, 'especial', false, null, 'texto', 1, true, false),
 ('rpm2016', 'ocu5', 'mie', 1, 'Código ocupación quinto dígito', true, 'especial', false, null, 'texto', 1, true, false),
 ('rpm2016', 'obsrama', 'mie', 1, 'Observaciones de rama', true, 'especial', false, null, 'texto', 1, true, false),
 ('rpm2016', 'obsocu', 'mie', 1, 'Observaciones de ocupación', true, 'especial', false, null, 'texto', 1, true, false);
 */
/*
ALTER TABLE encu.plana_i1_
  ADD CONSTRAINT "CODIGO DE OCUPACION NO VALIDO EN t41_cod2" FOREIGN KEY (pla_t41_cod2)
      REFERENCES encu.ocupacion (ocu_ocu) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE encu.plana_i1_
  ADD CONSTRAINT "CODIGO DE RAMA NO VALIDO EN t37_cod2" FOREIGN KEY (pla_t37_cod2)
      REFERENCES encu.rama (ram_ram) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

*/
NOTA:Datos de tabla rama y ocupacion tomarlos de donde nos indiquen
/*

SET search_path = encu, pg_catalog;

--datos de rama
INSERT INTO rama VALUES (101, 'Cultivos agrícolas', 1);
INSERT INTO rama VALUES (102, 'Cría de animales', 1);
INSERT INTO rama VALUES (103, 'Cultivo de productos agrícolas en combinación con la cría de animales', 1);
INSERT INTO rama VALUES (104, 'Servicios agrícolas y pecuarios, excepto los veterinarios', 1);
INSERT INTO rama VALUES (105, 'Caza y captura de animales vivos, repoblación de animales de caza y servicios de apoyo', 1);
INSERT INTO rama VALUES (200, 'Silvicultura, extracción de madera y actividades de apoyo', 1);
INSERT INTO rama VALUES (300, 'Pesca, acuicultura y actividades de apoyo', 1);
INSERT INTO rama VALUES (500, 'Extracción de carbón y lignito', 1);
INSERT INTO rama VALUES (600, 'Extracción de petróleo crudo y gas natural', 1);
INSERT INTO rama VALUES (700, 'Extracción de minerales metalíferos', 1);
INSERT INTO rama VALUES (800, 'Explotación de otras minas y canteras', 1);
INSERT INTO rama VALUES (900, 'Actividades de apoyo a la explotación de minas y canteras', 1);
INSERT INTO rama VALUES (1001, 'Producción y procesamiento de carne y pescado', 1);
INSERT INTO rama VALUES (1002, 'Preparación de frutas, hortalizas y legumbres, aceites y grasas', 1);
INSERT INTO rama VALUES (1003, 'Elaboración de productos lácteos', 1);
INSERT INTO rama VALUES (1009, 'Elaboración de productos alimenticios n.c.p.', 1);
INSERT INTO rama VALUES (1100, 'Elaboración de bebidas', 1);
INSERT INTO rama VALUES (1200, 'Elaboración de productos de tabaco', 1);
INSERT INTO rama VALUES (1300, 'Fabricación de productos textiles, excepto prendas de vestir', 1);
INSERT INTO rama VALUES (1400, 'Confección de prendas de vestir, terminación y teñido de pieles', 1);
INSERT INTO rama VALUES (1501, 'Curtido y terminación de cueros, fabricación de maletas, bolsos de mano y artículos de talabartería y guarnicionería, teñido de pieles', 1);
INSERT INTO rama VALUES (1502, 'Fabricación de calzado y sus partes', 1);
INSERT INTO rama VALUES (1600, 'Producción de madera y fabricación de productos de madera y corcho, excepto muebles, fabricación de artículos de paja y de materiales trenzables', 1);
INSERT INTO rama VALUES (1700, 'Fabricación de papel y productos de papel', 1);
INSERT INTO rama VALUES (1800, 'Actividades de impresión y servicios de apoyo, reproducción de grabaciones', 1);
INSERT INTO rama VALUES (1901, 'Fabricación de productos de hornos de coque', 1);
INSERT INTO rama VALUES (1902, 'Fabricación de productos de la refinación del petróleo', 1);
INSERT INTO rama VALUES (2001, 'Fabricación de pinturas, barnices y productos de revestimiento similares, tintas de imprenta y masillas', 1);
INSERT INTO rama VALUES (2002, 'Fabricación de jabones y detergentes, preparados para limpiar y pulir, perfumes y preparados de tocador', 1);
INSERT INTO rama VALUES (2009, 'Fabricación de otros productos químicos n.c.p.', 1);
INSERT INTO rama VALUES (2100, 'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos', 1);
INSERT INTO rama VALUES (2201, 'Fabricación de productos de caucho', 1);
INSERT INTO rama VALUES (2202, 'Fabricación de productos de plástico', 1);
INSERT INTO rama VALUES (2301, 'Fabricación de vidrio y productos de vidrio', 1);
INSERT INTO rama VALUES (2309, 'Fabricación de productos minerales no metálicos n.c.p.', 1);
INSERT INTO rama VALUES (2400, 'Fabricación de metales', 1);
INSERT INTO rama VALUES (2500, 'Fabricación de productos elaborados de metal y servicios de trabajos de metales, excepto máquinas y equipos', 1);
INSERT INTO rama VALUES (2601, 'Fabricación de componentes electrónicos', 1);
INSERT INTO rama VALUES (2602, 'Fabricación de equipos informáticos y periféricos', 1);
INSERT INTO rama VALUES (2603, 'Fabricación de equipos y aparatos de radio, televisión y comunicaciones', 1);
INSERT INTO rama VALUES (2604, 'Fabricación de equipos electromédicos, ópticos y de precisión, fabricación de relojes, soportes magnéticos y ópticos', 1);
INSERT INTO rama VALUES (2701, 'Fabricación de aparatos de uso doméstico, excepto equipos de audio y video', 1);
INSERT INTO rama VALUES (2709, 'Fabricación de otras maquinarias y equipos eléctricos n.c.p.', 1);
INSERT INTO rama VALUES (2800, 'Fabricación de maquinarias y equipos n.c.p.', 1);
INSERT INTO rama VALUES (2900, 'Fabricación de vehículos automotores, remolques y semirremolques', 1);
INSERT INTO rama VALUES (3001, 'Construcción de buques y otras embarcaciones', 1);
INSERT INTO rama VALUES (3002, 'Fabricación de locomotoras y de material rodante para ferrocarriles y tranvías', 1);
INSERT INTO rama VALUES (3003, 'Fabricación de aeronaves', 1);
INSERT INTO rama VALUES (3009, 'Fabricación de otros equipos de transporte n.c.p.', 1);
INSERT INTO rama VALUES (3100, 'Fabricación de muebles y colchones', 1);
INSERT INTO rama VALUES (3200, 'Industrias manufactureras n.c.p', 1);
INSERT INTO rama VALUES (3300, 'Mantenimiento, reparación e instalación de maquinas y equipos', 1);
INSERT INTO rama VALUES (3501, 'Generación, transmisión y distribución de energía eléctrica', 1);
INSERT INTO rama VALUES (3502, 'Fabricación de gas, distribución de combustibles gaseosos por tuberías, suministro de vapor y aire acondicionado', 1);
INSERT INTO rama VALUES (3600, 'Captación, tratamiento y suministro de agua', 1);
INSERT INTO rama VALUES (3700, 'Alcantarillado', 1);
INSERT INTO rama VALUES (3800, 'Recolección, tratamiento y eliminación de desechos, recuperación de materiales', 1);
INSERT INTO rama VALUES (3900, 'Actividades de saneamiento y otros servicios de gestión de desechos', 1);
INSERT INTO rama VALUES (4000, 'Construcción', 1);
INSERT INTO rama VALUES (4501, 'Venta de vehículos automotores, excepto motocicletas', 1);
INSERT INTO rama VALUES (4502, 'Mantenimiento y reparación de vehículos automotores, excepto motocicletas', 1);
INSERT INTO rama VALUES (4503, 'Venta de partes, piezas y accesorios de vehículos automotores, excepto motocicletas', 1);
INSERT INTO rama VALUES (4504, 'Venta, mantenimiento y reparación de motocicletas y de sus piezas y accesorios', 1);
INSERT INTO rama VALUES (4801, 'Comercio de intermediación', 1);
INSERT INTO rama VALUES (4802, 'Comercio de materias primas agropecuarias', 1);
INSERT INTO rama VALUES (4803, 'Comercio de alimentos, bebidas y tabaco', 1);
INSERT INTO rama VALUES (4804, 'Comercio de textiles y avíos, mercería, prendas de vestir, calzado, marroquinería y artículos similares', 1);
INSERT INTO rama VALUES (4805, 'Comercio de materiales de construcción, artículos de ferretería, plomería, pinturería, espejos y artículos para revestimiento', 1);
INSERT INTO rama VALUES (4806, 'Comercio de combustibles para vehículos', 1);
INSERT INTO rama VALUES (4807, 'Comercio de mercaderías n.c.p. incluso mercaderías usadas', 1);
INSERT INTO rama VALUES (4808, 'Tiendas no especializadas con predominancia de alimentos y bebidas', 1);
INSERT INTO rama VALUES (4809, 'Tiendas no especializadas sin predominancia de alimentos y bebidas', 1);
INSERT INTO rama VALUES (4810, 'Venta al por menor en puestos móviles y no realizadas en tiendas n.c.p.', 1);
INSERT INTO rama VALUES (4811, 'Venta al por menor por correo, televisión, internet y otros medios de comunicación', 1);
INSERT INTO rama VALUES (4899, 'Comercio n.c.p.', 1);
INSERT INTO rama VALUES (4901, 'Transporte ferroviario', 1);
INSERT INTO rama VALUES (4902, 'Transporte por metro', 1);
INSERT INTO rama VALUES (4903, 'Transporte automotor de pasajeros', 1);
INSERT INTO rama VALUES (4904, 'Transporte automotor de cargas', 1);
INSERT INTO rama VALUES (4905, 'Transporte por tuberías', 1);
INSERT INTO rama VALUES (4909, 'Transporte terrestre n.c.p.', 1);
INSERT INTO rama VALUES (5000, 'Transporte por vía acuática', 1);
INSERT INTO rama VALUES (5100, 'Transporte aéreo', 1);
INSERT INTO rama VALUES (5201, 'Depósito y almacenamiento', 1);
INSERT INTO rama VALUES (5202, 'Servicios auxiliares al transporte', 1);
INSERT INTO rama VALUES (5300, 'Correo y servicio de mensajería', 1);
INSERT INTO rama VALUES (5500, 'Servicios de alojamiento en hoteles, campamentos y otros tipos de hospedaje temporal', 1);
INSERT INTO rama VALUES (5601, 'Servicios de expendio de comidas y bebidas, excepto por vendedores ambulantes', 1);
INSERT INTO rama VALUES (5602, 'Servicios de expendio de comidas y bebidas por vendedores ambulantes', 1);
INSERT INTO rama VALUES (5800, 'Edición de libros, periódicos y otras publicaciones, incluso integrada a la impresión', 1);
INSERT INTO rama VALUES (5900, 'Actividades cinematográficas, producción de vídeos y programas de televisión, grabación sonora y edición de música', 1);
INSERT INTO rama VALUES (6000, 'Actividades de programación y difusión de radio y televisión', 1);
INSERT INTO rama VALUES (6100, 'Telecomunicaciones', 1);
INSERT INTO rama VALUES (6200, 'Actividades de programación y consultoría informáticas y otras actividades conexas', 1);
INSERT INTO rama VALUES (6300, 'Actividades de servicios de información', 1);
INSERT INTO rama VALUES (6400, 'Intermediación financiera y otros servicios financieros, excepto los de seguros y administración de fondos de jubilaciones y pensiones', 1);
INSERT INTO rama VALUES (6500, 'Seguros, reaseguros y fondos de pensiones, excepto los planes de seguridad social de afiliación obligatoria', 1);
INSERT INTO rama VALUES (6600, 'Actividades auxiliares a los servicios financieros y a los seguros', 1);
INSERT INTO rama VALUES (6800, 'Actividades inmobiliarias', 1);
INSERT INTO rama VALUES (6900, 'Actividades jurídicas y de contabilidad', 1);
INSERT INTO rama VALUES (7000, 'Actividades de servicios de consultoría en gestión empresarial', 1);
INSERT INTO rama VALUES (7100, 'Servicios de arquitectura e ingeniería, ensayos y análisis técnicos', 1);
INSERT INTO rama VALUES (7200, 'Investigación y desarrollo', 1);
INSERT INTO rama VALUES (7301, 'Actividades publicitarias', 1);
INSERT INTO rama VALUES (7302, 'Investigación de mercados y encuestas de opinión pública', 1);
INSERT INTO rama VALUES (7400, 'Otras actividades profesionales, científicas y técnicas', 1);
INSERT INTO rama VALUES (7500, 'Actividades veterinarias', 1);
INSERT INTO rama VALUES (7701, 'Alquiler de efectos personales y domésticos', 1);
INSERT INTO rama VALUES (7702, 'Alquiler de vehículos de transporte, de maquinaria y equipo sin operador y gestión de activos intangibles no financieros', 1);
INSERT INTO rama VALUES (7800, 'Actividades relacionadas con el suministro de empleo', 1);
INSERT INTO rama VALUES (7900, 'Agencias de viajes, operadores turísticos y actividades conexas', 1);
INSERT INTO rama VALUES (8000, 'Actividades de investigación y seguridad', 1);
INSERT INTO rama VALUES (8101, 'Servicios de apoyo a edificios y actividades de limpieza en general', 1);
INSERT INTO rama VALUES (8102, 'Servicios de paisajismo y jardinería', 1);
INSERT INTO rama VALUES (8200, 'Actividades administrativas de oficinas y otras actividades auxiliares de las empresas', 1);
INSERT INTO rama VALUES (8401, 'Servicios de la administración pública y prestación pública de servicios a la comunidad', 1);
INSERT INTO rama VALUES (8402, 'Servicios de seguridad publica (fuerzas armadas, policias, etc)', 1);
INSERT INTO rama VALUES (8403, 'Servicios de la seguridad social obligatoria', 1);
INSERT INTO rama VALUES (8501, 'Enseñanza inicial y primaria, secundaria y superior', 1);
INSERT INTO rama VALUES (8502, 'Otros tipos de enseñanza n.c.p., y servicios de apoyo', 1);
INSERT INTO rama VALUES (8600, 'Actividades de atención a la salud humana', 1);
INSERT INTO rama VALUES (8700, 'Asistencia social relacionada con la atención a la salud', 1);
INSERT INTO rama VALUES (8800, 'Servicios sociales sin alojamiento', 1);
INSERT INTO rama VALUES (9000, 'Actividades artísticas y de espectáculos', 1);
INSERT INTO rama VALUES (9100, 'Actividades de bibliotecas, archivos, museos y otras actividades culturales', 1);
INSERT INTO rama VALUES (9200, 'Actividades de juegos de azar y apuestas', 1);
INSERT INTO rama VALUES (9301, 'Actividades para la práctica deportiva', 1);
INSERT INTO rama VALUES (9302, 'Actividades de entretenimiento n.c.p.', 1);
INSERT INTO rama VALUES (9401, 'Actividades de organizaciones empresariales, profesionales y de empleadores', 1);
INSERT INTO rama VALUES (9402, 'Actividades de sindicatos', 1);
INSERT INTO rama VALUES (9409, 'Actividades de asociaciones n.c.p.', 1);
INSERT INTO rama VALUES (9501, 'Reparación de equipos informáticos', 1);
INSERT INTO rama VALUES (9502, 'Reparación de equipos de comunicación', 1);
INSERT INTO rama VALUES (9503, 'Reparación de efectos de uso personal y doméstico', 1);
INSERT INTO rama VALUES (9601, 'Lavado y limpieza de artículos de tela, cuero y o de piel incluso limpieza en seco', 1);
INSERT INTO rama VALUES (9602, 'Servicios de peluquería y tratamientos de belleza', 1);
INSERT INTO rama VALUES (9603, 'Pompas fúnebres y servicios conexos', 1);
INSERT INTO rama VALUES (9609, 'Servicios personales n.c.p.', 1);
INSERT INTO rama VALUES (9700, 'Actividades de los hogares como empleadores de personal doméstico', 1);
INSERT INTO rama VALUES (9900, 'Actividades de organizaciones y organismos extraterritoriales', 1);
INSERT INTO rama VALUES (9999, 'No sabe / No responde ó Actividad no especificada claramente', 1);

--datos de ocupacion
INSERT INTO ocupacion VALUES (1, 'Funcionarios del poder ejecutivo nacional, provincial, municipal y/o departamental- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (1001, 'Funcionarios del poder legislativo nacional, provincial/ municipal y/o departamental- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (2001, 'Funcionarios del poder judicialfederal/ nacional/ provincial/municipal y/o departamental- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (3001, 'Directivos de organismos, empresas e instituciones estatales - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (4001, 'Directivos de instituciones sociales (comunales, políticas, gremiales, religiosas, derechos humanos, medio ambiente y otras instituciones de bien público) - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (5001, 'Directivos de pequeñas y microempresas (patrones de 1 a 5 personas) - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (5002, 'Directivos de pequeñas y microempresas (patrones de 1 a 5 personas) - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (6001, 'Directivos de medianas empresas privadas productora de bienes y/o servicios (establecimientos de 6 a 40 personas) - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (7001, 'Directivos de grandes empresas privadas productoras de bienes y/o servicios (establecimientos de más de 41 personas) - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (10191, 'Cuenta propia de la gestión administrativa, planificación y control de gestión- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (10192, 'Cuenta propia de la gestión administrativa, planificación y control de gestión- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (10193, 'Cuenta propia de la gestión administrativa, planificación y control de gestión- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (10199, 'Cuenta propia de la gestión administrativa, planificación y control de gestión- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (10201, 'Jefes de gestión administrativa, de planificación, y control de gestión - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (10202, 'Jefes de gestión administrativa, de planificación, y control de gestión - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (10203, 'Jefes de gestión administrativa, de planificación, y control de gestión - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (10209, 'Jefes de gestión administrativa, de planificación, y control de gestión - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (10391, 'Trabajadores de la gestión administrativa, de planificación y control degestión Calificación profesional', 1);
INSERT INTO ocupacion VALUES (10392, 'Trabajadores de la gestión administrativa, de planificación y control degestión Calificación técnica', 1);
INSERT INTO ocupacion VALUES (10393, 'de la gestión administrativa, de planificación y control degestiónCalificación operativa', 1);
INSERT INTO ocupacion VALUES (10394, 'de la gestión administrativa, de planificación y control degestión- No calificados', 1);
INSERT INTO ocupacion VALUES (10399, 'de la gestión administrativa, de planificación y control degestión - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (11191, 'Cuenta propia de la gestión jurídico-legal - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (11192, 'Cuenta propia de la gestión jurídico-legal - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (11193, 'Cuenta propia de la gestión jurídico-legal - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (11199, 'Cuenta propia de maquinarias de la gestión jurídico-legal - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (11201, 'Jefes de la gestión jurídico-legal - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (11202, 'Jefes de la gestión jurídico-legal- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (11203, 'Jefes de la gestión jurídico-legal- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (11209, 'Jefes de la gestión jurídico-legal- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (11391, 'Trabajadores de la gestión jurídico-legal - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (11392, 'Trabajadores de la gestión jurídico-legal - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (11393, 'Trabajadores de la gestión jurídico-legal - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (11394, 'Trabajadores de la gestión jurídico-legal - No calificados', 1);
INSERT INTO ocupacion VALUES (11399, 'Trabajadores de la gestión jurídico-legal - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (20191, 'Cuenta propia de la gestión presupuestaria, contable y financiera- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (20192, 'Cuenta propia de la gestión presupuestaria, contable y financiera- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (20193, 'Cuenta propia de la gestión presupuestaria, contable y financiera- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (20199, 'Cuenta propia de la gestión presupuestaria, contable y financiera- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (20201, 'Jefes de gestión presupuestaria, contable y financiera- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (20202, 'Jefes de gestión presupuestaria, contable y financiera - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (20203, 'Jefes de gestión presupuestaria, contable y financiera - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (20209, 'Jefes de gestión presupuestaria, contable y financiera - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (20391, 'Trabajadores de la gestión presupuestaria, contable y financiera - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (20392, 'Trabajadores de la gestión presupuestaria, contable y financiera- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (20393, 'Trabajadores de la gestión presupuestaria, contable y financiera- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (20394, 'Trabajadores de la gestión presupuestaria, contable y financiera- No calificados', 1);
INSERT INTO ocupacion VALUES (20399, 'Trabajadores de la gestión presupuestaria, contable y financiera- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (30191, 'Cuenta propia de la comercialización directa (tradicional y telefónicos)- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (30192, 'Cuenta propia de la comercialización directa (tradicional y telefónicos)- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (30193, 'Cuenta propia de la comercialización directa (tradicional y telefónicos)- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (30199, 'Cuenta propia de la comercialización directa (tradicional y telefónicos)- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (30201, 'Jefes de la comercialización directa (tradicional y telefónicos)- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (30202, 'Jefes de la comercialización directa (tradicional y telefónicos)- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (30203, 'Jefes de la comercialización directa (tradicional y telefónicos)- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (30209, 'Jefes de la comercialización directa (tradicional y telefónicos)- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (30391, 'Vendedores y trabajadores de la comercialización directa (tradicional y telefónicos)- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (30392, 'Vendedores y trabajadores de la comercialización directa (tradicional y telefónicos)- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (30393, 'Vendedores y trabajadores de la comercialización directa (tradicional y telefónicos)- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (30394, 'Vendedores y trabajadores de la comercialización directa (tradicional y telefónicos) - No calificados', 1);
INSERT INTO ocupacion VALUES (30399, 'Vendedores y trabajadores de la comercialización directa (tradicional y telefónicos) - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (31191, 'Cuenta propia viajantes, corredores comerciales y vendedores domiciliarios y promotores- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (31192, 'Cuenta propia viajantes, corredores comerciales y vendedores domiciliarios y promotores- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (31193, 'Cuenta propia viajantes, corredores comerciales y vendedores domiciliarios y promotores- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (31199, 'Cuenta propia viajantes, corredores comerciales y vendedores domiciliarios y promotores- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (31201, 'Jefes de viajantes, corredores comerciales y vendedores domiciliarios- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (31202, 'Jefes de viajantes, corredores comerciales y vendedores domiciliarios- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (31203, 'Jefes de viajantes, corredores comerciales y vendedores domiciliarios- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (31209, 'Jefes de viajantes, corredores comerciales y vendedores domiciliarios- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (31391, 'Trabajadores viajantes, corredores comerciales y vendedores domiciliarios- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (31392, 'Trabajadores viajantes, corredores comerciales y vendedores domiciliarios- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (31393, 'Trabajadores viajantes, corredores comerciales y vendedores domiciliarios- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (31394, 'Trabajadores viajantes, corredores comerciales y vendedores domiciliarios- No calificados', 1);
INSERT INTO ocupacion VALUES (31399, 'Trabajadores viajantes, corredores comerciales y vendedores domiciliarios- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (32191, 'Cuenta propia de otras ocupaciones de la comercialización indirecta- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (32192, 'Cuenta propia de otras ocupaciones de la comercialización indirecta- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (32193, 'Cuenta propia de otras ocupaciones de la comercialización indirecta- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (32199, 'Cuenta propia de otras ocupaciones de la comercialización indirecta- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (32201, 'Jefes de otras ocupaciones de la comercialización- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (32202, 'Jefes de otras ocupaciones de la comercialización- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (32203, 'Jefes de otras ocupaciones de la comercialización- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (32209, 'Jefes de otras ocupaciones de la comercialización- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (32391, 'Trabajadores de otras ocupaciones de la comercialización- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (32392, 'Trabajadores de otras ocupaciones de la comercialización- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (32393, 'Trabajadores de otras ocupaciones de la comercialización- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (32394, 'Trabajadores de otras ocupaciones de la comercialización- No calificados', 1);
INSERT INTO ocupacion VALUES (32399, 'Trabajadores de otras ocupaciones de la comercialización- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (33191, 'Cuenta propia vendedores ambulantes y callejeros- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (33192, 'Cuenta propia vendedores ambulantes y callejeros- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (33193, 'Cuenta propia vendedores ambulantes y callejeros- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (33194, 'Cuenta propia vendedores ambulantes y callejeros- No calificados', 1);
INSERT INTO ocupacion VALUES (33199, 'Cuenta propia vendedores ambulantes y callejeros- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (33201, 'Jefes de los vendedores ambulantes y callejeros- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (33202, 'Jefes de los vendedores ambulantes y callejeros- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (33203, 'Jefes de los vendedores ambulantes y callejeros- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (33209, 'Jefes de los vendedores ambulantes y callejeros- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (33391, 'Trabajadores vendedores ambulantes y callejeros- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (33392, 'Trabajadores vendedores ambulantes y callejeros- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (33393, 'Trabajadores vendedores ambulantes y callejeros- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (33394, 'Trabajadores vendedores ambulantes y callejeros - No calificados', 1);
INSERT INTO ocupacion VALUES (33399, 'Trabajadores vendedores ambulantes y callejeros- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (34191, 'Cuenta propia del Transporte- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (34193, 'Cuenta propia del Transporte- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (34194, 'Cuenta propia del Transporte- No calificados', 1);
INSERT INTO ocupacion VALUES (34199, 'Cuenta propia del Transporte- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (34201, 'Jefes de servicios de transporte- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (34202, 'Jefes de servicios de transporte- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (34203, 'Jefes de servicios de transporte- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (34209, 'Jefes de servicios de transporte- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (34391, 'Trabajadores del transporte - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (34392, 'Trabajadores del transporte - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (34393, 'Trabajadores del transporte - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (34394, 'Trabajadores del transporte - No calificados', 1);
INSERT INTO ocupacion VALUES (34399, 'Trabajadores del transporte - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (35191, 'Cuenta propia de las telecomunicaciones- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (35192, 'Cuenta propia de las telecomunicaciones- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (35193, 'Cuenta propia de las telecomunicaciones- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (35199, 'Cuenta propia de las telecomunicaciones- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (35201, 'Jefes de las telecomunicaciones- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (35202, 'Jefes de las telecomunicaciones- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (35203, 'Jefes de las telecomunicaciones- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (35209, 'Jefes de las telecomunicaciones- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (35391, 'Trabajadores de las telecomunicaciones- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (35392, 'Trabajadores de las telecomunicaciones Calificación técnica', 1);
INSERT INTO ocupacion VALUES (35393, 'Trabajadores de las telecomunicaciones Calificación operativa', 1);
INSERT INTO ocupacion VALUES (35394, 'Trabajadores de las telecomunicaciones- No calificados', 1);
INSERT INTO ocupacion VALUES (35399, 'Trabajadores de las telecomunicaciones Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (36191, 'Cuenta propia del almacenaje - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (36192, 'Cuenta propia del almacenaje - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (36193, 'Cuenta propia del almacenaje - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (36194, 'Cuenta propia del almacenaje - No calificados', 1);
INSERT INTO ocupacion VALUES (36199, 'Cuenta propia del almacenaje - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (36201, 'Jefes del almacenaje - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (36202, 'Jefes del almacenaje - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (36203, 'Jefes del almacenaje - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (36209, 'Jefes del almacenaje - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (36391, 'Trabajadores del almacenaje- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (36392, 'Trabajadores del almacenaje- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (36393, 'Trabajadores del almacenaje- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (36394, 'Trabajadores del almacenaje- No calificados', 1);
INSERT INTO ocupacion VALUES (36399, 'Trabajadores del almacenaje- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (40191, 'Cuenta propia de la salud y sanidad- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (40192, 'Cuenta propia de la salud y sanidad- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (40193, 'Cuenta propia de la salud y sanidad- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (40199, 'Cuenta propia de la salud y sanidad- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (40201, 'Jefes de la salud y sanidad - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (40202, 'Jefes de la salud y sanidad - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (40203, 'Jefes de la salud y sanidad - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (40209, 'Jefes de la salud y sanidad - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (40391, 'Trabajadores de salud y sanidad- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (40392, 'Trabajadores de salud y sanidad - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (40393, 'Trabajadores de salud y sanidad - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (40394, 'Trabajadores de salud y sanidad - No calificados', 1);
INSERT INTO ocupacion VALUES (40399, 'Trabajadores de salud y sanidad - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (41191, 'Cuenta propia de la educación- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (41192, 'Cuenta propia de la educación- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (41193, 'Cuenta propia de la educación- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (41199, 'Cuenta propia de la educación- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (41201, 'Jefes de la educación - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (41202, 'Jefes de la educación - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (41203, 'Jefes de la educación - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (41209, 'Jefes de la educación - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (41391, 'Trabajadores de la educación- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (41392, 'Trabajadores de la educación- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (41393, 'Trabajadores de la educación - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (41394, 'Trabajadores de la educación - No calificados', 1);
INSERT INTO ocupacion VALUES (41399, 'Trabajadores de la educación - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (42191, 'Cuenta propia de la investigacióncientífica y tecnológica- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (42192, 'Cuenta propia de la investigacióncientífica y tecnológica- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (42193, 'Cuenta propia de la investigación científica y tecnológica- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (42199, 'Cuenta propia de la investigación científica y tecnológica- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (42201, 'Jefes de la investigación científica y tecnológica- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (42202, 'Jefes de la investigación científica y tecnológica- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (42203, 'Jefes de la investigación científica y tecnológica- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (42209, 'Jefes de la investigación científica y tecnológica- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (42391, 'Trabajadores de la investigación científica y tecnológica- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (42392, 'Trabajadores de la investigación científica y tecnológica- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (42393, 'Trabajadores de la investigación científica y tecnológica- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (42394, 'Trabajadores de la investigación científica y tecnológica- No calificados', 1);
INSERT INTO ocupacion VALUES (42399, 'Trabajadores de la investigación científica y tecnológica- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (43191, 'Cuenta propia de la asesoría y consultoría- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (43192, 'Cuenta propia de la asesoría y consultoría- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (43193, 'Cuenta propia de la asesoría y consultoría- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (43199, 'Cuenta propia de la asesoría y consultoría- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (43201, 'Jefes de la asesoría y consultoría- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (43202, 'Jefes de la asesoría y consultoría- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (43203, 'Jefes de la asesoría y consultoría- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (43209, 'Jefes de la asesoría y consultoría- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (43391, 'Trabajadores de la asesoría y consultoría- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (43392, 'Trabajadores de la asesoría y consultoría- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (43393, 'Trabajadores de la asesoría y consultoría- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (43394, 'Trabajadores de la asesoría y consultoría- No calificado', 1);
INSERT INTO ocupacion VALUES (43399, 'Trabajadores de la asesoría y consultoría- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (44191, 'Cuenta propia de la prevención de siniestros(naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (44192, 'Cuenta propia de la prevención de siniestros(naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (44193, 'Cuenta propia de la prevención de siniestros(naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (44199, 'Cuenta propia de la prevención de siniestros(naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (44201, 'Jefes de la prevención de siniestros (naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (50202, 'Jefes del arte- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (50203, 'Jefes del arte- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (44202, 'Jefes de la prevención de siniestros (naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (44203, 'Jefes de la prevención de siniestros (naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (44209, 'Jefes de la prevención de siniestros (naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (44391, 'Trabajadores de prevención de siniestros(naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (44392, 'Trabajadores de prevención de siniestros(naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (44393, 'Trabajadores de prevención de siniestros(naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (44394, 'Trabajadores de prevención de siniestros(naturales, humanos, productivos) y atención del medio ambiente y ecología - No calificados', 1);
INSERT INTO ocupacion VALUES (44399, 'Trabajadores de prevención de siniestros(naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (45191, 'Cuenta propia de la comunicación de masas- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (45192, 'Cuenta propia de la comunicación de masas- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (45193, 'Cuenta propia de la comunicación de masas - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (45199, 'Cuenta propia de la comunicación de masas - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (45201, 'Jefes de la comunicación de masas- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (45202, 'Jefes de la comunicación de masas- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (45203, 'Jefes de la comunicación de masas- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (45209, 'Jefes de la comunicación de masas- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (45391, 'Trabajadores de la comunicación de masas- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (45392, 'Trabajadores de la comunicación de masas- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (45393, 'Trabajadores de la comunicación de masas- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (45394, 'Trabajadores de la comunicación de masas- No calificado', 1);
INSERT INTO ocupacion VALUES (45399, 'Trabajadores de la comunicación de masas- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (46191, 'Cuenta propia de los servicios sociales, comunales, políticos, gremiales y religiosos- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (46192, 'Cuenta propia de los servicios sociales, comunales, políticos, gremiales y religiosos- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (46193, 'Cuenta propia de los servicios sociales, comunales, políticos, gremiales y religiosos- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (46199, 'Cuenta propia de los servicios sociales, comunales, políticos, gremiales y religiosos- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (46201, 'Jefes de los servicios sociales, comunales, políticos, gremiales y religiosos- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (46202, 'Jefes de los servicios sociales, comunales, políticos, gremiales y religiosos - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (46203, 'Jefes de los servicios sociales, comunales, políticos, gremiales y religiosos - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (46209, 'Jefes de los servicios sociales, comunales, políticos, gremiales y religiosos - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (46391, 'Trabajadores de servicios sociales, comunales, políticos, gremiales y religiosos- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (46392, 'Trabajadores de servicios sociales, comunales, políticos, gremiales y religiosos- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (46393, 'Trabajadores de servicios sociales, comunales, políticos, gremiales y religiosos- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (46394, 'Trabajadores de servicios sociales, comunales, políticos, gremiales y religiosos- No calificado', 1);
INSERT INTO ocupacion VALUES (46399, 'Trabajadores de servicios sociales, comunales, políticos, gremiales y religiosos- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (47191, 'Cuenta propia de los servicios de vigilancia y seguridad civil- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (47192, 'Cuenta propia de los servicios de vigilancia y seguridad civil- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (47193, 'Cuenta propia de los servicios de vigilancia y seguridad civil- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (47199, 'Cuenta propia de los servicios de vigilancia y seguridad civil- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (47201, 'Jefes de los servicios de vigilancia y seguridad civil- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (47202, 'Jefes de los servicios de vigilancia y seguridad civil- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (47203, 'Jefes de los servicios de vigilancia y seguridad civil- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (47209, 'Jefes de los servicios de vigilancia y seguridad civil- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (47391, 'Trabajadores de los servicios de vigilancia y seguridad civil - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (47392, 'Trabajadores de los servicios de vigilancia y seguridad civil - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (47393, 'Trabajadores de los servicios de vigilancia y seguridad civil- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (47394, 'Trabajadores de los servicios de vigilancia y seguridad civil- No calificados', 1);
INSERT INTO ocupacion VALUES (47399, 'Trabajadores de los servicios de vigilancia y seguridad civil- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (48391, 'Trabajadores de los servicios policiales- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (48392, 'Trabajadores de los servicios policiales- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (48393, 'Trabajadores de los servicios policiales- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (48394, 'Trabajadores de los servicios policiales- No calificados', 1);
INSERT INTO ocupacion VALUES (48399, 'Trabajadores de los servicios policiales- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (49391, 'Trabajadores de las FFAA, Gendarmería y Prefectura- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (49392, 'Trabajadores de las FFAA, Gendarmería y Prefectura- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (49393, 'Trabajadores de las FFAA, Gendarmería y Prefectura Calificación operativa', 1);
INSERT INTO ocupacion VALUES (49394, 'Trabajadores de las FFAA, Gendarmería y Prefectura- No calificados', 1);
INSERT INTO ocupacion VALUES (49399, 'Trabajadores de las FFAA, Gendarmería y Prefectura Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (50191, 'Cuenta propia del arte- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (50192, 'Cuenta propia del arte - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (50193, 'Cuenta propia del arte - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (50199, 'Cuenta propia del arte - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (50201, 'Jefes del arte- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (50209, 'Jefes del arte- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (50391, 'Trabajadores del arte - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (50392, 'Trabajadores del arte - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (50393, 'Trabajadores del arte- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (50394, 'Trabajadores del arte - No calificado', 1);
INSERT INTO ocupacion VALUES (50399, 'Trabajadores del arte- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (51191, 'Cuenta propia del deporte- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (51192, 'Cuenta propia del deporte - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (51193, 'Cuenta propia del deporte - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (51199, 'Cuenta propia del deporte - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (51201, 'Jefes del deporte- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (51202, 'Jefes del deporte- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (51203, 'Jefes del deporte- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (51209, 'Jefes del deporte- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (51391, 'Trabajadores del deporte - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (51392, 'Trabajadores del deporte - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (51393, 'Trabajadores del deporte - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (51394, 'Trabajadores del deporte - No calificados', 1);
INSERT INTO ocupacion VALUES (51399, 'Trabajadores del deporte - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (52191, 'Cuenta propia de la recreación - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (52192, 'Cuenta propia de la recreación - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (52193, 'Cuenta propia de la recreación - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (52199, 'Cuenta propia de la recreación - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (52201, 'Jefes de la recreación - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (52202, 'Jefes de la recreación - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (52203, 'Jefes de la recreación - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (52209, 'Jefes de la recreación - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (52391, 'Trabajadores de la recreación- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (52392, 'Trabajadores de la recreación- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (52393, 'Trabajadores de la recreación- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (52394, 'Trabajadores de la recreación- No calificados', 1);
INSERT INTO ocupacion VALUES (52399, 'Trabajadores de la recreación- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (53191, 'Cuenta propia de servicios gastronómicos- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (53192, 'Cuenta propia de servicios gastronómicos - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (53193, 'Cuenta propia de servicios gastronómicos- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (53199, 'Cuenta propia de servicios gastronómicos- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (53201, 'Jefes de servicios gastrnómicos- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (53202, 'Jefes de servicios gastrnómicos- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (53203, 'Jefes de servicios gastrnómicos- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (53209, 'Jefes de servicios gastrnómicos- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (53391, 'Trabajadores de servicios gastrnómicos- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (53392, 'Trabajadores de servicios gastrnómicos- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (53393, 'Trabajadores de servicios gastrnómicos- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (53394, 'Trabajadores de servicios gastrnómicos- No calificados', 1);
INSERT INTO ocupacion VALUES (53399, 'Trabajadores de servicios gastrnómicos- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (54191, 'Cuenta propia de los servicios de alojamiento y turismo- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (54192, 'Cuenta propia de los servicios de alojamiento y turismo- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (54193, 'Cuenta propia de los servicios de alojamiento y turismo- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (54199, 'Cuenta propia de los servicios de alojamiento y turismo- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (54201, 'Jefes del alojamiento y turismo- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (54202, 'Jefes del alojamiento y turismo - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (54203, 'Jefes del alojamiento y turismo - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (54209, 'Jefes del alojamiento y turismo - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (54391, 'del alojamiento y turismo- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (54392, 'del alojamiento y turismo- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (54393, 'del alojamiento y turismo- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (54394, 'del alojamiento y turismo- No calificados', 1);
INSERT INTO ocupacion VALUES (54399, 'del alojamiento y turismo- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (55193, 'Cuenta propia sin operaión de maquinarias de los servicios domésticos - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (55203, 'Jefes de los servicios domésticos - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (55393, 'Trabajadores del servicio doméstico - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (55394, 'Trabajadores del servicio doméstico - No calificados', 1);
INSERT INTO ocupacion VALUES (55399, 'Trabajadores del servicio doméstico - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (56193, 'Cuenta propia de los servicios de limpieza no doméstica- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (56202, 'Jefes de los servicios de limpieza no doméstica- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (56203, 'Jefes de los servicios de limpieza no doméstica- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (56209, 'Jefes de los servicios de limpieza no doméstica- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (56393, 'Trabajadores de servicios de limpieza no domésticos Calificación operativa', 1);
INSERT INTO ocupacion VALUES (56394, 'Trabajadores de servicios de limpieza no domésticos - No calificados', 1);
INSERT INTO ocupacion VALUES (56399, 'Trabajadores de servicios de limpieza no domésticos Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (57191, 'Cuenta propia del cuidado y la atenciónde las personas - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (57192, 'Cuenta propia del cuidado y la atenciónde las personas- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (57193, 'Cuenta propia del cuidado y la atenciónde las personas - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (57199, 'Cuenta propia del cuidado y la atenciónde las personas - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (57201, 'Jefes de los servicios del cuidado y la atención de las personas- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (57202, 'Jefes de los servicios del cuidado y la atención de las personas- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (57203, 'Jefes de los servicios del cuidado y la atención de las personas- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (57209, 'Jefes de los servicios del cuidado y la atención de las personas- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (57391, 'Trabajadores del cuidado y la atención de personas- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (57392, 'Trabajadores del cuidado y la atención de personas- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (57393, 'Trabajadores del cuidado y la atención de personas- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (57394, 'Trabajadores del cuidado y la atención de personas- No calificados', 1);
INSERT INTO ocupacion VALUES (57399, 'Trabajadores del cuidado y la atención de personas- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (58191, 'Cuenta propia de otras ocupaciones de los servicios sociales varios- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (58192, 'Cuenta propia de otras ocupaciones de los servicios sociales varios- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (58193, 'Cuenta propia de otras ocupaciones de los servicios sociales varios- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (58199, 'Cuenta propia de otras ocupaciones de los servicios sociales varios- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (58201, 'Jefes de otras ocupaciones de los servicios sociales varios - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (58202, 'Jefes de otras ocupaciones de los servicios sociales varios - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (58203, 'Jefes de otras ocupaciones de los servicios sociales varios - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (58209, 'Jefes de otras ocupaciones de los servicios sociales varios - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (58391, 'Trabajadores de otros servicios- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (58392, 'Trabajadores de otros servicios - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (58393, 'Trabajadores de otros servicios - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (58394, 'Trabajadores de otros servicios - No calificados', 1);
INSERT INTO ocupacion VALUES (58399, 'Trabajadores de otros servicios - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (60191, 'Cuenta propia de la producción agrícola- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (60192, 'Cuenta propia de la producción agrícola- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (60193, 'Cuenta propia de la producción agrícola- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (60199, 'Cuenta propia de la producción agrícola- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (60201, 'Jefes de la producción agrícola- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (60202, 'Jefes de la producción agrícola- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (60203, 'Jefes de la producción agrícola- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (60209, 'Jefes de la producción agrícola- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (60391, 'Trabajadores de la producción agrícola- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (60392, 'Trabajadores de la producción agrícola- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (60393, 'Trabajadores de la producción agrícola- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (60394, 'Trabajadores de la producción agrícola- No calificada', 1);
INSERT INTO ocupacion VALUES (60399, 'Trabajadores de la producción agrícola- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (61191, 'Cuenta propia de la producción ganadera- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (61192, 'Cuenta propia de la producción ganadera- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (61193, 'Cuenta propia de la producción ganadera- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (61199, 'Cuenta propia de la producción ganadera- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (61201, 'Jefes de la producción ganadera- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (61202, 'Jefes de la producción ganadera- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (61203, 'Jefes de la producción ganadera- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (61209, 'Jefes de la producción ganadera- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (61391, 'Trabajadores de la producción ganadera- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (61392, 'Trabajadores de la producción ganadera- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (61393, 'Trabajadores de la producción ganadera- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (61394, 'Trabajadores de la producción ganadera - No calificados', 1);
INSERT INTO ocupacion VALUES (61399, 'Trabajadores de la producción ganadera- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (62191, 'Cuenta propia de la producción forestal- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (62192, 'Cuenta propia de la producción forestal- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (62193, 'Cuenta propia de la producción forestal- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (62199, 'Cuenta propia de la producción forestal- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (62201, 'Jefes de la producción forestal- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (62202, 'Jefes de la producción forestal- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (62203, 'Jefes de la producción forestal- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (62209, 'Jefes de la producción forestal- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (62391, 'Trabajadores de la producción forestal- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (62392, 'Trabajadores de la producción forestal- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (62393, 'Trabajadores de la producción forestal- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (62394, 'Trabajadores de la producción forestal- No calificados', 1);
INSERT INTO ocupacion VALUES (62399, 'Trabajadores de la producción forestal- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (63191, 'Cuenta propia de la producción apicolaavicola yde otras especies menores- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (63192, 'Cuenta propia de la producción apicolaavicola yde otras especies menores- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (63193, 'Cuenta propia de la producción apicolaavicola yde otras especies menores- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (63199, 'Cuenta propia de la producción apicolaavicola yde otras especies menores- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (63201, 'Jefes de la producción apicolaavicola y de otras especies menores- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (63202, 'Jefes de la producción apicolaavicola y de otras especies menores- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (63203, 'Jefes de la producción apicolaavicola y de otras especies menores- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (63209, 'Jefes de la producción apicolaavicola y de otras especies menores- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (63391, 'Trabajadores de la producción apicolaavicola y de otras especies menores- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (63392, 'Trabajadores de la producción apicolaavicola y de otras especies menores- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (63393, 'Trabajadores de la producción apicolaavicola y de otras especies menores- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (63394, 'Trabajadores de la producción apicolaavicola y de otras especies menores - No calificados', 1);
INSERT INTO ocupacion VALUES (63399, 'Trabajadores de la producción apicolaavicola y de otras especies menores- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (64191, 'Cuenta propia de la producción pesquera- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (64192, 'Cuenta propia de la producción pesquera- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (64193, 'Cuenta propia de la producción pesquera- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (64199, 'Cuenta propia de la producción pesquera- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (64201, 'Jefes de la producción pesquera- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (64202, 'Jefes de la producción pesquera- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (64203, 'Jefes de la producción pesquera- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (64209, 'Jefes de la producción pesquera- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (64391, 'Trabajadores de la producción pesquera- Calificaciónprofesional', 1);
INSERT INTO ocupacion VALUES (64392, 'Trabajadores de la producción pesquera- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (64393, 'Trabajadores de la producción pesquera- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (64394, 'Trabajadores de la producción pesquera - No calificados', 1);
INSERT INTO ocupacion VALUES (64399, 'Trabajadores de la producción pesquera- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (65191, 'Cuenta propia de la caza- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (65192, 'Cuenta propia de la caza- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (65193, 'Cuenta propia de la caza- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (65199, 'Cuenta propia de la caza- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (65201, 'Jefes de la caza- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (65202, 'Jefes de la caza- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (65203, 'Jefes de la caza- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (65209, 'Jefes de la caza- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (65391, 'Trabajadores de la caza- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (65392, 'Trabajadores de la caza- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (65393, 'Trabajadores de la caza- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (65394, 'Trabajadores de la caza - No calificados', 1);
INSERT INTO ocupacion VALUES (65399, 'Trabajadores de la caza- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (70191, 'Cuenta propia de la producción extractiva- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (70192, 'Cuenta propia de la producción extractiva- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (70193, 'Cuenta propia de la producción extractiva- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (70199, 'Cuenta propia de la producción extractiva- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (70201, 'Jefes de la producción extractiva- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (70202, 'Jefes de la producción extractiva- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (70203, 'Jefes de la producción extractiva- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (70209, 'Jefes de la producción extractiva- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (70391, 'Trabajadores de la producción extractivaCalificación profesional', 1);
INSERT INTO ocupacion VALUES (70392, 'Trabajadores de la producción extractivaCalificación técnica', 1);
INSERT INTO ocupacion VALUES (70393, 'Trabajadores de la producción extractiva- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (70394, 'Trabajadores de la producción extractiva- No calificados', 1);
INSERT INTO ocupacion VALUES (70399, 'Trabajadores de la producción extractiva- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (71191, 'Cuenta propia de la producción de energ¡a, agua y gas- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (71192, 'Cuenta propia de la producción de energ¡a, agua y gas- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (71193, 'Cuenta propia de la producción de energ¡a, agua y gas - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (71199, 'Cuenta propia de la producción de energ¡a, agua y gas- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (71201, 'Jefes de la producción de energia, agua y gas - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (71202, 'Jefes de la producción de energia, agua y gas - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (71203, 'Jefes de la producción de energia, agua y gas - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (71209, 'Jefes de la producción de energia, agua y gas - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (71391, 'Trabajadores de la producción de energia, agua y gas - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (71392, 'Trabajadores de la producción de energia, agua y gas - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (71393, 'Trabajadores de la producción de energia, agua y gas - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (71394, 'Trabajadores de la producción de energia, agua y gas - No calificados', 1);
INSERT INTO ocupacion VALUES (71399, 'Trabajadores de la producción de energia, agua y gas - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (72191, 'Cuenta propia de la construcción edilicia y de obras de infraestructura y de redes de distribución de energia, agua potable, gas y telefonía - Calificación', 1);
INSERT INTO ocupacion VALUES (72192, 'Cuenta propia de la construcción edilicia y de obras de infraestructura y de redes de distribución de energia, agua potable, gas y telefonía - Calificación', 1);
INSERT INTO ocupacion VALUES (72193, 'Cuenta propia de la construcción edilicia y de obras de infraestructura y de redes de distribución de energia, agua potable, gas y telefonía - Calificación', 1);
INSERT INTO ocupacion VALUES (72199, 'Cuenta propia de la construcción edilicia y de obras de infraestructura y de redes de distribución de energia, agua potable, gas y telefonía - Calificación', 1);
INSERT INTO ocupacion VALUES (72201, 'Jefes de la construcción edilicia y de obras de infraestructura y de redes de distribución de energ¡a, agua potable, gas y telefonía Calificación profesional', 1);
INSERT INTO ocupacion VALUES (72202, 'Jefes de la construcción edilicia y de obras de infraestructura y de redes de distribución de energ¡a, agua potable, gas y telefonía Calificación técnica', 1);
INSERT INTO ocupacion VALUES (72203, 'Jefes de la construcción edilicia y de obras de infraestructura y de redes de distribución de energ¡a, agua potable, gas y telefonía- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (72209, 'Jefes de la construcción edilicia y de obras de infraestructura y de redes de distribución de energ¡a, agua potable, gas y telefonía- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (72391, 'Trabajadores de la construcción edilicia, de obras de infraestructura y de redes de distribución de energ¡a, agua potable, gas y telefonía- Calificación pro', 1);
INSERT INTO ocupacion VALUES (72392, 'Trabajadores de la construcción edilicia, de obras de infraestructura y de redes de distribución de energ¡a, agua potable, gas y telefonía- Calificación téc', 1);
INSERT INTO ocupacion VALUES (72393, 'Trabajadores de la construcción edilicia, de obras de infraestructura y de redes de distribución de energ¡a, agua potable, gas y telefonía- Calificación ope', 1);
INSERT INTO ocupacion VALUES (72394, 'Trabajadores de la construcción edilicia, de obras de infraestructura y de redes de distribución de energ¡a, agua potable, gas y telefonía- No calificados', 1);
INSERT INTO ocupacion VALUES (91392, 'Trabajadores del desarrollo tecnológico Calificación técnica', 1);
INSERT INTO ocupacion VALUES (72399, 'Trabajadores de la construcción edilicia, de obras de infraestructura y de redes de distribución de energ¡a, agua potable, gas y telefonía- Calificación ign', 1);
INSERT INTO ocupacion VALUES (80191, 'Cuenta propia de la producción Industrial y artesanal - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (80192, 'Cuenta propia de la producción Industrial y artesanal- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (80193, 'Cuenta propia de la producción Industrial y artesanal - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (80199, 'Cuenta propia de la producción Industrial y artesanal - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (80201, 'Jefes de la producción industrial y artesanal- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (80202, 'Jefes de la producción industrial y artesanal- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (80203, 'Jefes de la producción industrial y artesanal- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (80209, 'Jefes de la producción industrial y artesanal- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (80391, 'Trabajadores de la producción', 1);
INSERT INTO ocupacion VALUES (80392, 'Trabajadores de la producción industrial y artesanal- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (80393, 'Trabajadores de la producción industrial y artesanal- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (80394, 'Trabajadores de la producción industrial y artesanal- No calificados', 1);
INSERT INTO ocupacion VALUES (80399, 'Trabajadores de la producción industrial y artesanal- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (81191, 'Cuenta propia de la producción de software - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (81192, 'Cuenta propia de la producción de software - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (81193, 'Cuenta propia de la producción de software - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (81199, 'Cuenta propia de la producción de software - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (81201, 'Jefes de la producción de software- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (81202, 'Jefes de la producción de software- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (81203, 'Jefes de la producción de software- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (81209, 'Jefes de la producción de software- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (81391, 'Operadores de sistemas y/o equipos informatizados de la producción de software- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (81392, 'Operadores de sistemas y/o equipos informatizados de la producción de software- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (81393, 'Operadores de sistemas y/o equipos informatizados de la producción de software- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (81394, 'Operadores de sistemas y/o equipos informatizados de la producción de software- No calificado', 1);
INSERT INTO ocupacion VALUES (81399, 'Operadores de sistemas y/o equipos informatizados de la producción de software- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (82191, 'Cuenta propia de la reparación de bienes de consumo - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (82192, 'Cuenta propia de la reparación de bienes de consumo - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (82193, 'Cuenta propia de la reparación de bienes de consumo - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (82199, 'Cuenta propia de la reparación de bienes de consumo - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (82201, 'Jefes de la reparación de bienes de consumo - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (82202, 'Jefes de la reparación de bienes de consumo - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (82203, 'Jefes de la reparación de bienes de consumo - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (82209, 'Jefes de la reparación de bienes de consumo - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (82391, 'Trabajadores de la reparación de bienes de consumo - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (82392, 'Trabajadores de la reparación de bienes de consumo - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (82393, 'Trabajadores de la reparación de bienes de consumo- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (82394, 'Trabajadores de la reparación de bienes de consumo- No calificados', 1);
INSERT INTO ocupacion VALUES (82399, 'Trabajadores de la reparación de bienes de consumo- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (90191, 'Cuenta propia de la instalación y mantenimiento de maquinarias y equipos de la producción de bienes - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (90192, 'Cuenta propia de la instalación y mantenimiento de maquinarias y equipos de la producción de bienes - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (90193, 'Cuenta propia de la instalación y mantenimiento de maquinarias y equipos de la producción de bienes- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (90199, 'Cuenta propia de la instalación y mantenimiento de maquinarias y equipos de la producción de bienes- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (90201, 'Jefes de la instalación y mantenimiento de maquinaria y equipos dela producción de bienes- Calificaciónprofesional', 1);
INSERT INTO ocupacion VALUES (90202, 'Jefes de la instalación y mantenimiento de maquinaria y equipos dela producción de bienes- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (90203, 'Jefes de la instalación y mantenimiento de maquinaria y equipos dela producción de bienes- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (90209, 'Jefes de la instalación y mantenimiento de maquinaria y equipos dela producción de bienes- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (90391, 'Trabajadores de la instalación y mantenimiento de maquinaria y equipos de la producción de bienes Calificación profesional', 1);
INSERT INTO ocupacion VALUES (90392, 'Trabajadores de la instalación y mantenimiento de maquinaria y equipos de la producción de bienes Calificación técnica', 1);
INSERT INTO ocupacion VALUES (90393, 'Trabajadores de la instalación y mantenimiento de maquinaria y equipos de la producción de bienes Calificación operativa', 1);
INSERT INTO ocupacion VALUES (90394, 'Trabajadores de la instalación y mantenimiento de maquinaria y equipos de la producción de bienes- No calificados', 1);
INSERT INTO ocupacion VALUES (90399, 'Trabajadores de la instalación y mantenimiento de maquinaria y equipos de la producción de bienes Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (91191, 'Cuenta propia del desarrollo tecnológico productivo- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (91192, 'Cuenta propia del desarrollo tecnológico productivo Calificación técnica', 1);
INSERT INTO ocupacion VALUES (91193, 'Cuenta propia del desarrollo tecnológico productivo Calificación operativa', 1);
INSERT INTO ocupacion VALUES (91199, 'Cuenta propia del desarrollo tecnológico productivo Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (91201, 'Jefes del desarrollo tecnológico productivo- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (91202, 'Jefes del desarrollo tecnológico productivo- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (91203, 'Jefes del desarrollo tecnológico productivo - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (91209, 'Jefes del desarrollo tecnológico productivo - Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (91391, 'Trabajadores del desarrollo tecnológico Calificación profesional', 1);
INSERT INTO ocupacion VALUES (91393, 'Trabajadores del desarrollo tecnológico Calificación operativa', 1);
INSERT INTO ocupacion VALUES (91394, 'Trabajadores del desarrollo tecnológico- No calificados', 1);
INSERT INTO ocupacion VALUES (91399, 'Trabajadores del desarrollo tecnológico Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (92191, 'Cuenta propia de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios- Calificación profesional', 1);
INSERT INTO ocupacion VALUES (92192, 'Cuenta propia de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (92193, 'Cuenta propia de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (92199, 'Cuenta propia de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (92201, 'Jefes de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios Jefes de la instalación y mantenimiento de maquinaria y equipos de la prestación de servici', 1);
INSERT INTO ocupacion VALUES (92202, 'Jefes de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (92203, 'Jefes de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (92209, 'Jefes de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (92391, 'Trabajadores de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (92392, 'Trabajadores de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios- Calificación técnica', 1);
INSERT INTO ocupacion VALUES (92393, 'Trabajadores de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios- Calificación operativa', 1);
INSERT INTO ocupacion VALUES (92394, 'Trabajadores de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios- No calificado', 1);
INSERT INTO ocupacion VALUES (92399, 'Trabajadores de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios- Calificación ignorada', 1);
INSERT INTO ocupacion VALUES (99191, 'Cuenta propia de carácter ignorado - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (99192, 'Cuenta propia de carácter ignorado - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (99193, 'Cuenta propia de carácter ignorado - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (99199, 'Cuenta propia de carácter y calificación ignorados', 1);
INSERT INTO ocupacion VALUES (99201, 'Jefes de calificación profesional, carácter ignorado', 1);
INSERT INTO ocupacion VALUES (99202, 'Jefes de calificación técnica, carácter ignorado', 1);
INSERT INTO ocupacion VALUES (99203, 'Jefes de calificación operativa, carácter ignorado', 1);
INSERT INTO ocupacion VALUES (99209, 'Jefes, resto ignorado', 1);
INSERT INTO ocupacion VALUES (99391, 'trabajadores de carácter ignorado - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (99392, 'trabajadores de carácter ignorado - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (99393, 'trabajadores de carácter ignorado - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (99394, 'trabajadores de carácter ignorado - No calificados', 1);
INSERT INTO ocupacion VALUES (99399, 'trabajadores de carácter y calificación ignorados', 1);
INSERT INTO ocupacion VALUES (99991, 'trabajadores de carácter y categoría ocupacional ignorados - Calificación profesional', 1);
INSERT INTO ocupacion VALUES (99992, 'trabajadores de carácter y categoría ocupacional ignorados - Calificación técnica', 1);
INSERT INTO ocupacion VALUES (99993, 'trabajadores de carácter y categoría ocupacional ignorados - Calificación operativa', 1);
INSERT INTO ocupacion VALUES (99994, 'trabajadores de carácter y categoría ocupacional ignorados - No calificados', 1);
INSERT INTO ocupacion VALUES (99999, 'trabajadores de carácter, y categoría ocupacional y calificación ignorados', 1);
*/