-- Table: his.plana_a1_

-- DROP TABLE his.plana_a1_;

CREATE TABLE his.plana_a1_
(
  momento timestamp without time zone,
  pla_enc integer NOT NULL,
  pla_hog integer NOT NULL,
  pla_mie integer NOT NULL,
  pla_exm integer NOT NULL,
  pla_v1b integer,
  pla_v2 integer,
  pla_v2_esp text,
  pla_v4 integer,
  pla_v5 integer,
  pla_v5_esp text,
  pla_v6 integer,
  pla_v7 integer,
  pla_v9_a integer,
  pla_v9_b integer,
  pla_v12 integer,
  pla_h1 integer,
  pla_h2b integer,
  pla_h2d integer,
  pla_h2c integer,
  pla_h2e integer,
  pla_h2b_esp text,
  pla_h2f integer,
  pla_h2g integer,
  pla_h3 integer,
  pla_h4_tipot integer,
  pla_h4_num integer,
  pla_h4b integer,
  pla_h5 integer,
  pla_h20_1 integer,
  pla_h20_2 integer,
  pla_h20_4 integer,
  pla_h20_5 integer,
  pla_h20_6 integer,
  pla_h20_7 integer,
  pla_h20_8 integer,
  pla_h20_19 integer,
  pla_h20_9 integer,
  pla_h20_10 integer,
  pla_h20_15 integer,
  pla_h20_21 integer,
  pla_h20_25 integer,
  pla_h20_17 integer,
  pla_h20_20 integer,
  pla_h20_11 integer,
  pla_h20_12 integer,
  pla_h20_13 integer,
  pla_h20_16 integer,
  pla_h20_18 integer,
  pla_h20_14 integer,
  pla_h20_esp text,
  pla_h20b integer,
  pla_h20c_1 integer,
  pla_h20c_2 integer,
  pla_h20c_3 integer,
  pla_h20c_4 integer,
  pla_h21a integer,
  pla_h22_1 integer,
  pla_h22_2 integer,
  pla_h22_3 integer,
  pla_h22_4 integer,
  pla_h23 integer,
  pla_h24_1 integer,
  pla_h24_2 integer,
  pla_h24_3 integer,
  pla_h24_4 integer,
  pla_h25 integer,
  pla_h26_1 integer,
  pla_h26_2 integer,
  pla_h26_3 integer,
  pla_h26_4 integer,
  pla_h26_5 integer,
  pla_x5 integer,
  pla_x5_tot integer,
  pla_n1 integer,
  pla_n1_tot integer,
  pla_r1 integer,
  pla_r2 integer,
  pla_r3 integer,
  pla_r4_pcia text,
  pla_r4 integer,
  pla_r4_pais text,
  pla_r5 integer,
  pla_r6 integer,
  pla_r7 integer,
  pla_r8_pais text,
  pla_r8 integer,
  pla_r8_pcia text,
  pla_h30b_1 integer,
  pla_h30b_2 integer,
  pla_h30b_3 integer,
  pla_h30b_4 integer,
  pla_h30b_5 integer,
  pla_h30b_6 integer,
  pla_h30b_7 integer,
  pla_h30b_8 integer,
  pla_h30b_9 integer,
  pla_h30b_10 integer,
  pla_h30b_11 integer,
  pla_h30b_12 integer,
  pla_h30b_13 integer,
  pla_h30b_14 integer,
  pla_h30b_15 integer,
  pla_h30b_16 integer,
  pla_h31 integer,
  pla_h32_1 integer,
  pla_h32_1m integer,
  pla_h32_2 integer,
  pla_h32_2m integer,
  pla_h32_3 integer,
  pla_h32_3m integer,
  pla_ts1 integer,
  pla_ts2 integer,
  pla_ts3_men integer,
  pla_ts3_mnr integer,
  pla_ts3_mce integer,
  pla_ts3_tot integer,
  pla_h33a integer,
  pla_h34b integer,
  pla_h35c integer,
  pla_h36d integer,
  pla_tlg bigint NOT NULL,
  pla_h4_tel integer
)
WITH (
  OIDS=FALSE
);
ALTER TABLE his.plana_a1_
  OWNER TO tedede_php;

-- Table: his.plana_a1_m

-- DROP TABLE his.plana_a1_m;

CREATE TABLE his.plana_a1_m
(
  momento timestamp without time zone,
  pla_enc integer NOT NULL,
  pla_hog integer NOT NULL,
  pla_mie integer NOT NULL,
  pla_exm integer NOT NULL,
  pla_n2 integer,
  pla_n3_meses integer,
  pla_n3_anios integer,
  pla_n4 integer,
  pla_n5 integer,
  pla_n6 integer,
  pla_n6_esp text,
  pla_n7 integer,
  pla_n7_esp2 text,
  pla_n7_esp3 text,
  pla_n7_esp8 text,
  pla_tlg bigint NOT NULL
)
WITH (
  OIDS=FALSE
);
ALTER TABLE his.plana_a1_m
  OWNER TO tedede_php;

-- Table: his.plana_a1_x

-- DROP TABLE his.plana_a1_x;

CREATE TABLE his.plana_a1_x
(
  momento timestamp without time zone,
  pla_enc integer NOT NULL,
  pla_hog integer NOT NULL,
  pla_mie integer NOT NULL,
  pla_exm integer NOT NULL,
  pla_sexo_ex integer,
  pla_pais_nac integer,
  pla_edad_ex integer,
  pla_niv_educ integer,
  pla_anio integer,
  pla_lugar integer,
  pla_lugar_esp1 text,
  pla_lugar_esp3 text,
  pla_tlg bigint NOT NULL,
  pla_lugar_esp2 text
)
WITH (
  OIDS=FALSE
);
ALTER TABLE his.plana_a1_x
  OWNER TO tedede_php;

-- Table: his.plana_i1_

-- DROP TABLE his.plana_i1_;

CREATE TABLE his.plana_i1_
(
  momento timestamp without time zone,
  pla_enc integer NOT NULL,
  pla_hog integer NOT NULL,
  pla_mie integer NOT NULL,
  pla_exm integer NOT NULL,
  pla_obs text,
  pla_respondi integer,
  pla_t1 integer,
  pla_t2 integer,
  pla_t3 integer,
  pla_t4 integer,
  pla_t5 integer,
  pla_t6 integer,
  pla_t7 integer,
  pla_t8 integer,
  pla_t8_otro text,
  pla_t9 integer,
  pla_t10 integer,
  pla_t11 integer,
  pla_t11_otro text,
  pla_t12 integer,
  pla_t13 integer,
  pla_t14 integer,
  pla_t14b_esp text,
  pla_t15 integer,
  pla_t15a integer,
  pla_t15a_otro text,
  pla_t16 integer,
  pla_t17 integer,
  pla_t18 integer,
  pla_t19_anio integer,
  pla_t20 integer,
  pla_t21 integer,
  pla_t22 integer,
  pla_t23 text,
  pla_t24 text,
  pla_t25 text,
  pla_t26 text,
  pla_t27 integer,
  pla_t28 integer,
  pla_t29 integer,
  pla_t29a integer,
  pla_t30 integer,
  pla_t31_d integer,
  pla_t31_l integer,
  pla_t31_ma integer,
  pla_t31_mi integer,
  pla_t31_j integer,
  pla_t31_v integer,
  pla_t31_s integer,
  pla_t32_d integer,
  pla_t32_l integer,
  pla_t32_ma integer,
  pla_t32_mi integer,
  pla_t32_j integer,
  pla_t32_v integer,
  pla_t32_s integer,
  pla_t33 integer,
  pla_t34 integer,
  pla_t35 integer,
  pla_t36_1 integer,
  pla_t36_2 integer,
  pla_t36_3 integer,
  pla_t36_4 integer,
  pla_t36_5 integer,
  pla_t36_6 integer,
  pla_t36_7 integer,
  pla_t36_7_esp text,
  pla_t36_8 integer,
  pla_t36_8_esp text,
  pla_t36a integer,
  pla_t37 text,
  pla_t37sd integer,
  pla_t38 integer,
  pla_t38b integer,
  pla_t38b_esp text,
  pla_t39 integer,
  pla_t39_barrio text,
  pla_t39_otro text,
  pla_t39bis integer,
  pla_t39bis_cuantos integer,
  pla_t39bis1 integer,
  pla_t40 integer,
  pla_t41 text,
  pla_t42 text,
  pla_t43 text,
  pla_t44 integer,
  pla_t45 integer,
  pla_t46 integer,
  pla_t47 integer,
  pla_t48 integer,
  pla_t48a integer,
  pla_t48b integer,
  pla_t48b_esp text,
  pla_t49 integer,
  pla_t50a integer,
  pla_t50b integer,
  pla_t50c integer,
  pla_t50d integer,
  pla_t50e integer,
  pla_t50f integer,
  pla_t51 integer,
  pla_t51b integer,
  pla_t52a integer,
  pla_t52b integer,
  pla_t52c integer,
  pla_t53_ing integer,
  pla_t53_bis1 integer,
  pla_t53_bis1_sem integer,
  pla_t53_bis1_mes integer,
  pla_t53_bis2 integer,
  pla_t53c_anios integer,
  pla_t53c_meses integer,
  pla_t53c_98 integer,
  pla_t53b integer,
  pla_t54 integer,
  pla_t54b integer,
  pla_t55 integer,
  pla_t56a integer,
  pla_t56b integer,
  pla_t56c integer,
  pla_t57 integer,
  pla_t58 integer,
  pla_t59 integer,
  pla_i1 integer,
  pla_i2_totx integer,
  pla_i2_ticx integer,
  pla_i3_1 integer,
  pla_i3_1x integer,
  pla_i3_2 integer,
  pla_i3_2x integer,
  pla_i3_3 integer,
  pla_i3_3x integer,
  pla_i3_4 integer,
  pla_i3_4x integer,
  pla_i3_5 integer,
  pla_i3_5x integer,
  pla_i3_18 integer,
  pla_i3_18x integer,
  pla_i3_7 integer,
  pla_i3_7x integer,
  pla_i3_8 integer,
  pla_i3_8x integer,
  pla_i3_11 integer,
  pla_i3_11x integer,
  pla_i3_20 integer,
  pla_i3_20x integer,
  pla_i3_6 integer,
  pla_i3_6x integer,
  pla_i3_26 integer,
  pla_i3_26x integer,
  pla_i3_13 integer,
  pla_i3_13x integer,
  pla_i3_14 integer,
  pla_i3_14x integer,
  pla_i3_40 integer,
  pla_i3_40x integer,
  pla_i3_15 integer,
  pla_i3_15x integer,
  pla_i3_24 integer,
  pla_i3_24x integer,
  pla_i3_25 integer,
  pla_i3_25x integer,
  pla_i3_17 integer,
  pla_i3_17x integer,
  pla_i3_21 integer,
  pla_i3_21x integer,
  pla_i3_22 integer,
  pla_i3_22x integer,
  pla_i3_23 integer,
  pla_i3_23x integer,
  pla_i3_16 integer,
  pla_i3_16x integer,
  pla_i3_27 integer,
  pla_i3_27x integer,
  pla_i3_28 integer,
  pla_i3_28x integer,
  pla_i3_10 integer,
  pla_i3_10x integer,
  pla_i3_10_otro text,
  pla_i3_tot integer,
  pla_i3_99 integer,
  pla_e1 integer,
  pla_e2 integer,
  pla_e3 integer,
  pla_e3a integer,
  pla_e4 integer,
  pla_e5a_1 integer,
  pla_e5a_2 integer,
  pla_e5a_3 integer,
  pla_e5a_4 integer,
  pla_e5a_5 integer,
  pla_e5a_6 integer,
  pla_e5a_7 integer,
  pla_e5a_7_otro text,
  pla_e5b integer,
  pla_e6 integer,
  pla_e7 integer,
  pla_e7b integer,
  pla_e8 integer,
  pla_e8a_1 integer,
  pla_e8a_2 integer,
  pla_e8a_3 integer,
  pla_e8a_4 integer,
  pla_e8a_7 integer,
  pla_e8a_5 integer,
  pla_e8a_6 integer,
  pla_e8b integer,
  pla_e8c integer,
  pla_e10c integer,
  pla_e10d_anios integer,
  pla_e10e_1 integer,
  pla_e10e_18 integer,
  pla_e10e_19 integer,
  pla_e10e_20 integer,
  pla_e10e_16 integer,
  pla_e10e_17 integer,
  pla_e10e_cuales text,
  pla_e10e_4 integer,
  pla_e10e_5 integer,
  pla_e10e_6 integer,
  pla_e10e_7 integer,
  pla_e10e_8 integer,
  pla_e10e_10 integer,
  pla_e10e_11 integer,
  pla_e10e_12 integer,
  pla_e10e_13 integer,
  pla_e10e_14 integer,
  pla_e10e_15 integer,
  pla_e10e_esp text,
  pla_e10e2 integer,
  pla_e10a integer,
  pla_e10b integer,
  pla_e10f integer,
  pla_e10g_1 integer,
  pla_e10g_2 integer,
  pla_e10g_3 integer,
  pla_e10g_4 integer,
  pla_e10g_6 integer,
  pla_e10g_cual text,
  pla_e10g_5 integer,
  pla_e10g_esp text,
  pla_e8d_1 integer,
  pla_e8d_2 integer,
  pla_e8d_3 integer,
  pla_e8d_4 integer,
  pla_e8d_5 integer,
  pla_e8d_6 integer,
  pla_e8d_7 integer,
  pla_e8d_8 integer,
  pla_e8d_9 integer,
  pla_e8d_10 integer,
  pla_e8d_esp text,
  pla_e8d_1a integer,
  pla_e9_edad integer,
  pla_e9_anio integer,
  pla_e10 integer,
  pla_e12 integer,
  pla_e13 integer,
  pla_e14 integer,
  pla_e11_1 integer,
  pla_e11_18 integer,
  pla_e11_19 integer,
  pla_e11_20 integer,
  pla_e11_16 integer,
  pla_e11_17 integer,
  pla_e11_cuales text,
  pla_e11_4 integer,
  pla_e11_5 integer,
  pla_e11_6 integer,
  pla_e11_7 integer,
  pla_e11_8 integer,
  pla_e11_10 integer,
  pla_e11_11 integer,
  pla_e11_12 integer,
  pla_e11_13 integer,
  pla_e11_14 integer,
  pla_e11_15 integer,
  pla_e11_esp text,
  pla_e11a integer,
  pla_e14a integer,
  pla_e14b integer,
  pla_e14c_1 integer,
  pla_e14c_2 integer,
  pla_e14c_3 integer,
  pla_e14c_4 integer,
  pla_e14c_6 integer,
  pla_e14c_cual text,
  pla_e14c_5 integer,
  pla_e14c_esp text,
  pla_e15b_1 integer,
  pla_e15b_9 integer,
  pla_e15b_2 integer,
  pla_e15b_3 integer,
  pla_e15b_4 integer,
  pla_e15b_7 integer,
  pla_e15b_8 integer,
  pla_e15b_5 integer,
  pla_e15b_esp text,
  pla_e15c integer,
  pla_m1 integer,
  pla_m1_esp2 text,
  pla_m1_esp3 text,
  pla_m1_esp4 text,
  pla_m1b integer,
  pla_m2b integer,
  pla_m1a integer,
  pla_m1a_2_esp text,
  pla_m1a_3_esp text,
  pla_m1a_4_esp text,
  pla_m1c integer,
  pla_m3 integer,
  pla_m3_anio integer,
  pla_m4 integer,
  pla_m4_esp1 text,
  pla_m4_esp2 text,
  pla_m4_esp3 text,
  pla_m5 integer,
  pla_sn1_7 integer,
  pla_sn1_1 integer,
  pla_sn1_2 integer,
  pla_sn1_3 integer,
  pla_sn1_4 integer,
  pla_sn1_5 integer,
  pla_sn1_6 integer,
  pla_sn2 integer,
  pla_sn2_cant integer,
  pla_sn3 integer,
  pla_sn4 integer,
  pla_sn4_esp text,
  pla_sn5 integer,
  pla_sn5_esp text,
  pla_sn6 integer,
  pla_sn6_cant integer,
  pla_sn7 integer,
  pla_sn7_esp text,
  pla_sn11 integer,
  pla_sn13 integer,
  pla_sn13_otro text,
  pla_sn14 integer,
  pla_sn14_esp text,
  pla_sn18 integer,
  pla_sn19 integer,
  pla_sn20 integer,
  pla_sn17 integer,
  pla_sm1 integer,
  pla_sm2 integer,
  pla_sm3 integer,
  pla_sm4 integer,
  pla_sm5 integer,
  pla_sm6 integer,
  pla_sm6a integer,
  pla_sm7_anio integer,
  pla_sm7_mes integer,
  pla_sm8 integer,
  pla_sm8b integer,
  pla_sm8c integer,
  pla_sm8d integer,
  pla_sm9 integer,
  pla_mac1 integer,
  pla_mac1_esp text,
  pla_mac2 integer,
  pla_mac3_rit integer,
  pla_mac3_pas integer,
  pla_mac3_ovu integer,
  pla_mac3_pre integer,
  pla_mac3_espi integer,
  pla_mac3_dia integer,
  pla_mac3_otro integer,
  pla_mac3_esp text,
  pla_em1 integer,
  pla_em2 integer,
  pla_em3 integer,
  pla_rpm1 integer,
  pla_rpm2 integer,
  pla_sm10 integer,
  pla_sm10a_1 integer,
  pla_sm10a_2 integer,
  pla_sm10a_3 integer,
  pla_sm10a_4 integer,
  pla_sm10a_5 integer,
  pla_sm10a_6 integer,
  pla_sm10a_7 integer,
  pla_sm10a_8 integer,
  pla_sm10a_9 integer,
  pla_sm10a_10 integer,
  pla_sm10a_esp text,
  pla_sm10b integer,
  pla_sm11 integer,
  pla_sm12 integer,
  pla_sm12a_2 integer,
  pla_sm12a_3 integer,
  pla_sm12a_1 integer,
  pla_rpm3 integer,
  pla_sm13 integer,
  pla_sm13_esp text,
  pla_sm14 integer,
  pla_sm15 integer,
  pla_sm16 integer,
  pla_sm17 integer,
  pla_sm18 integer,
  pla_d1 integer,
  pla_d2_1 integer,
  pla_d2_2 integer,
  pla_d2_3 integer,
  pla_d2_4 integer,
  pla_d2_5 integer,
  pla_d2_6 integer,
  pla_d2_7 integer,
  pla_d2_otra text,
  pla_d3 integer,
  pla_d4 integer,
  pla_d5 integer,
  pla_vc1_1 integer,
  pla_vc1_2 integer,
  pla_vc1_3 integer,
  pla_vc1_4 integer,
  pla_vc1_5 integer,
  pla_vc1_6 integer,
  pla_vc1_7 integer,
  pla_vc2_1 integer,
  pla_vc2_2 integer,
  pla_vc3_1 integer,
  pla_vc3_2 integer,
  pla_vc4_1 integer,
  pla_vc4_2 integer,
  pla_vc5_1 integer,
  pla_vc5_2 integer,
  pla_vc6_1 integer,
  pla_vc6_2 integer,
  pla_vc7_1 integer,
  pla_vc7_2 integer,
  pla_vc7_3 integer,
  pla_vc7_4 integer,
  pla_vc7_5 integer,
  pla_vc8_1 integer,
  pla_vc8_2 integer,
  pla_vc9_1 integer,
  pla_vc9_2 integer,
  pla_vc10_1 integer,
  pla_vc10_2 integer,
  pla_vc11 integer,
  pla_vc12_1 integer,
  pla_vc12_2 integer,
  pla_vc13 integer,
  pla_vc14_1 integer,
  pla_vc14_2 integer,
  pla_vc15 integer,
  pla_vc16_2 integer,
  pla_vc16_1 integer,
  pla_tip1 integer,
  pla_tip2 integer,
  pla_tip3 integer,
  pla_tip3_9 integer,
  pla_tip4 integer,
  pla_tip4_pcia text,
  pla_tip4_pais text,
  pla_tip5 integer,
  pla_tip5b integer,
  pla_tip6 integer,
  pla_tip7 integer,
  pla_tip8 integer,
  pla_tip8_esp text,
  pla_tip9 integer,
  pla_tip9_9 integer,
  pla_tip10 integer,
  pla_tip10_pcia text,
  pla_tip10_pais text,
  pla_tip11 integer,
  pla_tip11b integer,
  pla_tip12 integer,
  pla_tip13 integer,
  pla_tip14 integer,
  pla_tip14_esp text,
  pla_tip15 integer,
  pla_tip16 integer,
  pla_tip17 integer,
  pla_rg1a integer,
  pla_rg1b integer,
  pla_rg1c integer,
  pla_rg2_1_a integer,
  pla_rg2_1_b integer,
  pla_rg2_1_c integer,
  pla_rg2_1_d integer,
  pla_rg2_1_e integer,
  pla_rg2_1_f integer,
  pla_rg2_2_a integer,
  pla_rg2_2_b integer,
  pla_rg2_2_c integer,
  pla_rg2_2_d integer,
  pla_rg2_2_e integer,
  pla_rg2_2_f integer,
  pla_rg2_3_a integer,
  pla_rg2_3_b integer,
  pla_rg2_3_c integer,
  pla_rg2_3_d integer,
  pla_rg2_3_e integer,
  pla_rg2_3_f integer,
  pla_rg2_4_a integer,
  pla_rg2_4_b integer,
  pla_rg2_4_c integer,
  pla_rg2_4_d integer,
  pla_rg2_4_e integer,
  pla_rg2_4_f integer,
  pla_rg2_5_a integer,
  pla_rg2_5_b integer,
  pla_rg2_5_c integer,
  pla_rg2_5_d integer,
  pla_rg2_5_e integer,
  pla_rg2_5_f integer,
  pla_rg2_6_a integer,
  pla_rg2_6_b integer,
  pla_rg2_6_c integer,
  pla_rg2_6_d integer,
  pla_rg2_7_e integer,
  pla_rg2_6_f integer,
  pla_rg2_7_a integer,
  pla_rg2_7_b integer,
  pla_rg2_7_c integer,
  pla_rg2_7_d integer,
  pla_rg2_8_e integer,
  pla_rg2_7_f integer,
  pla_rg2_8_a integer,
  pla_rg2_8_b integer,
  pla_rg2_8_c integer,
  pla_rg2_8_d integer,
  pla_rg2_9_e integer,
  pla_rg2_8_f integer,
  pla_rg2_9_a integer,
  pla_rg2_9_b integer,
  pla_rg2_9_c integer,
  pla_rg2_9_d integer,
  pla_rg2_6_e integer,
  pla_rg2_9_f integer,
  pla_rg2_10_a integer,
  pla_rg2_10_b integer,
  pla_rg2_10_c integer,
  pla_rg2_10_d integer,
  pla_rg2_10_e integer,
  pla_rg2_10_f integer,
  pla_rg2_11_a integer,
  pla_rg2_11_b integer,
  pla_rg2_11_c integer,
  pla_rg2_11_d integer,
  pla_rg2_11_e integer,
  pla_rg2_11_f integer,
  pla_rg3_1_a integer,
  pla_rg3_1_b integer,
  pla_rg3_1_c integer,
  pla_rg3_1_d integer,
  pla_rg3_1_e integer,
  pla_rg3_2_a integer,
  pla_rg3_2_b integer,
  pla_rg3_2_c integer,
  pla_rg3_2_d integer,
  pla_rg3_2_e integer,
  pla_rg3_3_a integer,
  pla_rg3_3_b integer,
  pla_rg3_3_c integer,
  pla_rg3_3_d integer,
  pla_rg3_3_e integer,
  pla_rg3_4_a integer,
  pla_rg3_4_b integer,
  pla_rg3_4_c integer,
  pla_rg3_4_d integer,
  pla_rg3_4_e integer,
  pla_rg3_5_a integer,
  pla_rg3_5_b integer,
  pla_rg3_5_c integer,
  pla_rg3_5_d integer,
  pla_rg3_5_e integer,
  pla_rg3_6_a integer,
  pla_rg3_6_b integer,
  pla_rg3_6_c integer,
  pla_rg3_6_d integer,
  pla_rg3_6_e integer,
  pla_rg3_7 integer,
  pla_rg4 integer,
  pla_rg5 integer,
  pla_rg6a integer,
  pla_rg6b integer,
  pla_rg6_c integer,
  pla_rg6_d integer,
  pla_rg6_e integer,
  pla_rg6_f integer,
  pla_rg6_g integer,
  pla_rg7a_1 integer,
  pla_rg7a_2 integer,
  pla_rg7a_4 integer,
  pla_rg7a_3 integer,
  pla_rg7b integer,
  pla_rg8a integer,
  pla_rg8b integer,
  pla_rg8c integer,
  pla_rg9 integer,
  pla_rg10 integer,
  pla_rg11 integer,
  pla_rg12 integer,
  pla_rg12_esp text,
  pla_rg13_1 integer,
  pla_rg13_2 integer,
  pla_rg13_2_esp integer,
  pla_rg13_3 integer,
  pla_rg13_3_esp integer,
  pla_rg13_4 integer,
  pla_rg13_4_espn integer,
  pla_rg13_4_espa integer,
  pla_ti1_1 integer,
  pla_ti1_2 integer,
  pla_ti1_3 integer,
  pla_ti1_4 integer,
  pla_ti1_5 integer,
  pla_ti1_6 integer,
  pla_ti1_7 integer,
  pla_ti1_otra text,
  pla_ti2_1 integer,
  pla_ti2_3 integer,
  pla_ti2_4 integer,
  pla_ti2_5 integer,
  pla_ti2_2 integer,
  pla_ti2_6 integer,
  pla_ti2_5_horas integer,
  pla_ti2_6_horas integer,
  pla_ti2_4_horas integer,
  pla_ti2_2_horas integer,
  pla_ti2_3_horas integer,
  pla_ti2_1_horas integer,
  pla_ti3 integer,
  pla_ti4 integer,
  pla_ti5 integer,
  pla_ti6 integer,
  pla_ti7 integer,
  pla_ti8 integer,
  pla_ti9 integer,
  pla_ti10 integer,
  pla_ti13 integer,
  pla_ti12 integer,
  pla_ti11 integer,
  pla_t23_cod integer,
  pla_t41_cod integer,
  pla_t37_cod integer,
  pla_t24_cod integer,
  pla_edad10a integer,
  pla_zona_3_1 integer,
  pla_edad10b integer,
  pla_t_ocup integer,
  pla_t_edad integer,
  pla_sc_edad integer,
  pla_t_desoc integer,
  pla_fp5_r integer,
  pla_fp5_agr integer,
  pla_t_ina integer,
  pla_cond_activ integer,
  pla_t_activ integer,
  pla_t_empleo integer,
  pla_t_desocup integer,
  pla_v2_2_mie integer,
  pla_e_nivela integer,
  pla_m1_2 integer,
  pla_e_nivelb integer,
  pla_e_nivelc integer,
  pla_e_nivel integer,
  pla_e_aesc integer,
  pla_e_raesc integer,
  pla_s_edad integer,
  pla_sn1_1a7 integer,
  pla_sn1_99 integer,
  pla_s_tipco integer,
  pla_s_tipco3 integer,
  pla_s_tipco3r integer,
  pla_s_tipco2 integer,
  pla_m_limit integer,
  pla_m_ln1 integer,
  pla_m_rallp integer,
  pla_tsemref integer,
  pla_t_diastra1p integer,
  pla_t_diastra2p integer,
  pla_t_diasnotr1p integer,
  pla_t_diasnotr2p integer,
  pla_sem_hs1p integer,
  pla_sem_hs2p integer,
  pla_sem_hs integer,
  pla_t_intens integer,
  pla_t_categ integer,
  pla_categori integer,
  pla_t51_re integer,
  pla_t39_comu integer,
  pla_t39_zona integer,
  pla_t39_rec integer,
  pla_tipodes integer,
  pla_f_edad integer,
  pla_s28r integer,
  pla_f_n_hij integer,
  pla_categdes integer,
  pla_codlab integer,
  pla_codnolab integer,
  pla_coding integer,
  pla_ingtot integer,
  pla_igtot integer,
  pla_tlg bigint NOT NULL,
  pla_e10d_edad integer,
  pla_tip5b_6_esp text,
  pla_rg11_esp text,
  t14b integer,
  pla_t14b integer
)
WITH (
  OIDS=FALSE
);
ALTER TABLE his.plana_i1_
  OWNER TO tedede_php;

-- Table: his.plana_s1_

-- DROP TABLE his.plana_s1_;

CREATE TABLE his.plana_s1_
(
  momento timestamp without time zone,
  pla_enc integer NOT NULL,
  pla_hog integer NOT NULL,
  pla_mie integer NOT NULL,
  pla_exm integer NOT NULL,
  pla_bcp1 integer,
  pla_bcp2 integer,
  pla_entrea integer,
  pla_respond integer,
  pla_nombrer text,
  pla_f_realiz_o text,
  pla_telefono text,
  pla_movil text,
  pla_v1 integer,
  pla_total_h integer,
  pla_total_m integer,
  pla_nmiembro_titular integer,
  pla_razon1 integer,
  pla_razon2_1 integer,
  pla_razon2_2 integer,
  pla_razon2_3 integer,
  pla_razon2_4 integer,
  pla_razon2_5 integer,
  pla_razon2_7 integer,
  pla_razon2_8 integer,
  pla_razon2_9 integer,
  pla_razon2_9_esp text,
  pla_s1a1_obs text,
  pla_zona_3 integer,
  pla_tot_mi integer,
  pla_pobnosd integer,
  pla_tot_mr integer,
  pla_h2_re integer,
  pla_h2_2 integer,
  pla_h_perhab integer,
  pla_h_hacina integer,
  pla_hacinam_2 integer,
  pla_v2_re integer,
  pla_v2_2 integer,
  pla_ipcf_calc integer,
  pla_ipcf integer,
  pla_codi_tot integer,
  pla_itf_calc integer,
  pla_itf integer,
  pla_tlg bigint NOT NULL
)
WITH (
  OIDS=FALSE
);
ALTER TABLE his.plana_s1_
  OWNER TO tedede_php;

-- Table: his.plana_s1_p

-- DROP TABLE his.plana_s1_p;

CREATE TABLE his.plana_s1_p
(
  momento timestamp without time zone,
  pla_enc integer NOT NULL,
  pla_hog integer NOT NULL,
  pla_mie integer NOT NULL,
  pla_exm integer NOT NULL,
  pla_nombre text,
  pla_sexo integer,
  pla_f_nac_d integer,
  pla_f_nac_m integer,
  pla_f_nac_a integer,
  pla_edad integer,
  pla_p4 integer,
  pla_p5 integer,
  pla_p5c integer,
  pla_p5b integer,
  pla_p6_b integer,
  pla_p6_a integer,
  pla_tlg bigint NOT NULL,
  pla_p9_1 integer,
  pla_p9_2 integer,
  pla_p9_3 integer,
  pla_p9_4 integer,
  pla_p9_5 integer,
  pla_p9_6 integer
)
WITH (
  OIDS=FALSE
);
ALTER TABLE his.plana_s1_p
  OWNER TO tedede_php;