SET search_path = encu, pg_catalog;

CREATE TABLE actividades_codigos (
    codigo integer NOT NULL,
    nombre_variable text,
    texto text,
    abr text,
    detalle text,
    imagen text,
    exclusividad boolean DEFAULT false,
    grupo character varying(1),
    obligatoriedad boolean DEFAULT false,
    opcion_d12 boolean,
    opcion_d13 boolean,
    opcion_d22 boolean,
    opcion_d23 boolean,
    act_cod_tlg bigint NOT NULL
);

ALTER TABLE actividades_codigos OWNER TO tedede_php;



INSERT INTO actividades_codigos VALUES (1, 'UT4', 'Trabajar para un patrón o por cuenta propia', 'Trabajar para un patrón o por cuenta propia', 'Se toma en cuenta sólo la población ocupada en la producción de bienes y servicios con valor en el mercado. Incluye a asalariados, patrones o empleadores, cuentapropistas, trabajadores familiares no remunerados. Incluye también las capacitaciones y cursos relacionados con el trabajo.', 'actividad1.gif', false, 'M', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (33, 'UT7', 'Lavar, planchar o arreglar la ropa', 'Lavar, planchar o arreglar la ropa', 'Comprende lavar, tender y/o secar, planchar y guardar la ropa. Hacer reparaciones y arreglos en ropa y textiles (arreglos menores: parches, botones). Limpieza y mantenimiento de calzado. Llevar y retirar ropa, textiles y calzado a lavar, planchar o reparar (en este caso se debe contabilizar el tiempo de traslado). No incluye el tiempo de funcionamiento del lavarropas.', 'actividad33.png', false, 'M', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (35, 'UT11', 'Hacer pagos y trámites del hogar', 'Hacer pagos y trámites del hogar', 'Comprende hacer trámites y pagar servicios, organizar documentos y presupuestos del hogar. Incluye también vigilar la seguridad del hogar (cerrar puertas y ventanas, guardar los vehículos o los animales del hogar). Incluye traslados y tiempos de espera.', 'actividad35.png', false, 'M', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (36, 'UT8', 'Hacer compras para el hogar', 'Hacer compras para el hogar', 'Se refiere a compras para la elaboración de la comida, de bienes para el hogar (muebles, electrodomésticos) y para sus miembros (ropa, calzado, útiles escolares). También la compra de vehículos e inmuebles (terrenos, casas). Incluye traslados y tiempo de búsqueda para la elección de los productos a comprar.', 'actividad36.png', false, 'M', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (37, 'UT9', 'Cuidar mascotas y plantas', 'Cuidar mascotas y plantas', 'Aseo, alimentación de mascotas; limpieza del lugar donde comen o duermen; incluye las visitas al veterinario y el tiempo de traslado y espera. Mantenimiento de las plantas del exterior e interior de la vivienda, riego, abono, poda, limpieza, corte de césped, juntado de hojas, etc.', 'actividad37.png', false, 'M', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (411, 'UT15', 'Cuidado personal a niños del hogar, menores de 14 años', 'Cuidado personal a niños del hogar, menores de 14 años', 'Incluye dar de comer, cargar, acostar, bañar, asear o arreglar, prepararlos para ir a la escuela, jugar, conversar, leer o estar pendiente, etc. Excluye a personas con discapacidad o dependencia permanente.', 'actividad411.png', false, 'M', false, true, true, false, false, 1);
INSERT INTO actividades_codigos VALUES (412, 'UT13', 'Cuidados temporales de salud a niños del hogar, menores de 14 años', 'Cuidados temporales de salud a niños del hogar, menores de 14 años', 'Dar medicamentos, hacer curaciones, aplicar terapias, etc.  Concurrir a servicios de salud, incluyendo tiempo de espera. Es independiente del lugar de asistencia del miembro del hogar. No incluye traslados, que se registran en el código 414.  Excluye a personas con discapacidad o dependencia permanente.', 'actividad412.png', false, 'M', false, true, true, true, false, 1);
INSERT INTO actividades_codigos VALUES (413, 'UT16', 'Apoyo escolar y/o de aprendizaje a niños del hogar, menores de 14 años', 'Apoyo escolar y/o de aprendizaje a niños del hogar, menores de 14 años', 'Apoyo en tareas escolares, asistencia a fiestas, reuniones u otras actividades escolares de miembros del hogar menores de 14 años. Excluye a personas con discapacidad o dependencia permanente.', 'actividad413.png', false, 'M', false, true, true, false, false, 1);
INSERT INTO actividades_codigos VALUES (421, 'UT21', 'Apoyo personal a miembros del hogar, entre 14 y 64 años', 'Apoyo personal a miembros del hogar, entre 14 y 64 años', 'Cuidados personales. Comprende actividades como supervisar las tareas escolares o el buen uso de la tecnología; asistir a reuniones de la escuela, apoyar el aprendizaje, etc.  Incluye cuidado pasivo. Excluye a personas con discapacidad o dependencia permanente.', 'actividad421.png', false, 'M', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (441, NULL, 'Apoyo personal a miembros del hogar con discapacidad o dependencia permanente (todas las edades)', 'Apoyo personal a miembros del hogar con discapacidad o dependencia permanente (todas las edades)', 'Cuidado y apoyo; incluye dar de comer, cargar, acostar, bañar, asear o arreglar, jugar, conversar, leer o estar pendiente.', 'actividad441.gif', false, 'M', false, false, false, true, false, 1);
INSERT INTO actividades_codigos VALUES (442, NULL, 'Cuidados de salud a miembros del hogar con discapacidad o dependencia permanente (todas las edades)', 'Cuidados de salud a miembros del hogar con discapacidad o dependencia permanente (todas las edades)', 'Comprende la asistencia por enfermedad temporal o crónica, asistencia personal y visitas al médico (con tiempos de espera). No incluye traslado. Es independiente del lugar de asistencia del miembro del hogar.', 'actividad442.png', false, 'M', false, false, false, true, false, 1);
INSERT INTO actividades_codigos VALUES (54, NULL, 'Trabajo voluntario', 'Hacer trabajos voluntarios', 'Trabajo no remunerado para la mejora de la comunidad; trabajo voluntario en instituciones sin fines de lucro; gestiones y trámites para el mejoramiento del ambiente y los servicios comunitarios; siempre que se trate de tareas NO remuneradas. Incluye tiempo de traslado.', 'actividad52.png', false, 'M', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (74, 'UT34', 'Deporte y ejercicio físico', 'Hacer deportes o ejercicios físicos', 'Incluye práctica de deportes organizada y hacer ejercicio físico de manera informal (caminatas, excursiones, hacer aerobics, etc). No incluye actividades de trabajo o estudio', 'actividad74.png', false, 'M', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (81, 'UT35', 'Lectura de libros, revistas, etc.', 'Leer libros o revistas', 'Leer libros, revistas, periódicos u otro material por cualquier medio. Utilización de bibliotecas con tiempo de traslado. No incluye las que se relacionan con actividades de trabajo o estudio.', 'actividad81.png', false, 'M', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (82, 'UT36', 'Ver televisión', 'Ver televisión', 'Ver televisión o videos, exclusivamente, por cualquier medio.', 'actividad822.gif', true, 'M', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (83, NULL, 'Escuchar radio', 'Escuchar radio', 'Escuchar radio u otros medios de audio exclusivamente (música, noticias, comentarios).', 'actividad83.png', true, 'M', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (84, 'UT37', 'Usar Computadora', 'Usar computadora, tableta o celular', 'Utilizar computadora, tableta o celular (navegar por Internet, usar redes sociales, descargar archivos, etc.). No incluye hacer pagos, compras o actividades de trabajo o estudio.', 'actividad84.png', false, 'M', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (911, 'UT39', 'Aseo y arreglo personal', 'Higiene, arreglo personal, etc.', 'Comprende actividades individuales relacionadas con las necesidades fisiológicas, de salud y descanso (bañarse, cambiarse de ropa, afeitarse, maquillarse, hacer tratamientos de belleza).', 'actividad911.png', false, 'M', true, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (914, NULL, 'Descanso, relajación, otras actividades personales', 'Descansar o realizar otras actividades personales', 'Descansar física o psicológicamente, meditar, orar, reflexionar. Cualquier otra actividad de cuidado personal. Incluye tener relaciones sexuales. Incluye traslados.', 'actividad9142.gif', false, 'M', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (921, 'UT40', 'Comer, beber, ir al baño', 'Comer y beber', 'Incluye comidas habituales (desayuno, almuerzo, merienda y cena), refrigerios y colaciones.', 'actividad921.png', false, 'M', true, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (922, 'UT41', 'Dormir', 'Dormir', 'Incluye dormir de noche, la siesta o en cualquier otro momento. También se computa el tiempo en la cama antes de levantarse. No incluye dormir durante el viaje.', 'actividad922.png', true, 'M', true, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (431, 'UT26', 'Apoyo personal a miembros del hogar de 65 años o más', 'Apoyo personal a miembros del hogar de 65 años o más', 'Cuidados personales. Apoyo en la realización de gestiones o trámites; ayuda en el uso de tecnología, etc. Incluye cuidado pasivo. Excluye a personas con discapacidad o dependencia permanente.', 'actividad431.png', false, 'M', false, false, false, true, true, 1);
INSERT INTO actividades_codigos VALUES (432, 'UT24', 'Cuidados temporales de salud a miembros del hogar de 65 años o más', 'Cuidados temporales de salud a miembros del hogar de 65 años o más', 'Comprende la asistencia por enfermedad temporal, asistencia personal y visitas al médico (con tiempos de espera). No incluye traslado. Es independiente del lugar de asistencia del miembro del hogar. Excluye a personas con discapacidad o dependencia permanente.', 'actividad432.png', false, 'M', false, false, false, true, true, 1);
INSERT INTO actividades_codigos VALUES (34, 'UT10', 'Hacer reparaciones y mantenimiento de la vivienda', 'Hacer reparaciones menores y mantenimiento de la vivienda', 'Incluye mantenimiento, instalación y reparaciones menores en la vivienda, en los bienes del hogar y personales: revoque, pintura, trabajos de electricidad (cambiar focos, conexiones), de carpintería (lijar, barnizar, etc.), mantenimiento de muebles, aparatos eléctricos, utensilios, elementos decorativos. También comprende los trabajos en los vehículos de uso propio del hogar (cambio de aceite, lavar, encerar); si los trabajos se realizan fuera de la vivienda se debe incluir el tiempo de traslado ida y vuelta a la vivienda.No se incluyen actividades de construcción, aunque sean parciales.', 'actividad34.png', false, 'M', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (912, 'UT38', 'Cuidados personales de salud', 'Cuidar su salud (tratamientos, terapias, etc.)', 'Tomarse un remedio, practicar alguna terapia, hacerse curaciones, tomarse la presión, realizar prácticas de diagnóstico (análisis, ecografías). Incluye traslados.', 'actividad912.png', false, 'M', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (433, 'UT27', 'Acompañamiento y traslados a  miembros del hogar de 65 años o más', 'Acompañamiento y traslados a  miembros del hogar de 65 años o más', 'Acompañamiento y traslados para las actividades de cuidado y apoyo personal o por motivos de salud. Comprende visitas al médico, actividades sociales o deportivas, gestiones legales, administrativas o financieras, etc. Es independiente del lugar de asistencia del miembro del hogar. Excluye a personas con discapacidad o dependencia permanente.', 'actividad433.png', false, 'F', false, false, false, true, true, 1);
INSERT INTO actividades_codigos VALUES (13, NULL, 'Buscar trabajo', 'Buscar trabajo', 'Consiste en la búsqueda laboral activa a fin de encontrar un trabajo asalariado o independiente (presentación de CV personalmente o vía Internet, distribución de carteles o volantes, asistencia a entrevistas, organización de un negocio o emprendimiento -gestiones, permisos- etc.).', 'actividad13.gif', false, 'M', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (14, NULL, 'Viajar para ir y volver al trabajo', 'Viajar para ir y volver al trabajo', 'Desplazamiento desde y hasta el trabajo, lugares de reuniones o gestiones laborales. Incluye el tiempo de espera del transporte.', 'actividad14.gif', false, 'F', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (2, NULL, 'Trabajar para consumo propio del hogar', 'Trabajar para consumo propio del hogar', 'Comprende tareas de los miembros del hogar para uso propio: cultivo de vegetales y cría de animales, elaboración de conservas de alimentos y bebidas, confección de ropa, calzado, muebles, cerámica, etc., construcción de viviendas y otros edificios para uso final propio del hogar, y las actividades de traslado relacionadas.', 'actividad2.gif', false, 'M', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (31, 'UT5', 'Preparar y servir la comida', 'Preparar y servir la comida', 'Reúne las siguientes actividades: cocinar, preparar, servir y empacar o guardar alimentos. Limpiar el comedor (colocar y sacar manteles, platos, cubiertos, etc.), la cocina y la vajilla (para preparar, servir y comer). Llevar fuera del hogar la comida a alguno de sus componentes (escuela, trabajo).', 'actividad31.png', false, 'M', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (422, 'UT19', 'Cuidados temporales de salud a miembros del hogar, entre 14 y 64 años', 'Cuidados temporales de salud a miembros del hogar, entre 14 y 64 años', 'Dar medicamentos, hacer curaciones, aplicar terapias, etc.  Concurrir a servicios de salud, incluyendo tiempo de espera. Es independiente del lugar de asistencia del miembro del hogar. No incluye traslados, que se registran en el código 423. Excluye a personas con discapacidad o dependencia permanente.', 'actividad422.png', false, 'M', false, false, false, true, false, 1);
INSERT INTO actividades_codigos VALUES (443, NULL, 'Acompañamiento y traslados a  miembros del hogar con discapacidad o dependencia permanente (todas las edades)', 'Acompañamiento y traslados a  miembros del hogar con discapacidad o dependencia permanente (todas las edades)', 'Acompañamiento y traslados para las actividades de cuidado y apoyo personal o por motivos de salud. Comprende vistas al médico, actividades sociales o deportivas, gestiones legales, administrativas o financieras, etc. Es independiente del lugar de asistencia del miembro del hogar.', 'actividad443.png', false, 'F', false, false, false, true, false, 1);
INSERT INTO actividades_codigos VALUES (51, 'UT28', 'Ayuda a otros hogares (trabajo no remunerado para otros hogares)', 'Ayudar a otros hogares (trabajo no remunerado para otros hogares)', 'Quehaceres domésticos (limpiar, cocinar, pagos de facturas, cuidados de mascotas, etc) y cuidado a personas de otros hogares, siempre que se trate de tareas NO remuneradas. Incluye tiempo de traslado.', 'actividad51.png', false, 'M', false, true, false, true, false, 1);
INSERT INTO actividades_codigos VALUES (32, 'UT6', 'Limpiar la casa', 'Limpiar la casa', 'Incluye el orden y la limpieza de la vivienda (baños, dormitorios, living, etc.) donde habita el hogar; muebles, cortinas, pisos del exterior y del interior, hacer y cambiar las camas, etc.; seleccionar o tirar la basura. Excluye la limpieza de los utensilios para preparar y servir comida.', 'actividad32.png', false, 'D', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (414, 'UT17', 'Acompañamiento y traslados a niños del hogar, menores de 14 años', 'Acompañamiento y traslados a niños del hogar, menores de 14 años', 'Acompañamiento y traslados a guarderías o escuelas, centros de salud u otros lugares (excursiones, museos, parques, etc.). Excluye a personas con discapacidad o dependencia permanente.', 'actividad414.png', false, 'F', false, true, true, false, false, 1);
INSERT INTO actividades_codigos VALUES (423, 'UT22', 'Acompañamiento y traslados a miembros del hogar, entre 14 y 64 años', 'Acompañamiento y traslados a miembros del hogar, entre 14 y 64 años', 'Acompañamiento y traslados para las actividades de cuidado y apoyo personal o por motivos de salud. Comprende visitas al médico, a establecimientos educativos, actividades sociales o deportivas. Es independiente del lugar de asistencia del miembro del hogar. Excluye a personas con discapacidad o dependencia permanente.', 'actividad423.png', false, 'F', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (61, 'UT30', 'Aprendizaje y estudio', 'Estudiar', 'Incluye asistir a clases en el sistema educativo, a distancia, en cursos extracurriculares (idiomas u otra formación no brindada por la escuela), estudiar y hacer tareas, y actividades de aprendizaje y estudio complementarias, recreos y compra de materiales. Está excluido el tiempo de traslado y el de comidas y meriendas.', 'actividad61.png', false, 'M', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (62, NULL, 'Traslados para aprendizaje y estudio', 'Viajar para estudiar', 'Desplazamiento desde y hasta el lugar de estudio. Incluye el tiempo de espera del transporte.', 'actividad62.png', false, 'F', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (71, 'UT31', 'Convivencia social', 'Reunirse con familiares o amigos', 'Convivencia con familia, amigos u otras personas, asistencia a actividades comunitarias, cívicas o religiosas. La finalidad de las actividades es la socialización; incluye la comunicación vía telefónica, por Internet, etc., y la escritura de correspondencia personal (comprende correo electrónico). Incluye también la asistencia a eventos sociales (cumpleaños, casamientos, etc.).', 'actividad71.png', false, 'M', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (72, 'UT32', 'Eventos culturales y deportivos', 'Asistir a enventos o espectáculos', 'Asistencia a eventos culturales (exposiciones de artes plásticas, teatro, música, danza, museos, etc.), deportivos y de entretenimiento.', 'actividad72.png', false, 'M', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (73, 'UT33', 'Actividades artísticas y aficiones', 'Realizar actividades artísticas, juegos o entretenimientos', 'Incluye realizar, como hobby, actividades artísticas (plásticas, gráficas, literarias o escénicas), juegos de mesa o azar, juegos por medios electrónicos, etc. No incluye actividades de trabajo o estudio.', 'actividad73.png', false, 'M', false, false, false, false, false, 1);
INSERT INTO actividades_codigos VALUES (999, 'UT42', 'Otro', 'Realizar otras actividades', 'Cualquier otra actividad que no esté comprendida en las categorías anteriores.', 'actividad9992.gif', false, 'M', false, false, false, false, false, 1);

ALTER TABLE ONLY actividades_codigos
    ADD CONSTRAINT act_cod_pkey PRIMARY KEY (codigo);
    
ALTER TABLE actividades_codigos
   ADD CONSTRAINT "Grupos considerados" CHECK (grupo::text in ('D','F','M'));    

ALTER TABLE ONLY actividades_codigos
    ADD CONSTRAINT actividades_codigos_tiempo_logico_fk FOREIGN KEY (act_cod_tlg) REFERENCES tiempo_logico(tlg_tlg);


GRANT ALL ON TABLE actividades_codigos TO tedede_php;
GRANT SELECT ON TABLE actividades_codigos TO ut2016_ro;


