drop table if exists encu.valcan;
CREATE TABLE encu.valcan
(
  pla_ope character varying(50) NOT NULL,
  pla_ca_p numeric,
  pla_alquiler_p numeric,
  pla_gastoexpensas_p numeric,
  pla_gas_p numeric,
  pla_electricidad_p numeric,
  pla_agua_p numeric,
  pla_jardin_p numeric,
  pla_preescyprim_p numeric,
  pla_secundaria_p numeric,
  pla_artytextos_p numeric,
  pla_transpu_p numeric,
  pla_comunicaciones_p numeric,
  pla_limpieza_p numeric,
  pla_esparcimiento_p numeric,
  pla_bieneserv_p numeric,
  pla_indadultos_p numeric,
  pla_indninios_p numeric,
  pla_salud_p numeric,
  pla_equipamiento_p numeric,
  pla_ca_c numeric,
  pla_alquiler_c numeric,
  pla_gastoexpensas_c numeric,
  pla_gas_c numeric,
  pla_electricidad_c numeric,
  pla_agua_c numeric,
  pla_jardin_c numeric,
  pla_preescyprim_c numeric,
  pla_secundaria_c numeric,
  pla_artytextos_c numeric,
  pla_transpu_c numeric,
  pla_comunicaciones_c numeric,
  pla_limpieza_c numeric,
  pla_esparcimiento_c numeric,
  pla_bieneserv_c numeric,
  pla_indadultos_c numeric,
  pla_indninios_c numeric,
  pla_salud_c numeric,
  pla_equipamiento_c numeric,
  pla_tlg bigint NOT NULL,
  pla_axesorios_c numeric,
  pla_servind_c numeric, 
  --A PARTIR DE ACA LO NUEVO 
  pla_ca_p_t               numeric,
  pla_alquiler_p_t         numeric,
  pla_gastoexpensas_p_t    numeric,
  pla_gas_p_t              numeric,
  pla_electricidad_p_t     numeric,
  pla_agua_p_t             numeric,
  pla_jardin_p_t           numeric,
  pla_preescyprim_p_t      numeric,
  pla_secundaria_p_t       numeric,
  pla_artytextos_p_t       numeric,
  pla_transpu_p_t          numeric,
  pla_comunicaciones_p_t   numeric,
  pla_limpieza_p_t         numeric,
  pla_esparcimiento_p_t    numeric,
  pla_bieneserv_p_t        numeric,
  pla_indadultos_p_t       numeric,
  pla_indninios_p_t        numeric,
  pla_salud_p_t            numeric,
  pla_equipamiento_p_t     numeric,
  pla_ca_c_t               numeric,
  pla_alquiler_c_t         numeric,
  pla_gastoexpensas_c_t    numeric,
  pla_gas_c_t              numeric,
  pla_electricidad_c_t     numeric,
  pla_agua_c_t             numeric,
  pla_jardin_c_t           numeric,
  pla_preescyprim_c_t      numeric,
  pla_secundaria_c_t       numeric,
  pla_artytextos_c_t       numeric,
  pla_transpu_c_t          numeric,
  pla_comunicaciones_c_t   numeric,
  pla_limpieza_c_t         numeric,
  pla_esparcimiento_c_t    numeric,
  pla_bieneserv_c_t        numeric,
  pla_indadultos_c_t       numeric,
  pla_indninios_c_t        numeric,
  pla_axesorios_c_t        numeric,
  pla_servind_c_t          numeric,
  pla_salud_c_t            numeric,
  pla_equipamiento_c_t     numeric,
  CONSTRAINT valcan_pkey PRIMARY KEY (pla_ope),
  CONSTRAINT valcan_operativos_fk FOREIGN KEY (pla_ope)
      REFERENCES encu.operativos (ope_ope) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT valcan_tiempo_logico_fk FOREIGN KEY (pla_tlg)
      REFERENCES encu.tiempo_logico (tlg_tlg) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION

);
ALTER TABLE encu.valcan
  OWNER TO tedede_php;
GRANT ALL ON TABLE encu.valcan TO tedede_php;