--etoi143
CREATE TABLE encu.ocupacion
(
  ocu_ocu integer NOT NULL,
  ocu_descripcion character varying(200),
  ocu_tlg bigint,
  CONSTRAINT ocupacion_pk PRIMARY KEY (ocu_ocu),
  CONSTRAINT "texto de descripción de ocupacion inválido" CHECK (comun.cadena_valida(ocu_descripcion, 'castellano'))
);

ALTER TABLE encu.ocupacion
  OWNER TO tedede_php;
  

insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (00001,'Funcionarios del poder ejecutivo nacional, provincial, municipal y/o departamental- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (01001,'Funcionarios del poder legislativo nacional, provincial/ municipal y/o departamental- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (02001,'Funcionarios del poder judicialfederal/ nacional/ provincial/municipal y/o departamental- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (03001,'Directivos de organismos, empresas e instituciones estatales - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (04001,'Directivos de instituciones sociales (comunales, políticas, gremiales, religiosas, derechos humanos, medio ambiente y otras instituciones de bien público) - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (05001,'Directivos de pequeñas y microempresas (patrones de 1 a 5 personas) - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (05002,'Directivos de pequeñas y microempresas (patrones de 1 a 5 personas) - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (06001,'Directivos de medianas empresas privadas productora de bienes y/o servicios (establecimientos de 6 a 40 personas) - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (07001,'Directivos de grandes empresas privadas productoras de bienes y/o servicios (establecimientos de más de 41 personas) - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (10191,'Cuenta propia de la gestión administrativa, planificación y control de gestión- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (10192,'Cuenta propia de la gestión administrativa, planificación y control de gestión- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (10193,'Cuenta propia de la gestión administrativa, planificación y control de gestión- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (10199,'Cuenta propia de la gestión administrativa, planificación y control de gestión- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (10201,'Jefes de gestión administrativa, de planificación, y control de gestión - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (10202,'Jefes de gestión administrativa, de planificación, y control de gestión - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (10203,'Jefes de gestión administrativa, de planificación, y control de gestión - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (10209,'Jefes de gestión administrativa, de planificación, y control de gestión - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (10391,'Trabajadores de la gestión administrativa, de planificación y control degestión Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (10392,'Trabajadores de la gestión administrativa, de planificación y control degestión Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (10393,'de la gestión administrativa, de planificación y control degestiónCalificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (10394,'de la gestión administrativa, de planificación y control degestión- No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (10399,'de la gestión administrativa, de planificación y control degestión - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (11191,'Cuenta propia de la gestión jurídico-legal - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (11192,'Cuenta propia de la gestión jurídico-legal - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (11193,'Cuenta propia de la gestión jurídico-legal - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (11199,'Cuenta propia de maquinarias de la gestión jurídico-legal - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (11201,'Jefes de la gestión jurídico-legal - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (11202,'Jefes de la gestión jurídico-legal- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (11203,'Jefes de la gestión jurídico-legal- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (11209,'Jefes de la gestión jurídico-legal- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (11391,'Trabajadores de la gestión jurídico-legal - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (11392,'Trabajadores de la gestión jurídico-legal - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (11393,'Trabajadores de la gestión jurídico-legal - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (11394,'Trabajadores de la gestión jurídico-legal - No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (11399,'Trabajadores de la gestión jurídico-legal - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (20191,'Cuenta propia de la gestión presupuestaria, contable y financiera- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (20192,'Cuenta propia de la gestión presupuestaria, contable y financiera- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (20193,'Cuenta propia de la gestión presupuestaria, contable y financiera- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (20199,'Cuenta propia de la gestión presupuestaria, contable y financiera- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (20201,'Jefes de gestión presupuestaria, contable y financiera- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (20202,'Jefes de gestión presupuestaria, contable y financiera - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (20203,'Jefes de gestión presupuestaria, contable y financiera - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (20209,'Jefes de gestión presupuestaria, contable y financiera - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (20391,'Trabajadores de la gestión presupuestaria, contable y financiera - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (20392,'Trabajadores de la gestión presupuestaria, contable y financiera- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (20393,'Trabajadores de la gestión presupuestaria, contable y financiera- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (20394,'Trabajadores de la gestión presupuestaria, contable y financiera- No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (20399,'Trabajadores de la gestión presupuestaria, contable y financiera- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (30191,'Cuenta propia de la comercialización directa (tradicional y telefónicos)- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (30192,'Cuenta propia de la comercialización directa (tradicional y telefónicos)- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (30193,'Cuenta propia de la comercialización directa (tradicional y telefónicos)- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (30199,'Cuenta propia de la comercialización directa (tradicional y telefónicos)- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (30201,'Jefes de la comercialización directa (tradicional y telefónicos)- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (30202,'Jefes de la comercialización directa (tradicional y telefónicos)- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (30203,'Jefes de la comercialización directa (tradicional y telefónicos)- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (30209,'Jefes de la comercialización directa (tradicional y telefónicos)- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (30391,'Vendedores y trabajadores de la comercialización directa (tradicional y telefónicos)- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (30392,'Vendedores y trabajadores de la comercialización directa (tradicional y telefónicos)- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (30393,'Vendedores y trabajadores de la comercialización directa (tradicional y telefónicos)- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (30394,'Vendedores y trabajadores de la comercialización directa (tradicional y telefónicos) - No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (30399,'Vendedores y trabajadores de la comercialización directa (tradicional y telefónicos) - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (31191,'Cuenta propia viajantes, corredores comerciales y vendedores domiciliarios y promotores- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (31192,'Cuenta propia viajantes, corredores comerciales y vendedores domiciliarios y promotores- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (31193,'Cuenta propia viajantes, corredores comerciales y vendedores domiciliarios y promotores- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (31199,'Cuenta propia viajantes, corredores comerciales y vendedores domiciliarios y promotores- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (31201,'Jefes de viajantes, corredores comerciales y vendedores domiciliarios- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (31202,'Jefes de viajantes, corredores comerciales y vendedores domiciliarios- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (31203,'Jefes de viajantes, corredores comerciales y vendedores domiciliarios- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (31209,'Jefes de viajantes, corredores comerciales y vendedores domiciliarios- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (31391,'Trabajadores viajantes, corredores comerciales y vendedores domiciliarios- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (31392,'Trabajadores viajantes, corredores comerciales y vendedores domiciliarios- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (31393,'Trabajadores viajantes, corredores comerciales y vendedores domiciliarios- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (31394,'Trabajadores viajantes, corredores comerciales y vendedores domiciliarios- No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (31399,'Trabajadores viajantes, corredores comerciales y vendedores domiciliarios- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (32191,'Cuenta propia de otras ocupaciones de la comercialización indirecta- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (32192,'Cuenta propia de otras ocupaciones de la comercialización indirecta- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (32193,'Cuenta propia de otras ocupaciones de la comercialización indirecta- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (32199,'Cuenta propia de otras ocupaciones de la comercialización indirecta- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (32201,'Jefes de otras ocupaciones de la comercialización- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (32202,'Jefes de otras ocupaciones de la comercialización- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (32203,'Jefes de otras ocupaciones de la comercialización- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (32209,'Jefes de otras ocupaciones de la comercialización- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (32391,'Trabajadores de otras ocupaciones de la comercialización- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (32392,'Trabajadores de otras ocupaciones de la comercialización- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (32393,'Trabajadores de otras ocupaciones de la comercialización- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (32394,'Trabajadores de otras ocupaciones de la comercialización- No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (32399,'Trabajadores de otras ocupaciones de la comercialización- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (33191,'Cuenta propia vendedores ambulantes y callejeros- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (33192,'Cuenta propia vendedores ambulantes y callejeros- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (33193,'Cuenta propia vendedores ambulantes y callejeros- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (33194,'Cuenta propia vendedores ambulantes y callejeros- No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (33199,'Cuenta propia vendedores ambulantes y callejeros- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (33201,'Jefes de los vendedores ambulantes y callejeros- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (33202,'Jefes de los vendedores ambulantes y callejeros- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (33203,'Jefes de los vendedores ambulantes y callejeros- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (33209,'Jefes de los vendedores ambulantes y callejeros- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (33391,'Trabajadores vendedores ambulantes y callejeros- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (33392,'Trabajadores vendedores ambulantes y callejeros- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (33393,'Trabajadores vendedores ambulantes y callejeros- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (33394,'Trabajadores vendedores ambulantes y callejeros - No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (33399,'Trabajadores vendedores ambulantes y callejeros- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (34191,'Cuenta propia del Transporte- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (34193,'Cuenta propia del Transporte- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (34194,'Cuenta propia del Transporte- No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (34199,'Cuenta propia del Transporte- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (34201,'Jefes de servicios de transporte- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (34202,'Jefes de servicios de transporte- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (34203,'Jefes de servicios de transporte- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (34209,'Jefes de servicios de transporte- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (34391,'Trabajadores del transporte - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (34392,'Trabajadores del transporte - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (34393,'Trabajadores del transporte - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (34394,'Trabajadores del transporte - No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (34399,'Trabajadores del transporte - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (35191,'Cuenta propia de las telecomunicaciones- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (35192,'Cuenta propia de las telecomunicaciones- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (35193,'Cuenta propia de las telecomunicaciones- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (35199,'Cuenta propia de las telecomunicaciones- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (35201,'Jefes de las telecomunicaciones- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (35202,'Jefes de las telecomunicaciones- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (35203,'Jefes de las telecomunicaciones- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (35209,'Jefes de las telecomunicaciones- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (35391,'Trabajadores de las telecomunicaciones- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (35392,'Trabajadores de las telecomunicaciones Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (35393,'Trabajadores de las telecomunicaciones Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (35394,'Trabajadores de las telecomunicaciones- No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (35399,'Trabajadores de las telecomunicaciones Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (36191,'Cuenta propia del almacenaje - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (36192,'Cuenta propia del almacenaje - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (36193,'Cuenta propia del almacenaje - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (36194,'Cuenta propia del almacenaje - No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (36199,'Cuenta propia del almacenaje - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (36201,'Jefes del almacenaje - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (36202,'Jefes del almacenaje - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (36203,'Jefes del almacenaje - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (36209,'Jefes del almacenaje - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (36391,'Trabajadores del almacenaje- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (36392,'Trabajadores del almacenaje- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (36393,'Trabajadores del almacenaje- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (36394,'Trabajadores del almacenaje- No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (36399,'Trabajadores del almacenaje- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (40191,'Cuenta propia de la salud y sanidad- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (40192,'Cuenta propia de la salud y sanidad- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (40193,'Cuenta propia de la salud y sanidad- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (40199,'Cuenta propia de la salud y sanidad- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (40201,'Jefes de la salud y sanidad - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (40202,'Jefes de la salud y sanidad - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (40203,'Jefes de la salud y sanidad - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (40209,'Jefes de la salud y sanidad - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (40391,'Trabajadores de salud y sanidad- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (40392,'Trabajadores de salud y sanidad - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (40393,'Trabajadores de salud y sanidad - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (40394,'Trabajadores de salud y sanidad - No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (40399,'Trabajadores de salud y sanidad - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (41191,'Cuenta propia de la educación- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (41192,'Cuenta propia de la educación- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (41193,'Cuenta propia de la educación- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (41199,'Cuenta propia de la educación- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (41201,'Jefes de la educación - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (41202,'Jefes de la educación - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (41203,'Jefes de la educación - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (41209,'Jefes de la educación - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (41391,'Trabajadores de la educación- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (41392,'Trabajadores de la educación- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (41393,'Trabajadores de la educación - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (41394,'Trabajadores de la educación - No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (41399,'Trabajadores de la educación - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (42191,'Cuenta propia de la investigacióncientífica y tecnológica- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (42192,'Cuenta propia de la investigacióncientífica y tecnológica- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (42193,'Cuenta propia de la investigación científica y tecnológica- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (42199,'Cuenta propia de la investigación científica y tecnológica- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (42201,'Jefes de la investigación científica y tecnológica- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (42202,'Jefes de la investigación científica y tecnológica- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (42203,'Jefes de la investigación científica y tecnológica- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (42209,'Jefes de la investigación científica y tecnológica- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (42391,'Trabajadores de la investigación científica y tecnológica- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (42392,'Trabajadores de la investigación científica y tecnológica- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (42393,'Trabajadores de la investigación científica y tecnológica- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (42394,'Trabajadores de la investigación científica y tecnológica- No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (42399,'Trabajadores de la investigación científica y tecnológica- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (43191,'Cuenta propia de la asesoría y consultoría- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (43192,'Cuenta propia de la asesoría y consultoría- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (43193,'Cuenta propia de la asesoría y consultoría- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (43199,'Cuenta propia de la asesoría y consultoría- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (43201,'Jefes de la asesoría y consultoría- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (43202,'Jefes de la asesoría y consultoría- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (43203,'Jefes de la asesoría y consultoría- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (43209,'Jefes de la asesoría y consultoría- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (43391,'Trabajadores de la asesoría y consultoría- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (43392,'Trabajadores de la asesoría y consultoría- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (43393,'Trabajadores de la asesoría y consultoría- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (43394,'Trabajadores de la asesoría y consultoría- No calificado',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (43399,'Trabajadores de la asesoría y consultoría- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (44191,'Cuenta propia de la prevención de siniestros(naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (44192,'Cuenta propia de la prevención de siniestros(naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (44193,'Cuenta propia de la prevención de siniestros(naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (44199,'Cuenta propia de la prevención de siniestros(naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (44201,'Jefes de la prevención de siniestros (naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (44202,'Jefes de la prevención de siniestros (naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (44203,'Jefes de la prevención de siniestros (naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (44209,'Jefes de la prevención de siniestros (naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (44391,'Trabajadores de prevención de siniestros(naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (44392,'Trabajadores de prevención de siniestros(naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (44393,'Trabajadores de prevención de siniestros(naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (44394,'Trabajadores de prevención de siniestros(naturales, humanos, productivos) y atención del medio ambiente y ecología - No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (44399,'Trabajadores de prevención de siniestros(naturales, humanos, productivos) y atención del medio ambiente y ecología- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (45191,'Cuenta propia de la comunicación de masas- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (45192,'Cuenta propia de la comunicación de masas- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (45193,'Cuenta propia de la comunicación de masas - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (45199,'Cuenta propia de la comunicación de masas - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (45201,'Jefes de la comunicación de masas- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (45202,'Jefes de la comunicación de masas- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (45203,'Jefes de la comunicación de masas- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (45209,'Jefes de la comunicación de masas- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (45391,'Trabajadores de la comunicación de masas- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (45392,'Trabajadores de la comunicación de masas- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (45393,'Trabajadores de la comunicación de masas- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (45394,'Trabajadores de la comunicación de masas- No calificado',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (45399,'Trabajadores de la comunicación de masas- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (46191,'Cuenta propia de los servicios sociales, comunales, políticos, gremiales y religiosos- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (46192,'Cuenta propia de los servicios sociales, comunales, políticos, gremiales y religiosos- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (46193,'Cuenta propia de los servicios sociales, comunales, políticos, gremiales y religiosos- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (46199,'Cuenta propia de los servicios sociales, comunales, políticos, gremiales y religiosos- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (46201,'Jefes de los servicios sociales, comunales, políticos, gremiales y religiosos- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (46202,'Jefes de los servicios sociales, comunales, políticos, gremiales y religiosos - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (46203,'Jefes de los servicios sociales, comunales, políticos, gremiales y religiosos - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (46209,'Jefes de los servicios sociales, comunales, políticos, gremiales y religiosos - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (46391,'Trabajadores de servicios sociales, comunales, políticos, gremiales y religiosos- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (46392,'Trabajadores de servicios sociales, comunales, políticos, gremiales y religiosos- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (46393,'Trabajadores de servicios sociales, comunales, políticos, gremiales y religiosos- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (46394,'Trabajadores de servicios sociales, comunales, políticos, gremiales y religiosos- No calificado',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (46399,'Trabajadores de servicios sociales, comunales, políticos, gremiales y religiosos- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (47191,'Cuenta propia de los servicios de vigilancia y seguridad civil- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (47192,'Cuenta propia de los servicios de vigilancia y seguridad civil- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (47193,'Cuenta propia de los servicios de vigilancia y seguridad civil- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (47199,'Cuenta propia de los servicios de vigilancia y seguridad civil- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (47201,'Jefes de los servicios de vigilancia y seguridad civil- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (47202,'Jefes de los servicios de vigilancia y seguridad civil- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (47203,'Jefes de los servicios de vigilancia y seguridad civil- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (47209,'Jefes de los servicios de vigilancia y seguridad civil- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (47391,'Trabajadores de los servicios de vigilancia y seguridad civil - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (47392,'Trabajadores de los servicios de vigilancia y seguridad civil - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (47393,'Trabajadores de los servicios de vigilancia y seguridad civil- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (47394,'Trabajadores de los servicios de vigilancia y seguridad civil- No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (47399,'Trabajadores de los servicios de vigilancia y seguridad civil- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (48391,'Trabajadores de los servicios policiales- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (48392,'Trabajadores de los servicios policiales- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (48393,'Trabajadores de los servicios policiales- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (48394,'Trabajadores de los servicios policiales- No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (48399,'Trabajadores de los servicios policiales- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (49391,'Trabajadores de las FFAA, Gendarmería y Prefectura- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (49392,'Trabajadores de las FFAA, Gendarmería y Prefectura- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (49393,'Trabajadores de las FFAA, Gendarmería y Prefectura Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (49394,'Trabajadores de las FFAA, Gendarmería y Prefectura- No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (49399,'Trabajadores de las FFAA, Gendarmería y Prefectura Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (50191,'Cuenta propia del arte- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (50192,'Cuenta propia del arte - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (50193,'Cuenta propia del arte - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (50199,'Cuenta propia del arte - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (50201,'Jefes del arte- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (50202,'Jefes del arte- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (50203,'Jefes del arte- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (50209,'Jefes del arte- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (50391,'Trabajadores del arte - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (50392,'Trabajadores del arte - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (50393,'Trabajadores del arte- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (50394,'Trabajadores del arte - No calificado',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (50399,'Trabajadores del arte- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (51191,'Cuenta propia del deporte- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (51192,'Cuenta propia del deporte - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (51193,'Cuenta propia del deporte - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (51199,'Cuenta propia del deporte - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (51201,'Jefes del deporte- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (51202,'Jefes del deporte- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (51203,'Jefes del deporte- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (51209,'Jefes del deporte- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (51391,'Trabajadores del deporte - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (51392,'Trabajadores del deporte - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (51393,'Trabajadores del deporte - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (51394,'Trabajadores del deporte - No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (51399,'Trabajadores del deporte - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (52191,'Cuenta propia de la recreación - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (52192,'Cuenta propia de la recreación - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (52193,'Cuenta propia de la recreación - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (52199,'Cuenta propia de la recreación - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (52201,'Jefes de la recreación - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (52202,'Jefes de la recreación - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (52203,'Jefes de la recreación - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (52209,'Jefes de la recreación - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (52391,'Trabajadores de la recreación- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (52392,'Trabajadores de la recreación- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (52393,'Trabajadores de la recreación- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (52394,'Trabajadores de la recreación- No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (52399,'Trabajadores de la recreación- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (53191,'Cuenta propia de servicios gastronómicos- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (53192,'Cuenta propia de servicios gastronómicos - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (53193,'Cuenta propia de servicios gastronómicos- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (53199,'Cuenta propia de servicios gastronómicos- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (53201,'Jefes de servicios gastrnómicos- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (53202,'Jefes de servicios gastrnómicos- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (53203,'Jefes de servicios gastrnómicos- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (53209,'Jefes de servicios gastrnómicos- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (53391,'Trabajadores de servicios gastrnómicos- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (53392,'Trabajadores de servicios gastrnómicos- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (53393,'Trabajadores de servicios gastrnómicos- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (53394,'Trabajadores de servicios gastrnómicos- No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (53399,'Trabajadores de servicios gastrnómicos- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (54191,'Cuenta propia de los servicios de alojamiento y turismo- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (54192,'Cuenta propia de los servicios de alojamiento y turismo- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (54193,'Cuenta propia de los servicios de alojamiento y turismo- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (54199,'Cuenta propia de los servicios de alojamiento y turismo- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (54201,'Jefes del alojamiento y turismo- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (54202,'Jefes del alojamiento y turismo - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (54203,'Jefes del alojamiento y turismo - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (54209,'Jefes del alojamiento y turismo - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (54391,'del alojamiento y turismo- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (54392,'del alojamiento y turismo- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (54393,'del alojamiento y turismo- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (54394,'del alojamiento y turismo- No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (54399,'del alojamiento y turismo- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (55193,'Cuenta propia sin operaión de maquinarias de los servicios domésticos - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (55203,'Jefes de los servicios domésticos - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (55393,'Trabajadores del servicio doméstico - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (55394,'Trabajadores del servicio doméstico - No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (55399,'Trabajadores del servicio doméstico - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (56193,'Cuenta propia de los servicios de limpieza no doméstica- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (56202,'Jefes de los servicios de limpieza no doméstica- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (56203,'Jefes de los servicios de limpieza no doméstica- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (56209,'Jefes de los servicios de limpieza no doméstica- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (56393,'Trabajadores de servicios de limpieza no domésticos Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (56394,'Trabajadores de servicios de limpieza no domésticos - No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (56399,'Trabajadores de servicios de limpieza no domésticos Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (57191,'Cuenta propia del cuidado y la atenciónde las personas - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (57192,'Cuenta propia del cuidado y la atenciónde las personas- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (57193,'Cuenta propia del cuidado y la atenciónde las personas - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (57199,'Cuenta propia del cuidado y la atenciónde las personas - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (57201,'Jefes de los servicios del cuidado y la atención de las personas- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (57202,'Jefes de los servicios del cuidado y la atención de las personas- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (57203,'Jefes de los servicios del cuidado y la atención de las personas- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (57209,'Jefes de los servicios del cuidado y la atención de las personas- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (57391,'Trabajadores del cuidado y la atención de personas- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (57392,'Trabajadores del cuidado y la atención de personas- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (57393,'Trabajadores del cuidado y la atención de personas- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (57394,'Trabajadores del cuidado y la atención de personas- No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (57399,'Trabajadores del cuidado y la atención de personas- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (58191,'Cuenta propia de otras ocupaciones de los servicios sociales varios- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (58192,'Cuenta propia de otras ocupaciones de los servicios sociales varios- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (58193,'Cuenta propia de otras ocupaciones de los servicios sociales varios- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (58199,'Cuenta propia de otras ocupaciones de los servicios sociales varios- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (58201,'Jefes de otras ocupaciones de los servicios sociales varios - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (58202,'Jefes de otras ocupaciones de los servicios sociales varios - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (58203,'Jefes de otras ocupaciones de los servicios sociales varios - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (58209,'Jefes de otras ocupaciones de los servicios sociales varios - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (58391,'Trabajadores de otros servicios- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (58392,'Trabajadores de otros servicios - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (58393,'Trabajadores de otros servicios - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (58394,'Trabajadores de otros servicios - No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (58399,'Trabajadores de otros servicios - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (60191,'Cuenta propia de la producción agrícola- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (60192,'Cuenta propia de la producción agrícola- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (60193,'Cuenta propia de la producción agrícola- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (60199,'Cuenta propia de la producción agrícola- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (60201,'Jefes de la producción agrícola- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (60202,'Jefes de la producción agrícola- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (60203,'Jefes de la producción agrícola- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (60209,'Jefes de la producción agrícola- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (60391,'Trabajadores de la producción agrícola- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (60392,'Trabajadores de la producción agrícola- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (60393,'Trabajadores de la producción agrícola- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (60394,'Trabajadores de la producción agrícola- No calificada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (60399,'Trabajadores de la producción agrícola- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (61191,'Cuenta propia de la producción ganadera- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (61192,'Cuenta propia de la producción ganadera- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (61193,'Cuenta propia de la producción ganadera- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (61199,'Cuenta propia de la producción ganadera- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (61201,'Jefes de la producción ganadera- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (61202,'Jefes de la producción ganadera- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (61203,'Jefes de la producción ganadera- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (61209,'Jefes de la producción ganadera- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (61391,'Trabajadores de la producción ganadera- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (61392,'Trabajadores de la producción ganadera- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (61393,'Trabajadores de la producción ganadera- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (61394,'Trabajadores de la producción ganadera - No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (61399,'Trabajadores de la producción ganadera- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (62191,'Cuenta propia de la producción forestal- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (62192,'Cuenta propia de la producción forestal- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (62193,'Cuenta propia de la producción forestal- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (62199,'Cuenta propia de la producción forestal- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (62201,'Jefes de la producción forestal- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (62202,'Jefes de la producción forestal- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (62203,'Jefes de la producción forestal- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (62209,'Jefes de la producción forestal- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (62391,'Trabajadores de la producción forestal- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (62392,'Trabajadores de la producción forestal- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (62393,'Trabajadores de la producción forestal- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (62394,'Trabajadores de la producción forestal- No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (62399,'Trabajadores de la producción forestal- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (63191,'Cuenta propia de la producción apicolaavicola yde otras especies menores- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (63192,'Cuenta propia de la producción apicolaavicola yde otras especies menores- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (63193,'Cuenta propia de la producción apicolaavicola yde otras especies menores- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (63199,'Cuenta propia de la producción apicolaavicola yde otras especies menores- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (63201,'Jefes de la producción apicolaavicola y de otras especies menores- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (63202,'Jefes de la producción apicolaavicola y de otras especies menores- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (63203,'Jefes de la producción apicolaavicola y de otras especies menores- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (63209,'Jefes de la producción apicolaavicola y de otras especies menores- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (63391,'Trabajadores de la producción apicolaavicola y de otras especies menores- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (63392,'Trabajadores de la producción apicolaavicola y de otras especies menores- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (63393,'Trabajadores de la producción apicolaavicola y de otras especies menores- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (63394,'Trabajadores de la producción apicolaavicola y de otras especies menores - No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (63399,'Trabajadores de la producción apicolaavicola y de otras especies menores- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (64191,'Cuenta propia de la producción pesquera- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (64192,'Cuenta propia de la producción pesquera- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (64193,'Cuenta propia de la producción pesquera- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (64199,'Cuenta propia de la producción pesquera- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (64201,'Jefes de la producción pesquera- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (64202,'Jefes de la producción pesquera- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (64203,'Jefes de la producción pesquera- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (64209,'Jefes de la producción pesquera- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (64391,'Trabajadores de la producción pesquera- Calificaciónprofesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (64392,'Trabajadores de la producción pesquera- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (64393,'Trabajadores de la producción pesquera- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (64394,'Trabajadores de la producción pesquera - No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (64399,'Trabajadores de la producción pesquera- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (65191,'Cuenta propia de la caza- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (65192,'Cuenta propia de la caza- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (65193,'Cuenta propia de la caza- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (65199,'Cuenta propia de la caza- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (65201,'Jefes de la caza- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (65202,'Jefes de la caza- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (65203,'Jefes de la caza- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (65209,'Jefes de la caza- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (65391,'Trabajadores de la caza- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (65392,'Trabajadores de la caza- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (65393,'Trabajadores de la caza- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (65394,'Trabajadores de la caza - No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (65399,'Trabajadores de la caza- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (70191,'Cuenta propia de la producción extractiva- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (70192,'Cuenta propia de la producción extractiva- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (70193,'Cuenta propia de la producción extractiva- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (70199,'Cuenta propia de la producción extractiva- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (70201,'Jefes de la producción extractiva- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (70202,'Jefes de la producción extractiva- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (70203,'Jefes de la producción extractiva- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (70209,'Jefes de la producción extractiva- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (70391,'Trabajadores de la producción extractivaCalificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (70392,'Trabajadores de la producción extractivaCalificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (70393,'Trabajadores de la producción extractiva- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (70394,'Trabajadores de la producción extractiva- No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (70399,'Trabajadores de la producción extractiva- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (71191,'Cuenta propia de la producción de energ¡a, agua y gas- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (71192,'Cuenta propia de la producción de energ¡a, agua y gas- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (71193,'Cuenta propia de la producción de energ¡a, agua y gas - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (71199,'Cuenta propia de la producción de energ¡a, agua y gas- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (71201,'Jefes de la producción de energia, agua y gas - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (71202,'Jefes de la producción de energia, agua y gas - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (71203,'Jefes de la producción de energia, agua y gas - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (71209,'Jefes de la producción de energia, agua y gas - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (71391,'Trabajadores de la producción de energia, agua y gas - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (71392,'Trabajadores de la producción de energia, agua y gas - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (71393,'Trabajadores de la producción de energia, agua y gas - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (71394,'Trabajadores de la producción de energia, agua y gas - No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (71399,'Trabajadores de la producción de energia, agua y gas - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (72191,'Cuenta propia de la construcción edilicia y de obras de infraestructura y de redes de distribución de energia, agua potable, gas y telefonía - Calificación',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (72192,'Cuenta propia de la construcción edilicia y de obras de infraestructura y de redes de distribución de energia, agua potable, gas y telefonía - Calificación',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (72193,'Cuenta propia de la construcción edilicia y de obras de infraestructura y de redes de distribución de energia, agua potable, gas y telefonía - Calificación',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (72199,'Cuenta propia de la construcción edilicia y de obras de infraestructura y de redes de distribución de energia, agua potable, gas y telefonía - Calificación',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (72201,'Jefes de la construcción edilicia y de obras de infraestructura y de redes de distribución de energ¡a, agua potable, gas y telefonía Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (72202,'Jefes de la construcción edilicia y de obras de infraestructura y de redes de distribución de energ¡a, agua potable, gas y telefonía Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (72203,'Jefes de la construcción edilicia y de obras de infraestructura y de redes de distribución de energ¡a, agua potable, gas y telefonía- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (72209,'Jefes de la construcción edilicia y de obras de infraestructura y de redes de distribución de energ¡a, agua potable, gas y telefonía- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (72391,'Trabajadores de la construcción edilicia, de obras de infraestructura y de redes de distribución de energ¡a, agua potable, gas y telefonía- Calificación pro',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (72392,'Trabajadores de la construcción edilicia, de obras de infraestructura y de redes de distribución de energ¡a, agua potable, gas y telefonía- Calificación téc',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (72393,'Trabajadores de la construcción edilicia, de obras de infraestructura y de redes de distribución de energ¡a, agua potable, gas y telefonía- Calificación ope',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (72394,'Trabajadores de la construcción edilicia, de obras de infraestructura y de redes de distribución de energ¡a, agua potable, gas y telefonía- No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (72399,'Trabajadores de la construcción edilicia, de obras de infraestructura y de redes de distribución de energ¡a, agua potable, gas y telefonía- Calificación ign',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (80191,'Cuenta propia de la producción Industrial y artesanal - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (80192,'Cuenta propia de la producción Industrial y artesanal- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (80193,'Cuenta propia de la producción Industrial y artesanal - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (80199,'Cuenta propia de la producción Industrial y artesanal - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (80201,'Jefes de la producción industrial y artesanal- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (80202,'Jefes de la producción industrial y artesanal- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (80203,'Jefes de la producción industrial y artesanal- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (80209,'Jefes de la producción industrial y artesanal- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (80391,'Trabajadores de la producción',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (80392,'Trabajadores de la producción industrial y artesanal- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (80393,'Trabajadores de la producción industrial y artesanal- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (80394,'Trabajadores de la producción industrial y artesanal- No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (80399,'Trabajadores de la producción industrial y artesanal- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (81191,'Cuenta propia de la producción de software - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (81192,'Cuenta propia de la producción de software - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (81193,'Cuenta propia de la producción de software - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (81199,'Cuenta propia de la producción de software - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (81201,'Jefes de la producción de software- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (81202,'Jefes de la producción de software- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (81203,'Jefes de la producción de software- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (81209,'Jefes de la producción de software- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (81391,'Operadores de sistemas y/o equipos informatizados de la producción de software- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (81392,'Operadores de sistemas y/o equipos informatizados de la producción de software- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (81393,'Operadores de sistemas y/o equipos informatizados de la producción de software- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (81394,'Operadores de sistemas y/o equipos informatizados de la producción de software- No calificado',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (81399,'Operadores de sistemas y/o equipos informatizados de la producción de software- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (82191,'Cuenta propia de la reparación de bienes de consumo - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (82192,'Cuenta propia de la reparación de bienes de consumo - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (82193,'Cuenta propia de la reparación de bienes de consumo - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (82199,'Cuenta propia de la reparación de bienes de consumo - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (82201,'Jefes de la reparación de bienes de consumo - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (82202,'Jefes de la reparación de bienes de consumo - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (82203,'Jefes de la reparación de bienes de consumo - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (82209,'Jefes de la reparación de bienes de consumo - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (82391,'Trabajadores de la reparación de bienes de consumo - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (82392,'Trabajadores de la reparación de bienes de consumo - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (82393,'Trabajadores de la reparación de bienes de consumo- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (82394,'Trabajadores de la reparación de bienes de consumo- No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (82399,'Trabajadores de la reparación de bienes de consumo- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (90191,'Cuenta propia de la instalación y mantenimiento de maquinarias y equipos de la producción de bienes - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (90192,'Cuenta propia de la instalación y mantenimiento de maquinarias y equipos de la producción de bienes - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (90193,'Cuenta propia de la instalación y mantenimiento de maquinarias y equipos de la producción de bienes- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (90199,'Cuenta propia de la instalación y mantenimiento de maquinarias y equipos de la producción de bienes- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (90201,'Jefes de la instalación y mantenimiento de maquinaria y equipos dela producción de bienes- Calificaciónprofesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (90202,'Jefes de la instalación y mantenimiento de maquinaria y equipos dela producción de bienes- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (90203,'Jefes de la instalación y mantenimiento de maquinaria y equipos dela producción de bienes- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (90209,'Jefes de la instalación y mantenimiento de maquinaria y equipos dela producción de bienes- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (90391,'Trabajadores de la instalación y mantenimiento de maquinaria y equipos de la producción de bienes Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (90392,'Trabajadores de la instalación y mantenimiento de maquinaria y equipos de la producción de bienes Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (90393,'Trabajadores de la instalación y mantenimiento de maquinaria y equipos de la producción de bienes Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (90394,'Trabajadores de la instalación y mantenimiento de maquinaria y equipos de la producción de bienes- No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (90399,'Trabajadores de la instalación y mantenimiento de maquinaria y equipos de la producción de bienes Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (91191,'Cuenta propia del desarrollo tecnológico productivo- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (91192,'Cuenta propia del desarrollo tecnológico productivo Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (91193,'Cuenta propia del desarrollo tecnológico productivo Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (91199,'Cuenta propia del desarrollo tecnológico productivo Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (91201,'Jefes del desarrollo tecnológico productivo- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (91202,'Jefes del desarrollo tecnológico productivo- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (91203,'Jefes del desarrollo tecnológico productivo - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (91209,'Jefes del desarrollo tecnológico productivo - Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (91391,'Trabajadores del desarrollo tecnológico Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (91392,'Trabajadores del desarrollo tecnológico Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (91393,'Trabajadores del desarrollo tecnológico Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (91394,'Trabajadores del desarrollo tecnológico- No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (91399,'Trabajadores del desarrollo tecnológico Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (92191,'Cuenta propia de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios- Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (92192,'Cuenta propia de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (92193,'Cuenta propia de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (92199,'Cuenta propia de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (92201,'Jefes de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios Jefes de la instalación y mantenimiento de maquinaria y equipos de la prestación de servici',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (92202,'Jefes de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (92203,'Jefes de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (92209,'Jefes de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (92391,'Trabajadores de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (92392,'Trabajadores de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios- Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (92393,'Trabajadores de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios- Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (92394,'Trabajadores de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios- No calificado',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (92399,'Trabajadores de la instalación y mantenimiento de maquinaria y equipos de la prestación de servicios- Calificación ignorada',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (99191,'Cuenta propia de carácter ignorado - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (99192,'Cuenta propia de carácter ignorado - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (99193,'Cuenta propia de carácter ignorado - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (99199,'Cuenta propia de carácter y calificación ignorados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (99201,'Jefes de calificación profesional, carácter ignorado',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (99202,'Jefes de calificación técnica, carácter ignorado',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (99203,'Jefes de calificación operativa, carácter ignorado',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (99209,'Jefes, resto ignorado',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (99391,'trabajadores de carácter ignorado - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (99392,'trabajadores de carácter ignorado - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (99393,'trabajadores de carácter ignorado - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (99394,'trabajadores de carácter ignorado - No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (99399,'trabajadores de carácter y calificación ignorados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (99991,'trabajadores de carácter y categoría ocupacional ignorados - Calificación profesional',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (99992,'trabajadores de carácter y categoría ocupacional ignorados - Calificación técnica',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (99993,'trabajadores de carácter y categoría ocupacional ignorados - Calificación operativa',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (99994,'trabajadores de carácter y categoría ocupacional ignorados - No calificados',1);
insert into encu.ocupacion (ocu_ocu, ocu_descripcion, ocu_tlg) values (99999,'trabajadores de carácter, y categoría ocupacional y calificación ignorados',1);