-- Role: cvp_owner

-- DROP ROLE cvp_owner;

CREATE ROLE cvp_owner LOGIN
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
-- Role: cvp_usuarios

-- DROP ROLE cvp_usuarios;

CREATE ROLE cvp_usuarios
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
