INSERT INTO estados_ingreso (esting_estado, esting_descripcion, esting_tlg) VALUES ('opc_blanco', 'esta variable está en blanco porque es la que se debe ingresar ahora y no hay errores de saltos', 1),
('opc_homi', 'hay variables anteriores omitidas, estas todavía no están ingresadas ni tienen nada abajo ingresado', 1),
('opc_inconsistente', 'pertenece a alguna inconsistencia', 1),
('opc_inex', 'un valor que no existe entre las opciones', 1),
('opc_nsnc', 'no sabe - no contesta', 1),
('opc_ok', 'OK', 1),
('opc_omit', 'esta variable se omitió el ingreso y era obligatoria', 1),
('opc_rana', 'fuera_de_rango_advertencia', 1),
('opc_rano', 'fuera_de_rango_obligatorio', 1),
('opc_salt', 'esta variable no tiene valor, lo cual es correcto, porque tiene un salto que la pasa por encima', 1),
('opc_sinesp', 'sin especificar', 1),
('opc_sosa', 'una opción sobre una variable que debía ser salteada', 1),
('opc_tipo', 'error de tipo', 1),
('opc_tono', 'esta variable todavía no debe ingresarse porque hay una variable en blanco más arriba', 1);