server:
  port: 62772
  base-url: /marco
db:
  motor: postgresql
  host: localhost
  database: sieh_db
  schema: marco
  user: tedede_php
login:
  table: usuarios
  userFieldName: usu_usu
  passFieldName: usu_clave
  infoFieldList: [usu_usu]
  plus:
    unloggedPath: client/unlogged
    loginPagePath: client/unlogged/login
    successRedirect: /