--tabla rama Eah2012
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (0101,'Cultivos agrícolas');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (0102,'Cría de animales');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (0103,'Cultivo de productos agrícolas en combinación con la cría de animales');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (0104,'Servicios agrícolas y pecuarios, excepto los veterinarios');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (0105,'Caza y captura de animales vivos, repoblación de animales de caza y servicios de apoyo');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (0200,'Silvicultura, extracción de madera y actividades de apoyo');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (0300,'Pesca, acuicultura y actividades de apoyo');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (0500,'Extracción de carbón y lignito');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (0600,'Extracción de petróleo crudo y gas natural');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (0700,'Extracción de minerales metalíferos');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (0800,'Explotación de otras minas y canteras');
--insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (0800,'Explotación de otras minas y canteras');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (0900,'Actividades de apoyo a la explotación de minas y canteras');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (1001,'Producción y procesamiento de carne y pescado');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (1002,'Preparación de frutas, hortalizas y legumbres; aceites y grasas');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (1003,'Elaboración de productos lácteos');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (1009,'Elaboración de productos alimenticios n.c.p.');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (1100,'Elaboración de bebidas');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (1200,'Elaboración de productos de tabaco');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (1300,'Fabricación de productos textiles, excepto prendas de vestir');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (1400,'Confección de prendas de vestir, terminación y teñido de pieles');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (1501,'Curtido y terminación de cueros; fabricación de maletas, bolsos de mano y artículos de talabartería y guarnicionería; teñido de pieles');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (1502,'Fabricación de calzado y sus partes');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (1600,'Producción de madera y fabricación de productos de madera y corcho, excepto muebles; fabricación de artículos de paja y de materiales trenzables');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (1700,'Fabricación de papel y productos de papel');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (1800,'Actividades de impresión y servicios de apoyo; reproducción de grabaciones');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (1901,'Fabricación de productos de hornos de coque');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (1902,'Fabricación de productos de la refinación del petróleo');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (2001,'Fabricación de pinturas, barnices y productos de revestimiento similares, tintas de imprenta y masillas');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (2002,'Fabricación de jabones y detergentes, preparados para limpiar y pulir, perfumes y preparados de tocador');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (2009,'Fabricación de otros productos químicos n.c.p.');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (2100,'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (2201,'Fabricación de productos de caucho');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (2202,'Fabricación de productos de plástico');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (2301,'Fabricación de vidrio y productos de vidrio');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (2309,'Fabricación de productos minerales no metálicos n.c.p.');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (2400,'Fabricación de metales');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (2500,'Fabricación de productos elaborados de metal y servicios de trabajos de metales, excepto máquinas y equipos');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (2601,'Fabricación de componentes electrónicos');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (2602,'Fabricación de equipos informáticos y periféricos');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (2603,'Fabricación de equipos y aparatos de radio, televisión y comunicaciones');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (2604,'Fabricación de equipos electromédicos, ópticos y de precisión; fabricación de relojes; soportes magnéticos y ópticos');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (2701,'Fabricación de aparatos de uso doméstico, excepto equipos de audio y video');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (2709,'Fabricación de otras maquinarias y equipos eléctricos n.c.p.');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (2800,'Fabricación de maquinarias y equipos n.c.p.');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (2900,'Fabricación de vehículos automotores, remolques y semirremolques');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (3001,'Construcción de buques y otras embarcaciones');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (3002,'Fabricación de locomotoras y de material rodante para ferrocarriles y tranvías');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (3003,'Fabricación de aeronaves');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (3009,'Fabricación de otros equipos de transporte n.c.p.');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (3100,'Fabricación de muebles y colchones');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (3200,'Industrias manufactureras n.c.p');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (3300,'Mantenimiento, reparación e instalación de maquinas y equipos');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (3501,'Generación, transmisión y distribución de energía eléctrica');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (3502,'Fabricación de gas; distribución de combustibles gaseosos por tuberías; suministro de vapor y aire acondicionado');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (3600,'Captación, tratamiento y suministro de agua');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (3700,'Alcantarillado');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (3800,'Recolección, tratamiento y eliminación de desechos; recuperación de materiales');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (3900,'Actividades de saneamiento y otros servicios de gestión de desechos');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (4000,'Construcción');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (4501,'Venta de vehículos automotores, excepto motocicletas');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (4502,'Mantenimiento y reparación de vehículos automotores, excepto motocicletas');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (4503,'Venta de partes, piezas y accesorios de vehículos automotores, excepto motocicletas');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (4504,'Venta, mantenimiento y reparación de motocicletas y de sus piezas y accesorios');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (4801,'Comercio de intermediación');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (4802,'Comercio de materias primas agropecuarias');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (4803,'Comercio de alimentos, bebidas y tabaco');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (4804,'Comercio de textiles y avíos, mercería, prendas de vestir, calzado, marroquinería y artículos similares');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (4805,'Comercio de materiales de construcción, artículos de ferretería, plomería, pinturería, espejos y artículos para revestimiento');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (4806,'Comercio de combustibles para vehículos');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (4807,'Comercio de mercaderías n.c.p. incluso mercaderías usadas');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (4808,'Tiendas no especializadas con predominancia de alimentos y bebidas');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (4809,'Tiendas no especializadas sin predominancia de alimentos y bebidas');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (4810,'Venta al por menor en puestos móviles y no realizadas en tiendas n.c.p.');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (4811,'Venta al por menor por correo, televisión, internet y otros medios de comunicación');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (4899,'Comercio n.c.p.');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (4901,'Transporte ferroviario');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (4902,'Transporte por metro');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (4903,'Transporte automotor de pasajeros');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (4904,'Transporte automotor de cargas');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (4905,'Transporte por tuberías');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (4909,'Transporte terrestre n.c.p.');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (5000,'Transporte por vía acuática');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (5100,'Transporte aéreo');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (5201,'Depósito y almacenamiento');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (5202,'Servicios auxiliares al transporte');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (5300,'Correo y servicio de mensajería');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (5500,'Servicios de alojamiento en hoteles, campamentos y otros tipos de hospedaje temporal');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (5601,'Servicios de expendio de comidas y bebidas, excepto por vendedores ambulantes');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (5602,'Servicios de expendio de comidas y bebidas por vendedores ambulantes');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (5800,'Edición de libros, periódicos y otras publicaciones, incluso integrada a la impresión');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (5900,'Actividades cinematográficas; producción de vídeos y programas de televisión; grabación sonora y edición de música');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (6000,'Actividades de programación y difusión de radio y televisión');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (6100,'Telecomunicaciones');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (6200,'Actividades de programación y consultoría informáticas y otras actividades conexas');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (6300,'Actividades de servicios de información');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (6400,'Intermediación financiera y otros servicios financieros, excepto los de seguros y administración de fondos de jubilaciones y pensiones');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (6500,'Seguros, reaseguros y fondos de pensiones, excepto los planes de seguridad social de afiliación obligatoria');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (6600,'Actividades auxiliares a los servicios financieros y a los seguros');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (6800,'Actividades inmobiliarias');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (6900,'Actividades jurídicas y de contabilidad');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (7000,'Actividades de servicios de consultoría en gestión empresarial');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (7100,'Servicios de arquitectura e ingeniería; ensayos y análisis técnicos');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (7200,'Investigación y desarrollo');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (7301,'Actividades publicitarias');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (7302,'Investigación de mercados y encuestas de opinión pública');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (7400,'Otras actividades profesionales, científicas y técnicas');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (7500,'Actividades veterinarias');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (7701,'Alquiler de efectos personales y domésticos');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (7702,'Alquiler de vehículos de transporte; de maquinaria y equipo sin operador y gestión de activos intangibles no financieros');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (7800,'Actividades relacionadas con el suministro de empleo');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (7900,'Agencias de viajes, operadores turísticos y actividades conexas');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (8000,'Actividades de investigación y seguridad');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (8101,'Servicios de apoyo a edificios y actividades de limpieza en general');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (8102,'Servicios de paisajismo y jardinería');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (8200,'Actividades administrativas de oficinas y otras actividades auxiliares de las empresas');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (8401,'Servicios de la administración pública y prestación pública de servicios a la comunidad');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (8402,'Servicios de seguridad publica (fuerzas armadas, policias, etc)');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (8403,'Servicios de la seguridad social obligatoria');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (8501,'Enseñanza inicial y primaria, secundaria y superior');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (8502,'Otros tipos de enseñanza n.c.p., y servicios de apoyo');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (8600,'Actividades de atención a la salud humana');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (8700,'Asistencia social relacionada con la atención a la salud');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (8800,'Servicios sociales sin alojamiento');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (9000,'Actividades artísticas y de espectáculos');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (9100,'Actividades de bibliotecas, archivos, museos y otras actividades culturales');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (9200,'Actividades de juegos de azar y apuestas');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (9301,'Actividades para la práctica deportiva');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (9302,'Actividades de entretenimiento n.c.p.');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (9401,'Actividades de organizaciones empresariales, profesionales y de empleadores');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (9402,'Actividades de sindicatos');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (9409,'Actividades de asociaciones n.c.p.');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (9501,'Reparación de equipos informáticos');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (9502,'Reparación de equipos de comunicación');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (9503,'Reparación de efectos de uso personal y doméstico');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (9601,'Lavado y limpieza de artículos de tela, cuero y o de piel incluso limpieza en seco');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (9602,'Servicios de peluquería y tratamientos de belleza');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (9603,'Pompas fúnebres y servicios conexos');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (9609,'Servicios personales n.c.p.');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (9700,'Actividades de los hogares como empleadores de personal doméstico');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (9900,'Actividades de organizaciones y organismos extraterritoriales');
insert into bu.eah12_bu_rama(codigo_rama, descripcion_rama) values (9999,'No sabe / No responde ó Actividad no especificada claramente');