--scripts de inserción en tabla tabulados
--delete from encu.tabulados;
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 1','Distribución porcentual de la población por sexo según comuna. ','comuna',null,'sexo','personas','comun',null,null,'Para todos los cuadros: Lugar y fecha: Ciudad de Buenos Aires. Año xxxx; Fuente: Dirección General de Estadística y Censos (Ministerio de Hacienda GCBA). EAHxxxx. La base debe estar ponderada por fexp.',1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 2','Distribución porcentual de la población por grupo de edad según comuna. ','comuna',null,'edad10a','personas','comun',null,null,null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 3','Distribución porcentual de la población por grupo de edad según sexo y zona','sexo','zona_3','edad10a','personas','comun',null,null,null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 4','Distribución porcentual de los jefes de hogar por grupo de edad según comuna','comuna',null,'edad10b','personas','comun','p4=1',null,null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 5','Distribución porcentual de los jefes de hogar por condición de actividad según comuna','comuna',null,'estado','personas','comun','p4=1',null,null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 6','Distribución porcentual de los jefes de hogar por sexo según comuna','comuna',null,'sexo','personas','comun','p4=1',null,null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 7','Distribución porcentual de los jefes de hogar por grupo de edad según sexo y zona','sexo','zona_3','edad10b','personas','comun','p4=1',null,null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 8','Distribución porcentual de los hogares por cantidad de personas en el hogar y tamaño medio según zona','zona_3',null,'total_mr','hogares','comun',null,null,'Ver como escribimos la parte de tamaño medio. Se hace calculando la media de la variable tot_mi',1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 9','Distribución porcentual de los hogares por régimen de tenencia de la vivienda según comuna','comuna',null,'h2_re','hogares','comun',null,'1 Incluye: propietario de la vivienda solamente, ocupante en relación de dependencia/ por trabajo, ocupante por préstamo, cesión o permiso, ocupante de hecho de la vivienda y otra situación',null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 10','Distribución porcentual de los hogares por régimen de tenencia de la vivienda según zona','zona_3',null,'h2_2','hogares','comun',null,null,null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 11',' Distribución porcentual de los hogares por personas por ambiente según comuna','comuna',null,'h_hacina','hogares','comun','h_hacina > 0 and h_hacina < 9','Nota: se excluyen los hogares sin  habitaciones de uso exclusivo y los hogares a los cuales no se puede determinar la cantidad exacta de habitaciones de uso exclusivo',null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 12','Distribución porcentual de las viviendas por tipo de vivienda según comuna','comuna',null,'v2_re','hogares','comun','hog = 1','1 Incluye: pieza de inquilinato/conventillo, pieza de hotel/pensión, construcción no destinada a vivienda, construcción no destinada a vivienda, rancho o casilla y otro tipo de vivienda','El filtro supone que en todas las encuestas existe un (y solo un) hogar Nº1. Ojo! Cambian las categorías de v2 con respecto a la onda 2012. En caso que existan sin dato en la variable v2 (que de existir por lo general representan menos del 0,05% del total de viviendas) se excluyen esos casos en el filtro y se aclara en una nota.',1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 13','Distribución porcentual de las viviendas por tipo de vivienda según zona','zona_3',null,'v2','hogares','comun','hog = 1',null,'En caso que existan sin dato en la variable v2 (que de existir por lo general representan menos del 0,05% del total de viviendas) se excluyen esos casos en el filtro y se aclara en una nota.',1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 14','Distribución porcentual de población, hogares y viviendas según tipo de vivienda','v2',null,null,'personas','comun','3) hog = 1',null,'VER COMO EXPRESAMOS ESTE CUADRO: cada columna representa una unidad de análisis distinta, la 1º población, la 2º hogares y la 3º viviendas. En caso que existan sin dato en la variable v2 (que de existir por lo general representan menos del 0,05% del total de viviendas) se excluyen esos casos en el filtro y se aclara en una nota.',1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 15','Distribución porcentual de la población de 3 años y más que asiste o asistió a un establecimiento educativo por sector al que pertenece el establecimiento según condición de asistencia y comuna',null,null,null,null,'comun',null,null,'Se dejó de preguntar sector para los que no asisten pero asistieron. Ver con sectorialista de reformular el cuadro solo para los que asisten o sacarlo',1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 16',' Distribución porcentual de la población de 3 años y más, por condición de asistencia escolar según comuna','comuna',null,'e2','personas','comun','edad >= 3',null,'En caso que existan sin dato o Ns/Nc en la variable e2 (que de existir por lo general representan menos del 0,05% del total de la población) se excluyen esos casos en el filtro y se aclara en una nota.',1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 17','Distribución porcentual de la población de 25 años y más por máximo nivel de instrucción alcanzado según comuna','comuna',null,'e_nivel','personas','comun','EDAD >= 25 AND e6 <> 6 AND e12 <> 6','Nota: se excluyen a los que asisten o asistieron como máximo a escuelas especiales no primarias. El análisis fue realizado en base a la edad declarada  ',null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 18','Distribución porcentual de la población de 25 años y más por cantidad de años de escolarización, mediana y promedio de años de escolarización según comuna','comuna',null,'e_raesc','personas','comun','(EDAD >= 25 and e_aesc <> 99 AND e_aesc <>98)','Nota: se excluyen los casos para los que no puede deternminarse la cantidad exacta de años de escolarización y los que cursan o cursaron escuelas especiales no primarias. El análisis fue realizado en base a la edad declarada','VER como expresamos la parte de mediana y promedio',1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 19',' Distribución porcentual de la población por tipo de cobertura médica según grupo de edad y zona','s_edad','zona_3','s_tipco3r','personas','comun',null,'1 Incluye a la población cubierta por dos o más sistemas y a la que tiene sólo mutual y/o sistemas de emergencias médicas',null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 20','Distribución porcentual de la población por cobertura médica según comuna','comuna',null,'s_tipco2','personas','comun',null,null,null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 21','Distribución porcentual de la población que sólo tiene sistema público de salud por grupo de edad según comuna','comuna',null,'s_edad','personas','comun','s_tipco2 = 1',null,null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 22','Distribución porcentual de la población por tipo de cobertura médica según comuna','comuna',null,'s_tipco3r','personas','comun',null,'1 Incluye a la población cubierta por dos o más sistemas y a la que tiene sólo mutual y/o sistemas de emergencias médicas',null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 23','Distribución porcentual de la población por tipo de cobertura médica según sexo y comuna','sexo','comuna','s_tipco3r','personas','comun',null,'1 Incluye a la población cubierta por dos o más sistemas y a la que tiene sólo mutual y/o sistemas de emergencias médicas','La presentación del cuadro no incluye el total de sexo abierto por comuna. Ver como se va a especificar el tema de los totales.',1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 24','Distribución porcentual de la población por tipo de cobertura médica según sexo y zona','sexo','zona_3','s_tipco3r','personas','comun',null,'1 Incluye a la población cubierta por dos o más sistemas y a la que tiene sólo mutual y/o sistemas de emergencias médicas',null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 25','Distribución porcentual de la población por lugar de nacimiento según comuna','comuna',null,'m_ln1','personas','comun',null,null,null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 26','Distribución porcentual de la población por lugar de nacimiento según sexo y zona','sexo','zona_3','m_ln1','personas','comun',null,null,null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 27','Distribución porcentual de la población extranjera por año de llegada al país según zona','zona_3',null,'m_rallp','personas','comun','m1 = 4',null,null,1);


insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 32','Tasas de actividad, empleo, desocupación y subocupación de la población de 10 años y más según sexo y comuna.','sexo','comuna',null,null,'comun',null,null,null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 33','Distribución porcentual de la población de 10 años y más por condición de actividad según sexo y comuna.','sexo','comuna','Condición de actividad','personas','comun','filter off.compute filter =( edad>=10).filter by filter.execute.filter off.compute filter= ( estado =1 or estado=2).filter by filter.execute.filter off.compute filter= ( estado =1 or estado=2).filter by filter.execute.',null,'Para todos los cuadros: Lugar y fecha: Ciudad de Buenos Aires. Año xxxx; Fuente: Dirección General de Estadística y Censos (Ministerio de Hacienda GCBA). EAHxxxx. La base debe estar ponderada por fexp.',1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 34','Distribución porcentual de la población ocupada por tramos de horas semanales trabajadas según comuna.','comuna',null,'t_intens','personas','comun','filter off.compute filter= t_intens >0.filter by filter.execute.','Nota: se excluye a los ocupados que no trabajaron la semana de referencia. Por tratarse de valores marginales, no se presentan los coeficientes de variación de la categoría Ns/Nc.',null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 35','Distribución porcentual de la población ocupada por sector de actividad según comuna.','comuna',null,'rama de actividad','personas','comun','filter off.use all.compute filter=estado=1.filter by filter.exe.','Otras ramas incluye: agricultura, ganadería, caza, silvicultura, pesca y minería; electricidad, gas y agua y organizaciones y órganos extraterritoriales. Servicios incluye: hoteles y restaurantes; transporte; actividades financieras, inmobiliarias y de alquiler; administración pública, defensa y seguridad social; educación; servicios sociales y de salud; otras servicios varios, sociales y personales y servicio doméstico',null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 36','Distribución porcentual de la población ocupada por categoría ocupacional de la ocupación principal según comuna.','comuna',null,'categoria ocupacional','personas','comun','use all.filter off.Compute filter=estado=1.filter by filter.exe.',null,null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 37','Distribución porcentual de la población de 10 años y más desocupada por máximo nivel de instrucción alcanzado según zona.','zona_3',null,'e_nivel','personas','comun','use all.filter off.compute filter= edad>=10 and estado =2.filter by filter.execute.',null,null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 38','Distribución porcentual de la población de 10 años y más inactiva por máximo nivel de instrucción alcanzado según comuna.','comuna',null,'e_nivel','personas','comun','use all.filter off.compute filter= edad>=10 and estado =3 and e_nivel <> 9.filter by filter.execute.',null,null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 39','Distribución porcentual de la población de 10 años y más ocupada por máximo nivel de instrucción alcanzado según comuna.','comuna',null,'e_nivel','personas','comun','use all.filter off.compute filter = estado = 1 and e_nivel = 1.filter by filter.exe.',null,null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 40','Distribución porcentual de la población asalariada por cobertura de jubilación según comuna.','comuna',null,'t51_re','personas','comun','use all.filter off.compute filter = categori = 3.filter by filter.exe.',null,null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 41','Distribución porcentual de la población ocupada por ubicación del lugar de trabajo según zona.','zona_3',null,'t39_rec','personas','comun','use all.filter off.compute filter = edad >= 10 and estado = 1.filter by filter.exe.',null,null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 42','Distribución porcentual de la población desocupada por tipo de desocupado según comuna.','comuna',null,'tipodes','personas','comun','use all.filter off.compute filter= (estado=2).filter by filter.execute.',null,null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 43','Distribución porcentual de desocupados cesantes por sector de actividad de la última ocupación según zona.','zona_3',null,'t_ramde2','personas','comun','use all.filter off.compute filter= tipodes=1.filter by filter.execute.',null,null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 44','Distribución porcentual de la población ocupada demandante de otra ocupación por condición de subocupación según comuna.','comuna',null,'t_deman','personas','comun','use all.filter off.compute filter=estado=1 and t35=1 and tsemref <> 2 and t_suboc3 <> 99.filter by filter.exe.',null,null,1);
insert into encu.tabulados(tab_tab,tab_titulo,tab_fila1,tab_fila2,tab_columna,tab_cel_exp,tab_cel_tipo,tab_filtro,tab_notas,tab_observaciones,tab_tlg)  values ( 'CUADRO 45','Tasas de actividad, empleo, desocupación y subocupación de la población de 10 años y más por grupo de edad.','tasas',null,'edad',null,'comun',null,null,null,1);

insert into encu.tabulados(tab_tab, tab_titulo, tab_fila1, tab_fila2, tab_columna, tab_cel_exp,tab_cel_tipo, tab_filtro, tab_notas, tab_observaciones, tab_tlg)
values 
('CUADRO 14a','Distribución porcentual de población según tipo de vivienda','v2',null,null,'personas','comun','hog=1',null,'VER COMO EXPRESAMOS ESTE CUADRO: cada columna representa una unidad de análisis distinta, la 1º población, la 2º hogares y la 3º viviendas. En caso que existan sin dato en la variable v2 (que de existir por lo general representan menos del 0,05% del total de viviendas) se excluyen esos casos en el filtro y se aclara en una nota.',1),
('CUADRO 14b','Distribución porcentual de hogares según tipo de vivienda','v2',null,null,'hogares','comun','hog=1',null,'VER COMO EXPRESAMOS ESTE CUADRO: cada columna representa una unidad de análisis distinta, la 1º población, la 2º hogares y la 3º viviendas. En caso que existan sin dato en la variable v2 (que de existir por lo general representan menos del 0,05% del total de viviendas) se excluyen esos casos en el filtro y se aclara en una nota.',1),
('CUADRO 14c','Distribución porcentual de viviendas según tipo de vivienda','v2',null,null,'viviendas','comun','hog=1',null,'VER COMO EXPRESAMOS ESTE CUADRO: cada columna representa una unidad de análisis distinta, la 1º población, la 2º hogares y la 3º viviendas. En caso que existan sin dato en la variable v2 (que de existir por lo general representan menos del 0,05% del total de viviendas) se excluyen esos casos en el filtro y se aclara en una nota.',1),
('CUADRO 46a','Distribución porcentual de mujeres de 14 años y más por condición de maternidad de las madres según grupo de edad',null, null, null,'personas','comun', null,'Nota: se excluye a las mujeres de condicion de maternidad ignorada y a las madres con cantidad ignorada de hijos nacidos vivos.','Columna: condición de maternidad. Filas: grupo de edad',1),
('CUADRO 46b','Distribución porcentual de mujeres de 14 años y más por cantidad de hijos según grupo de edad',null,null,null,'personas','comun', null,'Nota: se excluye a las mujeres de condicion de maternidad ignorada y a las madres con cantidad ignorada de hijos nacidos vivos.','Columna:cantidad de hijos. Filas: grupo de edad',1),
('CUADRO 47a','Distribución porcentual de mujeres de 14 años y más por condición de maternidad de las madres según comuna',null,null,null,'personas','comun', null,'Nota: por tratarse de valores marginales, no se presentan los coeficientes de variación de las categorías Ns/Nc.','Columna: condición de maternidad. Filas: comuna.',1),
('CUADRO 47b','Distribución porcentual de mujeres de 14 años y más por cantidad de hijos según comuna',null,null,null,'personas','comun', null,'Nota: por tratarse de valores marginales, no se presentan los coeficientes de variación de las categorías Ns/Nc.','Columna: cantidad de hijos. Filas: comuna.',1);