--EAH2013 nueva tabla rama
--DROP TABLE IF EXISTS encu.rama;
CREATE TABLE encu.rama
(
  ram_ram integer NOT NULL,
  ram_descripcion character varying(200),
  ram_tlg bigint,
  CONSTRAINT rama_pk PRIMARY KEY (ram_ram),
  CONSTRAINT "texto de descripción de rama inválido" CHECK (comun.cadena_valida(ram_descripcion::text, 'castellano'::text))
);

ALTER TABLE encu.rama
  OWNER TO tedede_php;
  
INSERT INTO encu.rama VALUES
 (101,'Cultivos agrícolas', 1)
,(102,'Cría de animales', 1)
,(103,'Cultivo de productos agrícolas en combinación con la cría de animales', 1)
,(104,'Servicios agrícolas y pecuarios, excepto los veterinarios', 1)
,(105,'Caza y captura de animales vivos, repoblación de animales de caza y servicios de apoyo', 1)
,(200,'Silvicultura, extracción de madera y actividades de apoyo', 1)
,(300,'Pesca, acuicultura y actividades de apoyo', 1)
,(500,'Extracción de carbón y lignito', 1)
,(600,'Extracción de petróleo crudo y gas natural', 1)
,(700,'Extracción de minerales metalíferos', 1)
,(800,'Explotación de otras minas y canteras', 1)
,(900,'Actividades de apoyo a la explotación de minas y canteras', 1)
,(1001,'Producción y procesamiento de carne y pescado', 1)
,(1002,'Preparación de frutas, hortalizas y legumbres, aceites y grasas', 1)
,(1003,'Elaboración de productos lácteos', 1)
,(1009,'Elaboración de productos alimenticios n.c.p.', 1)
,(1100,'Elaboración de bebidas', 1)
,(1200,'Elaboración de productos de tabaco', 1)
,(1300,'Fabricación de productos textiles, excepto prendas de vestir', 1)
,(1400,'Confección de prendas de vestir, terminación y teñido de pieles', 1)
,(1501,'Curtido y terminación de cueros, fabricación de maletas, bolsos de mano y artículos de talabartería y guarnicionería, teñido de pieles', 1)
,(1502,'Fabricación de calzado y sus partes', 1)
,(1600,'Producción de madera y fabricación de productos de madera y corcho, excepto muebles, fabricación de artículos de paja y de materiales trenzables', 1)
,(1700,'Fabricación de papel y productos de papel', 1)
,(1800,'Actividades de impresión y servicios de apoyo, reproducción de grabaciones', 1)
,(1901,'Fabricación de productos de hornos de coque', 1)
,(1902,'Fabricación de productos de la refinación del petróleo', 1)
,(2001,'Fabricación de pinturas, barnices y productos de revestimiento similares, tintas de imprenta y masillas', 1)
,(2002,'Fabricación de jabones y detergentes, preparados para limpiar y pulir, perfumes y preparados de tocador', 1)
,(2009,'Fabricación de otros productos químicos n.c.p.', 1)
,(2100,'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos', 1)
,(2201,'Fabricación de productos de caucho', 1)
,(2202,'Fabricación de productos de plástico', 1)
,(2301,'Fabricación de vidrio y productos de vidrio', 1)
,(2309,'Fabricación de productos minerales no metálicos n.c.p.', 1)
,(2400,'Fabricación de metales', 1)
,(2500,'Fabricación de productos elaborados de metal y servicios de trabajos de metales, excepto máquinas y equipos', 1)
,(2601,'Fabricación de componentes electrónicos', 1)
,(2602,'Fabricación de equipos informáticos y periféricos', 1)
,(2603,'Fabricación de equipos y aparatos de radio, televisión y comunicaciones', 1)
,(2604,'Fabricación de equipos electromédicos, ópticos y de precisión, fabricación de relojes, soportes magnéticos y ópticos', 1)
,(2701,'Fabricación de aparatos de uso doméstico, excepto equipos de audio y video', 1)
,(2709,'Fabricación de otras maquinarias y equipos eléctricos n.c.p.', 1)
,(2800,'Fabricación de maquinarias y equipos n.c.p.', 1)
,(2900,'Fabricación de vehículos automotores, remolques y semirremolques', 1)
,(3001,'Construcción de buques y otras embarcaciones', 1)
,(3002,'Fabricación de locomotoras y de material rodante para ferrocarriles y tranvías', 1)
,(3003,'Fabricación de aeronaves', 1)
,(3009,'Fabricación de otros equipos de transporte n.c.p.', 1)
,(3100,'Fabricación de muebles y colchones', 1)
,(3200,'Industrias manufactureras n.c.p', 1)
,(3300,'Mantenimiento, reparación e instalación de maquinas y equipos', 1)
,(3501,'Generación, transmisión y distribución de energía eléctrica', 1)
,(3502,'Fabricación de gas, distribución de combustibles gaseosos por tuberías, suministro de vapor y aire acondicionado', 1)
,(3600,'Captación, tratamiento y suministro de agua', 1)
,(3700,'Alcantarillado', 1)
,(3800,'Recolección, tratamiento y eliminación de desechos, recuperación de materiales', 1)
,(3900,'Actividades de saneamiento y otros servicios de gestión de desechos', 1)
,(4000,'Construcción', 1)
,(4501,'Venta de vehículos automotores, excepto motocicletas', 1)
,(4502,'Mantenimiento y reparación de vehículos automotores, excepto motocicletas', 1)
,(4503,'Venta de partes, piezas y accesorios de vehículos automotores, excepto motocicletas', 1)
,(4504,'Venta, mantenimiento y reparación de motocicletas y de sus piezas y accesorios', 1)
,(4801,'Comercio de intermediación', 1)
,(4802,'Comercio de materias primas agropecuarias', 1)
,(4803,'Comercio de alimentos, bebidas y tabaco', 1)
,(4804,'Comercio de textiles y avíos, mercería, prendas de vestir, calzado, marroquinería y artículos similares', 1)
,(4805,'Comercio de materiales de construcción, artículos de ferretería, plomería, pinturería, espejos y artículos para revestimiento', 1)
,(4806,'Comercio de combustibles para vehículos', 1)
,(4807,'Comercio de mercaderías n.c.p. incluso mercaderías usadas', 1)
,(4808,'Tiendas no especializadas con predominancia de alimentos y bebidas', 1)
,(4809,'Tiendas no especializadas sin predominancia de alimentos y bebidas', 1)
,(4810,'Venta al por menor en puestos móviles y no realizadas en tiendas n.c.p.', 1)
,(4811,'Venta al por menor por correo, televisión, internet y otros medios de comunicación', 1)
,(4899,'Comercio n.c.p.', 1)
,(4901,'Transporte ferroviario', 1)
,(4902,'Transporte por metro', 1)
,(4903,'Transporte automotor de pasajeros', 1)
,(4904,'Transporte automotor de cargas', 1)
,(4905,'Transporte por tuberías', 1)
,(4909,'Transporte terrestre n.c.p.', 1)
,(5000,'Transporte por vía acuática', 1)
,(5100,'Transporte aéreo', 1)
,(5201,'Depósito y almacenamiento', 1)
,(5202,'Servicios auxiliares al transporte', 1)
,(5300,'Correo y servicio de mensajería', 1)
,(5500,'Servicios de alojamiento en hoteles, campamentos y otros tipos de hospedaje temporal', 1)
,(5601,'Servicios de expendio de comidas y bebidas, excepto por vendedores ambulantes', 1)
,(5602,'Servicios de expendio de comidas y bebidas por vendedores ambulantes', 1)
,(5800,'Edición de libros, periódicos y otras publicaciones, incluso integrada a la impresión', 1)
,(5900,'Actividades cinematográficas, producción de vídeos y programas de televisión, grabación sonora y edición de música', 1)
,(6000,'Actividades de programación y difusión de radio y televisión', 1)
,(6100,'Telecomunicaciones', 1)
,(6200,'Actividades de programación y consultoría informáticas y otras actividades conexas', 1)
,(6300,'Actividades de servicios de información', 1)
,(6400,'Intermediación financiera y otros servicios financieros, excepto los de seguros y administración de fondos de jubilaciones y pensiones', 1)
,(6500,'Seguros, reaseguros y fondos de pensiones, excepto los planes de seguridad social de afiliación obligatoria', 1)
,(6600,'Actividades auxiliares a los servicios financieros y a los seguros', 1)
,(6800,'Actividades inmobiliarias', 1)
,(6900,'Actividades jurídicas y de contabilidad', 1)
,(7000,'Actividades de servicios de consultoría en gestión empresarial', 1)
,(7100,'Servicios de arquitectura e ingeniería, ensayos y análisis técnicos', 1)
,(7200,'Investigación y desarrollo', 1)
,(7301,'Actividades publicitarias', 1)
,(7302,'Investigación de mercados y encuestas de opinión pública', 1)
,(7400,'Otras actividades profesionales, científicas y técnicas', 1)
,(7500,'Actividades veterinarias', 1)
,(7701,'Alquiler de efectos personales y domésticos', 1)
,(7702,'Alquiler de vehículos de transporte, de maquinaria y equipo sin operador y gestión de activos intangibles no financieros', 1)
,(7800,'Actividades relacionadas con el suministro de empleo', 1)
,(7900,'Agencias de viajes, operadores turísticos y actividades conexas', 1)
,(8000,'Actividades de investigación y seguridad', 1)
,(8101,'Servicios de apoyo a edificios y actividades de limpieza en general', 1)
,(8102,'Servicios de paisajismo y jardinería', 1)
,(8200,'Actividades administrativas de oficinas y otras actividades auxiliares de las empresas', 1)
,(8401,'Servicios de la administración pública y prestación pública de servicios a la comunidad', 1)
,(8402,'Servicios de seguridad publica (fuerzas armadas, policias, etc)', 1)
,(8403,'Servicios de la seguridad social obligatoria', 1)
,(8501,'Enseñanza inicial y primaria, secundaria y superior', 1)
,(8502,'Otros tipos de enseñanza n.c.p., y servicios de apoyo', 1)
,(8600,'Actividades de atención a la salud humana', 1)
,(8700,'Asistencia social relacionada con la atención a la salud', 1)
,(8800,'Servicios sociales sin alojamiento', 1)
,(9000,'Actividades artísticas y de espectáculos', 1)
,(9100,'Actividades de bibliotecas, archivos, museos y otras actividades culturales', 1)
,(9200,'Actividades de juegos de azar y apuestas', 1)
,(9301,'Actividades para la práctica deportiva', 1)
,(9302,'Actividades de entretenimiento n.c.p.', 1)
,(9401,'Actividades de organizaciones empresariales, profesionales y de empleadores', 1)
,(9402,'Actividades de sindicatos', 1)
,(9409,'Actividades de asociaciones n.c.p.', 1)
,(9501,'Reparación de equipos informáticos', 1)
,(9502,'Reparación de equipos de comunicación', 1)
,(9503,'Reparación de efectos de uso personal y doméstico', 1)
,(9601,'Lavado y limpieza de artículos de tela, cuero y o de piel incluso limpieza en seco', 1)
,(9602,'Servicios de peluquería y tratamientos de belleza', 1)
,(9603,'Pompas fúnebres y servicios conexos', 1)
,(9609,'Servicios personales n.c.p.', 1)
,(9700,'Actividades de los hogares como empleadores de personal doméstico', 1)
,(9900,'Actividades de organizaciones y organismos extraterritoriales', 1)
,(9999,'No sabe / No responde ó Actividad no especificada claramente', 1);
