--EAH2013 nueva tabla dictra
--DROP TABLE IF EXISTS encu.dictra;
CREATE TABLE encu.dictra
(
  dictra_dic text NOT NULL,
  dictra_ori text NOT NULL,
  dictra_des integer,
  dictra_tlg bigint,
  CONSTRAINT dictra_pk PRIMARY KEY (dictra_dic, dictra_ori),
  CONSTRAINT dictra_diccionario_fk FOREIGN KEY (dictra_dic)
  REFERENCES encu.diccionario (dic_dic) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT dictra_tiempo_logico_fk FOREIGN KEY (dictra_tlg)
      REFERENCES encu.tiempo_logico (tlg_tlg) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

ALTER TABLE encu.dictra
  OWNER TO tedede_php;
  
INSERT INTO encu.dictra(
            dictra_dic, dictra_ori, dictra_des, dictra_tlg)
    VALUES 
('serv_dom_txt','chicos',1,1),
('serv_dom_txt','cuida',1,1),
('serv_dom_txt','niños',1,1),
('serv_dom_txt','niño',1,1),
('serv_dom_txt','nena',1,1),
('serv_dom_txt','niñera',1,1),
('serv_dom_txt','bebes',1,1),
('serv_dom_txt','ninos',1,1),
('serv_dom_txt','cuidado',1,1),
('serv_dom_txt','niña',1,1),
('serv_dom_txt','bebe',1,1),
('serv_dom_txt','nina',1,1),
('serv_dom_txt','Organización',2,1),
('serv_dom_txt','ONG',2,1),
('barrio','BB',99,1),
('barrio','PILAR',null,1),
('barrio','1-11-14',7,1),
('barrio','1 11 14',7,1),
('barrio','25 DE MAYO 175',1,1),
('barrio','25 DE MAYO 200',1,1),
('barrio','25 DE MAYO 221',1,1),
('barrio','25 DE MAYO ENTRE CORRIENTES Y SARMIENTO',1,1),
('barrio','25 DE MAYO Y ALEM',1,1),
('barrio','25 DE MAYO Y CORRIENTES',1,1),
('barrio','25 DE MAYO Y SARMIENTO',1,1),
('barrio','25 DE MAYO Y TUCUMAN',1,1),
('barrio','25 DEMAYO Y PERON',1,1),
('barrio','3 ARROYOS 2800',11,1),
('barrio','3 DE FEBRERO',99,1),
('barrio','9 DE ABRIL',99,1),
('barrio','9 DE JULIO',1,1),
('barrio','9 DE JULIO 1925',1,1),
('barrio','9 DE JULIO Y MORENO',1,1),
('barrio','ABASTO',3,1),
('barrio','ABASTO - ONCE',3,1),
('barrio','ACOYTE Y RIV',6,1),
('barrio','ACOYTE Y RIVADAVIA',6,1),
('barrio','AEROPARQUE',14,1),
('barrio','AGRONOMIA',15,1),
('barrio','AGUERO Y FRENCH',2,1),
('barrio','AGUERO Y LAS HERAS',2,1),
('barrio','AL MAGRO',5,1),
('barrio','ALBERDI 5500',9,1),
('barrio','ALEM 500',1,1),
('barrio','ALEM 600',1,1),
('barrio','ALEM Y BELGRANO',1,1),
('barrio','ALEM Y CORDOBA',1,1),
('barrio','ALEM Y CORRIENTES',1,1),
('barrio','ALEM Y MARCELO T ALVEAR',1,1),
('barrio','ALEM Y PARAGUAY',1,1),
('barrio','ALEM Y PERON',1,1),
('barrio','ALEM Y TUCUMAN',1,1),
('barrio','ALEM Y VIAMONTE',1,1),
('barrio','ALMAGRO',5,1),
('barrio','ALSINA 1495',1,1),
('barrio','ALSINA 2586',3,1),
('barrio','ALSINA Y ENTRE RIOS',1,1),
('barrio','ALSINA Y PARAGUAY',99,1),
('barrio','ALSINA Y SALTA',1,1),
('barrio','ALTE BROWN 400',4,1),
('barrio','ALTOLAGUIRRE1684',15,1),
('barrio','ALVAREZ THOMAS Y INCAS',15,1),
('barrio','AMENABAR Y VIRREY DEL PINO',13,1),
('barrio','ANCHORENA 1191',2,1),
('barrio','ANCHORENA Y STA FE',2,1),
('barrio','AQUINO Y OLIDEN',8,1),
('barrio','ARENALES 700',1,1),
('barrio','ARIAS Y GRECIA',13,1),
('barrio','ARIZMENDI 2600',15,1),
('barrio','ARREGUI Y MERCEDES',10,1),
('barrio','ARRIBEÑOS Y MENDOZA',13,1),
('barrio','ARRIBEÑOS Y ROOSEVELT',13,1),
('barrio','ARTIGAS Y ALVAREZ JONTE',11,1),
('barrio','ASAMBLEA Y VICTOR MARTINES',7,1),
('barrio','AV BELGRANO',99,1),
('barrio','AV CORDOBA',99,1),
('barrio','AV CORDOBA 2000',2,1),
('barrio','AV CORDOBA 696',1,1),
('barrio','AV CORDOBA 969',1,1),
('barrio','AV CORDOBA AL 900',1,1),
('barrio','AV CORDOBA Y AZCUENAGA',2,1),
('barrio','AV CORRIENTES Y PARANA',1,1),
('barrio','AV COSTA ERA YA V SARMIENTO',14,1),
('barrio','AV DE LOS CORRALES 6443',9,1),
('barrio','AV DE LOS INMIGRANTES 1950',1,1),
('barrio','AV DE MAYO',1,1),
('barrio','AV DE MAYO 1100',1,1),
('barrio','AV DE MAYO 56',1,1),
('barrio','AV DE MAYO 800',1,1),
('barrio','AV DE MAYO Y 9 DE JULIO',1,1),
('barrio','AV DE MAYO Y CERRITO',1,1),
('barrio','AV DE MAYO Y PERU',1,1),
('barrio','AV DE MAYO Y PIEDRAS',1,1),
('barrio','AV DIRECTORIO FLORES',7,1),
('barrio','AV IRIARTE Y JOVELLANOS',4,1),
('barrio','AV JUJUY Y CATULO CASTILLO',4,1),
('barrio','AV LA PLATA Y S JUAN',5,1),
('barrio','AV LEANDRO N ALEM',1,1),
('barrio','AV MAYO 560',1,1),
('barrio','AV PASEO COLON MONSERRAT',1,1),
('barrio','AV RIVADAVIA Y AV CALLAO',1,1),
('barrio','AV SAN JUAN',99,1),
('barrio','AV SAN MARTIN PATERNAL',15,1),
('barrio','AV SANTA FE 700',1,1),
('barrio','AV SANTA FE PALERMO',14,1),
('barrio','AV SANTA FE Y ANCHORENA',2,1),
('barrio','AV SANTA FE Y ECUADOR',2,1),
('barrio','AVELLANEDA E HIDALGO',6,1),
('barrio','AVELLANEDA Y DONATO ALVAREZ',6,1),
('barrio','AVELLANEDA Y HIDALGO',6,1),
('barrio','AVELLANEDA Y NAZCA',7,1),
('barrio','AYACUCHO Y LAS HERAS',2,1),
('barrio','AYACUCHO Y LAVALLE',3,1),
('barrio','AZCUENAGA Y CORDOBA',2,1),
('barrio','AZCUENAGA Y STA FE',2,1),
('barrio','AZOPARDO-P MADERO',1,1),
('barrio','AZOPARDO 250',1,1),
('barrio','AZOPARDO 670',1,1),
('barrio','AZOPARDO Y BELGRANO',1,1),
('barrio','AZOPARDO Y MORENO',1,1),
('barrio','AZOPARDO Y VENEZUELA',1,1),
('barrio','B MITRE 947',1,1),
('barrio','B MITRE Y ESMERALDA',1,1),
('barrio','B MITRE Y MAIPU',1,1),
('barrio','B MITRE Y SAAVEDRA',99,1),
('barrio','B MITRE Y URIBURU',1,1),
('barrio','B NORTE',2,1),
('barrio','B YRIGOYEN 972',1,1),
('barrio','BA NUÑEZ',13,1),
('barrio','BAJO FLORES',7,1),
('barrio','BAL ANERA',3,1),
('barrio','BALBANERA',3,1),
('barrio','BALCARCE 50',1,1),
('barrio','BALVA ERA',3,1),
('barrio','BALVANERA',3,1),
('barrio','BARRACAD',4,1),
('barrio','BARRACAS',4,1),
('barrio','BARRACAS DE BELGRANO',13,1),
('barrio','BARRANCAS DE BELGRANO',13,1),
('barrio','BARRIO ESPORA',4,1),
('barrio','BARRIO FATIMA',8,1),
('barrio','BARRIO FRAGA',15,1),
('barrio','BARRIO NORTE',2,1),
('barrio','BARRIO NORTE COMUNA 2',2,1),
('barrio','BARRIO NUEVO COMUNA 4',4,1),
('barrio','BARRIO PARQUE',14,1),
('barrio','BARRIO RIVADAVIA',7,1),
('barrio','BARRIO SAN NICOLAS',1,1),
('barrio','BARTOLOME MITRE 648',1,1),
('barrio','BARTOLOME MITRE Y URUGUAY',1,1),
('barrio','BELGRAMO',13,1),
('barrio','BELGRANO',13,1),
('barrio','BELGRANO 130',1,1),
('barrio','BELGRANO AL 2900',3,1),
('barrio','BELGRANO COGHLAN',13,1),
('barrio','BELGRANO Y DEFENSA',1,1),
('barrio','BELGRANO Y LIMA',1,1),
('barrio','BELGRANO Y PASCO',3,1),
('barrio','BELGRANO Y YRIGOYEN',1,1),
('barrio','BELIZARIO ROLDAN 4511',14,1),
('barrio','BEÑGRANO',13,1),
('barrio','BESARES Y HOLMERG',12,1),
('barrio','BILLINGHURST 1193',2,1),
('barrio','BLANCO ENCALADA Y SUPERI',13,1),
('barrio','BME MITRE AL 1900',3,1),
('barrio','BME MITRE Y RECONQUISTA',1,1),
('barrio','BME MITRE Y SUIPACHA',1,1),
('barrio','BOCA',4,1),
('barrio','BOEDO',5,1),
('barrio','BOEDO PAVON',5,1),
('barrio','BOEDO Y SALCEDO',5,1),
('barrio','BOGOTA 2800',7,1),
('barrio','BOLIVAR 1200',1,1),
('barrio','BOLIVAR 190',1,1),
('barrio','BOLIVAR 191',1,1),
('barrio','BOLIVAR 263',1,1),
('barrio','BOLIVAR Y CARLOS CALVO',1,1),
('barrio','BONIFACIO Y PUAN',6,1),
('barrio','BONORINO COMUNA 7',7,1),
('barrio','BORGES 2445',14,1),
('barrio','BORGUES 2445',14,1),
('barrio','BOUCHARD ENTRE TUCUMAN Y LAVALLE',1,1),
('barrio','BOUCHARD Y CORRIENTES',1,1),
('barrio','BOUCHARD Y TUCUMAN',1,1),
('barrio','BOYACA Y BACACAY',7,1),
('barrio','BRASIL 2500',4,1),
('barrio','BRASIL Y ING HUERGO',4,1),
('barrio','BULNES 2009',14,1),
('barrio','CABA LO DESIGNAN A DIFERENTES BARRIOS DE LA CIUDAD',99,1),
('barrio','CABALITO',6,1),
('barrio','CABALLIITO',6,1),
('barrio','CABALLITO',6,1),
('barrio','CABALLITO CERCA DE PARQUE CHACABUCO',7,1),
('barrio','CABALLITO RECOLET VTE LOPEZ Y COLEGIALES',99,1),
('barrio','CABILDO',99,1),
('barrio','CABILDO AL 400',14,1),
('barrio','CABILDO Y CESPEDES',14,1),
('barrio','CABILDO Y LACROZE',14,1),
('barrio','CABILDO Y SUCRE',13,1),
('barrio','CAFAYATE 5000',4,1),
('barrio','CALIFORNIA Y SANTA MAGDALENA',1,1),
('barrio','CALLAO E INDEPENDENCIA',2,1),
('barrio','CALLAO Y ARENALES',1,1),
('barrio','CALLAO Y B MITRE',1,1),
('barrio','CALLAO Y CORDOBA',1,1),
('barrio','CALLAO Y CORRIENTES',1,1),
('barrio','CALLAO Y LAVALLE',1,1),
('barrio','CALLAO Y QUINTANA',2,1),
('barrio','CALLAO Y SANTA FE',2,1),
('barrio','CALLAO Y SARMIENTO',1,1),
('barrio','CALLAO Y VIAMONTE',1,1),
('barrio','CALLE 9 DE JULIO',1,1),
('barrio','CALLE BOULOGNE SURMER',99,1),
('barrio','CALLE FLORIDA',1,1),
('barrio','CALLE HERRERA MATADEROS VILLA 15',8,1),
('barrio','CAMILO TORRES Y RIESTRA',7,1),
('barrio','CAMPANA Y SEGUROLA',99,1),
('barrio','CAMPICHUELO Y JAURECHE',6,1),
('barrio','CAÑITAS',14,1),
('barrio','CAP FED',99,1),
('barrio','CAPITAL FEDERAL',99,1),
('barrio','CARABOBO Y SARAZA',7,1),
('barrio','CARACAS Y JUAN B JUSTO',11,1),
('barrio','CARLOS PELLEGRINI',1,1),
('barrio','CARLOS PELLEGRINI 121',1,1),
('barrio','CARLOS PELLEGRINI Y ARENALES',1,1),
('barrio','CARODOBA Y FLORIDA',1,1),
('barrio','CARRILLO',4,1),
('barrio','CASA DE GOBIERNO',1,1),
('barrio','CASA ROSADA AL LADO',1,1),
('barrio','CASALLETO FORMOSA 590',6,1),
('barrio','CASEROS',99,1),
('barrio','CASEROS Y BOLIVAR',4,1),
('barrio','CASEROS Y COMBATE DE LOS POZOS',4,1),
('barrio','CASTAÑARES Y CARABOBO',7,1),
('barrio','CATALINAS',4,1),
('barrio','CENTENERA Y RIESTRA',4,1),
('barrio','CENTRO',1,1),
('barrio','CENTRO CALLE MEXICO NO SABE ALTURA',1,1),
('barrio','CENTRO COMUNA 1',1,1),
('barrio','CENTRO NO DETALLA MAS',1,1),
('barrio','CENTRO SAN TELMO',1,1),
('barrio','CERRITO 1248',1,1),
('barrio','CERRITO AL 600',1,1),
('barrio','CERRITO Y CORDOBA',1,1),
('barrio','CERRITO Y MARCELO T DE ALVEAR',1,1),
('barrio','CERRITO Y POSADAS',1,1),
('barrio','CERRITO Y TOCUMAN',1,1),
('barrio','CERVANTES MARGARIÑO',99,1),
('barrio','CIUDAD EVITA',null,1),
('barrio','CIUDAD UNIVERSITARIA',13,1),
('barrio','CIUDADELA',null,1),
('barrio','CNEL DIAZ Y PARAGUAY',14,1),
('barrio','COBO Y CENTENERA',4,1),
('barrio','COCHABAMBA Y GARAY',99,1),
('barrio','COGHLAN',12,1),
('barrio','COGLAN',12,1),
('barrio','COHGLAN',12,1),
('barrio','COLEGIALES',13,1),
('barrio','COMBATE DE LOS POZOS Y BRASIL',4,1),
('barrio','COMODORO PY',1,1),
('barrio','COMUNA 1',1,1),
('barrio','COMUNA 1- MICROCENTRO',1,1),
('barrio','COMUNA 1 ALEM Y AV DE MAYO',1,1),
('barrio','COMUNA 1 MICROCENTRO',1,1),
('barrio','COMUNA 10',10,1),
('barrio','COMUNA 11',11,1),
('barrio','COMUNA 13',13,1),
('barrio','COMUNA 2',2,1),
('barrio','COMUNA 4',4,1),
('barrio','COMUNA1',1,1),
('barrio','CONCEPCION ARENAL Y ALVAREZ THOMAS',13,1),
('barrio','CONDE 800',13,1),
('barrio','CONGRESO',1,1),
('barrio','CONGRESO 5000',12,1),
('barrio','CONSTIT B NORTE',99,1),
('barrio','CONSTITUCION',1,1),
('barrio','CONSTITUCION Y ENTRE RIOS',1,1),
('barrio','CONSTITUYENTES - V PUEYRREDON',12,1),
('barrio','CONSTITUYENTES Y BALIBIAN',15,1),
('barrio','CONSTITUYENTES Y GRAL PAZ',12,1),
('barrio','CONTITUCION',1,1),
('barrio','CONTUTICION',1,1),
('barrio','CONUMA 10',10,1),
('barrio','CORDOBA',99,1),
('barrio','CORDOBA 1300',1,1),
('barrio','CORDOBA 2100',3,1),
('barrio','CORDOBA 2122',3,1),
('barrio','CORDOBA 2351',3,1),
('barrio','CORDOBA 6103',15,1),
('barrio','CORDOBA URIBURU',2,1),
('barrio','CORDOBA Y',2,1),
('barrio','CORDOBA Y AYACUCHO',2,1),
('barrio','CORDOBA Y AZCUENAGA',2,1),
('barrio','CORDOBA Y CALLAO',2,1),
('barrio','CORDOBA Y ESMERALDA',1,1),
('barrio','CORDOBA Y FLORIDA',1,1),
('barrio','CORDOBA Y GASCON',5,1),
('barrio','CORDOBA Y JUNIN',2,1),
('barrio','CORDOBA Y L N ALEM',1,1),
('barrio','CORDOBA Y LEANDRO N ALEM',1,1),
('barrio','CORDOBA Y MAIPU',1,1),
('barrio','CORDOBA Y MEDRANO',14,1),
('barrio','CORDOBA Y PALESTINA',14,1),
('barrio','CORDOBA Y PARANA',2,1),
('barrio','CORDOBA Y PUEYRREDON',2,1),
('barrio','CORDOBA Y RIOBAMBA',2,1),
('barrio','CORDOBA Y RODRIGUEZ PEÑA',2,1),
('barrio','CORDOBA Y SAENZ PEÑA',99,1),
('barrio','CORDOBA Y SUIPACHA',1,1),
('barrio','CORDOBA Y URIBURU',2,1),
('barrio','CORDOBA Y URUGUAY',1,1),
('barrio','CORDOBA YLIBERTAD',1,1),
('barrio','CORRIENTES 1500',1,1),
('barrio','CORRIENTES 1530',1,1),
('barrio','CORRIENTES 2000',3,1),
('barrio','CORRIENTES 2200',3,1),
('barrio','CORRIENTES 378',1,1),
('barrio','CORRIENTES 600',1,1),
('barrio','CORRIENTES AL 300',1,1),
('barrio','CORRIENTES AL 5200',15,1),
('barrio','CORRIENTES ENTRE SAN MARTIN Y FLORIDA',1,1),
('barrio','CORRIENTES SAN NICOLAS',1,1),
('barrio','CORRIENTES Y 9 DE JULIO',1,1),
('barrio','CORRIENTES Y ALEM',1,1),
('barrio','CORRIENTES Y AYACUCHO',1,1),
('barrio','CORRIENTES Y CALLAO',1,1),
('barrio','CORRIENTES Y ECUADOR',3,1),
('barrio','CORRIENTES Y ESCALABRINI',15,1),
('barrio','CORRIENTES Y ESMERALDA',1,1),
('barrio','CORRIENTES Y FLORIDA',1,1),
('barrio','CORRIENTES Y MAIPU',1,1),
('barrio','CORRIENTES Y PARANA',1,1),
('barrio','CORRIENTES Y PRINGLES',5,1),
('barrio','CORRIENTES Y PUEYRREDON',3,1),
('barrio','CORRIENTES Y RECONQUISTA',1,1),
('barrio','CORRIENTES Y RODRIGUEZ PEÑA',1,1),
('barrio','CORRIENTES Y SUIPACHA',1,1),
('barrio','CORRIENTES Y URUGUAY',1,1),
('barrio','CORRIENTES700',1,1),
('barrio','COSTANERA AEROPARQUE',14,1),
('barrio','COSTANERA NORTE',14,1),
('barrio','COSTANERA SUR',4,1),
('barrio','COSTITUCION',1,1),
('barrio','CRAMER Y J NEWBERY',14,1),
('barrio','CRAMER Y JURAMENTO',13,1),
('barrio','CRAMER Y LARRALDE',13,1),
('barrio','CUBA 2039',12,1),
('barrio','CULPINA',7,1),
('barrio','CURAPALIGUE Y COBO',7,1),
('barrio','CHACABUCO Y BELGRANO',1,1),
('barrio','CHACARITA',15,1),
('barrio','CHACARITA LEMOS Y DUMONT',15,1),
('barrio','CHACARITA Y VILLA LUGANO',99,1),
('barrio','CHARCAS Y GODOY CRUZ',14,1),
('barrio','CHARCAS Y PUEYRREDON',2,1),
('barrio','CHICLANA Y URQUIZA',4,1),
('barrio','DARSENA F',1,1),
('barrio','DE LOS CONSTITUYENTES 6020',12,1),
('barrio','DEBOTO',11,1),
('barrio','DEFENSA E INDEPENDENCIA',1,1),
('barrio','DEFENSA Y MEXICO',1,1),
('barrio','DELEPIANE Y LACARRA',9,1),
('barrio','DEVOTO',11,1),
('barrio','DIAGONAL NORTE',1,1),
('barrio','DIAGONAL NORTE 600',1,1),
('barrio','DIAGONAL NORTE MICROCENTRO',1,1),
('barrio','DIAGONAL NORTE Y CHACABUCO',1,1),
('barrio','DIAGONAL NORTE Y FLORIDA',1,1),
('barrio','DIAGONAL ROQUE SAENZ PEÑA Y ESMERALDA',1,1),
('barrio','DIAGONAL SUR Y BELGRANO',1,1),
('barrio','DIAGONAL SUR Y CHACABUCO',1,1),
('barrio','DIAGONAL SUR Y PERU',1,1),
('barrio','DIAGONAL SUR Y ROCA',1,1),
('barrio','DIAZ VELEZ Y AMBROSETTI',6,1),
('barrio','DIAZ VELEZ Y HONORIO PUEYRREDON',6,1),
('barrio','DIG NORTE Y ESMERALDA',1,1),
('barrio','DIRECTORIO Y BEAUCHEF',7,1),
('barrio','DIRECTORIO Y ESCALADA',9,1),
('barrio','DIRECTORIO Y SAN PEDRITO',7,1),
('barrio','DOCK SUD',null,1),
('barrio','DON BOSCO Y V LINIERS',5,1),
('barrio','DONATE ALVAREZ Y MORON',99,1),
('barrio','DONATO ALVAREZ Y PAEZ',6,1),
('barrio','DORREGO Y NICARAGUA',14,1),
('barrio','DOT BAIRES',12,1),
('barrio','DRAGO',12,1),
('barrio','ECUADOR Y SANTA FE',2,1),
('barrio','ECUADOR Y STA FE',2,1),
('barrio','ECHAGUE Y SAENZ PEÑA',1,1),
('barrio','ECHEANDIA Y WHITE',9,1),
('barrio','ECHEANDIA Y WHITE COMUNA 9',9,1),
('barrio','ECHEVERRIA Y AMENABAR',13,1),
('barrio','EL SALVADOR Y BULNES',14,1),
('barrio','ELCANO 3100',13,1),
('barrio','EMILIO CASTRO',99,1),
('barrio','EMILIO CASTRO Y PILAR',9,1),
('barrio','EMILIO LAMARCA',99,1),
('barrio','EN EL CENTRO',1,1),
('barrio','EN TODA LA CIUDAD',99,1),
('barrio','ENTRE RIOS Y ALSINA',1,1),
('barrio','ESCALADA Y CRISOSTOMO ALVAREZ',9,1),
('barrio','ESCALADA Y CRUZ',8,1),
('barrio','ESCALADA Y DIRECTORIO',9,1),
('barrio','ESCALADA Y PRIMERA JUNTA',9,1),
('barrio','ESMERALDA 1212',1,1),
('barrio','ESMERALDA 130',1,1),
('barrio','ESMERALDA 762',1,1),
('barrio','ESMERALDA Y ARENALES',1,1),
('barrio','ESMERALDA Y LAVALLE',1,1),
('barrio','ESMERALDA Y LIBERTADOR',1,1),
('barrio','ESMERALDA Y RIVADAVIA',1,1),
('barrio','ESTACION CONGRESO',3,1),
('barrio','EVA PERON 5400',8,1),
('barrio','EVA PERON Y LAUTARO',7,1),
('barrio','EVA PERON Y SAN PEDRITO',7,1),
('barrio','EZEIZA',null,1),
('barrio','FERIA DE LAS NACIONES',99,1),
('barrio','FIGUEROA ALCORTA Y SARMIENTO',14,1),
('barrio','FINOCCHIETO Y SALTA',4,1),
('barrio','FLOES',7,1),
('barrio','FLOREA',7,1),
('barrio','FLORES',7,1),
('barrio','FLORES AVELLANEDA Y NAZCA',7,1),
('barrio','FLORES BALBASTRO Y CARABOBO',7,1),
('barrio','FLORES BOYACA Y AVELLANEDA',7,1),
('barrio','FLORES CALLE AVELLANEDA Y NAZCA',7,1),
('barrio','FLORES SUR',7,1),
('barrio','FLORES Y V LUGANO',7,1),
('barrio','FLORESTA',10,1),
('barrio','FLORESTA Y VILLA CRESPO',10,1),
('barrio','FLORIDA',1,1),
('barrio','FLORIDA 700',1,1),
('barrio','FLORIDA 860',1,1),
('barrio','FLORIDA Y AV DE MAYO',1,1),
('barrio','FLORIDA Y CORRIENTES',1,1),
('barrio','FLORIDA Y DIAGONAL',1,1),
('barrio','FLORIDA Y DIAGONAL NORTE',1,1),
('barrio','FLORIDA Y LAVALLE',1,1),
('barrio','FLORIDA Y PERON',1,1),
('barrio','FLORIDA Y SARMIENTO',1,1),
('barrio','FLORIDA Y VIAMONTE',1,1),
('barrio','FORESTA',10,1),
('barrio','FRENCH Y CORONEL DIAZ',2,1),
('barrio','GALLO Y HUMAHUACA',3,1),
('barrio','GALLO Y PARAGUAY',2,1),
('barrio','GAONA',99,1),
('barrio','GAONA 1584',6,1),
('barrio','GAONA Y DONATO ALVAREZ',6,1),
('barrio','GAONA Y SAN MARTIN',6,1),
('barrio','GARAY Y AZOPARDO',1,1),
('barrio','GARMENDIA COMUNA 15',15,1),
('barrio','GARZON 3900',9,1),
('barrio','GASCON 1125',5,1),
('barrio','GASCON Y SARMIENTO',5,1),
('barrio','GAUNA 2700',7,1),
('barrio','GENARO Y LAVALLE',99,1),
('barrio','GEND NAC',1,1),
('barrio','GENERAL PAZ Y CONSTITUYENTES',12,1),
('barrio','GORRITI Y DORREGO',14,1),
('barrio','GRAL PAZ 5445',12,1),
('barrio','GRAÑ PAZ Y CONSTITUYENTES',12,1),
('barrio','GREGORIO DE LA FERRERE 1325',7,1),
('barrio','GUATEMALA Y DORREGO',14,1),
('barrio','H IRIGOYEN 250 Y BALCARCE',1,1),
('barrio','H YRIGOYEN Y BOLIVAR',1,1),
('barrio','H YRIGOYEN Y ENTRE RIOS',1,1),
('barrio','H YRIGOYEN Y PERU',1,1),
('barrio','H YRIGOYEN Y RIVADAVIA',5,1),
('barrio','H YRIGOYEN Y SANTIAGO DEL ESTERO',1,1),
('barrio','HELGUERA VILLA PUEYRREDON',12,1),
('barrio','HERNANDARIAS 1450',4,1),
('barrio','HIDALGO Y ARANGUREN',6,1),
('barrio','HIPODROMO PALERMO',14,1),
('barrio','HIPOLITO IRIGOYEN 3200',3,1),
('barrio','HIPOLITO YRIGOYEN 250',1,1),
('barrio','HONDURAS Y SALGUERO',14,1),
('barrio','HOSP FERNANDEZ',14,1),
('barrio','HOSPITAL ITALIANO',5,1),
('barrio','HUMAHUACA Y GASCON',5,1),
('barrio','IGUAZU Y LOS PATOS',4,1),
('barrio','INDEPENDENCIA Y PERU',1,1),
('barrio','INDEPENDENCIA Y RINCON',3,1),
('barrio','INDEPENDENCIA Y SOLIS',1,1),
('barrio','IRIGOYEN 300',1,1),
('barrio','IRIGOYEN Y BALCARCE',1,1),
('barrio','J A ROCA Y PERU',1,1),
('barrio','J B JUSTO Y CORDOBA',15,1),
('barrio','J Y C BARROS',5,1),
('barrio','JEAN JAURES',99,1),
('barrio','JEAN JAURES 970',3,1),
('barrio','JONTE Y SEGUROLA',10,1),
('barrio','JORGE NEWBERY ENTRE CHARLONE Y ROSETI',15,1),
('barrio','JUAN B JUSTO Y CORRO',10,1),
('barrio','JUAN DE GARAY Y STGO DEL ESTERO',1,1),
('barrio','JUJUY E INDEPENDENCIA',3,1),
('barrio','JUJUY Y MEXICO',3,1),
('barrio','JULIO A ROCA 694',1,1),
('barrio','JUNCAL Y LIBERTADOR',1,1),
('barrio','JUNCAL Y S ORTIZ',14,1),
('barrio','JUNCAL Y SUIPACHA RETIRO',1,1),
('barrio','JUNIN 1100',2,1),
('barrio','JUNIN Y AYACUCHO',99,1),
('barrio','JUNIN Y CORDOBA',2,1),
('barrio','JUNIN Y CORRIENTES',3,1),
('barrio','JUNIN Y LIBERTADOR',2,1),
('barrio','JUNTA Y CARABOBO',7,1),
('barrio','JURAMENTO 750',13,1),
('barrio','JURAMENTO Y ARCOS',13,1),
('barrio','L N ALEM',1,1),
('barrio','L N ALEM Y PARAGUAY',1,1),
('barrio','LA BOCA',4,1),
('barrio','LA BOCA Y CONGRESO',4,1),
('barrio','LA FERRERE',null,1),
('barrio','LA MATANZA',null,1),
('barrio','LA PAMPA Y ARCOS',13,1),
('barrio','LA PATERNAL',15,1),
('barrio','LA PLATA',null,1),
('barrio','LA RIOJA 2975',4,1),
('barrio','LACROZE Y CONESA',13,1),
('barrio','LAFUENTE Y RIVADAVIA',7,1),
('barrio','LAGUNA Y LLANOS',99,1),
('barrio','LANUS',null,1),
('barrio','LARREA',99,1),
('barrio','LARREA Y CORDOBA',3,1),
('barrio','LARREA Y LAVALLE',3,1),
('barrio','LARREA Y M T DE ALVEAR',2,1),
('barrio','LARREA Y MARCELO T DE ALVEAR',2,1),
('barrio','LAS CAÑITAS',14,1),
('barrio','LAS CAÑITAS BELGRANO',14,1),
('barrio','LAS CASAS Y BOEDO',5,1),
('barrio','LAS HERAS',2,1),
('barrio','LAS HERAS 2900',2,1),
('barrio','LAS HERAS Y PUEYRREDON Y YRIGOYEN AL 400',2,1),
('barrio','LAVALLE',99,1),
('barrio','LAVALLE 1200',1,1),
('barrio','LAVALLE 1638',1,1),
('barrio','LAVALLE 1974',3,1),
('barrio','LAVALLE AL 700',1,1),
('barrio','LAVALLE MICROCENTRO',1,1),
('barrio','LAVALLE Y CORRIENTES',99,1),
('barrio','LAVALLE Y ESMERALDA',1,1),
('barrio','LAVALLE Y LIBERTAD',1,1),
('barrio','LAVALLE Y PARANA',1,1),
('barrio','LAVALLE Y PUEYRREDON',3,1),
('barrio','LAVALLE Y RECONQUISTA',1,1),
('barrio','LAVALLE Y SUIPACHA',1,1),
('barrio','LAVALLE Y URUGUAY',1,1),
('barrio','LEANDRO ALEM Y CORRIENTES',1,1),
('barrio','LEIVA Y GUZMAN',15,1),
('barrio','LIBERTAD 41',1,1),
('barrio','LIBERTAD Y ARENALES',1,1),
('barrio','LIBERTAD Y CERRITO',99,1),
('barrio','LIBERTAD Y CORDOBA',1,1),
('barrio','LIBERTAD Y SARMIENTO',1,1),
('barrio','LIBERTAD Y VIAMONTE',1,1),
('barrio','LIBERTADOR 6026',13,1),
('barrio','LIMA E INDEPENDENCIA',1,1),
('barrio','LIMA Y MORENO',1,1),
('barrio','LINIERS',9,1),
('barrio','LINIERS IBARROLA Y GRAL PAZ',9,1),
('barrio','LOS INCAS Y TRIUNVIRATO',15,1),
('barrio','LOS PATOS E IGUAZU',4,1),
('barrio','LUGANO',8,1),
('barrio','LUGANO 1 Y 2',8,1),
('barrio','LUGANO 1Y2',8,1),
('barrio','LUGANO RIESTRA 5030',8,1),
('barrio','LUIS M CAMPOS 700',14,1),
('barrio','M T DE ALVEAR',99,1),
('barrio','M T DE ALVEAR Y SUIPACHA',1,1),
('barrio','M T DE ALVEAR Y URUGUAY',2,1),
('barrio','M9 C 69 AL LADO DE LA IGLESIA',99,1),
('barrio','MADERO 200',9,1),
('barrio','MADERO 942 STA CATALINA AL LADO DE PTO MADERO',1,1),
('barrio','MAIPU',1,1),
('barrio','MAIPU 700',1,1),
('barrio','MAIPU 933',1,1),
('barrio','MAIPU Y CORRIENTES',1,1),
('barrio','MAIPU Y ESMERALDA',1,1),
('barrio','MAIPU Y MITRE',1,1),
('barrio','MAIPU Y RIVADAVIA',1,1),
('barrio','MAIPU Y VIAMONTE',1,1),
('barrio','MALVINAS ARGENTINAS',99,1),
('barrio','MANZANA 11 VILLA 1-11-14',7,1),
('barrio','MARC T DE ALVEAR Y LARREA',2,1),
('barrio','MARCELO T ALVEAR',99,1),
('barrio','MARCELO T DE ALVEAR Y URIBURU',2,1),
('barrio','MARCELO T Y SAN MARTIN',1,1),
('barrio','MARIO BRAVO Y CORDOBA',5,1),
('barrio','MARTINEZ',null,1),
('barrio','MATADERO',9,1),
('barrio','MATADEROS',9,1),
('barrio','MATADEROS 9 COMUNA',9,1),
('barrio','MATADEROS COMUNA 9',9,1),
('barrio','MATADEROS ES COMUNA NUEVE ME ACLARAN',9,1),
('barrio','MATANZA',null,1),
('barrio','MATIENZO 1500',14,1),
('barrio','MATIENZO Y CABILDO',14,1),
('barrio','MATURIN 2233',15,1),
('barrio','MAURE 1700',14,1),
('barrio','MAZA Y BELGRANO',5,1),
('barrio','MEDINA 1700',9,1),
('barrio','MEDRANO',99,1),
('barrio','MERCADO CENTRAL',null,1),
('barrio','MEXICO 300',1,1),
('barrio','MEXICO Y AGRELO',99,1),
('barrio','MIC',1,1),
('barrio','MICRCENTRO',1,1),
('barrio','MICRO CENTRO',1,1),
('barrio','MICRO CTRO',1,1),
('barrio','MICRO CTRO URUGUAY Y CORRIENTES',1,1),
('barrio','MICRO ENTRO',1,1),
('barrio','MICRO MONSERRAT',1,1),
('barrio','MICROCENTO',1,1),
('barrio','MICROCENTRO',1,1),
('barrio','MICROCENTRO 25 DE MAYO Y LAVALLE',1,1),
('barrio','MICROCENTRO FLORIDA Y CORRIENTES',1,1),
('barrio','MICROCENTRO LAVALLE Y MAIPU',1,1),
('barrio','MICROCENTRO NO SABE MAS',1,1),
('barrio','MICROCENTRO ONCE',1,1),
('barrio','MICROCENTRO SARMIENTO 700',1,1),
('barrio','MICRONCENTRO',1,1),
('barrio','MICROSENTRO AV CORRIENTES',1,1),
('barrio','MINISTERIO DE EDUCACION PASEO COLON AL 200',1,1),
('barrio','MIRALLA 130 COMUNA 7',9,1),
('barrio','MISIONES 71',3,1),
('barrio','MITRE 2700',3,1),
('barrio','MITRE 300',1,1),
('barrio','MITRE 3300',3,1),
('barrio','MITRE 3345',3,1),
('barrio','MITRE Y 9 DE JULIO',1,1),
('barrio','MITRE Y BUSTAMANTE',1,1),
('barrio','MITRE Y CHACABUCO OTRA POR DIAGONAL SON MUCHAS QUE LO CONTRATAN',1,1),
('barrio','MITRE Y PUEYRREDON',1,1),
('barrio','MITRE Y SAN MARTIN',1,1),
('barrio','MITRE Y URUGUAY',1,1),
('barrio','MONROE Y AMENABAR',13,1),
('barrio','MONSERRAT',1,1),
('barrio','MONSERRAT CONGRESO',1,1),
('barrio','MONSERRAT MAIPU',1,1),
('barrio','MONTE CASTRO',10,1),
('barrio','MONTE CASTRO LOPE DE VEGA Y SAN BLAS',10,1),
('barrio','MONTECASTRO',10,1),
('barrio','MONTEVIDEO 950',2,1),
('barrio','MONTEVIDEO Y LAVALLE',1,1),
('barrio','MONTIEL Y SCHMIDEL',9,1),
('barrio','MONTSERRAT',1,1),
('barrio','MORENO',1,1),
('barrio','MORENO 1550',1,1),
('barrio','MORENO 1660',1,1),
('barrio','MORENO 600',1,1),
('barrio','MORENO 648',1,1),
('barrio','MORENO AL 1300',1,1),
('barrio','MORENO Y 9 DE JULIO',1,1),
('barrio','MORENO Y ALSINA',1,1),
('barrio','MORENO Y AV DE MAYO',1,1),
('barrio','MORENO Y BOLIVAR',1,1),
('barrio','MORENO Y ENTRE RIOS',1,1),
('barrio','MORENO Y PERU',1,1),
('barrio','MORENO Y PIEDRAS',1,1),
('barrio','MORENO Y TACUARI',1,1),
('barrio','MT DE ALVEAR Y MONTEVIDEO',2,1),
('barrio','MUGRIONDO 1400',9,1),
('barrio','MUNRO',null,1),
('barrio','MUÑIZ Y RIVADAVIA',5,1),
('barrio','MURILLO Y MALABIA',15,1),
('barrio','NAZCA 2641 DEPTO 2',11,1),
('barrio','NAZCA Y GARCIA',11,1),
('barrio','NAZCA Y JUAN B JUSTO',11,1),
('barrio','SAN TEÑMO',1,1),
('barrio','NICASIO OROÑO Y JUAN B JUSTO',11,1),
('barrio','NICETO VEGA Y THAMES',14,1),
('barrio','NO CONTESTA',99,1),
('barrio','NO QUIERE CONTESTAR',99,1),
('barrio','NO RECUERDA',99,1),
('barrio','NO SABE',99,1),
('barrio','NORTE',99,1),
('barrio','NR',99,1),
('barrio','NS NC',99,1),
('barrio','NUEVA POMPEYA',4,1),
('barrio','NUEVE DE JULIO',1,1),
('barrio','NUEVO RETIRO COMUNA 1',1,1),
('barrio','NUÑEZ',13,1),
('barrio','NUÑEZ CRAMER',13,1),
('barrio','OBELISCO',1,1),
('barrio','OBLIGADO',99,1),
('barrio','OCAMPO Y CERVIÑO',14,1),
('barrio','OLIDE 4000',8,1),
('barrio','OLIVOS',null,1),
('barrio','ONCE',3,1),
('barrio','ONCE PLAZA MISERERE',3,1),
('barrio','ONCE SOBRE CALLE PUEYRREDON',3,1),
('barrio','P AVELLANEDA',1,1),
('barrio','P COLON Y BELGRANO',1,1),
('barrio','P MADERO',4,1),
('barrio','P PATRICIO',4,1),
('barrio','P PATRICIOS',4,1),
('barrio','PACHECO DE MELO 1826',2,1),
('barrio','PALACIO DE TRIBUNALES',1,1),
('barrio','PALEMO',14,1),
('barrio','PALERMO',14,1),
('barrio','PALERMO BERUTI ENTRE AGUERO Y LAPRIDA',14,1),
('barrio','PALERMO BERUTI Y N S',14,1),
('barrio','PALERMO BOTANICO',14,1),
('barrio','PALERMO HOLLYWOOD',14,1),
('barrio','PALERMO NUÑEZ',14,1),
('barrio','PARAGUAY 2155',2,1),
('barrio','PARAGUAY Y AZCUENAGA',2,1),
('barrio','PARAGUAY Y CORDOBA',99,1),
('barrio','PARAGUAY Y FLORIDA',1,1),
('barrio','PARAGUAY Y PARANA',2,1),
('barrio','PARAGUAY Y URIBURU',2,1),
('barrio','PARANA Y CORDOBA',2,1),
('barrio','PARANA Y CORRIENTES',1,1),
('barrio','PARQUE AVELLANEDA',9,1),
('barrio','PARQUE CENTENARIO',6,1),
('barrio','PARQUE CHACABUCO',7,1),
('barrio','PARQUE CHAS',15,1),
('barrio','PARQUE DE LOS PATRICIOS',4,1),
('barrio','PARQUE LEZAMA',1,1),
('barrio','PARQUE PATRCIOS',4,1),
('barrio','PARQUE PATRICIO',4,1),
('barrio','PARQUE PATRICIOS',4,1),
('barrio','PASAJE CARABELAS',1,1),
('barrio','PASEO COLON',1,1),
('barrio','PASEO COLON 1300',1,1),
('barrio','PASEO COLON 1400',1,1),
('barrio','PASEO COLON 171',1,1),
('barrio','PASEO COLON 700',1,1),
('barrio','PASEO COLON 850',1,1),
('barrio','PASEO COLON 982',1,1),
('barrio','PASEO COLON AV INDEPENDENCIA',1,1),
('barrio','PASEO COLON Y ALSINA',1,1),
('barrio','PASEO COLON Y AV DE MAYO',1,1),
('barrio','PASEO COLON Y EEUU SAN TELMO',1,1),
('barrio','PASEO COLON Y INDEPENDENCIA',1,1),
('barrio','PASEO COLON Y MEXICO',1,1),
('barrio','PASO 551',3,1),
('barrio','PASO Y TUCUMAN',3,1),
('barrio','PASTEUR Y LAVALLE',3,1),
('barrio','PASTEUR Y TUCUMAN',3,1),
('barrio','PATERNAL',15,1),
('barrio','PATRICIOS Y URIARTE',99,1),
('barrio','PAVON Y JUJUY',3,1),
('barrio','PEDERNERA Y EVA PERON',7,1),
('barrio','PEDERNERA Y RIVADAVIA',7,1),
('barrio','PEDRIEL Y CASEROS',4,1),
('barrio','PEDRO CHUTRO 3380',4,1),
('barrio','PEDRO CHUTRO Y MONTESQUIEU',4,1),
('barrio','PELERMO',14,1),
('barrio','PELLEGRINI Y CANGALLO',1,1),
('barrio','PELLEGRINI Y JUNCAL',1,1),
('barrio','PELLEGRINI Y POSADAS',1,1),
('barrio','PELLIGRINI Y SANTA FE',1,1),
('barrio','PEÑA Y PUEYRREDON',1,1),
('barrio','PEPIRI Y SANTO DOMINGO',1,1),
('barrio','PERDRIEL 1800',4,1),
('barrio','PERGAMINO Y RIVADAVIA',10,1),
('barrio','PERON Y BOULOGNE SUR MER',3,1),
('barrio','PERON Y DIAGONAL N',1,1),
('barrio','PERON Y FLORIDA',1,1),
('barrio','PERON Y LIBERTAD',1,1),
('barrio','PERON Y PASTEUR',3,1),
('barrio','PERON Y RECONQUISTA',1,1),
('barrio','PERON Y SUIPACHA',1,1),
('barrio','PERON Y URUGUAY',1,1),
('barrio','PERU 100',1,1),
('barrio','PERU Y AV DE MAYO',1,1),
('barrio','PERU Y DIAGONAL SUR',1,1),
('barrio','PERU Y J A ROCA',1,1),
('barrio','PERU Y MORENO',1,1),
('barrio','PERU Y ROCA',1,1),
('barrio','PIEDRAS Y RIVADAVIA',1,1),
('barrio','PILETONES',8,1),
('barrio','PINTO Y CORREA',12,1),
('barrio','PIZZURNO Y MARCELO T',2,1),
('barrio','PLAZA DE LOS VIRREYES - FLORES',7,1),
('barrio','PLAZA DE MAYO',1,1),
('barrio','PLAZA IRLANDA',6,1),
('barrio','PLAZA MAYO',1,1),
('barrio','PLAZA ONCE',3,1),
('barrio','PLAZA SAN MARTIN',1,1),
('barrio','PLENO CENTRO',1,1),
('barrio','PLENO CENTRO COMUNA 1',1,1),
('barrio','POMPEYA',4,1),
('barrio','PORTELA Y CRUZ',4,1),
('barrio','POTOSI Y RAWSON',5,1),
('barrio','PQE CENTANARIO',6,1),
('barrio','PQE CENTENARIO',6,1),
('barrio','PQE PATRICIOS',4,1),
('barrio','PQUE CHACABUCO',7,1),
('barrio','PQUE PATRICIOS',4,1),
('barrio','PRESIDENTE PERON 2048',3,1),
('barrio','PRIMERA JUNTA',6,1),
('barrio','PTE PERON Y RODRIGUEZ PEÑA',1,1),
('barrio','PTO MADERO',1,1),
('barrio','PUAN 430',1,1),
('barrio','PUERTO MADERO',1,1),
('barrio','PUERTO MADERO ALICIA MOREAU DE JUSTO 50',1,1),
('barrio','PUERTO MADERO BOUCHARD 556',1,1),
('barrio','PUERTO MADERO Y HURLINGHAM',1,1),
('barrio','PUEYRREDON',99,1),
('barrio','PUEYRREDON 1361',2,1),
('barrio','PUEYRREDON Y CORDOBA',2,1),
('barrio','PUEYRREDON Y FRANCIA',99,1),
('barrio','PUEYRREDON Y SANTA FE',2,1),
('barrio','PURTO MADERO',1,1),
('barrio','PZA DE MAYO',1,1),
('barrio','PZA ITALIA',14,1),
('barrio','PZA SAN MARTIN RETIRO',1,1),
('barrio','RAMOS MEJIA',6,1),
('barrio','RAMOS MEJIA 1000',6,1),
('barrio','RECOLETA',2,1),
('barrio','RECONQUISTA',1,1),
('barrio','RECONQUISTA 266',1,1),
('barrio','RECONQUISTA 600',1,1),
('barrio','RECONQUISTA Y BARTOLME MITRE',1,1),
('barrio','RECONQUISTA Y CORDOBA',1,1),
('barrio','RECONQUISTA Y CORRIENTES',1,1),
('barrio','RECONQUISTA Y ESMERALDA',1,1),
('barrio','RECONQUISTA Y LAVALLE',1,1),
('barrio','RECONQUISTA Y MITRE',1,1),
('barrio','RECONQUISTA Y TUCUMAN',1,1),
('barrio','REGIMIENTO DE PATRICIOS 1142',4,1),
('barrio','REMEDIO ESCALADA DE SAN MARTIN Y SEGUROLA',10,1),
('barrio','RESISTENCIA Y CORRIENTES',1,1),
('barrio','RETIRO',1,1),
('barrio','RETIRO ALEM Y M T DE ALVEAR',1,1),
('barrio','RETIRO COMUNA 1',1,1),
('barrio','RETIRO PUERTO',1,1),
('barrio','RIESTRA Y BONORINO',7,1),
('barrio','RIESTRA Y CAMILO TORRES',7,1),
('barrio','RIESTRAY CENTERA',7,1),
('barrio','RIOBAMBA Y CORRIENTES',3,1),
('barrio','RIV Y 24 DE NOVIEMBRE',3,1),
('barrio','RIVADABIA',99,1),
('barrio','RIVADAVIA',99,1),
('barrio','RIVADAVIA 2230',3,1),
('barrio','RIVADAVIA 4300',5,1),
('barrio','RIVADAVIA Y 9 DE JULIO',1,1),
('barrio','RIVADAVIA Y ACOYTE',6,1),
('barrio','RIVADAVIA Y ARTIGAS',7,1),
('barrio','RIVADAVIA Y CALLAO',3,1),
('barrio','RIVADAVIA Y CARLOS PELLEGRINI',1,1),
('barrio','RIVADAVIA Y ESMERALDA',1,1),
('barrio','RIVADAVIA Y LARREA',3,1),
('barrio','RIVADAVIA Y MAIPU',1,1),
('barrio','RIVADAVIA Y MARMOL',5,1),
('barrio','RIVADAVIA Y MITRE',6,1),
('barrio','RIVADAVIA Y PARANA',1,1),
('barrio','RODRIGUEZ PEÑA 4086',99,1),
('barrio','RODRIGUEZ PEÑA Y PARAGUAY',2,1),
('barrio','RODRIGUEZ PEÑA Y PERON',1,1),
('barrio','RONDEAU Y PICHINCHA',4,1),
('barrio','ROQUE SAENZ PEÑA 530',1,1),
('barrio','S DE BUSTAMANTE Y PEÑA',2,1),
('barrio','S DEBUSTAMANTE Y PEÑA',2,1),
('barrio','S FE Y CNEL DIAZ',14,1),
('barrio','S NICOLAS',1,1),
('barrio','S ORTIZ Y PARAGUAY',14,1),
('barrio','S TELMO',1,1),
('barrio','SAAVEDRA',12,1),
('barrio','SAAVEDRA DOT',12,1),
('barrio','SALGUERO Y HONDURAS',14,1),
('barrio','SALTA 1199',1,1),
('barrio','SALTA Y CARLOS CALVO',1,1),
('barrio','SAN CRISTOBAL',3,1),
('barrio','SAN ISIDRO',null,1),
('barrio','SAN JUAN Y BOEDO',5,1),
('barrio','SAN JUAN Y ENTRE RIOS',1,1),
('barrio','SAN JUAN Y RINCON',3,1),
('barrio','SAN JUSTO',null,1),
('barrio','SAN MARTIN',1,1),
('barrio','SAN MARTIN 451',1,1),
('barrio','SAN MARTIN 551',1,1),
('barrio','SAN MARTIN Y BARTOLOME MITRE',1,1),
('barrio','SAN MARTIN Y GAONA',1,1),
('barrio','SAN MARTIN Y M T ALVEAR',1,1),
('barrio','SAN MARTIN Y PERON',1,1),
('barrio','SAN MARTIN Y VIAMONTE',1,1),
('barrio','SAN NICOLAS',1,1),
('barrio','SAN NICOLAS MAIPU Y SUIPACHA',1,1),
('barrio','SAN NICOLAS SAN CRISTOBAL',1,1),
('barrio','SAN TELMO',1,1),
('barrio','SANABRIA SANBLAS',10,1),
('barrio','SANNICOLAS',1,1),
('barrio','SANRA FE Y CALLAO',2,1),
('barrio','SANTA 4320',14,1),
('barrio','SANTA FE 3311',14,1),
('barrio','SANTA FE ENTRE ESMERALDA Y SUIPACHA',1,1),
('barrio','SANTA FE Y AGUERO',2,1),
('barrio','SANTA FE Y AYACUCHO',2,1),
('barrio','SANTA FE Y BULNES',14,1),
('barrio','SANTA FE Y CALLAO',14,1),
('barrio','SANTA FE Y ECUADOR',2,1),
('barrio','SANTA FE Y JUNIN',2,1),
('barrio','SANTA FE Y MARCELO T DE ALVEAR',99,1),
('barrio','SANTA FE Y PELLEGRINI',1,1),
('barrio','SANTA FE Y PUEYRREDON',1,1),
('barrio','SANTA FE Y RIOBAMBA',2,1),
('barrio','SANTA RITA',11,1),
('barrio','SANTANDER 3793',9,1),
('barrio','SANTE FE Y CALLAO',2,1),
('barrio','SANTELMO',1,1),
('barrio','SANTIAGO DEL ESTERO Y BRASIL',1,1),
('barrio','SANTIAGO DEL ESTERO Y ESTADOS UNIDOS',1,1),
('barrio','SANTOS DUMOND Y CABILDO',14,1),
('barrio','SARMIENTO 1500',1,1),
('barrio','SARMIENTO 300',1,1),
('barrio','SARMIENTO 329',1,1),
('barrio','SARMIENTO 877',1,1),
('barrio','SARMIENTO Y 25 DE MAYO',1,1),
('barrio','SARMIENTO Y CALLAO',14,1),
('barrio','SARMIENTO Y FLORIDA',1,1),
('barrio','SARMIENTO Y FLORIDA MICROCENTRO',1,1),
('barrio','SARMIENTO Y PARANA',1,1),
('barrio','SARMIENTO Y PELLEGRINI',1,1),
('barrio','SARMIENTO Y RECONQUISTA',1,1),
('barrio','SARMIENTO Y SUIPACHA',1,1),
('barrio','SARMIENTO Y URUGUAY',1,1),
('barrio','SAVEEDRA',12,1),
('barrio','SEGUI Y ESPINOSA',15,1),
('barrio','SEGUROLA',99,1),
('barrio','SEGUROLA Y JONTE',10,1),
('barrio','SINCLAIR Y CERVIÑO',14,1),
('barrio','SOBRE LA CALLE FLORIDA',1,1),
('barrio','SOLDATI',8,1),
('barrio','SOLIS Y ALSINA',1,1),
('barrio','STA FE Y ARENALES',99,1),
('barrio','SUIPACHA 1300',1,1),
('barrio','SUIPACHA Y CORDOBA',1,1),
('barrio','SUIPACHA Y DIAGONAL NORTE',1,1),
('barrio','SUIPACHA Y TUCUMAN',1,1),
('barrio','TACUARI 138',1,1),
('barrio','TACUARI E INDEPENDENCIA',1,1),
('barrio','TACUARI Y FINOCHIETO',4,1),
('barrio','TACUARI Y MORENO',1,1),
('barrio','TALCAHUANO 1055',1,1),
('barrio','TALCAHUANO 550',1,1),
('barrio','TALCAHUANO Y CALLAO',1,1),
('barrio','TALCAHUANO Y CORDOBA',1,1),
('barrio','TALCAHUANO Y CORRIENTES',1,1),
('barrio','TALCAHUANO Y LAVALLE',1,1),
('barrio','TALCAHUANO Y LIBERTAD',1,1),
('barrio','TALCUAHUANO ENTRE TUCUMAN Y LAVALLE',1,1),
('barrio','TEMPERLEY',null,1),
('barrio','TERMINAL DE OMNIBUS DE RETIRO',1,1),
('barrio','TERRERO Y SAN BLAS',11,1),
('barrio','THAMES 2164',14,1),
('barrio','THAMES Y COSTA RICA',14,1),
('barrio','THAMES Y GUEMES',14,1),
('barrio','TRIBUNALES',1,1),
('barrio','TRIBUNALES SAN NICOLAS',1,1),
('barrio','TRONADOR 400',15,1),
('barrio','TUCUMAN 1700',1,1),
('barrio','TUCUMAN 501',1,1),
('barrio','TUCUMAN AL 1300',1,1),
('barrio','TUCUMAN Y BOUCHARD',1,1),
('barrio','TUCUMAN Y C PELLEGRINI',1,1),
('barrio','TUCUMAN Y CALLAO',1,1),
('barrio','TUCUMAN Y CERRITO',1,1),
('barrio','TUCUMAN Y ESMERALDA',1,1),
('barrio','TUCUMAN Y MAIPU',1,1),
('barrio','TUCUMAN300',1,1),
('barrio','UADE',1,1),
('barrio','URQUIZA',12,1),
('barrio','URQUIZA 700',3,1),
('barrio','URUGUAY 440',3,1),
('barrio','URUGUAY Y CORDOBA',1,1),
('barrio','URUGUAY Y CORRIENTES',1,1),
('barrio','URUGUAY Y LAVALLE',1,1),
('barrio','URUGUAY Y PERON',1,1),
('barrio','URUGUAY Y RVADAVIA',1,1),
('barrio','URUGUAY Y VIAMONTE',1,1),
('barrio','USPALLATA 2272',4,1),
('barrio','V CRESPO',15,1),
('barrio','V DEL PARQUE',11,1),
('barrio','V LURO',10,1),
('barrio','V ORTUZAR',15,1),
('barrio','V PUERREDON',12,1),
('barrio','V PUEYRREDON',12,1),
('barrio','V SOLDATI',8,1),
('barrio','V URQUIZA',12,1),
('barrio','VARELA 1305',7,1),
('barrio','VARELA 802',7,1),
('barrio','VARELA Y DIRECTORIO',7,1),
('barrio','VCTE LOPEZ',null,1),
('barrio','VELEZ SARDFIELD',4,1),
('barrio','VELEZ SARFIELD',4,1),
('barrio','VELEZ SARFIELD 1600',4,1),
('barrio','VELEZ SARFIELD Y CASEROS',4,1),
('barrio','VENEZUELA 1500',1,1),
('barrio','VENEZUELA Y MEXICO',1,1),
('barrio','VENEZUELA Y PERU',1,1),
('barrio','VENTANA 3366',4,1),
('barrio','VERSAILLES',10,1),
('barrio','VERSALLES',10,1),
('barrio','VESAILLES',10,1),
('barrio','VIAMONTE 1400',1,1),
('barrio','VIAMONTE 1600',1,1),
('barrio','VIAMONTE 400',1,1),
('barrio','VIAMONTE 430',1,1),
('barrio','VIAMONTE 800',1,1),
('barrio','VIAMONTE Y CERRITO',1,1),
('barrio','VIAMONTE Y FLORIDA',1,1),
('barrio','VIAMONTE Y MONTEVIDEO',1,1),
('barrio','VIAMONTE Y PARANA',1,1),
('barrio','VIAMONTE Y RECONQUISTA',1,1),
('barrio','VIAMONTE Y SAN LUIS',99,1),
('barrio','VIAMONTE Y SAN MARTIN',1,1),
('barrio','VIAMONTE Y SUIPACHA',1,1),
('barrio','VIAMONTE Y TALCAHUANO',1,1),
('barrio','VIAMONTE Y TUCUMAN',99,1),
('barrio','VICENTE LOPEZ Y JUNIN',2,1),
('barrio','VICENTELOPEZ Y JUNIN',2,1),
('barrio','VICTOR MARTINEZ Y ASAMBLEA',7,1),
('barrio','VIDT 658',99,1),
('barrio','VIEYTES BARRACAS',4,1),
('barrio','VIILLA DE PARQUE',11,1),
('barrio','VILA DEVOTO',11,1),
('barrio','VILA PUEYRREDON',12,1),
('barrio','VILLA 1-11-14',7,1),
('barrio','VILLA 1-11-14 FLORES',7,1),
('barrio','VILLA 1 11 14',7,1),
('barrio','VILLA 11-14 BAJO FLORES',7,1),
('barrio','VILLA 19',8,1),
('barrio','VILLA 20',8,1),
('barrio','VILLA 21',4,1),
('barrio','VILLA 21-24',4,1),
('barrio','VILLA 31',1,1),
('barrio','VILLA 31 BIS',1,1),
('barrio','VILLA 6',9,1),
('barrio','VILLA BALLESTER',null,1),
('barrio','VILLA CELINA',null,1),
('barrio','VILLA CRESPO',15,1),
('barrio','VILLA CRESPO ANGEL GALLARDO 600',15,1),
('barrio','VILLA DE PARQUE',11,1),
('barrio','VILLA DEL PARQUE',11,1),
('barrio','VILLA DEVOTO',11,1),
('barrio','VILLA GENERAL MITRE',6,1),
('barrio','VILLA LUGANO',8,1),
('barrio','VILLA LURO',10,1),
('barrio','VILLA MARTELLI',null,1),
('barrio','VILLA MEDERO',1,1),
('barrio','VILLA MITRE',11,1),
('barrio','VILLA ORTUZAR',15,1),
('barrio','VILLA OTRUZAR',15,1),
('barrio','VILLA PUEYREDON',12,1),
('barrio','VILLA PUEYRREDON',12,1),
('barrio','VILLA REAL',10,1),
('barrio','VILLA RIACHUELO',8,1),
('barrio','VILLA SANTA RITA',11,1),
('barrio','VILLA SOLDATI',8,1),
('barrio','VILLA STA RITA',11,1),
('barrio','VILLA URQUIZA',12,1),
('barrio','VILLADEL PARQUE',11,1),
('barrio','VILLAFAÑE 500',4,1),
('barrio','VILLAPUEYRREDON',12,1),
('barrio','VILLAURQUIZA',12,1),
('barrio','VIRREY CEBALLOS',99,1),
('barrio','VIRREY CEBALLOS Y SAENZ PEÑA',99,1),
('barrio','VIRREYES',7,1),
('barrio','VPUEYRREDON',12,1),
('barrio','YERBAL 1766',7,1),
('barrio','YRIGOYEN Y 9 DE JULIO',1,1),
('barrio','ZABALETA',4,1),
('barrio','ZONA NORTE',99,1),
('barrio','ZONA SUR',99,1),
('barrio','ZUVIRIA Y CULPINA',7,1),
('barrio','ZUVIRIA Y MURGUIONDO',8,1);
