DROP SCHEMA if exists proc;
CREATE SCHEMA proc  AUTHORIZATION tedede_php;

DROP TABLE if exists proc.eah_hog_2012;

CREATE TABLE proc.eah_hog_2012
(
enc                 integer  NOT NULL,
id                  integer,   
hogbu               integer,   
hog_orig            integer  NOT NULL,  
comuna              integer,   
replica             integer,   
up                  integer,   
lote                integer,   
bolsa               integer,   
tlg                 integer,   
entrea              integer,   
respond             integer,   
telefono            character varying(50),   
nombrer             character varying(100),  
f_realiz            character varying(10),   
v1                  integer,   
total_h             integer,   
hog_pre             integer,   
tot_mi              integer,   
s1a1_obs            character varying(255), 
v2                  integer,   
v2_esp              character varying(50),  
v4                  integer,   
v5_esp              character varying(50),  
v5                  integer,   
v6                  integer,   
v7                  integer,   
v12                 integer,   
h1                  integer,   
h2                  integer,   
h2_esp              character varying(150),   
h3                  integer,  
h4                  integer,  
h4_tipot            integer,  
h4_tel              character varying(100),
h20_1               integer,  
h20_4               integer,  
h20_2               integer,  
h20_17              integer,  
h20_18              integer,  
h20_5               integer,  
h20_6               integer,  
h20_7               integer,  
h20_15              integer,  
h20_8               integer,  
h20_19              integer,  
h20_20              integer,  
h20_16              integer,  
h20_10              integer,  
h20_12              integer,  
h20_11              integer,  
h20_13              integer,  
h20_14              integer,  
h20_esp             character varying(150), 
h20_99              integer, 
x5                  integer, 
x5_tot              integer, 
h30_tv_sm           integer, 
h30_tv_pl           integer, 
h30_ce              integer, 
h30_nt              integer, 
h30_tb              integer, 
h30_cv              integer, 
h30_lv              integer, 
h30_au              integer, 
h30_im              integer, 
h30_in              integer, 
h30_tv_cs           integer, 
h30_tcel            integer, 
ec1                 integer, 
ec2                 integer, 
ec3                 integer, 
sexoj               integer, 
edadj               integer, 
FEXP                integer, 
FEXPA1              integer, 
FEXPB2              integer, 
DOMINIO             integer, 
H_PERHAB            numeric,  
h_hacina            numeric,   
hacinam             numeric, 
CONSTRAINT eah_hog_2012_pk PRIMARY KEY (enc, hog_orig)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE proc.eah_hog_2012
  OWNER TO tedede_php;


-- Table: proc.eah_ind_2012

DROP TABLE if exists proc.eah_ind_2012;  

CREATE TABLE proc.eah_ind_2012
(
enc                integer NOT NULL,
id                 integer, 
hogbu              integer, 
miebu              integer, 
hog_orig           integer NOT NULL,
mie_orig           integer NOT NULL,
nombre             character varying(100),
sexo               integer,   
p7                 integer,   
p8                 integer,   
f_nac              character varying(10),
edad               integer,     
p4                 integer,     
p5                 integer,     
p5b_bu             integer,     
p6a_bu             integer,     
p6b_bu             integer,     
p5b_orig           integer,     
p6a_orig           integer,     
p6b_orig           integer,     
f_realiz           character varying(10), 
comuna             integer,   
replica            integer,   
up                 integer,   
lote               integer,   
bolsa              integer,   
respondi_orig      integer,   
t1                 integer,   
t2                 integer,   
t3                 integer,   
t4                 integer,   
t5                 integer,   
t6                 integer,   
t7                 integer,   
t8                 integer,   
t8_otro            character varying(150), 
t9                 integer,     
t10                integer,     
t11                integer,     
t11_otro           character varying(150),
t12                integer,     
t13                integer,     
t14                integer,     
t15                integer,     
t16                integer,     
t17                integer,     
t18                integer,     
t19_anio           integer,     
t20                integer,     
t21                integer,     
t22                integer,     
t23                character varying(200), 
t24                character varying(200), 
t25                character varying(200), 
t26                character varying(200), 
t27                integer,     
t28                integer,     
t29                integer,     
t29a               integer,     
t30                integer,     
t31_d              integer,     
t31_l              integer,     
t31_ma             integer,     
t31_mi             integer,     
t31_j              integer,     
t31_v              integer,     
t31_s              integer,     
t32_d              integer,     
t32_l              integer,     
t32_ma             integer,     
t32_mi             integer,     
t32_j              integer,     
t32_v              integer,     
t32_s              integer,     
t33                integer,     
t34                integer,     
t35                integer,     
t36_1              integer,     
t36_2              integer,     
t36_3              integer,     
t36_4              integer,     
t36_5              integer,     
t36_6              integer,     
t36_7              integer,     
t36_7_otro         character varying(150), 
t36_8              integer,   
t36_8_otro         character varying(150),
t36_99             integer,      
t36_a              integer,   
t37                character varying(250), 
t37sd              integer,     
t38                integer,     
t39                integer,     
t39_barrio         character varying(250), 
t39_otro           character varying(250),
t39_bis            integer,      
t39_bis_cuantos    integer,      
t39_bis2           integer,      
t39_bis2_esp       character varying(200),
t40                integer,   
t41                character varying(250), 
t42                character varying(250),
t43                character varying(250),
t44                integer,     
t45                integer,     
t46                integer,     
t47                integer,     
t48                integer,     
t48a               integer,     
t48b               integer,     
t48b_esp           character varying(150), 
t49                integer,     
t50a               integer,     
t50b               integer,     
t50c               integer,     
t50d               integer,     
t50e               integer,     
t50f               integer,     
t51                integer,     
t52a               integer,     
t52b               integer,     
t52c               integer,     
t53_ing            integer,     
t53_bis1           integer,     
t53_bis1_sem       integer,     
t53_bis1_mes       integer,     
t53_bis2           integer,     
t53c_anios         integer,     
t53c_meses         integer,     
t53c_98            integer,     
t54                integer,     
t54b               integer,     
i1                 integer,     
i2_totx            integer,     
i2_ticx            integer,     
i3_1               integer,     
i3_1x              integer,     
i3_2               integer,     
i3_2x              integer,     
i3_3               integer,     
i3_3x              integer,     
i3_4               integer,     
i3_4x              integer,     
i3_5               integer,     
i3_5x              integer,     
i3_6               integer,     
i3_6x              integer,     
i3_7               integer,     
i3_7x              integer,     
i3_8               integer,     
i3_8x              integer,     
i3_11              integer,     
i3_11x             integer,     
i3_12              integer,     
i3_12x             integer,     
i3_10              integer,     
i3_10_otro         character varying(200), 
i3_10x             integer,    
i3_13              integer,    
i3_13x             integer,    
i3_tot             integer,    
i3_99              integer,    
e1                 integer,    
e2                 integer,    
e3                 integer,    
e3a                integer,     
e4                 integer,     
e6                 integer,     
e8                 integer,    
e9_edad            integer,    
e9_anio            integer,    
e10                integer,    
e11_1              integer,    
e11_2              integer,    
e11_3              integer,    
e11_4              integer,    
e11_5              integer,    
e11_6              integer,    
e11_7              integer,    
e11_8              integer,    
e11_9              integer,    
e11_10             integer,    
e11_11             integer,    
e11_12             integer,    
e11_13             integer,    
e11_14             integer,    
e11_15             integer,    
e11_15_otro        character varying(255),
e11_99             integer,    
e11a               integer,    
e11_sum            numeric,    
e12                integer,    
e13                integer,    
e14                integer,    
te_1               integer,    
te_2               integer,    
e15_1              integer,    
e15_2              integer,    
e15_3              integer,    
e15_4              integer,    
e15_5              integer,    
e15_5_otro         character varying(255),
e15_6              integer,  
e15_7              integer,  
e15_99             integer,  
e15a               integer,  
e15_sum            numeric,  
m1                 integer,  
m1_esp2            character varying(50), 
m1_esp3            character varying(50),
m1_esp4            character varying(50), 
m1_anio            integer,      
m1a                integer,      
m1a_esp2           character varying(50),  
m1a_esp3           character varying(50),  
m1a_esp4           character varying(50), 
m3                 integer,    
m3_anio            integer,    
m4                 integer,    
m4_esp1            character varying(50),  
m4_esp2            character varying(50),  
m4_esp3            character varying(50), 
m5                 integer,    
sn1_1              integer,    
sn1_1_esp          character varying(100), 
sn1_7              integer,     
sn1_7_esp          character varying(100), 
sn1_2              integer,      
sn1_2_esp          character varying(100), 
sn1_3              integer,     
sn1_3_esp          character varying(100), 
sn1_4              integer,      
sn1_4_esp          character varying(100), 
sn1_5              integer,   
sn1_6              integer,   
sn1_99             integer,   
sn2                integer,   
sn2_cant           integer,   
sn3                integer,   
sn4                integer,   
sn4_esp            character varying(100), 
sn5                integer,     
sn5_esp            character varying(100), 
sn6                integer,   
sn6_cant           integer,   
sn8                integer,   
sn8_esp            character varying(150), 
sn9                integer,     
sn10a              integer,     
sn10b              integer,     
sn10c              integer,     
sn10d              integer,     
sn10e              integer,     
sn10f              integer,     
sn10g              integer,     
sn10h              integer,     
sn10i              integer,     
sn10j              integer,     
sn10_j_esp         character varying(150), 
sn11               integer,      
sn12               integer,      
sn12_esp           integer,      
sn13               integer,      
sn13_otro          character varying(150), 
sn14               integer,      
sn14_esp           character varying(150), 
sn15a              integer,      
sn15b              integer,      
sn15c              integer,      
sn15d              integer,      
sn15e              integer,      
sn15f              integer,      
sn15g              integer,      
sn15h              integer,      
sn15i              integer,      
sn15j              integer,      
sn15k              integer,      
sn15k_esp          character varying(255), 
sn16               integer,     
s28                integer,     
s29                integer,     
s30                integer,     
s31_anio           integer,     
s31_mes            integer,     
bc1_1              integer,     
bc1_2              integer,     
bc1_3              integer,     
bc1_4              integer,     
bc1_5              integer,     
bc1_6              integer,     
bc1_7              integer,     
bc1_8              integer,     
bc1_9              integer,     
bc1_99             integer,     
bc1_0              integer,     
bc1a               integer,     
bc2                integer,     
bc3                integer,     
bc4                integer,     
bc5                integer,     
bc6                integer,     
bc7                integer,     
bc8                integer,     
bc9                integer,     
bc10               integer,     
bc11               integer,     
bc12               integer,     
bc13               integer,     
OBS_i1C            character varying(255), 
estado             integer,   
DOMINIO            integer,   
FEXP               integer,   
FEXPA1             integer,   
FEXPB2             integer,   
CODLAB             integer,   
CODNOLAB           integer,   
CODING             integer,   
INGTOT             integer,   
itf                integer,   
CODITOT            numeric,  --cambiado 
ipcf               numeric,   
codlabu            integer,   
codnolbu           integer,   
CODINGBU           integer,   
coditobu           integer,   
f_n_hij            integer,   
sem_hs             numeric,   
tsemref            integer,   
t_intens           integer,   
t_suboc3           integer,   
categori           integer,   
tipodes            integer,   
categdes           integer,   
t_deman            integer,   
t39_comu           integer,   
t39zona3           integer,   
t39_rec            integer,   
t51_re             integer,   
e_nivela           integer,   
e_nivelb           integer,   
e_nivelc           integer,   
e_nivel            integer,   
e_aesc             integer,   
e_raesc            integer,   
e_sector           integer,   
edad_30_           integer,   
zona_3             integer,   
m_ln1              integer,   
m_ln2              integer,   
m_ln3              integer,   
m1_BU              integer,   
m1_2_BU            integer,   
s_tipco            integer,   
s_tipco2           integer,   
s_tipco3           integer,   
qipcf              integer,   
dipcf              integer,   
qitf               integer,   
ditf               integer,   
tipo_hb            integer,   
OBSOLparentes      integer,   
parentes_2BU       integer,   
p5_2BU             integer,   
m_limit            integer,   
m_lrma1            integer,   
m_lrma2            integer,   
m_rarc             integer,   
m_rlimit           integer,   
m_lvac1            integer,   
m_lvac2            integer,   
m_lvac3            integer,   
t37_coda           integer,   
sn2bu              integer,   
s9_2               integer,   
s12_2              integer,   
s12a               integer,   
tipco2_2bu         integer,   
m4_2               integer,   
m4_3               integer,   
t_ramDES           integer,   
t_ramOCU           integer,   
t_ramoc2           integer,   
t_ramde2           integer,   
T23_COD            integer,   
T24_COD            integer,   
T37_COD            integer,   
T41_COD            integer,   
t_calocu           numeric,   
t_calocu2          numeric,   
T23_CODNUE         integer,  
T37_CODNUE         integer,   
T24_CNUE           integer,   
T41_CNUE           integer,   
t_ramDESv          integer,   
t_ramocuv          integer,   
t_ramoc2v          numeric,   
t_ramde2v          numeric,   
cnc                integer,   
QNCony             integer,   
nc                 integer,   
h_ncp              integer,   
h_ncs              integer,   
h_sin_nc           integer,   
th_ncps            integer,   
qncs_h             integer,   
TH_NCPSQ           integer,   
nca                integer,   
qmieNC             integer,   
nc_pres_hj         numeric,   
nc_pres_hj6        numeric,   
nc_pres_hj14       numeric,   
idnc               numeric,   
t53_ing_2          numeric,   
i2_totx_2          numeric,--cambiado  
i3_tot_2           numeric,--cambiado   
ingtot_2           numeric, --cambiado  
itf_2              numeric, --cambiado   
ipcf_2             numeric, --cambiado   
qipcf_2            integer,   
dipcf_2            integer,   
qitf_2             integer,   
ditf_2             integer,   
i3_1x_2            integer,   
i3_2x_2            integer,   
i3_3x_2            integer,   
i3_4x_2            integer,   
i3_5x_2            integer,   
i3_6x_2            integer,   
i3_7x_2            integer,   
i3_8x_2            integer,   
i3_11x_2           integer,   
i3_12x_2           integer,   
i3_13x_2           integer,   
i3_10x_2           integer,   
codi3_1x           integer,   
codi3_2x           integer,   
codi3_3x           integer,   
codi3_4x           integer,   
codi3_5x           integer,   
codi3_6x           integer,   
codi3_7x           integer,   
codi3_8x           integer,   
codi3_11x          integer,   
codi3_12x          integer,   
codi3_13x          integer,   
codi3_10x          integer,   
sn7                integer,   
sn7_esp            character varying(100), 
cons6m             numeric,     
sn15_con           integer,     
sn4_r              numeric,     
consino            numeric,     
filter             numeric,     
sn10_3             numeric,     
CONSTRAINT eah_ind_2012_pk PRIMARY KEY (enc, hog_orig, mie_orig)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE proc.eah_ind_2012
  OWNER TO tedede_php;
ALTER TABLE proc.eah_ind_2012 ADD CONSTRAINT eah_hog_2012_eah_ind_2012_fk FOREIGN KEY (enc, hog_orig) REFERENCES proc.eah_hog_2012;