INSERT INTO siscen.proy_usu(
            proyusu_usu, proyusu_proy, proyusu_puede_escribir, proyusu_ver_todo, 
            proyusu_puede_confirmar, proyusu_tlg)
    VALUES ('prueba',         'EAH',   true, true, true, 1),
           ('prueba',         'IPCBA', true, true, true, 1),
           ('prueba',         'OPSIS', true, true, true, 1),
           ('emilio',         'EAH',   true, true, true, 1),
           ('emilio',         'IPCBA', true, true, true, 1),
           ('emilio',         'OPSIS', true, true, true, 1),
           ('mauro',          'EAH',   true, true, true, 1),
           ('mauro',          'IPCBA', true, true, true, 1),
           ('mauro',          'OPSIS', true, true, true, 1),
           ('martinr',        'EAH',   true, true, true, 1),
           ('martinr',        'IPCBA', true, true, true, 1),
           ('martinr',        'OPSIS', true, true, true, 1),
           ('alejandromunoz', 'EAH',   true, true, true, 1),
           ('alejandromunoz', 'IPCBA', true, true, true, 1),
           ('alejandromunoz', 'OPSIS', true, true, true, 1),
           ('lgarcia',        'EAH',   true, true, true, 1),
           ('lgarcia',        'IPCBA', true, true, true, 1),
           ('lgarcia',        'OPSIS', true, true, true, 1),
           ('vkosciukowicz',  'EAH',   true, true, true, 1),
           ('vkosciukowicz',  'IPCBA', true, true, true, 1),
           ('vkosciukowicz',  'OPSIS', true, true, true, 1),
           ('eabus',          'EAH',   true, true, true, 1),
           ('eabus',          'IPCBA', true, true, true, 1),
           ('eabus',          'OPSIS', true, true, true, 1),
           ('fquiroz',        'EAH',   true, true, true, 1),
           ('fquiroz',        'IPCBA', true, true, true, 1),
           ('fquiroz',        'OPSIS', true, true, true, 1),
           ('tere',           'EAH',   true, true, true, 1),
           ('tere',           'IPCBA', true, true, true, 1),
           ('tere',           'OPSIS', true, true, true, 1),
           ('ranodal',        'EAH',   true, true, true, 1),
           ('ranodal',        'OPSIS', true, true, true, 1);
    
